### ISSUE TITLE
BE CAREFUL !

### ISSUE THREAD

**Issue by serious-angel** [icetee/remote-ftp#1001]
# IT REMOVED
**some files from LOCAL project's path were I've created FTP Config because NOONE/NOTHING alerted me that it'll REPLACE/REMOVE/REWRITE files with the same LOCATION/FILENAME !**

# DAMN IT
I.e. you have some file like script.js with ~5k lines in the same folder where you've created FTP Config with this plugin ... so if you'll open file with **same remote path and name** it'll replace you local file with downloaded one >:( This's really good plugin, but ...

# WTH, DEV. ?!

**Comment by icetee** [comment]
This is the default operation. This package helps keep local and remote files in sync. You can not decide which one is the most recent. If you are developing locally use git.

If you do not commit to git, overwrite the file. Actually, the situation is similar here too.

This package is more about developing on a remote server.

I'm really sorry about your data loss, but I close this issue.

**Comment by serious-angel** [comment]
THEN PLEASE TELL ABOUT THIS BEFORE DOWNLOADING AND REMOVING THESE FILES ! PLEASE ALERT USER IF THIS FILE ALREADY EXISTS ! DAMN ...
I've removed very important files ... because of this ...
