### ISSUE TITLE
Remote FTP: Error: Unknown error 550.

### ISSUE THREAD

**Issue by Jukit-Barrett** [icetee/remote-ftp#1003]
Remote FTP: Error: Unknown error 550.

**Comment by icetee** [comment]
I will not be able to tell you so much. Version number, server type, use FTP or SFTP? If simple FTP check debug mode in Remote-FTP settings view and copy paste here.

You use Remote-FTP v1.2.4?

**Comment by icetee** [comment]
I closed. No response.
