### ISSUE TITLE
Connection without password

### ISSUE THREAD

**Issue by masiama** [icetee/remote-ftp#1004]
In config I selected "promptForPass": true to not to show my pass there. After update when connecting prompt is shown but also it tries to connect without password
![Screenshot](https://i.imgur.com/T9PICxs.jpg)

**Comment by tominal** [comment]
I'm not sure that it's trying to connect, but it is seriously annoying that it's throwing that error everytime I connect even when promptForPass is set to true. Not enjoying this update at all.

**Comment by masiama** [comment]
About IP you can setup what you want to be show at the top

**Comment by tominal** [comment]
How can I change that at least?

**Comment by masiama** [comment]
In package settings

**Comment by tominal** [comment]
you rock, now just gotta kill this stupid thing. might revert to the last version
![passphrase](https://user-images.githubusercontent.com/8497308/31414688-c983e8f8-ade4-11e7-8c77-59fd0ef77046.png)

**Comment by masiama** [comment]
Is there a better alternative?

**Comment by icetee** [comment]
@masiama Please try my fix.

**Comment by masiama** [comment]
@icetee, sorry for silly question but how?

**Comment by icetee** [comment]
Go your Atom > packages > Remote-FTP folder and changes with commit https://github.com/icetee/remote-ftp/commit/4d91f689691b52ce58ad3aee061ec48f37c7cac1 in `~/.atom/packages/Remote-FTP/lib/client.js` and restart Atom. (In v1.2.4)

If there is an old version then in command line:
```
apm uninstall remote-ftp
apm install remote-ftp@1.2.4
```

**Comment by masiama** [comment]
@icetee thanks a lot. This works

**Comment by icetee** [comment]
Thanks. The new version is coming soon.

**Comment by tominal** [comment]
Thanks @icetee great support!
