### ISSUE TITLE
Installing remote-ftp failed

### ISSUE THREAD

**Issue by PovilasSam** [icetee/remote-ftp#1005]
Installing “Remote-FTP@1.2.4” failed.Hide output…
C:\Users\Povilas\AppData\Local\Temp\apm-install-dir-11797-6184-1yp4lkg.8ybcqjv2t9
`-- (empty)

npm ERR! not a package C:\Users\Povilas\.atom\.apm\readable-stream\1.1.14\package.tgz
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\Remote-FTP\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Povilas\AppData\Local\Temp\apm-install-dir-11797-6184-1yp4lkg.8ybcqjv2t9\package.json'
npm WARN apm-install-dir-11797-6184-1yp4lkg.8ybcqjv2t9 No description
npm WARN apm-install-dir-11797-6184-1yp4lkg.8ybcqjv2t9 No repository field.
npm WARN apm-install-dir-11797-6184-1yp4lkg.8ybcqjv2t9 No README data
npm WARN apm-install-dir-11797-6184-1yp4lkg.8ybcqjv2t9 No license field.
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Users\\Povilas\\AppData\\Local\\atom\\app-1.21.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Povilas\\AppData\\Local\\atom\\app-1.21.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Povilas\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Povilas\\.atom\\.apmrc" "install" "C:\\Users\\Povilas\\AppData\\Local\\Temp\\d-11797-6184-h1h8n3.7pprjm7vi\\package.tgz" "--runtime=electron" "--target=1.6.9" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! path C:\Users\Povilas\AppData\Local\Temp\apm-install-dir-11797-6184-1yp4lkg.8ybcqjv2t9\node_modules\.staging\readable-stream-cd0af21e\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Povilas\AppData\Local\Temp\apm-install-dir-11797-6184-1yp4lkg.8ybcqjv2t9\node_modules\.staging\readable-stream-cd0af21e\package.json'
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Povilas\AppData\Local\Temp\apm-install-dir-11797-6184-1yp4lkg.8ybcqjv2t9\node_modules\.staging\readable-stream-cd0af21e\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Povilas\AppData\Local\Temp\apm-install-dir-11797-6184-1yp4lkg.8ybcqjv2t9\npm-debug.log
npm ERR! code 1

Tried reinstalling, uninstalling nothing helps

**Comment by icetee** [comment]
Have you managed to solve the problem?
Did you try to install it with a command line?

```
apm uninstall remote-ftp
apm install remote-ftp
```

If that does not help you try the old version.

```
apm install remote-ftp@1.1.3
```

**Comment by icetee** [comment]
Does it work with a new Atom version?

**Comment by PovilasSam** [comment]
Still does not work with a new Atom version :/

**Comment by PovilasSam** [comment]
Installing remote-ftp@1.1.3 to C:\Users\Povilas\.atom\packages failed
C:\Users\Povilas\AppData\Local\Temp\apm-install-dir-117925-2520-z7guix.cxx51rwwmi
`-- (empty)


npm ERR! not a package C:\Users\Povilas\.atom\.apm\readable-stream\1.1.14\package.tgz
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\Remote-FTP\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Povilas\AppData\Local\Temp\apm-install-dir-117925-2520-z7guix.cxx51rwwmi\package.json'
npm WARN apm-install-dir-117925-2520-z7guix.cxx51rwwmi No description
npm WARN apm-install-dir-117925-2520-z7guix.cxx51rwwmi No repository field.
npm WARN apm-install-dir-117925-2520-z7guix.cxx51rwwmi No README data
npm WARN apm-install-dir-117925-2520-z7guix.cxx51rwwmi No license field.
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Users\\Povilas\\AppData\\Local\\atom\\app-1.21.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Povilas\\AppData\\Local\\atom\\app-1.21.1\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Povilas\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Povilas\\.atom\\.apmrc" "install" "C:\\Users\\Povilas\\AppData\\Local\\Temp\\d-117925-2520-1dc4dqj.xyf6uk57b9\\package.tgz" "--runtime=electron" "--target=1.6.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! path C:\Users\Povilas\AppData\Local\Temp\apm-install-dir-117925-2520-z7guix.cxx51rwwmi\node_modules\.staging\readable-stream-b65d2164\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Povilas\AppData\Local\Temp\apm-install-dir-117925-2520-z7guix.cxx51rwwmi\node_modules\.staging\readable-stream-b65d2164\package.json'
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Povilas\AppData\Local\Temp\apm-install-dir-117925-2520-z7guix.cxx51rwwmi\node_modules\.staging\readable-stream-b65d2164\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Povilas\AppData\Local\Temp\apm-install-dir-117925-2520-z7guix.cxx51rwwmi\npm-debug.log
npm ERR! code 1


older version does not work as well, used command line

**Comment by icetee** [comment]
I think you might have a cache problem. Or no installed git?
https://github.com/atom/atom/issues/2263

**Comment by icetee** [comment]
Was it installed before?

**Comment by PovilasSam** [comment]
yes, but I reset the windows, so it shouldn't be installed anymore, git didn't solve it

**Comment by icetee** [comment]
Try this:
```
apm clean
npm cache clean --force
```

**Comment by PovilasSam** [comment]
npm cache clean --force
'npm' is not recognized as an internal or external command,
operable program or batch file.

sry if I'm retarded :D

**Comment by icetee** [comment]
In principle, it lacks the readable-stream npm package. Can not install it. I do not know what the reason is.

`apm clean` did not you solve it?

**Comment by PovilasSam** [comment]
unfortunately not

**Comment by icetee** [comment]
Try:
```
apm rebuild
apm rebuild-module-cache
```

If that does not help then:
```
apm remove Remote-FTP
git clone https://github.com/icetee/remote-ftp
cd remote-ftp
git checkout 1.x
apm install
```

**Comment by PovilasSam** [comment]
git checkout 1.x
fatal: Not a git repository (or any of the parent directories): .git

done everything else nothing helps :///

**Comment by icetee** [comment]
Missed: `cd remote-ftp`
Do you have a chance to see a team viewer?

**Comment by PovilasSam** [comment]
of course where do I post it

**Comment by icetee** [comment]
htomy92@gmail.com

**Comment by icetee** [comment]
The solution:
`Remove-Item -Recurse %HOMEPATH%\.atom\.apm\readable-stream\1.1.14`

**Comment by me-cedric** [comment]
It does not work for me unfortunately
