### ISSUE TITLE
Latest update broke sync remote -> local

### ISSUE THREAD

**Issue by gvoronov** [icetee/remote-ftp#1006]
Just try it
It fails to pull everything and the directory structure is flattened.

**Comment by Luminaire117** [comment]
I too have this problem, seems to ignore the .ftpignore file as well

**Comment by IvanRevchuk** [comment]
+1
i also have the same problem

**Comment by edmundyipll** [comment]
+1
Every time I want to sync, Atom crashes :(

**Comment by Luminaire117** [comment]
still happening after newest update as well

**Comment by ashishsajwan** [comment]
+1

**Comment by icetee** [comment]
Try v1.2.6!
