### ISSUE TITLE
Can't Download or Synch

### ISSUE THREAD

**Issue by MrJimOT** [icetee/remote-ftp#1007]
I normally open files from server to make sure I get latest version. I can't do that now. I uninstalled and reinstall remote-ftp. Still no joy. This message:
![image](https://user-images.githubusercontent.com/23161206/31312930-8748ec4e-ab97-11e7-9b54-db288a0432f7.png)
I installed latest update to remote-ftp today. But I also had a great deal of other trouble with my site. I ended up deleting my local copy of the entire site and tried to download it for an hour or so. It's really 5 integrated sites. It's 79GB for the whole thing so I am going to do the rest later. Am I looping to my own local files? When I save changes they are uploaded correctly. I just can't synch to or download from server. Love the package though. I am just operating over my head technologywise. 

UPDATE 10/10/17 rolled back to version 1.1.3 and attained joy. Clicking on the remote file now opens in local Atom. No error message.

**Comment by MrJimOT** [comment]
I just realized I aborted the downloads I attempted as there was not enough time to allow the transfer. Could that have created this issue?

**Comment by icetee** [comment]
Try v1.2.6!

**Comment by MrJimOT** [comment]
Joy! That now works fine. Thanks MrJim
