### ISSUE TITLE
promptForPass conflict with pass value

### ISSUE THREAD

**Issue by StephenNeate** [icetee/remote-ftp#1009]
Odd bug, not sure how best to fix, but easy to avoid.

With SFTP setup and the promptForPass value set to TRUE it appears the script checks the input from the dialog, but then reads the config value for re-connection. So if you leave any value (default is "pass") when prompted you will get the following actions on screen.

![image](https://user-images.githubusercontent.com/740283/31314133-f9c7f78e-ac3b-11e7-8410-a36d5a4af422.png)

Using the correct password as the pass variable allows stable connections, or ensuring that the pass variable is empty will also work just as well.

This is a different process than earlier versions of remote-ftp (from a couple of days ago) where any value left in the pass variable was ignored.

So this will fail
`"pass": "pass",
 "promptForPass": true,`

This works fine
` "pass": "",
 "promptForPass": true,`

Hope this helps.

**Comment by tominal** [comment]
Unlike previous versions, if you're using a privatekey it'll throw an error even with promptForPass set to true. I'm greeted by this everytime I connect :-1:  
![passphrase](https://user-images.githubusercontent.com/8497308/31414702-e22f70b6-ade4-11e7-8965-f2ff64883158.png)

**Comment by icetee** [comment]
Duplicate of #1004
