### ISSUE TITLE
File not found - Delete or rename file

### ISSUE THREAD

**Issue by AndryHTC** [icetee/remote-ftp#1011]
If the local path is empty, it creates an empty folder for each file I try to open, and gives me the error "Remote FTP: Error: File not found" (<550 file not found). If the local path is the same of the remote path, it gives me the same error and says also:
"Remote FTP: Already exists file in localhost"
"Delete or rename file before downloading folder"
I think is a strange error... Because isn't a folder, but an .ASP file.

Package version: Remote-FTP 1.2.4
Editor version: Atom 1.21.0 x64
Protocol: FTP

**Comment by icetee** [comment]
Try v1.2.6!
