### ISSUE TITLE
Suggestion - Rename the remote view's title

### ISSUE THREAD

**Issue by niccolomineo** [icetee/remote-ftp#1012]
Hi, first of all thanks for the plugin, which is a very important part of my daily work.

I'd like propose to rename the remote view's title to a simpler "Remote", to comply to a convention whereby the functionalities are labeled by their functional name, not by the plugin name, and in their most concise and experience friendly way.

"Remote Server" or "Remote FTP" (notice the dash drop) would also be a rather satisfying choice, but not as good as "Remote", as the latter would be a much better complement (it being one word and referring clearly to a remote location without adding any further, unnecessary differentiation or specification) to the "Project" label always appearing immediately to its own left:
![remote-ftp-rename-title](https://user-images.githubusercontent.com/5409469/31374742-66620466-ad9f-11e7-8490-bf8e549b358b.png)

I hope this stirs up a debate.

Keep up the great job with the plugin!

**Comment by icetee** [comment]
I changed title.
