### ISSUE TITLE
Not Uploading files since the API update.

### ISSUE THREAD

**Issue by ArielSaldana** [icetee/remote-ftp#102]
Uploading files to a server no longer works since I updated the package. It probably has something to do with the API deprecation update.

**Comment by JamesCoyle** [comment]
Having the same issue I think. I can upload files manually but they are not automatically uploaded on save. :(

**Comment by ArielSaldana** [comment]
Same here, I can manually upload files but they don't automatically upload on save.

**Comment by kwinne** [comment]
Same here. Manually is working fine but it's not working automatically.

**Comment by grenierdev** [comment]
There is a new setting in the package `autoUploadOnSave` (enabled by default). Can you verify that it's enabled?

**Comment by kwinne** [comment]
It is the first thing i've checked and it is enabled.
![image](https://cloud.githubusercontent.com/assets/11462085/7898197/93d14f6a-06f8-11e5-92f7-1b8a7e9a2894.png)

**Comment by grenierdev** [comment]
I can not reproduce the bug. If your willing to dive in the code, you could help me debug on your end by adding few lines in `remote-ftp/lib/remote-ftp.js`

After line 390 you should be in the `fileSaved` function :

``` js
if (!hasProject()) return;

if (!atom.config.get('remote-ftp.autoUploadOnSave')) return;

var self = this;
```

Comment `if (!atom.config.get('remote-ftp.autoUploadOnSave')) return;` and add a `console.log(text);` right after :

``` js
if (!hasProject()) return;

//if (!atom.config.get('remote-ftp.autoUploadOnSave')) return;
console.log(text);

var self = this;
```

Reload Atom (shortcut `CTRL+ALT+R` on Win) or just close Atom and reopen it.

Now each time you save a change, you should see the path to the file in the Atom console (`CTRL+ALT+I` on Win).

**Comment by JamesCoyle** [comment]
Commenting out that line makes auto-uploading work and the path is outputted correctly.

**Comment by grenierdev** [comment]
Can you modify the code again :

``` js
if (!hasProject()) return;

console.log(atom.config.get('remote-ftp.autoUploadOnSave'));
if (!atom.config.get('remote-ftp.autoUploadOnSave')) return;

var self = this;
```

It should print `true` or `false` in the console and it should reflect the setting you have in your screenshot.

**Comment by JamesCoyle** [comment]
atom.config.get('remote-ftp.autoUploadOnSave') is undefined.

**Comment by grenierdev** [comment]
What Atom version?

**Comment by ArielSaldana** [comment]
Version 0.204.0 for me, And same here. After I commented out the if statement the upload on save works.

**Comment by grenierdev** [comment]
If you guys disable & enable back the `Auto Upload On Save` settings, is it still `undefined` ?

**Comment by ArielSaldana** [comment]
Yes, I've also tried uninstalling the package and reinstalling

**Comment by grenierdev** [comment]
What really bugs me is that the setting does not seems to work at all on your end.

In your installed packages, is the folder named **Remote-FTP** or **remote-ftp** ? In any case, can you try to print `atom.config.get('Remote-FTP.autoUploadOnSave')` or `atom.config.get('remote-ftp.autoUploadOnSave')`.

**Comment by JamesCoyle** [comment]
The folder is Remote-FTP for me. Changing it to `if (!atom.config.get('Remote-FTP.autoUploadOnSave')) return;` seems to work.

**Comment by kwinne** [comment]
The problem is with the new update the dir name changed to Remote-FTP I think. 
If I edit the dir name to remote-ftp autouploadonsave works fine again. 
So you should make new update with dir to lowercase or change code to the right casing

**Comment by grenierdev** [comment]
It's working for me because I'm on Win and everything is case insensitive. The package's name is **Remote-FTP** and that's why the code is not working on your end. I changed my code to reflect the package's name.
