### ISSUE TITLE
Can't open a file with backslash in file name

### ISSUE THREAD

**Issue by aaaatpdev** [icetee/remote-ftp#1021]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/icetee/remote-ftp/issues

### Description

Can't open a file with backslash in file name.

### Steps to Reproduce

1. Right click on a folder, select "Add File", type "test".
2. Right click on the file, select "rename", change "test" to "\test".
3. Open the file.

**Expected behavior:** Ability to open files with backslashes in file names.

**Actual behavior:** Can't open a file with backslash in file name.

### Versions

Atom 1.20.1
Remote-FTP 1.1.3

### Additional Information

1. Another special symbols can also reproduce the issue.
2. Changing "test" to "te\st" produces "st" filename in Remote-FTP tree.
3. Also can't rename and delete the file.
4. It's able to open, rename or delete the file in Project tree.

**Comment by icetee** [comment]
Why does the backslash in the filename? :)
Backslash is represents folder in Window and replace in code.

https://github.com/icetee/remote-ftp/blob/3075b21f00386893181559842c7522bda5cd0365/lib/directory.js#L217-L231

https://github.com/icetee/remote-ftp/blob/3075b21f00386893181559842c7522bda5cd0365/lib/file.js#L58-L72

**Comment by icetee** [comment]
I supported. I think do not use backslash in file/folder name.

**Comment by aaaatpdev** [comment]
I added backslash to the file accidentally and decided to report the issue. I don't think the backslash in filename is a good idea

**Comment by icetee** [comment]
I thought and corrected it. Next version will include. Thank you very much for the report!
