### ISSUE TITLE
Files are downloaded as a folder with the files name

### ISSUE THREAD

**Issue by warriotox** [icetee/remote-ftp#1022]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/icetee/remote-ftp/issues

### Description
I'm having issues with all files. They seem to be processed as folders when trying to access them directly but when downloading the parent folder they are processed correctly as files. 

Screenshot of create files: https://puu.sh/y0dp0/488af110f2.png

For example when I try to download a /folder/style.css the progress bar is trying to download /folder/style.css/style.css

### Steps to Reproduce
Create a file on your FTP server and try downloading it with the remote-ftp plugin in Atom.

**Expected behavior:**
1. Downloading a file that doesnt exist on my computer from the server creates the file with the same name and contents.
2. Downloading the parent directory of my files creates/updates the files and the directory
3. Uploading the file to server updates the file on the server

**Actual behavior:** 
1. Downloading a file that doesnt exist on my computer from the server creates a folder instead.
2. Downloading the parent directory of my files creates files correctly
3. Uploading the file to server gets stuck.

**Reproduces how often:** [100%]

### Versions
Atom - 1.21.1
OS - Windows 10 Pro 64bit

### Additional Information

I'm not experiencing this behavior in IntelliJ Remote Host plugin, or FileZilla app..

**Comment by kucits** [comment]
I am having this same issue...

**Comment by ahkelly** [comment]
Same issue here, started happening 2 updates ago. As a result of the issue and error is reported claiming the file does not exist. Seriously need to rollback update that caused this.

![ftperror](https://user-images.githubusercontent.com/7065207/31744559-3eabb752-b42d-11e7-8c19-3e68bb43d36a.PNG)

**Comment by icetee** [comment]
Try v1.2.6!

**Comment by warriotox** [comment]
@icetee Hey, just updated to 1.2.6 and restarted Atom. The issue is still present. https://puu.sh/y3ntw/cfb0dfaddd.png
