### ISSUE TITLE
Unreliable downloads from Project Tab

### ISSUE THREAD

**Issue by SlimJim192** [icetee/remote-ftp#1023]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/icetee/remote-ftp/issues

### Description

When downloading files/folders from the project tab, file never downloads, remote-ftp must be disconnected and reconnected to perform any other operation

### Steps to Reproduce

1. Connect to FTP
2. Right click desired file/folder on project pane (not remote)
3. Click download

**Expected behavior:** File downloads succefully (Green confirmation)

**Actual behavior:** Remote tab claims to be downloading, but no progress is made.

**Reproduces how often:** 100%

### Versions

Windows 10 64bit (Latest)
Atom: 1.21.1
Electron: 1.6.15
Chrome: 56.0.2924.87
Node: 7.4.0
 
You can get this information from copy and pasting the output of `atom --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

This worked perfectly prior to your last update.

**Comment by kucits** [comment]
I can also confirm this behaviour.

**Comment by SlimJim192** [comment]
The behaviour here has changed since the 1.2.6 update.

Now if I try to download a single file from the project view, directories from the root of my remote server (and some directories from public_html) are all downloaded into the root (regardless of original location) of my project. Hidden files are downloaded from the root of the server.

It generally makes a huge mess of my project folder now!

**Comment by icetee** [comment]
Would you like to test the changes? https://github.com/icetee/remote-ftp/commit/743487d58739d78c8fdc929469f95a491a960e18

Remote FTP in the Atom folder must be rewritten. And restart Atom.

If okay, I'm releasing a new version.

**Comment by SlimJim192** [comment]
Just tested, all working.

Good work!

**Comment by btstw** [comment]
It doesn't download file in sub-directories.
