### ISSUE TITLE
Cannot Download Files - Either File exists issue or 550 File not Found

### ISSUE THREAD

**Issue by kucits** [icetee/remote-ftp#1024]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/icetee/remote-ftp/issues

### Description

When attempting to download files from the remote server I get a warning that the file already exists:

Remote FTP: Already exists file in localhost
Delete or rename file before downloading folder D:\wwwroot\upgrade\web.config.txt

 If I do delete the file and attempt to download from remote I get 550 File not found error.

### Steps to Reproduce

1. Attempt to download file from Remote
2. Delete or Rename local file when prompted
3. Attempt to download file from Remote

**Expected behavior:** I expect the file to be downloaded

**Actual behavior:** I end up with either a deleted file or renamed file and having to go to an external FTP client to get my files.

**Reproduces how often:** !00% - EVERY TIME

### Remote FTP - 1.2.5 | Atom - 1.21.1

You can get this information from copy and pasting the output of `atom --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by icetee** [comment]
Try v1.2.6!
