### ISSUE TITLE
Minor Issue with Tree-View

### ISSUE THREAD

**Issue by jccrofty30** [icetee/remote-ftp#103]
In tree-view, when you scroll horizontally, the highlighting on the selected file does not span the full row. If you expand the frame, however, the highlighting grows with it.

**Comment by arielnoname** [comment]
+1 
![screen shot 2015-06-18 at 17 42 04](https://cloud.githubusercontent.com/assets/11996305/8241777/aca0549e-15e1-11e5-9813-a8389d817220.png)

**Comment by jpxd** [comment]
It seems to work now. Please reopen if this is still an issue
