### ISSUE TITLE
"Error: All configured authentication methods failed" after update to 1.2.6

### ISSUE THREAD

**Issue by bkroll** [icetee/remote-ftp#1043]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/icetee/remote-ftp/issues

### Description

After updating to version 1.2.6 on 1.21.2, all previously working SFTP configurations do not work any more. The error message is: `Error: All configured authentication methods failed`

Rewriting a new configuration using the template provided by the "create sftp config file" menu item did not help.

My config files look like this (working until before the update):
```
{
    "protocol": "sftp",
    "host": "mybox", 
    "port": 22, 
    "user": "myuser",
    "pass": "",
    "promptForPass": true, 
    "remote": "/srv/www/myvhost/html/mydir", 
    "keyboardInteractive": true
}
```

### Steps to Reproduce

1. Open project with pre-update configuration.
2. Click "Connect" in the Remote FTP menu

**Expected behavior:** [What you expect to happen]
Connect successfully.

**Actual behavior:** [What actually happens]
"Error: All configured authentication methods failed"

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

Atom    : 1.21.2
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
Windows 10

### Additional Information

Console shows:
```
IntersectionObserver.observe(target): target element is not a descendant of root.
TreeView @ <embedded>:119177
<embedded>:116344 spell-check:en-us Can't load en_US: Cannot find dictionary for en_US.
[Violation] Long running JavaScript task took 475ms
```

Any advice how to solve this would be great. Thanks!

**Comment by icetee** [comment]
@bkroll See https://github.com/icetee/remote-ftp/issues/698#issuecomment-340923241
