### ISSUE TITLE
Remote-FTP goes into a broken loop when I start Atom

### ISSUE THREAD

**Issue by dantman** [icetee/remote-ftp#105]
When I startup Atom now Remote-FTP goes into an loop of connecting, connected, failed to connect messages while showing a connected tree with nothing inside of `/` and saying it's uploading. These messages all show up at once and new ones show up continually.

![screen shot 2015-06-01 at 5 20 38 pm](https://cloud.githubusercontent.com/assets/53399/7926237/745d1d48-0884-11e5-8db3-8e670b97c7f6.png)

**Comment by dantman** [comment]
Re-installing appears to have fixed my problem.

<i>Though that wasn't easy. Since due to bugs in Atom's settings view this bug (can't disable/uninstall from safe mode, can't uninstall disabled packages, etc...) I had to try manually disabling the package by editing my config file and using `apm` to do the actual uninstallation).</i>

**Comment by grenierdev** [comment]
What was the Atom & plugin version?

**Comment by dantman** [comment]
My current Atom is 0.204.0.

Because I re-installed the plugin I can't answer what the versions were when I had the issue.

**Comment by dantman** [comment]
I'm on 0.7.1 right now. The loop itself didn't come back. But the part where the remote tree is empty and says it's uploading randomly returned (I'll note that Remote-FTP seemed slow to finish its connection to the server).

((I reinstalled again and that's not happening))

**Comment by dantman** [comment]
I got the tree issue and reinstalled once more. After restarting Atom the whole issue, loop included, showed up.

Atom: 0.207.0
Remote-FTP: 0.7.1

Another restart made the loop go away. But not the empty tree + 'uploading'. Which only disappeared after I made Remote FTP disconnect and then connect.

So rather than something fixed by reinstallation or upgrade this appears to be an intermittent issue that pops up sometimes when Atom tries automatically connecting on startup.

**Comment by dantman** [comment]
Happened again.
Atom 1.0.7
Remote-FTP 0.7.2

Happened > Restarted > Happened again > Restarted > Seemed to work

**Comment by mapled** [comment]
I have the same issue.
Atom 1.0.11
Remote-FTP 0.7.2

I am on a Mac as well with 10.10.5.

**Comment by jimmaaay** [comment]
If anyone is still having issues with this bug leave a comment and I'll reopen the issue.

**Comment by darrenbarklie** [comment]
Atom 1.18.0 for Win 10
Remote-FTP 1.1.3

Standard .ftpconfig pointing to domain root
Tried uninstalling and reinstalling Remote-FTP, problem reoccurs

![remote-ftp-bug](https://user-images.githubusercontent.com/3026261/28391103-de1dbaf6-6d06-11e7-81e7-9a91bef8e571.JPG)

**Comment by kilazer** [comment]
A very long download opening FTP files.
Reinstalling the atom and the plugin did not help. In version atom 1.38.2, everything works well. The problem is in version 1.40.1.
ubuntu 19.04
atom 1.40.1 x 64
