### ISSUE TITLE
Help Wanted: transfer done (but failed to open directory)

### ISSUE THREAD

**Issue by ecwio** [icetee/remote-ftp#1057]
SOLVED: forgot to define "remote"

### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/icetee/remote-ftp/issues

### Description

FTP connects and auth fine with server but does not list remote files in the tree (error message) :
transfer done (but failed to open directory)

### Steps to Reproduce

1. connect to ftp

**Expected behavior:** [What you expect to happen]
list files

**Actual behavior:** [What actually happens]
no file listing; error message:
transfer done (but failed to open directory)

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions
1.22.1

### Additional Information
works fine with other ftp client such as Cyberduck

**Comment by icetee** [comment]
I set standard value for him, thanks.
