### ISSUE TITLE
Wrong file uploaded

### ISSUE THREAD

**Issue by ecwio** [icetee/remote-ftp#1058]
### Description
I can't manage to upload the file I want. everytime it uploads .ftpconfig even if the file is not opened.
### Steps to Reproduce

1. use upload shortcut cmd+shift+U

**Expected behavior:** [What you expect to happen]
upload selected tab or file

**Actual behavior:** [What actually happens]
always upload .ftpconfig

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Versions
1.22.1

**Comment by icetee** [comment]
The `cmd+shift+u` triggered `remote-ftp:upload-selected` command. It upload in selected on TreeView. This command can be changed otherwise in your `keymap.cson`. By default, it upload once on `cmd + s`.
