### ISSUE TITLE
Unable to list FTP root directory

### ISSUE THREAD

**Issue by thebluesheep** [icetee/remote-ftp#1060]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/icetee/remote-ftp/issues

### Description

When using remote-ftp package version 2.0.0, 1.3.4, 1.3.1, 1.2.6 and 1.2.1 when I connect to a FTP site, it connects but halts when "Listing web" ... shows this error message "Remote FTP: Error: Timed out while making data connection".
I have no problem when using sFTP.

### Steps to Reproduce

1. Create .ftpconfig file to FTP site
2. Press "Connect" button

**Expected behavior:** Show FTP file tree

**Actual behavior:** Shows error message and show empty tree

**Reproduces how often:** 100%

### Versions

Windows 10 Pro Version 1709 Build 16299.64
Atom 1.22.1 ia32
Remote-FTP 2.0.0

FTP server: Pure-FTP 1.0.36

### Additional Information

From debug console when trying to connect to FTP ...

< 220---------- Welcome to Pure-FTPd [privsep] [TLS] ---------- ...
> USER test_user
< 331 User test_user OK. Password required
> PASS ******
< 230 OK. Current restricted directory is /
> FEAT
< 211-Extensions supported:\r\n EPRT\r\n IDLE\r\n MDTM\r\n SIZE\r\n MFMT\r\n REST STREAM\r\n MLST type*;size*;sizd*;modify*;UNIX.mode*;UNIX.uid*;UNIX.gid*;unique*;\r\n MLSD\r\n AUTH TLS\r\n PBSZ\r\n PROT\r\n UTF8\r\n ESTA\r\n PASV\r\n EPSV\r\n SPSV\r\n ESTP\r\n211 End.
> OPTS UTF8 ON
< 200 OK, UTF-8 enabled
> TYPE I
< 200 TYPE is now 8-bit binary
> EPSV
< 229 Extended Passive mode OK (|||59312|)
> EPSV
< 229 Extended Passive mode OK (|||35109|)
> ABOR
< 226 Since you see this ABOR must\'ve succeeded

**Comment by icetee** [comment]
Can you tell which Pure-FTPd version you are using?

**Comment by thebluesheep** [comment]
Pure-FTP 1.0.36 on CentOS 6.5

**Comment by icetee** [comment]
Otherwise I think it does not support your server for passive FTP. For an active connection it is unfortunately unable to plugin for the time being.

**Comment by thebluesheep** [comment]
I got it to work with Remote-FTP package version 1.1.3 ... but it is a very old version ... and it is a pain to downgrade if I accidentally upgrade package to new version.

**Comment by icetee** [comment]
I try to debug it, then back to the old version. Thanks for the report and infos.

```
apm remove remote-ftp
apm install remote-ftp@1.1.3
```

**Comment by icetee** [comment]
I installed pure-ftpd and working, show tree list on MacOS local Pure-FTPd 1.0.47 and try public pure-ftpd servers (I don't know version numbers).
I tried vsFTPd 3.0.3 (Amazon), ProFTPD 1.3.5a (DigitalOcean).

```
< 220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------\r\n220-You are user number 1 of 50 allowed.\r\n220-Local time is now 02:22. Server port: 21.\r\n220-IPv6 connections are also welcome on this server.\r\n220 You will be disconnected after 15 minutes of inactivity.
helpers.js [sm]:97 > USER icetee
helpers.js [sm]:97 < 331 User icetee OK. Password required
helpers.js [sm]:97 > PASS ******
helpers.js [sm]:97 < 230 OK. Current directory is /
helpers.js [sm]:97 > FEAT
helpers.js [sm]:97 < 211-Extensions supported:\r\n EPRT\r\n IDLE\r\n MDTM\r\n SIZE\r\n MFMT\r\n REST STREAM\r\n MLST type*;size*;sizd*;modify*;UNIX.mode*;UNIX.uid*;UNIX.gid*;unique*;\r\n MLSD\r\n AUTH TLS\r\n PBSZ\r\n PROT\r\n TVFS\r\n ESTA\r\n PASV\r\n EPSV\r\n SPSV\r\n ESTP\r\n211 End.
helpers.js [sm]:97 > TYPE I
helpers.js [sm]:97 < 200 TYPE is now 8-bit binary
helpers.js [sm]:97 > EPSV
helpers.js [sm]:97 < 229 Extended Passive mode OK (|||59301|)
helpers.js [sm]:97 > EPSV
helpers.js [sm]:97 < 229 Extended Passive mode OK (|||7891|)
helpers.js [sm]:97 > LIST -al /
helpers.js [sm]:97 < 150 Accepted data connection
helpers.js [sm]:97 < 226-Options: -a -l \r\n226 4 matches total
```
I found this: https://github.com/icetee/remote-ftp/issues/306

With the same configuration, firewall setting etc go with 1.1.3? :O

**Comment by icetee** [comment]
Please try this changes: https://github.com/icetee/remote-ftp/commit/ae9bfaf52a94cf56dfc0f43a1374c3460f039232 and restart Atom.

**Comment by aaroniker** [comment]
@icetee this worked for me! thanks

**Comment by anrsbusk** [comment]
I just updated my Remote-FTP to 1.3.4, and I get the error above also.

It connects at first, but then I get an error saying  "Timed out while making the data connection"

I have used Remote-FTP for about a year, and never had a single problem.

**Comment by aaroniker** [comment]
@anrsbusk did you try these changes: https://github.com/icetee/remote-ftp/commit/ae9bfaf52a94cf56dfc0f43a1374c3460f039232 ?

**Comment by icetee** [comment]
@anrsbusk What you are writing refers to the absence of a passive connection. There's a package's dependence ([node-ftp](https://github.com/mscdex/node-ftp)) on this plugin. I started rewriting, a it already supports the active connection (https://github.com/icetee/node-ftp/commit/342ccecc25edbff38b82c0adefb7e0b7464ec013). It is in the testing phase.

You may want to try to go back to the previous version. I think you have to get that result.

--

Thanks @aaroniker for response!
The next version will include the fix. I close this issue.
