### ISSUE TITLE
Enable Watch File Change not working after updating to v2.0.0

### ISSUE THREAD

**Issue by johnimperio** [icetee/remote-ftp#1062]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/icetee/remote-ftp/issues

### Description
Updated to Remote-FTP 2.0.0 and watch folders aren't being watched.
I use watch folders for auto-uploading css files when compiling less files

### Steps to Reproduce

These aren't exactly steps but this is the setup that I use
1. Auto Upload On Save or Only when connected 
2. Enable Watch File Change checked
3. via 'Less-Autocompile' package or via CodeKit Less Compiler

**Expected behavior:** file created notification, css and less files uploaded

**Actual behavior:** file created notification (less-autocompile works), less uploaded but css not uploaded

**Reproduces how often:** n/a

### Versions

Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
OS: Mac OS Sierra 10.12.6

### Additional Information

Watch folder path setup:
'watch': [
   "/public/accounts/*/css/style.css",
   "/public/accounts/*/certificates/*/certificate.css"
]

**Comment by icetee** [comment]
@johnimperio Try to change File System Watcher type in `Settings View > Core > File System Watcher > Native operating system APIs`. I use Mac OS Hight Sierra v10.13.1, working perfectly.

**Comment by pkimmlinger** [comment]
@icetee not working for me.  High Sierra 10.13.1

**Comment by icetee** [comment]
In the devtool no logs?
I tried an star (\*) charachter, it really did not work. Try skipping joker (\*) charachter.

Can you confirm that this is a bug? If yes, I'll figure out something.

**Comment by pkimmlinger** [comment]
@icetee You're right. Looks like the asterisk will not work anymore. After removing it the watcher works well.

**Comment by benjamenjohnsondev** [comment]
just dropping in to confirm joker not working - discovered this this morning windows 10

**Comment by pengyan518** [comment]
I have the same issue:
Atom : 1.22.1
OS: Mac OS Sierra 10.12.6

Additional Information
Watch folder path setup:
'watch': [
  "./httpdocs/"
]

**Comment by adamgda** [comment]
Anyone have idea how to fix this asterisk problem? This is important for me.

**Comment by icetee** [comment]
The fastest you get back older version.

**Comment by mdurchholz** [comment]
Has there been any updated for the asterisk(*) issue? I currently have to individually list out the files I want the plugin to watch.

**Comment by benjamenjohnsondev** [comment]
@mdurchholz I don't know about any progress sorry - but as a workaround you can watch whole folders for change and list files you want to ignore in .ftpignore

**Comment by RvWensen** [comment]
@benjamenhogben and what if i want to watch all folders inside a folder?
Or do i have to add every folder i want watch?

**Comment by benjamenjohnsondev** [comment]
@RvWensen test for yourself - I'm pretty sure it watches sub directories but I've not tried it out

**Comment by adamgda** [comment]
Sadly I use 1.3.4 and wait for problem fix in any newer version.
