### ISSUE TITLE
Download creates a folder instead of a file

### ISSUE THREAD

**Issue by probablyVincentIp** [icetee/remote-ftp#1063]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/icetee/remote-ftp/issues

### Description

When I download (by double clicking or right click > download), I get a local folder with the name of the remote file instead of the remote file. The folder itself is empty

### Steps to Reproduce

1. Connect to remote server
2. Download file (double click or right click download)
3. When download is finished a local folder is made

**Expected behavior:** A local copy of the remote file is expected 

**Actual behavior:** A folder is made with the name of the remote file (ie trying to download a remote file `example.php` creates a folder named example.php

**Reproduces how often:** 100%

### Versions

Windows 10 Professional, fully updated 
Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
Remote-FTP: 2.0.0 (issue was present in 1.1.4 as well) 

### Additional Information

`Sync local <- remote` works as expected

**Comment by icetee** [comment]
I think related of #1026 so I close.

What is your ftp server name? (vsftpd?)
Plain FTP or SFTP?
