### ISSUE TITLE
F5 does not refresh file contents any more

### ISSUE THREAD

**Issue by singhaxn** [icetee/remote-ftp#1064]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/icetee/remote-ftp/issues

### Description

Pressing F5 does not reload the contents of an open file from the server in version 2.0.0. I'm not sure what version I had before updating but this definitely worked in a previous version.

### Steps to Reproduce

1. Open a remote file
2. Modify the remote file outside Atom
3. Press F5

**Expected behavior:** Modified contents of the remote file should be loaded in the current tab

**Actual behavior:** Current tab continues to display old contents

**Reproduces how often:** 100%

### Versions

Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
remote-ftp version: 2.0.0
OS: Windows 10 Home Edition, Version 1709, Build 16299.64

### Additional Information

-

**Comment by icetee** [comment]
Yes really deleted. It has caused more problems and has been deleted by default. https://github.com/icetee/remote-ftp/commit/dc00cfec3432400342b7381a08cf6501a4ba4f94

**Simple resolve:**
Add your `keymap.cson` this `'f5': 'remote-ftp:download-active'`.
In macOS `Atom > Keymap...`
