### ISSUE TITLE
Can't install 2.0 on ATOM beta 1.23.0-beta1 [SOLVED:-)]

### ISSUE THREAD

**Issue by tweed** [icetee/remote-ftp#1066]
WINDOWS 10 - 64 bit
ATOM: beta 1.23.0-beta1

Can anyone help - I have tried for days
Is It IMPOSSIBLE to run Remote-FTP 2.0  on latest beta 1.23.0-beta1 ??

thank you very much for your time

Here's the error:

```
Installing “Remote-FTP@2.0.0” failed.Hide output…
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\Users\Administrator\.atom\packages\Remote-FTP\package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Proxy.fs.readFileSync (fs.js:508:33)
    at Proxy.fs.readFileSync (C:\Users\Administrator\AppData\Local\atom\app-1.23.0-beta1\resources\app\apm\node_modules\asar-require\lib\require.js:86:27)
    at C:\Users\Administrator\AppData\Local\atom\app-1.23.0-beta1\resources\app\apm\lib\install.js:476:42
    at fn (C:\Users\Administrator\AppData\Local\atom\app-1.23.0-beta1\resources\app\apm\node_modules\async\lib\async.js:582:34)
    at Immediate.<anonymous> (C:\Users\Administrator\AppData\Local\atom\app-1.23.0-beta1\resources\app\apm\node_modules\async\lib\async.js:498:34)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)

```

**Comment by brockdunda** [comment]
I'm also getting this error. I had this package installed already and it was working. I got the notification that some of the packages needed to update, and this one failed to update. I restarted atom to find that the package was removed from my package list and can no longer install it.

I'm getting the same error as the OP.

Hoping for a fix soon.

**Comment by tweed** [comment]
YES - i had to search again for package, 'Remote-FTP' - eventually it popped up and the re-install attempt of course still failed.

maybe caused by the big jump from previous version to 2.0 i guess, AND that I am using a beta version.

I would happily downgrade to earlier Remote-FTP if I knew how.

CAN ANYONE- tell us how to find the last version,  then downgrade to the previous version before 2.0?

Really missing it as it's SO wonderful.

whatever happens - great thanks!

**Comment by cmalkus** [comment]
I had the same issue where I was unable to reinstall through the settings. What worked for me was to reinstall through the command line: `apm install remote-ftp` . This installs version 1.3.4

**Comment by brockdunda** [comment]
Thanks cmalkus, that worked for me too.

**Comment by icetee** [comment]
I think this is an APM (Atom package manager) bug.
@cmalkus solution works.

```
apm uninstall remote-ftp
apm install remote-ftp
```

**Comment by tweed** [comment]
I'm a huge OpenBSD and also Linux(es) fan - though currently on Windows locally.

Sorry to appear lazy when I ask if anyone could tell me whether 
apm install remote-ftp
might somehow work on windows 10?

guess not? 
SOLUTION for me on windows?

super-crazy busy - SORRY for literally not having time to google etc....etc.... etc.... :-)

**Comment by tweed** [comment]
GEEZ - that DOES work on windows command line as well
just bring up powershell and  paste in --> apm install remote-ftp

as there no longer was anything to uninstall for me
I just installed
WOW THANK YOU SOoooooooo MUCH

**Comment by icetee** [comment]
The new atom supports only the lowercase package name.This has been fixed in the new remote-ftp version. **The package's previous settings will be lost.**
