### ISSUE TITLE
Use Dock Integration doesn't save it's location state on atom restart

### ISSUE THREAD

**Issue by muggy8** [icetee/remote-ftp#1068]
### Prerequisites

* enable "Use Dock Integration" in settings
* move the remote panel somewhere else

### Description

When you move the doc to somewhere else after checking use dock integration in settings and restart atom. the remote panel finds it's way back on the left side. If you do not have any other pannels on the left side, you cannot actually get the to show up at all panel

**Expected behavior:** Move panel to right and reload atom and the location of the panel should remain where it was before the restart

**Actual behavior:** Move the panel to the right and reload resulting in the panel returning to the left. If no other panels are on the left, there's no way of getting the remote panel to show up at all

**Reproduces how often:** 100%

### Versions

Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
Remote-FTP  : 2.0.0
OS   : Mac 10.11.6 (OSX El Captian)

### Additional Information

I'm not sure if this is a bug with Atom in general or a bug with Remote-FTP. I know that treeview stays where it is when I restart but the Remote-FTP panel doesn't so I think it might be more of a remote FTP bug but feel free to correct me if i'm wrong :)

**Comment by icetee** [comment]
Thanks for open the issue. I change the method.
I deleted the non-working (deprecated) methods, options. https://github.com/icetee/remote-ftp/commit/00fa497675fb40133f0d79a6ee8d62f75466fa44

By the time the plugin save on what site is placed the tree view and it’s opened. (Order is not supported yet)

I hope it helps. The next version will include the fix. I close this issue.
