### ISSUE TITLE
download-selected-local not working on Windows

### ISSUE THREAD

**Issue by MikeWillis** [icetee/remote-ftp#1069]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/icetee/remote-ftp/issues

### Description

I believe there is a problem with /lib/menus/commands.js on line 394 (the download-selected-local function). I added:

`console.log("remotePath = '" + remotePath + "'");`

on my Windows machine on line 395 to debug, and the output is like so:

`remotePath = '/example.com/\htdocs\path\to\file.txt'`

My remote server is a linux box, and the download is failing. To make matters worse, no error is generated, in fact the system thinks that the download was successful, and it proceeds to bring up the atom notification claiming that all transfers succeeded. 

### Steps to Reproduce

1. On a windows machine, connect to a site hosted on linux
2. trigger the download-selected-local function

**Expected behavior:** [What you expect to happen]
the file is downloaded

**Actual behavior:** [What actually happens]
the file is not downloaded

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions
Windows 10
Atom 1.22.1
Electron 1.6.15
Chrome 56.0.2924.87
Node 7.4.0
Remote FTP 2.0.0

### Additional Information

I contributed the download-selected-local function a long time ago, but I had it set to modify the path like so:

```
// if this is windows, the path may have \ instead of / as directory separators
const remotePath = atom.project.remoteftp.root.remote + localPath.replace(/\\/g, '/');
```

I'm really not familiar with the Path.posix.normalize() function so I'm reading up on it now, and if I can come up with a fix I'll make a pull request. But hopefully someone else beats me to it, this can be a pretty serious issue if multiple people are sharing files and they think they downloaded a fresh copy of something when in fact they didn't

**Comment by MikeWillis** [comment]
After reading up on Path.posix.normalize() it seems to me that this function will normalize the path according to the local operating system, which is why my Windows system ends up with \ as directory separator, which doesn't agree with my remote server's / directory separator

**Comment by icetee** [comment]
I find it so good:
```javascript
const remotePath = Path.posix.normalize(Path.join(atom.project.remoteftp.root.remote + localPath));
```

**Comment by MikeWillis** [comment]
hmm on my machine that results in an error:

```
remotePath = '\example.com\htdocs\path\to\file.txt'
Uncaught Error: EEXIST: file already exists, mkdir 'C:\MyFolderStructure\example.com\pData\Local\atom\app-1.22.1'
    at fs.mkdirSync (fs.js:855)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:670)
    at sync (C:\Users\me\.atom\packages\Remote-FTP\node_modules\mkdirp\index.js:71)
    at sync (C:\Users\me\.atom\packages\Remote-FTP\node_modules\mkdirp\index.js:77)
    at sync (C:\Users\me\.atom\packages\Remote-FTP\node_modules\mkdirp\index.js:78)
```

edit: I left out a few lines from the error message, added them here

**Comment by icetee** [comment]
I also get such an error message. The folder or file does not exist on the server.

Maybe you can try to improve it in pull request?

**Comment by MikeWillis** [comment]
Sure I'd be glad to, I switched my machine to just do a replace of all \ with /

I'll do some digging today to see if there's a better option and will put a pull request in with whatever I come up with
