### ISSUE TITLE
Feature Request: Double click opens folder and treats it like root

### ISSUE THREAD

**Issue by arielnoname** [icetee/remote-ftp#107]
I've been using "Coda" for some time and the thing I like the most is the built-in FTP. In fact, the moment I saw your "remote-ftp" plugin was the moment I changed to Atom.

So, Im just dropping some ideas.

I don't know if I made myself clear. 

When I'm in the tree view, I would like to double click a folder and that folder act as the "working directory" so the tree is not so big because of the upper level directories. And if you want to go to the most surface folders, could be a button like ".." or " <- " lol.

Cheers man, awesome plugin.

**Comment by grenierdev** [comment]
`"remote": "/"` (config file) is maybe what your looking for.

This plugin is meant to be use to "sync" a local folder with a remote. Thus the root folder needs to be set before anything happens.

Request #44 Support for multiple server, could potentially achieve an alternative to what your asking.
