### ISSUE TITLE
cannot use with version 2.1.2

### ISSUE THREAD

**Issue by phamhung77** [icetee/remote-ftp#1084]
Just upgraded to version 2.1.2, running on Atom 1.23.1, and the program stops working. It seems able to connect to the host, but the status line keeps showing "Listing". The result is that I cannot update any file to the host.

**Comment by janstieler** [comment]
Hi,
I have also a problem. I get an connection to my server and the treeview is loading but if I will open a file nothing happens.
Version 2.1.2 with Atom 1.23.1

**Comment by adamgda** [comment]
I have same problem. Need to back to older version :(

**Comment by icetee** [comment]
Please add more information for me, because me can't be solved the issue.

[ ] **Do you receive any error messages?**
[ ] **Which protocol do you affect? [FTP, SFTP, All]**
[ ] **Did you checked that has old issue?**
[ ] **Which version did you switch from?**
[ ] **What type of the FTP server is connecting to?**

Please try set `"forcePasv": true` parameter in `.ftpconfig` file. This paramter make to force old passive connection. (The new supported IPv6, but not all servers support.

@adamgda Which version is winning?

**Comment by adamgda** [comment]
@icetee 1.3.4 works.

I want to test forcePasv method but now I can't update plugin...

```
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/adammz/.atom/packages/remote-ftp/package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Proxy.fs.readFileSync (fs.js:508:33)
    at Proxy.fs.readFileSync (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/asar-require/lib/require.js:86:27)
    at /Applications/Atom.app/Contents/Resources/app/apm/lib/install.js:476:42
    at fn (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/async/lib/async.js:582:34)
    at Immediate.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/async/lib/async.js:498:34)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```

**Comment by icetee** [comment]
Yes, unfortunately, from Atom 1.23.0 don't supported uppercase package name, only lowercase. Because of the change of name, only delete and install it.
https://github.com/icetee/remote-ftp/issues/1086#issuecomment-352404018

**Comment by adamgda** [comment]
Ok, I reainstall package. If I edit "normal" file its upload correctly, but if I edit some file from watch list (sass or js files edited by another sass or js files with grunt) nothing is send.

My watch array:
`    "watch": [
      "./adam/*/wp-content/themes/theme/*.css",
      "./adam/*/wp-content/themes/theme/*.map",
      "./adam/*/wp-content/themes/theme/js/*.js",
      "./adam/*/wp-content/themes/theme/js/*.map",
      "./adam/*/wp-content/themes/theme/js/modules/*/js/*.js"
    ],
`

If i remove * symbols and set specify template source it work, but I need to use *.
In 1.3.4 works perfectly but I like new features... :(

**Comment by jbelien** [comment]
Try with this command : `apm install remote-ftp`

See https://github.com/icetee/remote-ftp/issues/1066#issuecomment-347335300 for more details !

**Comment by welljsjs** [comment]
> It seems able to connect to the host, but the status line keeps showing "Listing". The result is that I cannot update any file to the host.

Same problem here, 
__Atom Version:__ 1.23.1
__remote-ftp Version:__ 2.1.2
__OS:__ Mac OSX 10.13.2

Just installed the remote-ftp-package, filled out the .ftpconfig-file, but it does not work. Even after adding "forcePasv": true.
The status line keeps showing "Listing."; no files from the server are shown.

I also tried the steps above: 

    apm install remove-ftp

Did not solve the problem. 

@icetee  @phamhung77 (Sorry to disturb you)
Any update on this?

Any help is appreciated.

**Comment by icetee** [comment]
New version available. If it's still problematic, open up a new issue.
