### ISSUE TITLE
wrong

### ISSUE THREAD

**Issue by badobaali** [icetee/remote-ftp#1091]
[Enter steps to reproduce:]

1. open the Atom Editor
2. connection

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.1.2

### Stack Trace

Uncaught Error: Remote FTP: getConfigPath returned false, but expected a string

```
At C:\Users\UserName\.atom\packages\remote-ftp\lib\client.js:222

Error: Remote FTP: getConfigPath returned false, but expected a string
    at Client.readConfig (/packages/remote-ftp/lib/client.js:222:45)
    at /packages/remote-ftp/lib/views/tree-view.js:159:30)
    at HTMLDivElement.dispatch (/packages/remote-ftp/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/remote-ftp/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -0:17.1.0 remote-ftp:disconnect (input.hidden-input)
     -0:11.9.0 remote-ftp:toggle (input.hidden-input)
```

### Non-Core Packages

```
wordpress-api 1.2.2 
remote-ftp 2.1.2 
wordpress-autocomplete 1.2.0 
```

**Comment by icetee** [comment]
This plugin works only in projects. This is not a bug.
Can not use 1 to 1 file, create or open project.
