### ISSUE TITLE
Version 2.1.2   -- -- -- 'Object.dirname is deprecated.'

### ISSUE THREAD

**Issue by tweed** [icetee/remote-ftp#1098]
CAN'T see the remote-FTP tree at all though will connect from pulldown ATOM menu - Am able to see remote-FTP tree ONLY if I remove the local folder and then other errors occur which have been reported.
Sorry for poor explain here - must sleep.

```
Argument to `path.dirname` must be a string
```
Object.dirname (C:\Users\Administrator\AppData\Local\atom\app-1.19.0-beta7\resources\app\src\electron-shims.js:9:10)
<unknown> (C:\Users\Administrator\.atom\packages\remote-ftp\lib\connectors\sftp.js:337:62)
SFTPStream._transform (C:\Users\Administrator\.atom\packages\remote-ftp\node_modules\ssh2-streams\lib\sftp.js:501:15)
SFTPStream.Transform._read (_stream_transform.js:167:10)
SFTPStream._read (C:\Users\Administrator\.atom\packages\remote-ftp\node_modules\ssh2-streams\lib\sftp.js:181:15)
SFTPStream._write (_stream_transform.js:155:12)
```
```

**Comment by tweed** [comment]
OK, I'll leave the above hoping it might be helpful
YET I HAVE GOT IT WORKING

the remote now shows up as a TAB right beside the local folder tab
I use a combination of PULL-DOW N ATOM MENU "toggle" and "connect" and made sure it was wide:ish on the left side where the local folder shows.  TOP ATOM MENU ---> /Packages/Remote FTP

THANKS
may be able to explain better after some sleep

**Comment by icetee** [comment]
Object.basename is deprecated. #1089
Show panel only dock. https://github.com/icetee/remote-ftp/issues/1093#issuecomment-353983887
