### ISSUE TITLE
Uncaught No `protocol` found in connection credential. Please recreate .ftpconfig file from Packages -> Remote-FTP -> Create (S)FTP config file.

### ISSUE THREAD

**Issue by vikoperdomo** [icetee/remote-ftp#110]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.206.0
**System**: Mac OS X 10.10.1
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.7.1
### Stack Trace

Uncaught No `protocol` found in connection credential. Please recreate .ftpconfig file from Packages -> Remote-FTP -> Create (S)FTP config file.

```
At /Users/3dcart/.atom/packages/Remote-FTP/lib/client.js:195

undefined
```
### Commands

```
     -7:02.7.0 remote-ftp:create-ftp-config (atom-pane.pane.active)
  2x -6:55.3.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -0:53.3.0 core:paste (atom-text-editor.editor.is-focused)
  2x -0:12.5.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.7.1
atom-jade, v0.3.0
emmet, v2.3.10
language-jade, v0.4.0

# Dev
No dev packages
```

**Comment by grenierdev** [comment]
This _bug_ mean that you have an error in your `.ftpconfig` file. Can you recreate your config file?

**Comment by vikoperdomo** [comment]
Ok cool I got it, thank you
