### ISSUE TITLE
Toggle does not show anything.

### ISSUE THREAD

**Issue by felixholub** [icetee/remote-ftp#1103]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/icetee/remote-ftp/issues

### Description

Toggling remote-ftp does not toggle. I can connect to the ftp successfully but there is no window/tab to show the content of the

### Steps to Reproduce

1. Remote Ftp: Toggle

**Expected behavior:** In the tree view, a tab should open with some buttons, or, if connected, listing files on the remote.

**Actual behavior:** Nothing happens.

**Reproduces how often:** 100%

### Versions

Atom    : 1.23.2
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

OS : Win 7

**Comment by iampatrick** [comment]
This sounds a lot like the issue I've been experiencing. If you open the Dev Tools, "Window: Toggle Dev Tools" or ctrl+shift+i, do you see any errors in the console?

**Comment by icetee** [comment]
Check this comment: https://github.com/icetee/remote-ftp/issues/1093#issuecomment-353983887 Only use Dock!
