### ISSUE TITLE
Two ftp-remote panels

### ISSUE THREAD

**Issue by serious-angel** [icetee/remote-ftp#1108]
Dear Developer,

How to remove these two ftp-remote panels ? I've just intsalled ftp-remote and this happened when I've clicked on: FTP-Remote Toggle

![screenshot_20180112_181656](https://user-images.githubusercontent.com/25136754/34884333-15b9ec0c-f7c5-11e7-8e96-5b7d55c3bb5f.png)

Btw I have two of these installed somehow:

![screenshot_20180112_182125](https://user-images.githubusercontent.com/25136754/34884449-729126b6-f7c5-11e7-80ba-67663836feab.png)

**Comment by RebelDesign** [comment]
Can you access two different servers at the same time>?!

**Comment by icetee** [comment]
Hi, the new atom version does not support uppercase plugin names. Please remove Remote-FTP@1.3.1 instance.

**Comment by serious-angel** [comment]
Yup, but why then it exists in plugins ? It's mb strange.
