### ISSUE TITLE
Status line keeps showing "Listing"

### ISSUE THREAD

**Issue by welljsjs** [icetee/remote-ftp#1109]
> It seems able to connect to the host, but the status line keeps showing "Listing". The result is that I cannot update any file to the host.
#1084 

Same problem here, 
__Atom Version:__ 1.23.1
__remote-ftp Version:__ 2.1.2
__OS:__ Mac OSX 10.13.2

Just installed the remote-ftp-package, filled out the .ftpconfig-file, but it does not work. Even after adding "forcePasv": true.
The status line keeps showing "Listing."; no files from the server are shown.

I also tried the steps above: 

    apm install remote-ftp

( And removing it before. )
Did not solve the problem. 

Any help is appreciated.

**Comment by Fogrunner** [comment]
Same here.

Some servers makes the same resulting like writer.
Specially, Amazon Server (EC2)

I can access the server with other ftp software in PasvMode. There is no issue, working perfectly.

However, this package can not get any list of remote server. So, this package try to get list infinity with "Listing" indicator at bottom of Remote Panel.

Yes, It happens by wrong setting of the server. If so, package should let know user what is problem to process.

**Comment by Fogrunner** [comment]
In my case to resolve it, i changed accessing way to SFTP instead of FTP
