### ISSUE TITLE
Folder and file that share a name throw exception

### ISSUE THREAD

**Issue by baconbrad** [icetee/remote-ftp#112]
[Enter steps to reproduce below:]
1. Create a file on accident ('tmpl') when trying to create a directory (also called 'tmpl')
2. Delete file and create directory with the same name
3. When you click on this directory or a file in it Atom will throw an editor and hang
4. Deleting the directory and any contained files in Atom or another FTP client and recreating them still throws this error.

Solution: Open up project directory remote-ftp uses on the local machine and manually delete the file that shares the folder name

**Atom Version**: 0.208.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.7.1
### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'C:\Users\Brad\Documents\www\components\PATH CHANGED TO PROTECT CLIENT\tmpl'

```
At C:\Users\Brad\AppData\Local\atom\app-0.208.0\resources\app.asar\node_modules\fs-plus\node_modules\mkdirp\index.js:76

Error: EEXIST: file already exists, mkdir 'C:\Users\Brad\Documents\www\components\PATH CHANGED TO PROTECT CLIENT\tmpl'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:791:18)
    at Function.sync (C:\Users\Brad\AppData\Local\atom\app-0.208.0\resources\app.asar\node_modules\fs-plus\node_modules\mkdirp\index.js:55:12)
    at Object.fsPlus.makeTreeSync (C:\Users\Brad\AppData\Local\atom\app-0.208.0\resources\app.asar\node_modules\fs-plus\lib\fs-plus.js:343:23)
    at C:\Users\Brad\.atom\packages\Remote-FTP\lib\connectors\ftp.js:441:8
    at Object.cb (C:\Users\Brad\.atom\packages\Remote-FTP\node_modules\ftp\lib\connection.js:1017:13)
    at Parser.<anonymous> (C:\Users\Brad\.atom\packages\Remote-FTP\node_modules\ftp\lib\connection.js:117:20)
    at emitTwo (events.js:87:13)
    at Parser.emit (events.js:169:7)
    at Parser._write (C:\Users\Brad\.atom\packages\Remote-FTP\node_modules\ftp\lib\parser.js:59:10)
```
### Commands

```
  2x -0:49.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "remote-edit",
      "shadow",
      "shadow"
    ],
    "autoHideMenuBar": true,
    "themes": [
      "northem-dark-atom-ui",
      "monokai"
    ]
  },
  "Remote-FTP": {
    "hideLocalWhenDisplayed": true
  }
}
```
### Installed Packages

``` coffee
# User
monokai, v0.14.0
northem-dark-atom-ui, v0.2.1
Remote-FTP, v0.7.1

# Dev
No dev packages
```

**Comment by jpxd** [comment]
Should not throw an exception but display a user-friendly error message which explains the problem.

**Comment by jpxd** [comment]
Known exceptions related to this:

When syncing: `Uncaught Error: ENOTDIR: not a directory, scandir '/Users/....'`
When opening/downloading a file: `Uncaught Error: EEXIST: file already exists, mkdir '....`

CC @samifouad

**Comment by ghost** [comment]
> Solution: Open up project directory remote-ftp uses on the local machine and manually delete the file that shares the folder name.

Sorry, I didn´t find the corresponding local folder. Can you give me a hint?

**Comment by baconbrad** [comment]
> Sorry, I didn´t find the corresponding local folder. Can you give me a hint?

It is the project folder you are currently working in. It's root folder is where your .ftpconfig file sits. But the file may be in a subfolder if you created it in one. It will be different for user to user and project to project. It's specific location is shown in the error. (Or at least it was for me when I had this issue 2 years ago.)
