### ISSUE TITLE
Windows path in config

### ISSUE THREAD

**Issue by jadjay** [icetee/remote-ftp#1130]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/icetee/remote-ftp/issues

### Description

Don't know how to write a windows path in the .ftpconfig file

### Steps to Reproduce

1. Put a cygwin ssh key in privatekey with windows PATH style (C:\blabla\)
1. Try to connect
1. You get message : **"Unexpected token i in JSON at position 638"**

**Reproduces how often:** Every time

### Versions

atom 1.23.3

**Comment by icetee** [comment]
`~/.ssh/rsa_id` or `~\\.ssh\\rsa_id`

**Comment by jadjay** [comment]
? Remote ftp know where cygwin is ?

**Comment by icetee** [comment]
Remote-ftp no supported Cygwin, but supported OpenSSH (included Cygwin). The default SSH key location `~/.ssh/` folder. The `~` is a home directory in Unix, Linux and Windows 10. (But I find the character and replace manual the real home directory in code.)

This works only SFTP. https://github.com/icetee/remote-ftp/issues/216#issuecomment-330403128

Your JSON not valid... try normal `slash` or try `double backslash`.

**Comment by icetee** [comment]
No Feedback. It is closed.
