### ISSUE TITLE
Tab is missing if switching projects

### ISSUE THREAD

**Issue by andreknieriem** [icetee/remote-ftp#1137]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/icetee/remote-ftp/issues

### Description

If I change my project to another the remote-ftp Tab is missing. I have to do toggle the plugin two times to bring it back again.

### Steps to Reproduce

1. Open project
2. connect to project
3. switch project
4. Tab is missing now
5. Packages / Remote FTP / Toggle
6. Packages / Remote FTP / Toggle
7. Now Tab is visible again

**Expected behavior:**
Tab is always visible

**Actual behavior:**
Tab is missing

**Reproduces how often:**
Everytime

### Versions
1.24.0 Windows 10 64bit

**Comment by icetee** [comment]
Hi, thanks for report! I fixed, will be included in the next version.

Behavior:

State | Visibility | Dock location | Dock attached
----- | ------- | --- | ---
Close (virgin project) | No visible (default) | Left (default) | No
Open | Visible | Variable (left, right, bottom) | Yes
Close | Unvisible | - | No

Within a given project, it saves the changes.
