### ISSUE TITLE
Is there no way to use this with long remote banners?

### ISSUE THREAD

**Issue by samarth-b** [icetee/remote-ftp#1145]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    [X] Checked that your issue isn't already filed: https://github.com/icetee/remote-ftp/issues

### Description
My remote server has a long banner and this causes sftp to return "Received message too long". 
Since ftp is not supported on MacOS Sierra, what is the alternative? 

The banner can not be removed (public cloud server)

### Steps to Reproduce

1. sftp login to a remote machine with long welcome message (or banner)
2. tried sftp -q doesnt work.

**Expected behavior:** Should have logged in

**Actual behavior:** Just blank after "connecting to remote"

**Reproduces how often:** 100%

### Versions

You can get this information from copy and pasting the output of `atom --version` from the command line. Also, please include the OS and what version of the OS you're running.

Atom    : 1.25.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
OS: MacOS Sierra 

### Additional Information

Is there no alternative to sftp or any flag to ignore banner? I saw some way to increase buffer size with -B but it didnt help. Any hack to .bashrc to suppress banner is also useful.

**Comment by icetee** [comment]
I do not think it could be banned in this form. Have you ever found a solution?

If I guess I don't work with command line ssh. So this issue is over. This is rather a server-side problem.

If you have a solution, I'm happy to implement it.

**Comment by samarth-b** [comment]
Yes, its the ECHO commands in .bashrc that causes the problem, not the actual banner. 
https://bugzilla.redhat.com/show_bug.cgi?id=20527

Please close. Thanks.
