### ISSUE TITLE
"Remote" panel label after "Project"?

### ISSUE THREAD

**Issue by niccolomineo** [icetee/remote-ftp#1148]
Hi, can you make so that the "Remote" panel label shows up after "Project", as shown below?

![schermata 2018-04-04 alle 12 06 22](https://user-images.githubusercontent.com/5409469/38301689-9e4a7ac0-3800-11e8-8bcd-292834b000de.png)

**Comment by Devligue** [comment]
And how it looks normally? Because on Windows it looks exactly like you want:

![screenshot](https://i.imgur.com/uuuYosh.png)

**Comment by icetee** [comment]
@niccolomineo I do not really understand the question. The panels are freely movable with drag and drop.
