### ISSUE TITLE
Download broken

### ISSUE THREAD

**Issue by grenierdev** [icetee/remote-ftp#115]
Atom 0.209
Remote-FTP 0.7.1

Downloading a folder create bunch of local root folder in the form of `name.substr(1)`

**Comment by JamesCoyle** [comment]
Same problem here on the same version. It downloads individual files correctly but when downloading directories the first 12 letters are removed and the folders are empty. The log says 'No such file or directory' but the files are on the server and shown in the FTP tree view correctly.

**Comment by fzhukov** [comment]
Same problem.

**Comment by jpxd** [comment]
I just tested this and it seems to work now. Please reopen if this is still an issue

**Comment by JamesCoyle** [comment]
Yep seems to work for me too. Will keep an eye on it just in case.
