### ISSUE TITLE
SSH config is not loaded when sshConfigPath is not set

### ISSUE THREAD

**Issue by sparanoid** [icetee/remote-ftp#1151]
### Description

SSH config is not loaded when `sshConfigPath` is not set in settings.

### Steps to Reproduce

1. Leave `sshConfigPath` unset.
2. Use custom hostname like `"host": "webserver-la-2"` in `.ftpconfig`.
3. Try to connect to the server then you will got connection error

**Expected behavior:** 
Supposed to read `~/.ssh/config` by default, connection should be made without any issue.

**Actual behavior:** 
Connection error

**Reproduces how often:** 
100%

### Versions

```shell
$ atom --version
Atom    : 1.25.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
```

### Additional Information

N/A

**Comment by bearpaw** [comment]
Hi @sparanoid , can you share your `.ftpconfig` file and `~/.ssh/config` file? Thank you very much!

**Comment by icetee** [comment]
Settings must specify the path for the configuration. I changed the default value, but only next version included. (Look at this)
