### ISSUE TITLE
Remote-FTP Not Working

### ISSUE THREAD

**Issue by oghngroup** [icetee/remote-ftp#116]
So, remote-ftp was working fine and it would automatically load when atom was opened.
Suddenly, it doesn't open when atom is opened and nothing happens when I hit connect.

**Comment by josephmiclaus** [comment]
What version of Remote-FTP do you have installed ? 
Also, have you tried restarting Atom and then retrying to connect ?
Do you still have a .ftpconfig file with currently valid settings ?

**Comment by oghngroup** [comment]
I have version 0.7.1 installed.
Restarting atom didn't work.

Also, the settings are valid.

**Comment by jpxd** [comment]
Still the same problem ? Try to look into the Developer console...

**Comment by oghngroup** [comment]
I got it to work.
Thanks
