### ISSUE TITLE
Why no pointer-events on directory elements?

### ISSUE THREAD

**Issue by niccolomineo** [icetee/remote-ftp#1166]
Hi, I would like to style the directory hover effect in remote ftp's tree list, but the `none`ing of the `pointer-events` property in the `.remote-ftp-view .ftptree-view.list-tree .header` rule makes it impossible to actually use a custom effect. I am wondering whether you set that property to `none`for a specific reason.

Thank you and keep up the great job on this essential plugin.

**Comment by icetee** [comment]
I don't quite understand, you want your own effect? If yes, try to overwrite the focus rule. The standard [atom-dark-ui](https://github.com/atom/atom-dark-ui) updated, so it was necessary.

https://github.com/icetee/remote-ftp/blob/00db9569287d72b09e2a0159ff8f8e4797dce28e/styles/remote-ftp.less#L170-L230
