### ISSUE TITLE
Use drag and drop on Remote FTP

### ISSUE THREAD

**Issue by samuelesantoni** [icetee/remote-ftp#1168]
Hi! I use Remote FTP 2.2.0 and now support drag and drop (https://github.com/icetee/remote-ftp/blob/master/CHANGELOG.md 1) 

I have tried to drag an image from my desktop but doesn't work. 
How can i use drag and drop in Remote FTP?
Thanks.

**Comment by icetee** [comment]
Hi, not yet supported IPC transfer (from outsite Atom IDE). This changes only between two tree-view work. Or does not it work?

**Comment by samuelesantoni** [comment]
ah! but is possible drag and drop file from desktop BUT inside atom? (see my screenshot)
![screen](https://user-images.githubusercontent.com/19838074/40355158-f9215c04-5db5-11e8-92a7-15352868e5d3.png)

**Comment by icetee** [comment]
It can be used.

![atom_drag_and_drop](https://user-images.githubusercontent.com/1855340/40515428-0af7ce24-5fad-11e8-9968-ff42ee277d99.gif)

**Comment by samuelesantoni** [comment]
Wow! Thanks for your gif! ok, first i copy the file im my project folder after with drag and drop on server.
