### ISSUE TITLE
Add a file/folder fails unless parent directory is selected

### ISSUE THREAD

**Issue by lukepighetti** [icetee/remote-ftp#1171]
The keybindings don't match Atom's project tree bindings, which would be preferred by this user.

More importantly, if you have a file selected and try to add a new file, it gives an error, instead of just trying to add it to the parent directory.

**Comment by icetee** [comment]
Yes, there are many features that do not exist. Or not been dumped into command. I added available commands to keymaps: https://github.com/icetee/remote-ftp/commit/28516d9324cfa7a0a1981836463aa6e4039188eb The full list [here](https://github.com/atom/tree-view/blob/master/keymaps/tree-view.cson). Maybe Pull Request?

**Comment by icetee** [comment]
No response, I closed the issue. More keymap added.
