### ISSUE TITLE
Watchers not working on 2.2.0

### ISSUE THREAD

**Issue by ignacionelson** [icetee/remote-ftp#1172]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/icetee/remote-ftp/issues

### Description

After updating to 2.2.0, watchers are not working anymore.
If I save a compiled css file manually, it is uploaded, but when it is compiled from a sass source it doesn't get uploaded automatically.
It was working fine on 2.1.4.
Already tried disabling all other packages.

The notification for watchers being added correctly appears after connecting.

Rolling back manually to 2.1.4 made the watchers work again :(

### Versions

Atom    : 1.27.1
Electron: 1.7.15
Chrome  : 58.0.3029.110
Node    : 7.9.0
Windows 10 64bit

**Comment by icetee** [comment]
Hi, I need more information!

- How is it configured watch property in ftpconfig?
- FTP or SFTP?

I try again, and works. Even now wildcard is okay.
Need to give you access relatively path(s). (The base path the actual project folder.)

I tested configs:
```
"watch": [
  "keymaps"
],
```

```
"watch": [
  "bower_components/**/*.css"
],
```

**Comment by ignacionelson** [comment]
Hi!
Finally found the problem.
I have all of my watchers paths start with ./
For example:

`"watch": [
	"./file.min.css"
],`

This worked fine up until 2.1.4, but on 2.2.0 I need to remove ./ for the watchers to work again :)

**Comment by icetee** [comment]
Super! :)
I close this issue!

**Comment by ignacionelson** [comment]
Great! But please keep this issue in mind, as the example on the readme file uses ./ on the watchers.
I don't think that it needs to be replaced, but maybe add a little note? :)
