### ISSUE TITLE
Keybindings not working properly

### ISSUE THREAD

**Issue by arielnoname** [icetee/remote-ftp#118]
My keymap file:

'.platform-darwin .workspace .editor':
  'shift-cmd-z': 'remote-ftp:toggle'

Tried with several hotkeys. Sometimes it works, sometimes it doesn't.
Works almost every time I'm in the editor.

**Comment by arielnoname** [comment]
I was checking my atom after the 0.210.0 and I had 2 deprecations. Was for the keybindings.

If I write .atom-workspace and .aton-editor instead of .workspace and .editor the Keybindings doesn't work at all.

**Comment by hatzopoulos** [comment]
@arielnoname is this still an issue for you with the latest version?
