### ISSUE TITLE
Tree view font size

### ISSUE THREAD

**Issue by btstw** [icetee/remote-ftp#1184]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/icetee/remote-ftp/issues

### Description

I was using One Dark theme it can customize font size.
Since you already fix the font-size it might overwrite my theme font size setting.

### Steps to Reproduce

1. Use One Dark Theme
2. Set font size : 14
3. Open tree of remote ftp

**Expected behavior:** [What you expect to happen]

font size of remote ftp tree view should be same as the original tree view

**Actual behavior:** [What actually happens]
![screenhunter_01 jun 13 17 27](https://user-images.githubusercontent.com/25838252/41342917-ea61a9ea-6f2f-11e8-8333-80a8061b405d.gif)
![screenhunter_02 jun 13 17 28](https://user-images.githubusercontent.com/25838252/41342918-ea8a26fe-6f2f-11e8-9a9c-7bf56f736a22.gif)

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

You can get this information from copy and pasting the output of `atom --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

I fix this by modify remote-ftp.less in line 171
--font-size: @font-size;
++font-size: @ui-size;

**Comment by icetee** [comment]
I changed, thanks.
