### ISSUE TITLE
No longer works after last update

### ISSUE THREAD

**Issue by adamparr** [icetee/remote-ftp#1189]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/icetee/remote-ftp/issues

### Description

Uncaught Error: Unexpected packet before version
events.js:183

Error thrown after most recent update to this package. Updated Atom as well with same result.
It is shown when I try connect, everytime.

### Steps to Reproduce

1. Trying to connect to FTP via CMD + S or packages > remote-ftp > connect.

**Expected behavior:** [What you expect to happen]

It to connect

**Actual behavior:** [What actually happens]

Error thrown described abouve

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

Currently on Atom version 1.28.0.
macOS High Sierra 10.13.5 

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by icetee** [comment]
Please paste full error message from console. FTP or SFTP protocol?

**Comment by adamparr** [comment]
**Atom**: 1.28.0 x64
**Electron**: 2.0.3
**OS**: Mac OS X 10.13.5
**Thrown From**: [remote-ftp](https://github.com/icetee/remote-ftp) package 2.2.0


### Stack Trace

Uncaught Error: Unexpected packet before version

```
At events.js:183

Error: Unexpected packet before version
    at SFTPStream._transform (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:304:27)
    at SFTPStream.Transform._read (_stream_transform.js:186:10)
    at SFTPStream._read (/packages/remote-ftp/node_modules/ssh2-streams/lib/sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at SFTPStream.Writable.write (_stream_writable.js:290:11)
    at Channel.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Channel.emit (events.js:211:7)
    at Channel.Readable.read (_stream_readable.js:475:10)
    at flow (_stream_readable.js:846:34)
    at resume_ (_stream_readable.js:828:3)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
     -0:21 window:toggle-dev-tools (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
atom-beautify 0.32.5 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.1.3 
file-icons 2.1.21 
fold-lines 0.2.2 
fonts 3.1.0 
goto-definition 1.3.4 
highlight-selected 0.13.1 
minimap 4.29.8 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
nucleus-dark-ui 0.12.3 
php-cs-fixer 4.1.1 
pigments 0.40.2 
remote-ftp 2.2.0 
```

using SFTP

**Comment by icetee** [comment]
The `remote-ftp` uses https://github.com/mscdex/ssh2. I think is not this package issue. We can try to refresh it, but I think the bug is still alive.

There are several packages that are affected by this:
https://github.com/yongkangchen/remote-sync/issues/460
https://github.com/liximomo/vscode-sftp/issues/202

You can back to any previous version
```
apm remove remote-ftp
apm install remote-ftp@2.1.4
```

(The last upgrade `SSH2` and `SSH2-streams` in [v1.3.4](https://github.com/icetee/remote-ftp/releases/tag/v1.3.4))

**Comment by icetee** [comment]
Did I upgrade to let you test it?

```
apm remove remote-ftp
cd ~
git clone https://github.com/icetee/remote-ftp
cd remote-ftp
git checkout develop
apm install
apm link .
```

**Comment by adamparr** [comment]
Fixed! Not sure what happened. Think the refresh fixed it. Thanks
