### ISSUE TITLE
Multiple servers in one config

### ISSUE THREAD

**Issue by vanbroup** [icetee/remote-ftp#122]
I would like to have support for multiple servers in a single project. The first 'directory' in the tree could simply be the server identifier (maybe a 'name' or 'label' option in the config).

The config could be transferred to an array to support this.

``` json
[{
    "protocol": "sftp",
    "host": "server.com"
},{
    "protocol": "sftp",
    "host": "my.domain.net"
}]
```

**Comment by d3f3kt** [comment]
would be a great feature!

**Comment by hatzopoulos** [comment]
see https://github.com/mgrenier/remote-ftp/issues/122

**Comment by hatzopoulos** [comment]
see https://github.com/mgrenier/remote-ftp/issues/44

**Comment by jimmaaay** [comment]
See #469
