### ISSUE TITLE
Post Install Error Nov. 2018

### ISSUE THREAD

**Issue by fman29** [icetee/remote-ftp#1220]
### Prerequisites

* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/icetee/remote-ftp/issues

### Description

[Description of the issue]

### Steps to Reproduce

1. Looked up remote-ftp in the Package Installer on Atom
2. Clicked the Install button
3. Waited until I got the mesage(s) posted below

**Expected behavior:** I expected Atom to install remote-ftp and allow me to us it.

**Actual behavior:** The installation fails.

**Reproduces how often:** So far, 3 out of 3 attempts.  So 100% of the time.

### Versions

Atom    : 1.32.2
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3
Running on Ubuntu 18.04.1
Gnome 3.28.2
Intel® Core™ i7 CPU 920 @ 2.67GHz × 8 

You can get this information from copy and pasting the output of `atom --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

This is the/These are the message(s) I received:

 remote-ftp@2.2.0 postinstall /tmp/apm-install-dir-1181015-20572-1ymdtux.8npq/node_modules/remote-ftp
> opencollective postinstall

sh: 1: opencollective: Permission denied
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-1181015-20572-1ymdtux.8npq/package.json'
npm WARN apm-install-dir-1181015-20572-1ymdtux.8npq No description
npm WARN apm-install-dir-1181015-20572-1ymdtux.8npq No repository field.
npm WARN apm-install-dir-1181015-20572-1ymdtux.8npq No README data
npm WARN apm-install-dir-1181015-20572-1ymdtux.8npq No license field.

npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! remote-ftp@2.2.0 postinstall: `opencollective postinstall`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the remote-ftp@2.2.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.atom/.apm/_logs/2018-11-15T06_46_54_684Z-debug.log

**Comment by modnar1226** [comment]
Can also confirm this error. i have downloaded this previously and it works great. would love to see it back up. going to see if i cant build a previous version.

**Comment by icetee** [comment]
I removed opencollective in the new version.

**Comment by modnar1226** [comment]
what luck i was in the middle of trying to take care of the errors it was giving me and than boom, it worked. more likely your doing than mine lol. thank you!
