### ISSUE TITLE
Multiple hosts in 2.2.1

### ISSUE THREAD

**Issue by Seand1796** [icetee/remote-ftp#1225]
## Description

Multiple hosts does not work

### Steps to Reproduce

1. Enable multiple hosts
2. Open >2 projects
3. Connect to second project
4. You are connected to first project :D

**Expected behavior:** [What you expect to happen]
Connect to second project

**Actual behavior:** [What actually happens]
You can only connect to the first project

**Reproduces how often:** [What percentage of the time does it reproduce?]
is always

### Versions
2.2.1

### Additional Information
You are a great developer!
I used this plugin and it is the fastest!
Thanks you;

**Comment by icetee** [comment]
Hi!

Unfortunately, it never worked. Long time ago added, but in Beta state.

My old desire to be able to work this way.

Thanks the report, but I close this issue, because it is duplicated. Related of https://github.com/icetee/remote-ftp/issues/815

**Comment by Seand1796** [comment]
> Hi!
> 
> Unfortunately, it never worked. Long time ago added, but in Beta state.
> 
> My old desire to be able to work this way.
> 
> Thanks the report, but I close this issue, because it is duplicated. Related of #815

@icetee , [it great works in 2.2.0](https://drive.google.com/file/d/1ruWmSQMeGNFU7eyiOYNdTJ7EoVNrnf1v/view?usp=sharing) and it is very important function for me :)
If you can, please, fix it
Even if at the cost of some mistakes, it allows to work with several projects very, very quickly!
