### ISSUE TITLE
Connection fails when using keyboard shortcuts (2.2.1 + 2.2.2)

### ISSUE THREAD

**Issue by matthew-e-brown** [icetee/remote-ftp#1229]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/icetee/remote-ftp/issues

Similar issues have been filed, but none bring up my specific problem.

### Description

Since updating to re mote-ftp 2.2.1, the keyboard shortcut (`CTRL+ALT+C`) to connect fails. I can connect normally by switching to the Remote tab and clicking on Connect.

### Steps to Reproduce

1. Create SFTP config file / use previously functioning one
2. Attempt to connect using keyboard shortcut `CTRL+ALT+C`

**Expected behavior:** Connection established successfully.

**Actual behavior:** Error thrown:

>Remote FTP: Could not read `.ftpconfig` file.
>```
>Error: ENOENT: no such file or directory, open 'C:\Users\Matthew\.ssh\config'
>```

**Reproduces how often:** 100% of the time when using keyboard shortcut, 0% when manually clicking the button.

### Versions

Atom    : 1.32.2
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3

**Windows 10**
Version : 1803
OS build : 17134.345

### Additional Information

Issue #1221 brings up a similar problem, but with a solution that did not work for me. I have no `.ssh` directory in my Users folder, let alone the `known_hosts` or `config` file.

**Comment by matthew-e-brown** [comment]
> This is also happening for me, only I noticed it when using `CMD + SHIFT + P` and typing in the _ftp connect_ command and selecting it from the menu.

Command palette also spits out the error for me as well.

**Comment by furroy** [comment]
the root cause of the issue is that it now requires you have an .ssh/config file when it didn't previously care if you weren't using rsa key.  you can do anything that creates  an .ssh/config file, touch it, rename another file, copy a file, etc.  it doesn't seem to matter what's inside the file, just that it's present

**Comment by matthew-e-brown** [comment]
That fixed my problem. I literally just made an empty file, it's 0 bytes. Why is this required if it's an empty file anyways?

It was just kind of annoying to make the file and folder, since Windows doesn't let you name a folder as a .name, nor will it let you name things without a file extension. I had to use `ren` from command prompt to rename the files and folder accordingly.

**Comment by davidchoy** [comment]
Note, this is still an issue for me in Windows. Shortcut keys don't work while UI buttons do. Referencing a blank config file still fixes the problem:

1. Create a blank ssh "config" file in a place that makes sense to you
2. Reference your file in File > Settings > Packages > remote-ftp > SSH Config Path

For me, I created the file in `~/ssh/config` where `~` references my home folder in `C:/Users/UserName` (Notice the lack of the dot in ssh. You can't create a folder that starts with a dot via Explorer.)

**Comment by matthew-e-brown** [comment]
@davidchoy to make a folder with a dot starting, use CMD's `ren` something like Git Bash's `mv`.
`$ mv ssh .ssh` will do the trick. Not that I think it makes a difference in Windows, but my .ssh folder not being named properly would drive me crazy!

Although, the fact that it works fine from the GUI makes it clear that there is something to be done to make it work fine: it's just that that something has only been done on the method that the GUI uses, not the keyboard shortcut.

I think.
