### ISSUE TITLE
Upload file(s) or directory

### ISSUE THREAD

**Issue by vanbroup** [icetee/remote-ftp#125]
Currently you can only create new files or directories. It would be very useful if you can upload existing file(s) and directories to the remote server. This could save you from making a second connection with a third party file transfer client to copy for example a small library to the remote server.

**Comment by dantman** [comment]
Did you miss the "Upload" and sync up options in the tree view's context menu?
(Download and create on server options are in the remote view; Upload and create local options are in the local view)

**Comment by vanbroup** [comment]
I did indeed missed the upload function in the local menu. While this might work it's still a lot more work. You need to download everything, copy it to the local folder (first you need to find it) while I just want to upload something from my temporary folder. 

To clarify, the remote machine is actually the workspace and the desktop is really a desktop with the editor. Everything (including git) is done from the remote machine, the local system is just one of my clients where the data is not in sync.

It would be great if you are not required to use the local Tree View for these simple tasks.
