### ISSUE TITLE
Uncaught TypeError: Cannot read property '_pasvSocket' of null

### ISSUE THREAD

**Issue by 78points** [icetee/remote-ftp#126]
Uncaught TypeError: Cannot read property '_pasvSocket' of null

TypeError: Cannot read property '_pasvSocket' of null
  at /Users/admin/.atom/packages/Remote-FTP/lib/connectors/ftp.js:315:19

**Comment by 78points** [comment]
it happens only when creating new file

**Comment by 78points** [comment]
fixed by reinstalling linter-php package

**Comment by SmartyB** [comment]
Same problem here, reinstalling linter-php worked for me as well. Thanks!

# 

**Atom Version**: 1.0.2
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.7.1

### Stack Trace

Uncaught TypeError: Cannot read property '_pasvSocket' of null

```
At C:\Users\...\.atom\packages\Remote-FTP\lib\connectors\ftp.js:176

TypeError: Cannot read property '_pasvSocket' of null
    at C:\Users\...\.atom\packages\Remote-FTP\lib\connectors\ftp.js:176:23
```

### Commands

```
     -0:21.1.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:21.1.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:14.9.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:14.9.0 core:cancel (atom-text-editor.editor.is-focused)
```
