### ISSUE TITLE
Undocumented config

### ISSUE THREAD

**Issue by kkevindev** [icetee/remote-ftp#1265]
### Description

README.md show's:

**FTP & FTPS Configuration Options**

```
{
    "protocol": "ftp",
    "host": "example.com", // string - The hostname or IP address of the FTP server. Default: 'localhost'
    "port": 21, // integer - The port of the FTP server. Default: 21
    "user": "user", // string - Username for authentication. Default: 'anonymous'
    "pass": "pass", // string - Password for authentication. Default: 'anonymous@'
    "promptForPass": false, // boolean - Set to true for enable password dialog. This will prevent from using cleartext password in this config. Default: false
    "remote": "/",
    "secure": false, // mixed - Set to true for both control and data connection encryption, 'control' for control connection encryption only, or 'implicit' for implicitly encrypted control connection (this mode is deprecated in modern times, but usually uses port 990) Default: false
    "secureOptions": null, // object - Additional options to be passed to tls.connect(). Default: (null) see https://nodejs.org/api/tls.html#tls_tls_connect_options_callback
    "connTimeout": 10000, // integer - How long (in milliseconds) to wait for the control connection to be established. Default: 10000
    "pasvTimeout": 10000, // integer - How long (in milliseconds) to wait for a PASV data connection to be established. Default: 10000
    "keepalive": 10000, // integer - How often (in milliseconds) to send a 'dummy' (NOOP) command to keep the connection alive. Default: 10000\. If set to 0, keepalive is disabled.
    "watch":[ // array - Paths to files, directories, or glob patterns that are watched and when edited outside of the atom editor are uploaded. Default : []
        "dist/stylesheets/main.css", // reference from the root of the project.
        "dist/stylesheets/",
        "dist/stylesheets/*.css"
    ],
    "watchTimeout":500 // integer - The duration ( in milliseconds ) from when the file was last changed for the upload to begin.
}
```

However, generating an ftp/sftp file gets you this:
```
{
    "protocol": "sftp",
    "host": "example.com",
    "port": 22,
    "user": "user",
    "pass": "pass",
    "promptForPass": false,
    "remote": "/",
    "local": "",
    "agent": "",
    "privatekey": "",
    "passphrase": "",
    "hosthash": "",
    "ignorehost": true,
    "connTimeout": 10000,
    "keepalive": 10000,
    "keyboardInteractive": false,
    "keyboardInteractiveForPass": false,
    "remoteCommand": "",
    "remoteShell": "",
    "watch": [],
    "watchTimeout": 500
}
```

This includes the `local` option, that's undocumented in the README.md, it's unclear what it does.

### Versions

remote-ftp 2.2.2

### Additional Information

fix: explain in README.md what the options does.
`"local": "" // explain here`

**Comment by Christopher-Eli-Oswald** [comment]
After some testing I'm pretty sure that the local settings is just a way to set the project folder where you want the files to be stored on your local machine. If you just remove the setting remote-ftp has a way to tell where you might want the files. I'm guessing that's why you need to open a project folder in Atom. Hope this helps.

**Comment by kkevindev** [comment]
https://github.com/icetee/remote-ftp/issues/1265#issuecomment-486117603

I’ve tried to set it to a ‘src’ folder, that didn’t work.

**Comment by Christopher-Eli-Oswald** [comment]
> [#1265 (comment)](https://github.com/icetee/remote-ftp/issues/1265#issuecomment-486117603)
> 
> I’ve tried to set it to a ‘src’ folder, that didn’t work.

I think it might be the same as the 'remote' setting where you need to use absolute paths starting with '/'

I was having problems and I did that and it seems to be working now.

**Comment by kkevindev** [comment]
> > [#1265 (comment)](https://github.com/icetee/remote-ftp/issues/1265#issuecomment-486117603)
> > I’ve tried to set it to a ‘src’ folder, that didn’t work.
> 
> I think it might be the same as the 'remote' setting where you need to use absolute paths starting with '/'
> 
> I was having problems and I did that and it seems to be working now.

Shouldn't `"local": "./src"` work then, since `./` is an 'absolute' path to the current directory?

**Comment by Christopher-Eli-Oswald** [comment]
> > > [#1265 (comment)](https://github.com/icetee/remote-ftp/issues/1265#issuecomment-486117603)
> > > I’ve tried to set it to a ‘src’ folder, that didn’t work.
> > 
> > 
> > I think it might be the same as the 'remote' setting where you need to use absolute paths starting with '/'
> > I was having problems and I did that and it seems to be working now.
> 
> Shouldn't `"local": "./src"` work then, since `./` is an 'absolute' path to the current directory?

Maybe try it without the . (dot)
