### ISSUE TITLE
Remote files not downloading

### ISSUE THREAD

**Issue by MattGHarvey** [icetee/remote-ftp#1288]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/icetee/remote-ftp/issues

### Description

When attempting to download a file via FTP, download seems to initiate but never completes. Status just says "Downloading <filename>"
### Steps to Reproduce

1. Connect to remote server
2. Double click file in filetree to initiate download
3. Download never completes

**Expected behavior:** [What you expect to happen]
File downloaded and opened in Atom
**Actual behavior:** [What actually happens]
File download does not complete
**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Versions
Atom    : 1.39.1
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0
Microsoft Windows [Version 10.0.18362.239]

You can get this information from copy and pasting the output of `atom --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by paokodo** [comment]
Yes, Me too.
Download never completes.
Donwloading ......  0s

Versions
Atom    : 1.40.0
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0

**Comment by david43** [comment]
#1286

**Comment by icetee** [comment]
Duplicated of #1286
