### ISSUE TITLE
Unable to completely download a directory

### ISSUE THREAD

**Issue by fseminario** [icetee/remote-ftp#129]
Made a screencast of the issue
https://drive.google.com/file/d/0B0bbDSCtovQIazUzc25ORWlfU1k/view?usp=sharing

Remote FTP 0.7.1
Atom 1.0.0 (1.0.0)
Mac OS X Yosemite 10.10.3

**Comment by ghost** [comment]
Same issue. It downloads the folder, but not the contents. Feature or bug?

**Comment by jpxd** [comment]
Should be working by now. Please reopen if this is still an issue
