### ISSUE TITLE
Feature Request: Connect / Disconnect Button 

### ISSUE THREAD

**Issue by andriaripratama** [icetee/remote-ftp#134]
Hi!

I love using your package Remote-FTP.
I'm request to add shortcut button on connect and disconnect Remote FTP.

Thanks!

**Comment by arielnoname** [comment]
I think you could use a keybinding.
Or you could also use this package: https://atom.io/packages/tool-bar

Cheers

**Comment by jpxd** [comment]
Or you use atoms [command palette](https://atom.io/docs/latest/getting-started-atom-basics#command-palette). Just type in "ftp". It's a really fast way to access all features of atom (its faster to use your keyboard when coding than to reach out to your mouse in between).

**Comment by simultsop** [comment]
Disconnect button still missing in 0.8.3

**Comment by jpxd** [comment]
The connect button is already there. And for connecting/disconnecting we have the menu, keybindings and the command palette. I think the disconnect button would be too much in the remote tree view with lots of files.
