### ISSUE TITLE
Secure FTP issue

### ISSUE THREAD

**Issue by ghost** [icetee/remote-ftp#137]
Hello,

I am trying to login to my secured FTP.
I configured my FTP server to avoid "cleartext".

The "secure" option in the .ftpconfig file is set to true.

I am able to login to my FTP server, but thats it. Atom does not shown my server's contents.

If setting the secure to "false"and disabling my FTP security to accept cleartext on my server, everything works.

Any advice?

Thanks.

**Comment by jpxd** [comment]
Please try to connect in secure mode and open the Developer Console (View->Developer->Toggle Developer Tools) to view the FTP debug output and paste it here
