### ISSUE TITLE
Add Connect/Disconnect to Context Menu

### ISSUE THREAD

**Issue by JamesCoyle** [icetee/remote-ftp#138]
It would be really helpful to be able to quickly disconnect from the FTP server by right clicking on the FTP treeview and selecting disconnect. I'd rather not have to set up/remember a hotkey to do something which is rarely ever required but searching the packages menu for 'RemoteFTP' is rather irksome.

**Comment by jpxd** [comment]
Related to #134

You can just type in `ftp` in Atom's command palette to see connect/disconnect

**Comment by JamesCoyle** [comment]
I always right click on the treeview to do it out of habit. The treeview is more of a mouse based control so it would be nice to have the option available to the mouse as well as the keyboard.

**Comment by jpxd** [comment]
Feel free to submit a PR :)
Shouldn't be too hard to implement that

**Comment by JamesCoyle** [comment]
I'll have a look into it. Still haven't really used github so I forget I can do that haha.

**Comment by jpxd** [comment]
It's not that hard :)
- Fork the remote-ftp repository
- Clone it somewhere on your PC (e.g. `git clone https://github.com/SolusSoftworks/remote-ftp.git`)
- CD into it in terminal, install dependencies with `apm install` and make Atom use your development version with `apm link`
- Create your own feature branch with e.g. `git branch feature-connect-in-contextmenu` and check it out `git checkout feature-connect-in-contextmenu`
- Code your feature and test it (You can reload Atoms packages in Atoms Command Palette with "window reload", so you don't have to reopen it all the time to test changes)
- Commit your code and push it to your fork on Github
- Go on Github and create a pull request

**Comment by jpxd** [comment]
This feature already exists in the latest version :)

**Comment by JamesCoyle** [comment]
The current version seems to be broken for me after the update. Reinstalling seems to fix it but could be something to be aware of if others are having issues. 
![image](https://cloud.githubusercontent.com/assets/10384436/23189599/99894f4e-f88b-11e6-8173-9bc99cdd04bf.png)

**Comment by jpxd** [comment]
Because even the settings pane is broken and the author label states `undefinded` this looks more like an Atom bug to me....

**Comment by JamesCoyle** [comment]
It looks like atom didn't download the files properly or something like that when it updated as there was no functionality at all. Figured I'd just make you aware of the issue in case people start opening issues here looking for a fix.

**Comment by jpxd** [comment]
Thanks :)
