### ISSUE TITLE
Explicit SSL/TLS

### ISSUE THREAD

**Issue by NejcZdovc** [icetee/remote-ftp#140]
Hi,

can you please help with config file.

I get the following error: Remote FTP: Error: Have to use explicit SSL/TLS before logging on. 

In filezilla I set Require implicit FTP over TLS and it works, but here I don't know how to set this.

When I was browsing trough documentation about tls.connect, I find this tag "rejectUnauthorized", but don't know how to use it in config file or if this is even the solution to my problem.

Thank you for the help and your work,
Nejc

**Comment by UziTech** [comment]
I got explicit tls working with the following settings:

```
    "secure": true,
    "secureOptions": {"rejectUnauthorized": false},
```

**Comment by NejcZdovc** [comment]
Thank you, it's working now.
