### ISSUE TITLE
vscode version

### ISSUE THREAD

**Issue by G33kNoob** [icetee/remote-ftp#1402]
please make ths plugin available on Vscode please.

**Comment by SlimJim192** [comment]
+1 - cant find anything that compares and atom is due to die soon!

**Comment by G33kNoob** [comment]
yea, i got simple-ftp and its better then this remote-ftp

**Comment by Weblure** [comment]
> yea, i got simple-ftp and its better then this remote-ftp

Which one are you using? I couldn't find anything that 'just works' in the way remote-ftp did. I really liked how remote-ftp would save a config file locally in the directory you're working in, and then just automatically use that to connect to the right host with the right settings.

All the FTP extensions for VSCode seem to require some kind of global config file and custom paths and whatnot, which is a huge pain when you're managing 20 different websites.

**Comment by zhaoest** [comment]
> please make ths plugin available on Vscode please.

https://github.com/ayuayue/sftp-tools
