### ISSUE TITLE
Uncaught Parse error in `.ftpconfig` JSON : SyntaxError: Unexpected token K

### ISSUE THREAD

**Issue by Karuma** [icetee/remote-ftp#142]
[Enter steps to reproduce below:]
1. I use azure and user name there looks like "projectname\username" 
2. when i try make a connection a get json error Token K
3. some azure username can look like "projectname\$projectname" and then i error with $

**Atom Version**: 1.0.0
**System**: Microsoft Windows 8.1
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.7.1
### Stack Trace

Uncaught Parse error in `.ftpconfig` JSON : SyntaxError: Unexpected token K

```
At C:\Users\Admin\.atom\packages\Remote-FTP\lib\client.js:78

undefined
```
### Commands

```
     -0:12.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:08.9.0 remote-ftp:toggle (atom-text-editor.editor.is-focused)
     -0:02.7.0 remote-ftp:connect (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.7
file-icons, v1.5.8
Remote-FTP, v0.7.1

# Dev
No dev packages
```

**Comment by djbusby** [comment]
Don't you need to escape the \ in your JSON?  Like:

```
"user": "project_name\\$username",
```
