### ISSUE TITLE
Refuses to work...?

### ISSUE THREAD

**Issue by mark-ross** [icetee/remote-ftp#148]
After working through remote-ftp for the past few days to connect to a locally hosted virtual machine, the entire plugin has completely stopped working.  Basically, the plugin worked yesterday, and today it will not respond to any commands.  I have not changed any settings between the two days.

OS: Windows 7, 64-bit Enterprise
Running: Atom, 64-bit

What kind of information would make replicating this error easier?  I'd be glad to provide anything else!

**Comment by jpxd** [comment]
Did you try to reinstall the package ? Do you use the latest version of Atom & Remote-FTP ?

**Comment by markentingh** [comment]
this is happening to me too. Just installed latest version of Atom, can connect to remote server, but doing anything else has proved unresponsive. Can't upload, sync, or download. I just realized that there is a very small status bar at the bottom of the remote sidebar that, when resized vertically, will display a list of commands being sent to the FTP server. perhaps that should be made more clear to the user?

**Comment by pjrfigueiredo** [comment]
Same here.
I'm new to atom.io...
After the fresh install remote-ftp worked perfectly... when I tried to create a new connection on a new window nothing happened... reopened atom - nothing -...

Nothing from the Packages -> Remote-FTP works :(

**Comment by pjrfigueiredo** [comment]
OK!
realised that we need to have a project open...
that way it will work.
