### ISSUE TITLE
Excluding files/folders

### ISSUE THREAD

**Issue by mwolfindale** [icetee/remote-ftp#149]
Would be great to have the option in the configuration file to ignore files/folders.

Either:
- in the same way as Sublime SFTP (http://wbond.net/sublime_packages/sftp/settings#setting-ignore_regexes)
- parse the `.gitattributes` file for lines ending in `export-ignore` (https://feeding.cloud.geek.nz/posts/excluding-files-from-git-archive/) - these files/folders are excluded from `git archive`

**Comment by jpxd** [comment]
Duplicate to #36
