### ISSUE TITLE
Where are passwords saved?

### ISSUE THREAD

**Issue by jford1** [icetee/remote-ftp#152]
I wasn't sure if when setting up a .ftpconfig file, the password is stored safely. I know programs like filezilla store the password in plain text, which is a big vulnerability if there is malware out there targeting Atom.

**Comment by zenopopovici** [comment]
It's stored in plaintext in the config file. You may want use a RSA Key if you want it to be secure.

**Comment by jpxd** [comment]
Use public-key authentication for SFTP as suggested by @zenopopovici. For FTP we will soon have a possibility to ask for the password every time so it doesn't need to be stored in plain-text on disk (see PR #113).
