### ISSUE TITLE
Incorrect download folder

### ISSUE THREAD

**Issue by fzhukov** [icetee/remote-ftp#153]
Linux
Atom 1.0.0-3874576
Remote-FTP 0.7.1
Then I downloaded folder, i getting this. With single file no problems. (Sorry for my english)
![remote-ftp](https://cloud.githubusercontent.com/assets/3644240/8861840/c03223de-319d-11e5-9acc-3a1ebc7e36a1.png)

**Comment by Derekholio** [comment]
I am having this same issue. 
Windows Atom 1.0.6, Remote FTP 0.7.1.
Server: Windows 2012, FileZilla FTP server

FTP log: http://pastebin.com/GyWKySqW

It also attempts to download files inside of folders with out a CD to that folder. Ex: A download attempt of "css.css" without a CD to "/css". I'm not sure if that is related to this particular issue. Double clicking a file inside a folder will download it properly, however.

Edit: .ftpconfig http://pastebin.com/VEGj9d0L

**Comment by jpxd** [comment]
Duplicate to #115
