### ISSUE TITLE
All files are blank

### ISSUE THREAD

**Issue by JasonRaveling** [icetee/remote-ftp#154]
After connecting, tree view is populated with the contents of my remote server. When I double click a file, Atom opens a blank file with the name of the file I just tried to open. In my local tree view, I see the files are stored locally as well. These files are all empty too. 

Edit: I notice that the files get downloaded to my local `atom:` directory with all of the code in them. They are just being opened as blank in Atom.

Atom 1.0.2
Debian 8.1 (amd64)

**Comment by JasonRaveling** [comment]
So I've discovered that unless I have `~/.atom/` open as a project in my project tree, a file is created in my home directory (`~/`) called `atom:`. Inside this directory, it appears there is an infinite loop happening to create this directory. Inside the `~/atom:/` directory is another directory called `config` which has a hidden directory called `.atom`. I kept going deeper and deeper into the directories until I realized I could probably do it all night. This is what I ended up with. `~/atom:/config/.atom/atom:/config/.atom/atom:/config/.atom/atom:/config/`. Hope this helps narrow down what is happening.

**Comment by vomchik** [comment]
I have the same problem :(

**Comment by jpxd** [comment]
This is weird, still happening with the latest Atom & the latest Remote-FTP version ?

**Comment by webhacking** [comment]
same issue for me .. TT

**Comment by matthijsthoolen** [comment]
I have the same issue on Linux Mint 16. 

Latest Atom version and also latest version of Remote-FTP (0.7.8)

**Comment by matthijsthoolen** [comment]
Any updates?

**Comment by gbrandallen** [comment]
I'm having this same issue, has there been any progress?

**Comment by jpxd** [comment]
What is the project path?

**Comment by jpxd** [comment]
This seems to be an issue when there is no working/project directory
But it should go away after restarting Atom with the correct Project path
Please re-open if necessary

**Comment by IIYAMA12** [comment]
Now I am having the same problem. Remote-FTP 0.8.9 (mac)

"But it should go away after restarting Atom with the correct Project path
Please re-open if necessary" @ jpxd 
Doesn't work for me.

Edit: 
I noticed that atom is creating an 'I' folder, which is causing the problem. The file that is opened is blank because it doesn't add that direction while opening the file.
I am not sure how to fix this.

**Comment by EvanHerman** [comment]
I too am running into this issue. Remote connections to certain servers are empty.

**Comment by andrewgribben** [comment]
@webunraveling @jpxd I too am having this problem even when restarting and selecting a project. Opening a remote file downloads the file to a local path but seems to nest it inside a directory labelled "m" moving the contents of m to my project root and then re-opening the remote file works as intended.

**Comment by carloverhamme** [comment]
Same error here! All files are blank for me on the server, but when I check on my computer, I see the code in it

**Comment by solonmedia** [comment]
Same error. I've tried using netwrok share address directly and mapped network drive link. Windows 10. The files are saved locally and populate when opened on the local side, but are blank when opened from the remote tab.
