### ISSUE TITLE
Different settings for Auto-Upload and Auto-Connect

### ISSUE THREAD

**Issue by fly1ted** [icetee/remote-ftp#157]
Hello,

While I work on my project I have my .ftpconfig in the root. When Auto save is enabled and I try to edit any file it gets automatically connected, but I don't need that since it can be just a minor change. It would be useful to have an option to disable auto connecting.

Thanks.

**Comment by jpxd** [comment]
`Auto Upload on Save` can be disabled in the package preferences

**Comment by fly1ted** [comment]
Ok, putting it simply. Is it possible to not establish connection automatically? Then auto-upload will only work when the connection is made.
