### ISSUE TITLE
Constant connections after restarting Atom

### ISSUE THREAD

**Issue by donCarlosOne** [icetee/remote-ftp#159]
Installed  this and got it working.  That's great.  did what I needed and disconnected.  Reloaded Atom later, and remote-ftp began executing multiple conections (successful) to the server.  Did not stop, even after disabling.  Had to shut Atom down while it was disabled to get it to stop.

**Comment by jpxd** [comment]
What exactly did you disable? The complete package or the auto-uploading feature? Probably the same problem as in #163 ?
