### ISSUE TITLE
remote-ftp does not load properly on "auto"

### ISSUE THREAD

**Issue by jerometan1** [icetee/remote-ftp#16]
Remote-FTP does not load properly with the loading of Atom, but disabling and enabling it would make it fine.

**Comment by grenierdev** [comment]
Step to reproduce :
1. Open Atom
2. Open Folder...
3. Create config file
4. Toggle/connect do not show sidebar but console show that were connected to server and sending NOOP command successfuly
5. Disable + enable plugin brings back the sidebar and everything works fine

**Comment by jerometan1** [comment]
Yes correct
