### ISSUE TITLE
Download remote folder

### ISSUE THREAD

**Issue by NodexTech** [icetee/remote-ftp#160]
Every-time I try to Right click -> Download on a remote folder the plugin tells me to "Please select a folder first". 

I can only surmise that this is not intended behaviour as there is nowhere to "Select a folder first"

**Comment by JamesCoyle** [comment]
Did you try left clicking on the folder first to select it?

**Comment by jpxd** [comment]
First left-click a folder to select it, then right-click -> "Download"
