### ISSUE TITLE
Connects on save or ctrl+s

### ISSUE THREAD

**Issue by Bulmer** [icetee/remote-ftp#163]
I really liked how well this programme worked until i realised that it connects on save or ctrl+s keystroke. When I disabled it in settings it continued to try and connect, so i've had to uninstall it. Im using the latest Atom AMD64 on Debian 8.

**Comment by stdex** [comment]
+1
I'm open local file, plugin connect to ftp with save process.

**Comment by jpxd** [comment]
Hmm I can't really reproduce this behaviour...
When the auto-upload feature is disabled in the package settings it should not try to connect on save.
Is there an entry for `Remote-FTP` in your Atom's `config.cson` file (on Mac in the context menu: Atom -> Open Your Config) after you disable the setting?

**Comment by stdex** [comment]
1) Create project in /home/username/
2) Create ftp connection cfg file (in /home/username/)
3) Connect to server.
4) Disconnect from server.
5) Open file in /home/username/subdir/
6) Save file.
7) Catch ftp-connection message.

**Comment by jpxd** [comment]
@stdex Did you disable the auto-uploading in the package preferences ?

**Comment by stdex** [comment]
@jpxd no, but I disconnect from ftp.

**Comment by jpxd** [comment]
@stdex This behavior is indented! If there is a `.ftpconfig` file in your project's directory, Remote-FTP defaults to upload any changed file instantly (Wether there is an open connection or not. This way you don't have to manually connect everytime). You can disable it in the package settings.

@Bulmer seemed to have the problem that disabling the auto-uploading didn't work

**Comment by jpxd** [comment]
Now there is an option in the package settings allowing to choose the auto upload mode.
