### ISSUE TITLE
Feature request: multiple ftp servers

### ISSUE THREAD

**Issue by stdex** [icetee/remote-ftp#166]
Now we have one config. How to create multiple configs with selection in connect process?
In notepad++ I can do it...
![image](https://cloud.githubusercontent.com/assets/4608879/9098152/ac7bf24c-3bd0-11e5-919b-3cf589d0379f.png)

**Comment by phawxby** [comment]
Notepad++ allows you to select FTP profiles and then switch to a local directory, with Atom you select the project first then connect. 

What I use for this is open-recent, it allows me to quickly pick a project from a drop down then press connect.
https://atom.io/packages/open-recent

**Comment by wasikuss** [comment]
True, but when you are using same project with two remote servers ( testing, development ) this would be good. I will take care on it.

**Comment by jpxd** [comment]
duplicate #122
