### ISSUE TITLE
Password visible in cleartext in password propmt

### ISSUE THREAD

**Issue by jpxd** [icetee/remote-ftp#167]
The password currently is visible in cleartext in the password prompt:
![screenshot 2015-08-08 00 17 33](https://cloud.githubusercontent.com/assets/10384363/9147105/ea7faa8c-3d62-11e5-9c31-6cd7455618d5.png)

Because there is no really easy way to use password inputs in atom-space-pen-views currently I would suggest a something like `this.element.children[1].style.color='rgba(0,0,0,0)';` in the PasswordPromtDialog's constructor to hide the password at least....

Any ideas?

**Comment by wasikuss** [comment]
Typed and copy-pasted passwords are now hidden.

https://github.com/wasikuss/remote-ftp/compare/master...wasikuss:fix-hidden-password

**Comment by jpxd** [comment]
Nice! Can you submit a pull request referencing to this issue @wasikuss ?

**Comment by wasikuss** [comment]
Yes, I'll do PR soon.

BTW. How to do clean PR's? Should I first merge original master to my new branch? Because if I do new branch on my master which is different than original master I get additional changes in PR...

**Comment by jpxd** [comment]
You can rebase to the current master I think. You could also PR just the diff from your master to your feature-branch https://github.com/wasikuss/remote-ftp/compare/master...wasikuss:fix-hidden-password (the button there). But I would love if you just cloned the current master, applied your changes and then PRd just one commit with the feature (better for the history).

And, for future PRs, if you want to PR multiple commits for one feature it's good practice (if the feature is not too big) to squash the commits into one. See http://eli.thegreenplace.net/2014/02/19/squashing-github-pull-requests-into-a-single-commit
