### ISSUE TITLE
cannot save .ftpconfig file and connect to ftp after upgrade to 1.8.15

### ISSUE THREAD

**Issue by adamlukacka** [icetee/remote-ftp#171]
Hi, after the upgrade I cannot save the .ftpconfig file, the adress of the file looks funny
atom:/.atom/config/atom:/.atom/config/atom:/.atom/config/atom:/.atom/config/.ftpconfig
an I cannot connect to the ftp, before the upgrade it worked normal without problems
can you suggest me how to fix this? 
Thanks in advance
Adam

**Comment by jpxd** [comment]
Did you try to re-install remote-ftp and restart Atom?

**Comment by adamlukacka** [comment]
Hi,

I have tried it right now but it doesn’t work, I think that the problem is in the file location of the .ftpconfig file
as it shows on the bottom atom:/.atom/config/atom:/.atom/config/atom:/.atom/config/atom:/.atom/config/.ftpconfig 

when I try to save I get a system screen that Atom Helper is trying to comit changes, and asking for my login password and even when I enter it, it doesnt work

I get a error message Unable to save file: Permission denied '/atom:'

S pozdravom

Adam Lukacka

+421907164572
adam@lukacka.com

**Comment by adamlukacka** [comment]
The worst is I cannot conect to any ftp, when I click the Connect link in the menu, there is no response, not even an error message, could you please have a look at this? it would help me a lot, because your plugin is very handy to work with :)

S pozdravom

Adam Lukacka

+421907164572
adam@lukacka.com

**Comment by jpxd** [comment]
No... Not really
What is the real location of your .ftpconfig file?

**Comment by wasikuss** [comment]
And what errors are in console? Restart Atom, open project, `View > Developer > Toggle Developer  Tools` and then Connect.

**Comment by adamlukacka** [comment]
from what is shows it is atom:/.atom/config/atom:/.atom/config/atom:/.atom/config/atom:/.atom/config/.ftpconfig when I click Edit configuration and it displays blank, that never happend before the upgrade

is there another way to find out?

S pozdravom

Adam Lukacka

+421907164572
adam@lukacka.com

**Comment by jpxd** [comment]
I mean you must have a project directory somewhere where the file saved. The real path on the disk

**Comment by adamlukacka** [comment]
when I click connect without editing the configuration first I get this

Uncaught Could not read `.ftpconfig` file/Users/adamlukacka/.atom/packages/Remote-FTP/lib/remote-ftp.js:110 (anonymous function)/Users/adamlukacka/.atom/packages/Remote-FTP/lib/client.js:67 e/Users/adamlukacka/.atom/packages/Remote-FTP/lib/client.js:72 (anonymous function)fs.js:302 readFileAfterOpen

maybe this is the problem

/Users/adamlukacka/.atom/packages/Remote-FTP/lib/client.js:78 Uncaught Parse error in `.ftpconfig` JSON : SyntaxError: Unexpected token /

S pozdravom

Adam Lukacka

+421907164572
adam@lukacka.com

**Comment by adamlukacka** [comment]
a subdirectory in documents...

S pozdravom

Adam Lukacka

+421907164572
adam@lukacka.com

**Comment by wasikuss** [comment]
looks like error in .ftpconfig. Can you show contents? Of course without lines with host and credentials.

**Comment by adamlukacka** [comment]
it is basic

{
    "protocol": "ftp",
    "host": “zzz",
    "port": 21,
    "user": “xxx",
    "pass": “yyy",
    "remote": "/fork/",
    "secure": false,
    "secureOptions": null,
    "connTimeout": 10000,
    "pasvTimeout": 10000,
    "keepalive": 10000
}

strange is that everything works in the dev mode, otherwise noting :)

S pozdravom

Adam Lukacka

+421907164572
adam@lukacka.com

**Comment by adamlukacka** [comment]
Hi I think you fixed it, it works fine now :)

S pozdravom

Adam Lukacka

+421907164572
adam@lukacka.com

**Comment by adamlukacka** [comment]
Hi when I now tried the developer mode Open id dev mode it works without problems :) very strange 

S pozdravom

Adam Lukacka

+421907164572
adam@lukacka.com

**Comment by adamlukacka** [comment]
Hi when I now tried the developer mode Open id dev mode it works without problems :) very strange 

S pozdravom

Adam Lukacka

+421907164572
adam@lukacka.com mailto:adam@lukacka.com
