### ISSUE TITLE
Doesn't watch if a .ftpconfig is in the tree view / projects folder

### ISSUE THREAD

**Issue by visualcookie** [icetee/remote-ftp#173]
Hi,

just saved a file of another project and it got uploaded to a project, which I already closed. It looks like `remote-ftp` uses the last `.ftpconfig` created.

**Comment by jpxd** [comment]
Can you provide steps to reproduce the bug? Did you open a new folder in the same window you were working on the old project before without disconnecting?

**Comment by visualcookie** [comment]
Well, I disconnected and changed switched the project with Project Manager in Atom. If I saved the file it uploaded the file to another server instead of just doing nothing. For the second project I had a local server running, which didn't need to be setup via FTP.

**Comment by jpxd** [comment]
I could not reproduce this... I'm using https://atom.io/packages/project-manager which opens the project in a new window

**Comment by visualcookie** [comment]
If I have a config in the first project and open the other that has no config and save a file there, it uploads it to the first projects config... thats what I've discovered.

**Comment by MarkTaylor1** [comment]
This is also happening with me, When I disconnect and change to a project that does not have the config file, It will connect and upload to the previous files config.

**Comment by jpxd** [comment]
Should do so since PR #347
