### ISSUE TITLE
Weird duplication of root folder.

### ISSUE THREAD

**Issue by JamesCoyle** [icetee/remote-ftp#179]
A weird folder showed up after the update (v0.7.2) which appears to duplicate the root folder. 

![Tree view screenshot showing issue](http://i.imgur.com/nlRwIKa.png)

**Comment by jpxd** [comment]
Uhh Ohh.... Is the problem reproducible after Atom restart ? Can you try to disable the `Hidden Folders` option in the package preferences?

**Comment by JamesCoyle** [comment]
Restarting and/or disabling hidden folders doesn't have any affect.

**Comment by jpxd** [comment]
Did you restart after disabling the `Hidden Folders` ? This is the only change since the last release I can think of causing something in this direction....

**Comment by JamesCoyle** [comment]
Yep. Restarted with it both on and off but has no effect.

**Comment by wasikuss** [comment]
Can you test another FTP server? To make sure that problem is related to one server or shows always.

**Comment by jpxd** [comment]
If the problem is still persistent, please install the release from before this update and test if the issue really wasn't already there in the last version:

```
git clone https://github.com/mgrenier/remote-ftp.git
cd remote-ftp
git checkout 44aebc2195e4bf11fffebbb53008d682f7fa5656
apm install
apm link
```

**Comment by JamesCoyle** [comment]
Huh. I just opened the connection in filezilla to see `c:/users/solus softworks/google drive/site backup` which is my local root folder (not that directory downloading works but I already reported that). It appears that RemoteFTP may have synced the `.` directory (referencing the current directory) by mistake?
