### ISSUE TITLE
Feature request: File tab context menu options

### ISSUE THREAD

**Issue by wyqydsyq** [icetee/remote-ftp#180]
It'd be really nice if there was an option to upload/download a file from the tab bar, currently if I want to download a file I'm already editing, I need to hunt it down in the remote tree panel and use the context menu from there. I should be able to right-click the open file on the tab bar and download or upload it.

**Comment by jpxd** [comment]
You can use Atom's command palette to upload/download a file if it is opened.
I don't think it is a good idea to overpopulate Atoms's context menu with too many options....

**Comment by wyqydsyq** [comment]
I have version 0.7.3 installed and don't get any upload functions from the command palette other than "upload selected" which is useless when you use the fuzzy finder to open files instead of the file tree.

Is this functionality part of an update not yet pushed to NPM?

**Comment by jpxd** [comment]
Nope.
I was under the impression, the fuzzy finder auto-selects the currently viewed file. I will have a look into it later

**Comment by jpxd** [comment]
Made a proposal in issue #200
