### ISSUE TITLE
File/folder Watcher Feature

### ISSUE THREAD

**Issue by Bana0615** [icetee/remote-ftp#184]
it would be a nice feature if you could set a folder/file to be watched so that if any changes are detected it would auto upload the file. A big use for this would be if you use less or sass because it is pretty annoying to have to upload the newly created css file every time.

**Comment by moerphie** [comment]
+1 👍👍

**Comment by onetrev** [comment]
Agreed, this would be huge! If it helps, I see it was added to a fork of Remote Sync, which can be found here: https://github.com/theproducer/remote-sync

**Comment by jpxd** [comment]
This feature exists as of the latest release (PR #312 version 8.0.0) but is limited to files. Feel free to extend it to folders.
