### ISSUE TITLE
Invalid certificate - can't connect and crash

### ISSUE THREAD

**Issue by vinnytroia** [icetee/remote-ftp#187]
If I try connecting to an FTP site (FTP with TLS/SSL) that has an invalid certificate, I can not connect and am given a certificate error. If I press connect again, Atom crashes. 

is there any way to bypass the certificate check?

**Comment by HeckoLeSorcier** [comment]
Same error for me. This plugin seems not popup a window to allow self-signed certificate...

I found a solution. Use it ONLY if you have a self signed certificate !

add this line (or modify it) in the .ftpconfig :

"secureOptions": { "rejectUnauthorized": false},

**Comment by jpxd** [comment]
Added to wiki 
https://github.com/mgrenier/remote-ftp/wiki/Settings#usage-of-self-signed-certs
