### ISSUE TITLE
Packages -> Remote-FTP -> "any tab") - when pressed - no action...

### ISSUE THREAD

**Issue by bartwork** [icetee/remote-ftp#189]
And thanks for this useful plugin.

**Comment by bartwork** [comment]
I tried to reinstall - but it did not help.

**Comment by jpxd** [comment]
Ok ?!

**Comment by bartwork** [comment]
I'm sorry. I can not open the configuration file and connect to the server. (Packages -> Remote-FTP -> "any tab") - when pressed - no action... I tried to Add "Project Folder" (Alt + Ctrl+O) And now Remote-ftp works (https://github.com/mgrenier/remote-ftp/issues/148#issuecomment-134387800)
