### ISSUE TITLE
Recursive Folder Download

### ISSUE THREAD

**Issue by llanosCoder** [icetee/remote-ftp#190]
When I press Download a Folder it only downloads the folder itself. It would be a lot more faster and intuitive if this download the Folder recursivly.

**Comment by agence104** [comment]
Id like to have this functionality also.

**Comment by senica** [comment]
Indeed. When I do download a folder, it cuts off the first letter of the name of any sub-files or sub-directories and places them in the root. So if I have

```
images
    ~ hello
      ~ bluebird.png
```

and download the images directory, I end up with

```
~ images
~ ello
~ luebird.png

```

This is transferring from a Godaddy hosted site...so perhaps some wonky with them is not out of question.

**Comment by jpxd** [comment]
Folder download is currently broken.... See #115
