### ISSUE TITLE
promptForPass not in default .ftpconfig

### ISSUE THREAD

**Issue by ilrico** [icetee/remote-ftp#191]
hi, we can only find this option reading docs (which is nice RTFM behaviour) but for new user, one try with blank password (since file is plain text stored on project) and Remote-ftp gives an error. So my first reaction was to deinstall the package and try another.
I suggest to put this option by default on .ftpconfig file.

**Comment by jpxd** [comment]
The option is in the default .ftpconfig file but it is set to `false`
But we could show a password prompt when a blank password fails instead of throwing an error...
This is better behaviour anyway

**Comment by ilrico** [comment]
with Atom 1.0.11 and Remote-FTP 0.7.2, promptForPass is _not_ present in default .ftpconfig

you have protocol, host, port, user, pass, remote, agent, privatekey, passphrase, hosthash, ignorehost, connTimeout, keepalive, keyboardInteractive
but nowhere promptForPass

**Comment by jpxd** [comment]
Sorry, you're right! It was already added but the current version from GitHub has not been released yet >.<
I will do this later today :)
