### ISSUE TITLE
Keepalive for SFTP not working

### ISSUE THREAD

**Issue by abvincita** [icetee/remote-ftp#193]
Hello, I wonder if anyone else is having the same issue with the keepalive option when using SFTP?

Even with the keepalive option enabled, I keep getting disconnected from my SFTP connection periodically. I've tried lowering the value of the keep alive until 120 (and even lower) but it's not helping at all. I also tried playing around with the option keepaliveCountMax and keepaliveInterval options but they're also not making things any better.

Here's my current settings:
{
    "protocol": "sftp",
    "host": "host",
    "port": 22,
    "user": "user",
    "promptForPass": false,
    "remote": "/",
    "agent": "env",
    "privatekey": "",
    "hosthash": "",
    "ignoreHost": true,
    "connTimeout": 30000,
    "keepalive": 120,
    "keepaliveCountMax": 10,
    "keyboardInteractive": false
}

I'm trying to figure out whether it's the keepalive that's not working or if there's something wrong with my server. I've contacted my server administrator and they said everything looks all good. 

Additionally, if I use sublime SFTP with similar settings, my connection doesn't seem to drop off. Therefore, I'm wondering if it's the keepalive that is not working?

Thanks beforehand!

**Comment by hphuhtin** [comment]
I seem to have similar problems, except maybe much worse. My connection hangs and then I have to wait for a long period (have not measured, maybe minute or so) until I can access files again unless I manuall disconnect/connect. This happens all the time, once in a few minutes. Quite annoying.

**Comment by GeneralCan** [comment]
similar issue, which is weird because it was working before. It wasn't until the last couple of updates where it began breaking the connection.

**Comment by jpxd** [comment]
Should be working in the next update.
The ssh2 dependency changed an option name which was missed in a Remote-FTP update (https://github.com/mscdex/ssh2/wiki/Changes-from-0.3.x-to-0.4.x)

**Comment by GeneralCan** [comment]
@jpxd next update as in 0.10.1? or the one after that?

**Comment by jpxd** [comment]
Will be 0.10.2 but its not out yet because there is a bug in sync that needs to be fixed first.

**Comment by jpxd** [comment]
v0.10.2 is out

**Comment by tominal** [comment]
Left for class and came back, still connected! Cheers!
