### ISSUE TITLE
Ignore file(s) to sync when upload a directory

### ISSUE THREAD

**Issue by indrimuska** [icetee/remote-ftp#195]
Hi, everyone.
Is there any way to define a set of file type to upload when syncing a directory?
I need a behavior similar to `.gitignore` file for git repositories, to prevent uploading of `.git` directory or MacOS `.DS_Store` file into the remote server.
Thanks.

**Comment by jpxd** [comment]
Duplicate to #36 
There is a pull request ( #117 ) trying to solve this which has to be tested yet...

**Comment by indrimuska** [comment]
Oh sorry, I haven't seen that PR nor that issue.

**Comment by jpxd** [comment]
If you are willing to help and you have some spare time, you could sort out those merging conflicts and/or test the PR :smile:

**Comment by indrimuska** [comment]
Definitely I'll do something in the next few days, I'll test that PR or maybe I will open a new one.

I think that this feature is extremely important for this package, keep in mind that [remote-sync](https://atom.io/packages/remote-sync) already has an `ignore` parameter for doing this.
