### ISSUE TITLE
Updating to Remote-FTP@0.7.3 failed

### ISSUE THREAD

**Issue by daftpanda** [icetee/remote-ftp#196]
**Atom version:**
1.0.15

**System:**
Windows 7 Ultimate 64bit

![image](https://cloud.githubusercontent.com/assets/14540591/10046148/4f4a54b2-6207-11e5-991e-b682331b77a6.png)

**Comment by jpxd** [comment]
Wat ?!
What happens after restarting Atom?

**Comment by daftpanda** [comment]
1. Tried to update it --> error see above
2. Closed Atom completely and restarted it --> package was "succesfully updated" (didn't show me that R-FTP needs to be updated)
3. Uninstalled the package and reinstalled it --> <code>Load Package Error</code>...

**Comment by jpxd** [comment]
The Error after re-install was the same ?
It didn't find the readme file from a submodule?

**Comment by daftpanda** [comment]
@jpxd I will try to reproduce it tomorrow

**Comment by daftpanda** [comment]
Uninstalled the package, restarted atom and reinstalled it:

![image](https://cloud.githubusercontent.com/assets/14540591/10066802/cd256bbc-6296-11e5-84fc-6317a13bf8e8.png)

/edit: same after completely removed atom, reinstalled and installed the package...

**Comment by jpxd** [comment]
Can you try to install it from the command line using `apm install remote-ftp`?
I don't really know what is causing your problem since the dependency for jslint is in the package.json...

**Comment by daftpanda** [comment]
@jpxd mate, this probably has nothing to do with you (or your nice package)...

I already reported those errors here:

https://github.com/atom/atom/issues/8891

just for the record - after uninstalling R-FTP and reinstalled vai <code>apm install remote-ftp</code>
![image](https://cloud.githubusercontent.com/assets/14540591/10094448/60b7eaac-6360-11e5-8283-cedac9b4e3a4.png)

**Comment by jpxd** [comment]
Ok, thanks
Lets hope the folks at Github will fix Atom soon 😏
