### ISSUE TITLE
Connection not completing

### ISSUE THREAD

**Issue by JamesCoyle** [icetee/remote-ftp#197]
When pressing connect I sometimes get an error saying it couldn't connect. That's fine as its usually fixable as it identifies what went wrong. 

Recently however it shows the connecting message but doesn't actually complete the connection and retrieve the files yet it doesn't show any sort of error message either. Looking at my server's CPanel I can see there is an FTP connection sitting idle for every time I clicked connect. It is connecting but not actually retrieving anything and isn't detecting that it is already connected.

**Comment by jpxd** [comment]
Can you look into the developer console? The FTP debug messages should be listed there

**Comment by JamesCoyle** [comment]
![Console log](https://cloud.githubusercontent.com/assets/10384436/10117886/12eec05c-645f-11e5-9068-969bbc8b5b60.png)

Seems to connect as normal but the treeview doesn't update.

**Comment by shogerr** [comment]
I've had odd problems like this, try changing the remote folder field in the config to the location on the server where your home folder is. I've had the remote-ftp connect to / sometimes, so its best to explicitly state the directory you would like to instantiate on a connection.

**Comment by JamesCoyle** [comment]
It seems to have been fixed in one of the recent updates (I noticed a couple of versions).
