### ISSUE TITLE
Could not parse .ftpconfig

### ISSUE THREAD

**Issue by phawxby** [icetee/remote-ftp#201]
.ftpconfig can no longer be parsed when using hard tabs. Although I have no real preference to either the project I'm working on uses hard tabs, as such atom is set to convert to hard tabs. This validation is problematic for me.

![capture](https://cloud.githubusercontent.com/assets/1090602/10192656/d778d570-6775-11e5-9e7f-8a9d42ba0fad.PNG)

**Comment by jpxd** [comment]
Yeah, this definitely was not intended... Can we close the issue as you already merged the fix?

**Comment by phawxby** [comment]
Yep, I wasn't expecting time to figure it out
