### ISSUE TITLE
cant determine where .ftpconfig file will be created 

### ISSUE THREAD

**Issue by miscbits** [icetee/remote-ftp#208]
I want to have remote connections saving to a folder that I can easily empty out once I am done editing files in it. When I have ftp files being saved to whatever directory Im working in regardless of whether the files are contextually related or not is annoying. 

Currently when I create a new .ftpconfig file it is just created in my top project forlder. my top project folder in this case is an unrelated project that is being tracked with git. when I save my files can be automatically commited and pushed which makes this a disaster for figuring out what content went to whatever sites. Please add an option to tell atom where it should be creating the .ftpconfig file.

**Comment by jpxd** [comment]
Currently Remote-FTP works project based, so you need a project directory for every server which contains the .ftpconfig
