### ISSUE TITLE
[0.7.20] Right click does not select clicked folder

### ISSUE THREAD

**Issue by sircon-john** [icetee/remote-ftp#209]
Example:
Right-clicking a folder to perform "Refresh" (or any other action) will not refresh the right-clicked folder. It will instead refresh the file or folder that is already selected, which more than likely is another folder than the one you right-clicked.

Yes, quite insignificant, but also very annoying.
Looking forward to the next version :) Keep up the great work!

Edit: Title was misleading. Rightclicking files seems to have always worked. The issue is about rightclicking folders.
Update [0.7.15]: This issue is still present

**Comment by JamesCoyle** [comment]
I second this. In most other programs the right click will perform a sort of 'soft selection' before bringing up the context menu.

**Comment by sircon-john** [comment]
Any news on this 6 month old issue that still persists in 0.7.20?
I've gotten used to performing extra left clicks to ensure a correct right click on the target folder.
This habit has carried over to other editors, where I basically never trust that my right click will actually click the thing at which I'm pointing.

**Comment by jimmaaay** [comment]
Should be fixed in 0.8.9
