### ISSUE TITLE
SSH Client / Terminal emulator

### ISSUE THREAD

**Issue by cakebake** [icetee/remote-ftp#210]
What do you think about the integration of a terminal emulator for console work?

**Comment by hatzopoulos** [comment]
see these
- https://atom.io/packages/atom-terminal
- https://atom.io/packages/atom-terminal-panel
- https://github.com/atom-archive/terminal (not maintained)

**Comment by cakebake** [comment]
Sorry, but as far as I've seen, these are no emulators. These serve the native console of the operating system.

**Comment by hatzopoulos** [comment]
I'm not the maintainer of this project. I think it's a great idea, although perhaps as a separate package that tied into this one? Maybe you should start it up. 

I for one wouldn't be able to spend time on a project like that. The [black-screen project](https://github.com/black-screen/black-screen) might be of interest to you, it is also built on Electron (atom shell).
