### ISSUE TITLE
Please add support for multiple hosts

### ISSUE THREAD

**Issue by PawelGIX** [icetee/remote-ftp#212]
It would be nice if you could easily switch between multiple remote mappings. Like dev, production, test.

And ignored files is must have feature.

**Comment by laubsterboy** [comment]
:+1:

**Comment by mdahlke** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by GeekMustHave** [comment]
I agree, I move between 5 FTP sites in a day.

**Comment by tlygnersjo** [comment]
+1

**Comment by jlivas** [comment]
:+1:

**Comment by GStarSade** [comment]
Also need this as I am working on multiple projects.

**Comment by Kaijiro** [comment]
:+1:

**Comment by mediaworksmt** [comment]
+1 - Being able to easily switch between remote hosts would be incredibly helpful.

**Comment by jimmaaay** [comment]
See #469
