### ISSUE TITLE
Uncaught TypeError: Cannot read property '_pasvSocket' of null

### ISSUE THREAD

**Issue by fsje** [icetee/remote-ftp#215]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Unknown Windows Version
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.7.8
### Stack Trace

Uncaught TypeError: Cannot read property '_pasvSocket' of null

```
At C:\Users\fred369h\.atom\packages\Remote-FTP\lib\connectors\ftp.js:321

TypeError: Cannot read property '_pasvSocket' of null
  at C:\Users\fred369h\.atom\packages\Remote-FTP\lib\connectors\ftp.js:321:19

```
### Commands

```
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
color-picker, v2.0.13
drunken-php, v0.2.1
Remote-FTP, v0.7.8

# Dev
No dev packages
```

**Comment by jpxd** [comment]
Can you please checkout the last version from github and test?

**Comment by jpxd** [comment]
Patch is published now, if the issue persists after the latest update please reopen the issue
