### ISSUE TITLE
Cross Platform ftpconfig

### ISSUE THREAD

**Issue by laubsterboy** [icetee/remote-ftp#216]
Would it be possible to parse the .ftpconfig file path for privatekey allowing for ~/ user home directory relative paths?

Many of my projects are saved in a cloud sync (dropbox), but I work on Windows and Linux and there isn't a (easy) way to use the same path that will work on Windows and Linux.

Ideally I would just use "agent" instead of specifying a privatekey, but I have the same cross platform problem with that as well.

**Comment by jpxd** [comment]
What are you requesting exactly?
The possibility to use e.g. "~/.ssh/id_rsa" as path for the privatekey?

**Comment by laubsterboy** [comment]
Correct. For the "privatekey" setting - it would be nice to be able to use something like "~/.ssh/id_rsa" as the path and have it interpreted as:

Windows: "%userprofile%/.ssh/id_rsa"
Linux: "~/.ssh/id_rsa"
OS X: "~/.ssh/id_rsa" 

This would allow the setting to be saved as one relative path that works on all OSs.

For the "agent" setting - it would be nice to be able to specify a setting per OS (unless there is a better way to do it). Something like: 

`"agent": {"windows": "pageant", "linux": "SSH_AUTH_SOCK", "osx": "AUTH_SOCK"}`

**Comment by icetee** [comment]
Next version will be included. https://github.com/icetee/remote-ftp/commit/2be9fc8526e119e8db0765f45a2ee32caad11c42

Supported methods all desktop platforms:

```
"privatekey": "~/.ssh/id_rsa"
```

or just use only ssh config file. https://github.com/icetee/remote-ftp/issues/910#issuecomment-328809608

**Comment by laubsterboy** [comment]
This is fantastic! Thank you!
