### ISSUE TITLE
File Icons

### ISSUE THREAD

**Issue by TheVaan** [icetee/remote-ftp#22]
Is there anyway to get file icons to the remote-ftp-tree like some plugins do for the local tree?
That help because I often have files with the same name but different endings (yes, I know, use folder structure for this - but one one of my projects has to manage on that dirty way) and it is a bit difficult to find the right files quickly.

**Comment by grenierdev** [comment]
@TheVaan Can you tell me what plugin you have in mind?

**Comment by TheVaan** [comment]
@mgrenier Currently I'm using https://github.com/DanBrooker/file-icons for the file icons in the local tree view.

Here you can see how it looks like:
on the left is the local tree, on the right the remote-ftp tree
![bildschirmfoto 2015-01-24 um 09 58 31](https://cloud.githubusercontent.com/assets/1108485/5886782/48647ab2-a3b0-11e4-998d-d1d192783382.png)

**Comment by grenierdev** [comment]
Thank you for the request, it's a nice addition!
