### ISSUE TITLE
Uncaught TypeError: object is not a function

### ISSUE THREAD

**Issue by nitro9090** [icetee/remote-ftp#220]
I am new to this program and I believe I put all of my credentials in properly, but keep getting this error.  Can anyone help?  I really look forward to using this program.

[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Microsoft Windows 8.1
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.7.10
### Stack Trace

Uncaught TypeError: object is not a function

```
At C:\Users\nitro9090\.atom\packages\Remote-FTP\node_modules\ssh2\node_modules\ssh2-streams\lib\utils.js:475

TypeError: object is not a function
  at convertPPKPrivate (C:\Users\nitro9090\.atom\packages\Remote-FTP\node_modules\ssh2\node_modules\ssh2-streams\lib\utils.js:475:14)
  at module.exports.decryptKey (C:\Users\nitro9090\.atom\packages\Remote-FTP\node_modules\ssh2\node_modules\ssh2-streams\lib\utils.js:139:7)
  at Client.connect (C:\Users\nitro9090\.atom\packages\Remote-FTP\node_modules\ssh2\lib\client.js:153:7)
  at ConnectorSFTP.module.exports.ConnectorSFTP.connect (C:\Users\nitro9090\.atom\packages\Remote-FTP\lib\connectors\sftp.js:78:13)
  at Client.module.exports.Client.doConnect (C:\Users\nitro9090\.atom\packages\Remote-FTP\lib\client.js:237:18)
  at Client.module.exports.Client.connect (C:\Users\nitro9090\.atom\packages\Remote-FTP\lib\client.js:155:9)
  at Client.<anonymous> (C:\Users\nitro9090\.atom\packages\Remote-FTP\lib\views\tree-view.js:178:28)
  at C:\Users\nitro9090\.atom\packages\Remote-FTP\lib\client.js:85:15
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)

```
### Commands

```
     -3:57.8.0 tree-view:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -3:34.4.0 remote-ftp:toggle (atom-text-editor.editor.is-focused)
     -3:20.9.0 tree-view:remove (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -3:06.0 remote-ftp:connect (atom-text-editor.editor.is-focused)
     -3:01.0 remote-ftp:navigate-to (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
language-marko, v0.4.18
Remote-FTP, v0.7.10

# Dev
No dev packages
```

**Comment by jpxd** [comment]
Related to mscdex/ssh2-streams#28

**Comment by jpxd** [comment]
Did you try to reinstall the package? (To update the dependencies)

**Comment by laubsterboy** [comment]
I'm having the same problem, and have been since 10/30/2015, and was hoping the ssh2 or ssh-streams node modules would be updated. I just tried reinstalling and am still having the problem. It only happens when I specify a "privatekey" in my .ftpconfig. I don't want a plain text password in my config file so I was opting to use the key, but the password route works as a fallback for now.

**Comment by mccrearyp** [comment]
I think one of the recent updates is causing this issue. My config was working fine until today when I updated.

(I attempted uninstall and reinstalling the package, didn't help)

**Comment by ArielSaldana** [comment]
@jpxd It's not related to the issue you linked to. At all.

**Comment by ArielSaldana** [comment]
If anyone wants a quick fix under :

C:\Users\systems\.atom\packages\Remote-FTP\node_modules\ssh2\node_modules\ssh2-streams\lib

comment out lines 197 / 198. The code should look like this :

(cb = requests[keys[i]].cb) && cb(err);
  //  state.requests = {};

**Comment by ccamarat** [comment]
FWIW utils.js:475 reads

```
p1 = new BigInteger(p, 256),
```

It appears that `BigInteger` is being interpreted as an object rather than a constructor. Digging in, I discovered the jsbn lib doesn't consistently export itself between environments. Not sure why this would suddenly become a problem since it looks like that lib hasn't been updated in a few years, but I [submitted a PR](https://github.com/andyperlitch/jsbn/pull/7) there for it.

**Comment by mscdex** [comment]
[This](https://github.com/andyperlitch/jsbn/commit/72f1a24486f8d4d4e895a9fdd9e34a3d66f9f90b) was the breaking commit. However a new version of `jsbn` was published to npm just a week ago which included this commit. It's unfortunate because the backwards incompatibility was totally avoidable.

**Comment by ccamarat** [comment]
FYI @mscdex updated ssh2; if you reinstall remote-ftp this issue should go away.

**Comment by jpxd** [comment]
Thanks @mscdex!
