### ISSUE TITLE
Upload and Auto Upload on Save Not Working for New Files

### ISSUE THREAD

**Issue by hull-aaron** [icetee/remote-ftp#222]
This was working previously (before the 1.1.0 update), albeit in a strange way (files in other project folders were getting uploaded to the project with .ftpconfig in it - but that's a different issue).

There's no popup or any sign of error in the editor or console, so there's no error stack to provide.

If I create a directory with a dummy file of the file I want to upload, auto upload works just fine.

**Comment by jpxd** [comment]
Please retry in the latest version.
