### ISSUE TITLE
Is there a way to write a ignore file list?

### ISSUE THREAD

**Issue by JW-M2RD** [icetee/remote-ftp#223]
Is there a way to write a ignore file list for sync? Or i can ignore the config file while i am uploading or syncing?

**Comment by hatzopoulos** [comment]
Not yet but it's planned. See https://github.com/mgrenier/remote-ftp/issues/36

**Comment by hatzopoulos** [comment]
Also see this PR https://github.com/mgrenier/remote-ftp/pull/117

**Comment by JW-M2RD** [comment]
Thanks

**Comment by AdrienLZ** [comment]
+1

**Comment by rielc** [comment]
+1 This feature would be very useful. :)

**Comment by hiaselhans** [comment]
+1

**Comment by GauSim** [comment]
+1

**Comment by gdevdeiv** [comment]
+1

**Comment by bmkorkut** [comment]
+1, Thanks

**Comment by mschristensen** [comment]
+1

**Comment by jpxd** [comment]
duplicate
