### ISSUE TITLE
Upload/download progress

### ISSUE THREAD

**Issue by ironhussar** [icetee/remote-ftp#224]
Thanks for a great plugin. I am slowly trying to wean myself off Sublime, and having a good FTP plugin is the main step for me :)

Is there any way to add a upload/download progress indicator? In sublime, any FTP action opens a small panel at the bottom indicating the status (connecting, uploading, and any fail state). For single files this is obviously very quick, but when uploading whole folder(s), you don't know whether it's done, or if you have time to make another coffee.

Could this be added? Even as a toggable option.

Thanks!

**Comment by danseethaler** [comment]
Have you noticed the small console at the bottom of the tree-view? It doesn't have a progress bar but there is a red bar when files are downloading and gives you a success message on complete.

![image](https://cloud.githubusercontent.com/assets/11202705/11312113/4b433354-8f91-11e5-9ec0-0e00a71268b0.png)

You can also expand the console message by hitting the down arrow when the FTP tree-view is active.

**Comment by ironhussar** [comment]
I did, it works well - but if the tree view is closed (as I have 99% of the time), there is no notification... unless I missed something?

**Comment by jpxd** [comment]
No, except in the bottom of the tree view, there is none
