### ISSUE TITLE
Self Signed Certs cause Atom to crash after 2nd connection attempt

### ISSUE THREAD

**Issue by datanotion** [icetee/remote-ftp#227]
The FTPS server I'm trying to connect to has a self signed cert.  If I try to connect to it, an error appears in Atom stating "Remote FTP:  Error:  self signed certificate".

If I try to connect again, **the entire Atom editor crashes**.

Has anyone been able to connect using a self-signed cert yet?

Thank you.

**Comment by jpxd** [comment]
Look into #187 or the wiki (https://github.com/mgrenier/remote-ftp/wiki/Settings#usage-of-self-signed-certs) :smile:
