### ISSUE TITLE
Overwrites .ftpconfig

### ISSUE THREAD

**Issue by pjrfigueiredo** [icetee/remote-ftp#228]
When we have a directory open, and we, by mistake, hit Create SFTP/FTP config file, it doesn't open the existing one.
Creates a new one directly without prompting and alert and overwrites the existing one.

**Comment by JamesCoyle** [comment]
I like that it overwrites as it makes it easier to switch to a new server but I agree it does need some sort of confirmation.

**Comment by jimmaaay** [comment]
This is sorted in the dev branch. When a user tries to create a config file when there is already one in the project directory it will prompt them if they want to overwrite it. This will be out in the next release.
