### ISSUE TITLE
Infinite loop 

### ISSUE THREAD

**Issue by polarpixel** [icetee/remote-ftp#231]
This seems to be a similar problem as #218.
On some servers I have an infinite loop in some folders. I mean that the folder structure rein and again. See screenshot. Working with Macs.
![2015-11-19_13-33-14](https://cloud.githubusercontent.com/assets/330160/11270879/bb10cb94-8ec2-11e5-9a63-f060b450271c.png)

This only happens with some folders, but I cannot find out what's special with these folders. Maybe that they have been created by a PHP script.
Other FTP programs like Yummy FTP, Coda and so on have no problems.

**Comment by jpxd** [comment]
Yeah its the same issue 
Duplicate to #218
