### ISSUE TITLE
Watch folder file

### ISSUE THREAD

**Issue by tchalupnik** [icetee/remote-ftp#234]
Hello.
I am using sass compilator and would be great if there is a device what is watching when file was changed and then sends it via ftp.
Is it possible to do?

**Comment by robertluedke** [comment]
Heyho,
I would really appreciate this feature too. Currently I have to save the SASS module and after compiling, I have to open the compiled CSS file and save this one too. It's a bit annoying.

**Comment by tchalupnik** [comment]
same to me

**Comment by jpxd** [comment]
Can anyone recommend a good way to watch for file changes via Atom or Node.js module?

Or we could make a setting that you say: "Every time I save a sass file, search for other changed files". This way we don't need to check all files all the time...

**Comment by hatzopoulos** [comment]
I wonder if [`fs.watch`](https://nodejs.org/docs/latest/api/fs.html#fs_fs_watch_filename_options_listener) would be sufficient for the task? It would seem like it would.

On the other hand one could also setup the server to do the watching and then do the building via a scripted process (compile/minify the SASS). 

FWIW Facebook via their [nuclide.io](http://nuclide.io/) project uses [watchman](https://facebook.github.io/watchman/).

**Comment by tchalupnik** [comment]
@hatzopoulos I dont know if I understand you. There is no need to hold scss files on site server. 
When i save external file then compilator makes f.e. style.css 
And now, when main file has been changed i need to send it via ftp
Without this enhancement i need to save external and go to style.css where need to save/upload it too to send it via remote-ftp.

**Comment by mkstix6** [comment]
I get @hatzopoulos' point and it would be a nice solution. However I would wager that most front-end devs are compiling their scss locally.

I'd really like to see something that achieves what the file monitoring in Sublime SFTP does:
You select a file to monitor. If the file changes it's uploaded.

**Comment by ceski23** [comment]
+1

**Comment by ManuelColombo** [comment]
:+1: 
I've the same prolem, both with LESS and Jade files.

**Comment by Deanmv** [comment]
Another +1 from me! :+1:

**Comment by jimmaaay** [comment]
I've currently created a pull request with this feature implemented.

**Comment by Deanmv** [comment]
@jimmaaay Thanks! Just tried and works great! Top work :shipit:

**Comment by dallanlee** [comment]
Thank you @jimmaaay This is essential to my workflow and I'm glad someone seems to really care. Thanks for taking the time and effort 👍🏻

**Comment by jpxd** [comment]
@jimmaaay s PR has been merged

**Comment by dallanlee** [comment]
Very cool. Thank you @jpxd
