### ISSUE TITLE
Symlinks shown as directories

### ISSUE THREAD

**Issue by efrecon** [icetee/remote-ftp#238]
Files that are a symbolic link to another files are shown as a directory in the tree-view. This makes it impossible to double-click on them and start editing them. Can somebody reproduce this? How can we fix?

**Comment by jpxd** [comment]
Connected via SSH ?

**Comment by efrecon** [comment]
Yes

On Wed, 2 Dec 2015, 15:29 Jan notifications@github.com wrote:

> Per SSH ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mgrenier/remote-ftp/issues/238#issuecomment-161315422
> .
> 
> ## 

## 

Emmanuel Frécon

**Comment by ghoben** [comment]
This would be really nice if fixed.

**Comment by ghoben** [comment]
I tried to fix this on a forked branch, put I'm not allowed to create a pull request. How would you like to get the changes to review?

**Comment by jpxd** [comment]
??? Everybody is allowed to create a PR...
But you didn't push your changes to your fork, did you?
Can't see any new commits of you in https://github.com/ghoben/remote-ftp

**Comment by ghoben** [comment]
sorry, my fault. I'm still struggling with the way GitHub works. I was creating a branch within your repository, I therefore was denied to sync my private branch with your main repository.... Anyway, I committed into the fork and was able to create a pull request. I hope you are fine with the changes. If not let me know. I only adapted sftp.js connections.

**Comment by jpxd** [comment]
Thanks for the PR :) Merged

**Comment by jpxd** [comment]
Will be part of the next update

**Comment by efrecon** [comment]
Great! Thanks.
