### ISSUE TITLE
Not working on FTP active mode

### ISSUE THREAD

**Issue by ghacosta** [icetee/remote-ftp#239]
Hi! 
I have a host which only works with active transference mode. After set credencial and successful login "listing" keeps on loop and don't retrieve any file.
![image](https://cloud.githubusercontent.com/assets/10713501/11543395/18ebde18-991b-11e5-8986-33ed2873d869.png)

**Comment by jpxd** [comment]
Are there any errors in the Developer Console?

**Comment by jpxd** [comment]
Okay, forget it. The ftp module we are currently using doesn't support Active FTP connections (see e.g. mscdex/node-ftp/issues/100). Sorry :/
