### ISSUE TITLE
Support for hidden files

### ISSUE THREAD

**Issue by Solander** [icetee/remote-ftp#244]
Can't find a way to include hidden files in the list. A not so uncommon scenario when working with web projects, is that you want to edit the .htaccess in some way.
EDIT: I found the setting in Packages Settings after restarting Atom, but nothing changes if I have it ticked or unticked. I'm using Mac OS X.

**Comment by ghost** [comment]
Have same problem, Linux Mint 14

**Comment by jpxd** [comment]
FTP ?

**Comment by ghost** [comment]
Yes, FTP.

**Comment by bitrixdo** [comment]
I too have this problem.
I've heard that this is due to the remote server settings

**Comment by ghost** [comment]
FileZilla show hidden files in my ftp server.

**Comment by bitrixdo** [comment]
FileZilla shows hidden files, and Atom - no!
This is a problem since it is necessary to download the entire project

**Comment by robmim** [comment]
Same here using FTP. Cant see the .htaccess file even if the Show hiddens files is checked

**Comment by daraul** [comment]
I've got this same problem. Ubuntu 15.10.

**Comment by RobinBoersma** [comment]
Same problem here! Cant see .htaccess files

**Comment by kikoseijo** [comment]
We need to enable hidden on remote, please request, accept, push.

**Comment by dimsanchuk** [comment]
Same problem. Windows 10

**Comment by aaroniker** [comment]
Same problem here on Debian 7 - still no fix?

**Comment by mtamadon** [comment]
Same problem ... (Fedora 23)

**Comment by RobinBoersma** [comment]
It is finally working now!

**Comment by aaroniker** [comment]
awesome!
