### ISSUE TITLE
All directories are seen a files

### ISSUE THREAD

**Issue by justbane** [icetee/remote-ftp#246]
Just downloaded your update (0.7.15) - all of my directories are now seen as files.

Can not browse them at all, the system tries to download the entire directory as a file.

**Comment by jpxd** [comment]
Oh no... Are you using SSH?

**Comment by justbane** [comment]
Yes SSH... and the folders are technically symlinks.

Hope that helps

**Comment by jpxd** [comment]
Symlinks should be working with SFTP after the new update (v0.7.16)
