### ISSUE TITLE
Implement drag & drop

### ISSUE THREAD

**Issue by grenierdev** [icetee/remote-ftp#25]
1. Drag & drop within remote tree for quickly moving
2. Drag & drop between remote/local for quickly downloading/uploading
3. Drop from "system file/folder" (outsite Atom) to remote for quickly uploadling

**Comment by vorillaz** [comment]
+1

**Comment by emerson5** [comment]
+1

**Comment by samuelesantoni** [comment]
Hi, are implemented this feature?
Drag & drop within remote tree for quickly moving
Drag & drop between remote/local for quickly downloading/uploading
Drop from "system file/folder" (outsite Atom) to remote for quickly uploadling

I have problem for upload file. I use drag and drop inside Atom but doesn't works.
How can i do for upload my files?
Thanks.

**Comment by skeddles** [comment]
+1 hope this is still in development

**Comment by skeddles** [comment]
Welp I killed it
