### ISSUE TITLE
Remote-FTP can't open the downloaded files

### ISSUE THREAD

**Issue by makayjozsef** [icetee/remote-ftp#250]
Remote-FTP connects to FTP server, shows the file tree, downloads files at open, but can't open the downloaded file. No error, only an empty tab.

Files are downloaded to $HOME/atom:/about/ but editor try to open from /atom:/about/atom:/about/atom:/about/

**Comment by jpxd** [comment]
Why is your directory called "atom:"? Please try to use a name without ":" and tell me if the issue persists.

**Comment by makayjozsef** [comment]
This local directory is created by Remote-FTP for temporary files. When I want to edit a file on FTP server, Remote-FTP downloads automatically that file to this local directory and open it for editing.

(Ubuntu 15.10, Atom 1.3)

**Comment by jpxd** [comment]
And whats the project/working directory?

**Comment by makayjozsef** [comment]
Hmm... Atom forgot my project directory so Remote-FTP tries to solve this problem with an atom: directory. Re-opening of project directory solves the "bug". Thank you!
