### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by Backhoe** [icetee/remote-ftp#251]
Hello guys.
When I try to connect to my server, it says that I'm connected but a few second later I have this error: "read ECONNRESET".
My ftpconfig is correct so I don't know why I got this :/
Thank you for your help !

**Comment by samwyness** [comment]
Having the same issue, spent the last 3 days trying to find an answer. Any luck fixing error?

**Comment by leonsaysHi** [comment]
I also have this issue, I have tried different ftp upload/download packages they all failed.
The probleme may be somewhere else.

**Comment by samwyness** [comment]
Changing the name of my folder I was trying to connect did the trick.

**Comment by jpxd** [comment]
@samwyness Can you post the folder name to give us a hint?

**Comment by samwyness** [comment]
@jpxd I changed the theme folder I was trying to upload.

**Comment by gahmed92** [comment]
I've the same issue, my ftp works well on chrome, but in atom I got this "Remote FTP: Error: read ECONNRESET" , any one can help us ?

**Comment by paul2903** [comment]
This is also happening to me. I have opened: https://github.com/mgrenier/remote-ftp/issues/595

**Comment by socratesone** [comment]
I was also having this issue. Turns out the server I was using didn't support SCP/SFTP, so I had to do it over plain old vanilla FTP. Working fine, now.

**Comment by kaysiz** [comment]
i am able to connect when on linux but when i try logging on using windows i get that error too. please help

**Comment by dkdefender** [comment]
After update Remote-FTP to latest version - not connect to any host with error ECONNRESET - in other ftp clients all works fine.

**Comment by spaced-out-factory** [comment]
Same

**Comment by Jany-M** [comment]
@gahmed92 @jpxd It seems that the issue could be related to specific hosting providers.

**Comment by hatzopoulos** [comment]
conversation locked, see #585
