### ISSUE TITLE
Saving Config Crash

### ISSUE THREAD

**Issue by Elements-** [icetee/remote-ftp#254]
I just did a fresh install of Atom and Remote-FTP, I created a new project, toggled remote-ftp from the menu. The create sftp and ftp config buttons dont do anything, however the edit configuration button in the popup opens a new file. When I make changes to the file and save it, my Atom crashes. Would it be possible to manually insert the config file? If so, where should it be placed?

**Comment by jpxd** [comment]
Your Atom "crashes"?? Doesn't sound good... Any error messages?

**Comment by Elements-** [comment]
Just a generic "Editor has stopped responding" followed by a full crash.

**Comment by remithomas** [comment]
+1 I got the same issue. Atom version: 1.3.2 / Remote-FTP version : 0.7.15

**Comment by r-pluss** [comment]
Having this issue as well on a fresh install of Atom (1.4.0) on Windows 7, package version 0.7.15.

**Comment by jpxd** [comment]
This seems to be an issue of Atom, since plugins should not be able to crash the whole application...
I'll try to replicate it in the next days when I can get my hands on a Windows 7 machine
@Elements- Just copy the example .ftpconfig file in your project folder

**Comment by aidan-doherty** [comment]
+1 same here was working fine for a while then lost the config tried to set it up again then this started happening

**Comment by hatzopoulos** [comment]
Closing old ticket because there is no real leads to go on. Let us know if this happens with the latest versions of both Atom and remote-ftp. (Atom is at [v1.13.0](https://github.com/atom/atom/releases) and remote-ftp is at [v0.9.4](https://github.com/mgrenier/remote-ftp/releases))
