### ISSUE TITLE
Drag and Drop

### ISSUE THREAD

**Issue by mediafish** [icetee/remote-ftp#255]
Hi, 

I cannot drag and drop files in the tree view on my server (can do it locally) and all issues have been closed without an answer.. 

Can you please let me know if that is possible or not.

**Comment by jpxd** [comment]
Drag and Drop is currently not supported in the Remote-FTP tree view

**Comment by jpxd** [comment]
I'm sure it can be implemented and if you have some time to look into it and submitted a PR, that would be great :)

**Comment by DustinWStout** [comment]
This is the LAST thing remaining for me to be able to completely switch from Coda. If I had any idea how to program a drag/drop for this, I would.

**Comment by jpxd** [comment]
Duplicate to #25
