### ISSUE TITLE
Exclude paths and file from sync

### ISSUE THREAD

**Issue by jevo** [icetee/remote-ftp#259]
Hi,

this package is really good. I'm using it just for 4 hours but it makes programming tasks much easier for me. I'm developing on web server and I'm using the package for synchronizing the files and folders.There git is used as SCM. My workflow is:
1. Connect to server
2. Initial sync remote -> local
3. Development
4. Synchronize local -> remote
5. Testing the web app
6. If necessary repeat 3. til 5 
7. Commit and push code
8. Go home;-)

I've recognized a problem while working with git. When I use the command **git status** the changed files were shown as deleted and added, but I've only changed  one code line. That is a little bit confusing and it's not possible to diff staged files.

After a short period of testing I realized that the folder .git is also synchronized to the remote. So I deleted the local folder .git and now I can synchronize the whole local folder to the remote.
And **git diff** and **git status** are working fine.

The same problem is with the file .ftpconfig. This file is saved in the same local folder where the remote files are saved. If I sync local -> remote, it is upload to the folder. **This is an security issue.**

In my opinion it will be a nice extension if the user could defined files, folders which should not been synchronized.

May be it is also possible to add a key map for synchronizing all folder and file of the current project.

Bye
Jens

**Comment by bmkorkut** [comment]
Agreed, an ignore file would be very handy.

**Comment by luglio7** [comment]
+1

**Comment by hatzopoulos** [comment]
Duplicate of https://github.com/mgrenier/remote-ftp/issues/36
