### ISSUE TITLE
latest atom and remote-ftp

### ISSUE THREAD

**Issue by hcanning2014** [icetee/remote-ftp#261]
Hi,
I can't create remote folders or files in the remote tree view and uploading a folder from the local view to remote view doesn't work. Folder doesn't show in remote view. General uploading issues
Thanks

**Comment by hcanning2014** [comment]
its ok figured out I needed to use Add Folder and Add File instead

**Comment by JamesCoyle** [comment]
I had that issue a while ago. The context menu really needs cleaning up. I might look into it at some point. You mind closing the issue if you've solved it?
