### ISSUE TITLE
When I save files, Atom makes duplicate copies of those files and folders arbitrarily on my hard drive.

### ISSUE THREAD

**Issue by justyn-clark** [icetee/remote-ftp#270]
When I double click to open a file on the remote server, that file and folders get copied to my system User folder. However, I have not activated any settings to allow that sync or behavior.

<img width="568" alt="screen shot 2016-01-25 at 11 18 44 am" src="https://cloud.githubusercontent.com/assets/11221796/12562100/3f546bf8-c358-11e5-9fd7-6b472c9edf81.png">

**Comment by jpxd** [comment]
Your probably dropped your ftpconfig into your home folder. Remote-FTP is project folder based. Please create a project folder which should contain your ftpconfig and open this folder (project). When you edit a remote file it will be downloaded into your project folder in order to edit it.
