### ISSUE TITLE
Select local folder root

### ISSUE THREAD

**Issue by timothyarmes** [icetee/remote-ftp#271]
My project is a DocPad project. DocPad generates the static HTML files inside a folder called 'out'.

It's the contents of this folder that I'd like to send to the server. Currently if I upload a filr in that folder then it ends up on the server in a folder called 'out', as you'd expect.

Can we have a configuration option to specify the local project folder which should be considered the root for FTP purposes?

**Comment by jpxd** [comment]
This would overcomplicate some things in the already messy code... Sorry :/
