### ISSUE TITLE
Mark: Files are not identical.

### ISSUE THREAD

**Issue by tchalupnik** [icetee/remote-ftp#273]
Hello.
Everyone at least once has saved and sent file that was changed by someone else earlier using search engine(Ctrl+P). That occurs because when we are using Ctrl+P file opens from local directory and it could be older than a file on remote.
Can i ask you to create a simple label what shows us if opened file is not identical with remote?  # #

**Comment by samifouad** [comment]
Closing this as it's related to the conversation in #20 

Package currently doesn't hash/compare local and remote files. Feature is planned though!
