### ISSUE TITLE
Add Find File (Ctrl + P) capability

### ISSUE THREAD

**Issue by tupto** [icetee/remote-ftp#276]
Using the 'Find File' command increases my personal efficiency hugely (I struggle with remembering file structures) so being able to use Ctrl + P would be of great benefit

**Comment by cstyves** [comment]
Seriously, this !

**Comment by hatzopoulos** [comment]
You mean something like https://github.com/atom/fuzzy-finder ?

Or something that can search through remote files you have yet to download locally?

**Comment by jpxd** [comment]
Yeah, the fuzzy-finder doesn't work for remote files. I don't think there's a way to add 'virtual' remeote files to the fuzzy finder for Remote-FTP. Downloading the complete remote directory before working should do the trick...

**Comment by CasperHK** [comment]
I really need this function.
