### ISSUE TITLE
support SFTP authentication using Keyfiles or Agents (e.g. pagent)

### ISSUE THREAD

**Issue by fnkr** [icetee/remote-ftp#28]

**Comment by grenierdev** [comment]
Need a bit more information. Remote-FTP use [ssh2](https://github.com/mscdex/ssh2) and does support [keyfiles/agent](https://github.com/mscdex/ssh2#client-methods).

In terms of Remote-FTP SFTP config, you need to configure :
- `agent`
- `privatekey`
- `passphrase`

Will be present in future documentation.

**Comment by fnkr** [comment]
Oh, I didnt see the "Create SFTP config" option. Thanks!
