### ISSUE TITLE
FTP Problem (Tree View not updating)

### ISSUE THREAD

**Issue by Sternberg** [icetee/remote-ftp#281]
When uploading a file via FTP, the tree view panel is not showing an uploaded file or folder once the upload has completed. You firstly have to disconnect, then reconnect to see the uploaded file on the remote server.
This started with the 0.7.16 release and it's still present in the 0.7.17 release. Please help!

**Comment by jpxd** [comment]
@mgrenier could this have something to do with 9909f15374f4c035a67c9d7c4009eb594c5efb7a ?
Nothing else affecting the tree view or ftp was changed since the release before

**Comment by grenierdev** [comment]
Ya I noticed that I messed up the upload feature this monday. The changes in [lib/remote-ftp.js](https://github.com/mgrenier/remote-ftp/commit/9909f15374f4c035a67c9d7c4009eb594c5efb7a) should be reverted.

**Comment by jpxd** [comment]
Should be resolved in the latest release
