### ISSUE TITLE
Could not parse .ftpconfig

### ISSUE THREAD

**Issue by maziar55** [icetee/remote-ftp#288]
Could you please tell me if I'm making a mistake or this is a bug? I receive "could not parse .ftpconfig" with this file:

{
    "protocol": "sftp",
    "host": "xxx.xxx.xxx.xxx",
    "port": 22,
    "user": "ubuntu",
    "pass": "pass",
    "promptForPass": false,
    "remote": "/",
    "agent": "",
    "privatekey": "~/.ssh/_ida_rsa",
    "passphrase": "",
    "hosthash": "",
    "ignorehost": true,
    "connTimeout": 10000,
    "keepalive": 10000
}

**Comment by jpxd** [comment]
The error message was bad... I added a better one more verbose now.
In your case: Your specified privatekey does not exist

**Comment by maziar55** [comment]
Thanks!

```
  From: Jan <notifications@github.com>
```

 To: mgrenier/remote-ftp remote-ftp@noreply.github.com 
Cc: Maziar maziarmotahari@yahoo.com
 Sent: Thursday, February 11, 2016 11:57 PM
 Subject: Re: [remote-ftp] Could not parse .ftpconfig (#288)

The error message was bad... I added a better one more verbose now.
In your case: Your specified privatekey does not exist—
