### ISSUE TITLE
Broken, after new directory created

### ISSUE THREAD

**Issue by Kulikovpavel** [icetee/remote-ftp#290]
After operations with created folder on remote host (SFTP), plugin seems broken, "listing {dirname}" at bottom all time.
http://puu.sh/n5tS6/4f5ed2f2bc.png
Endless.
Only disconnect-connect work, but when try some operation with this folder, "listing" again appear and hold.
Windows 10, plugin version 0.7.19, atom 1.5.2

**Comment by julienmonnard-old** [comment]
I have the exact same problem.

My config is also Windows 10, same plugin version (0.7.19), and atom 1.5.3

**Comment by Kulikovpavel** [comment]
Same problem on my linux system with same remote dir. So, i guess,
something badly broken.
14 Фев 2016 г. 21:06 пользователь "LordAvenfold" notifications@github.com
написал:

**Comment by coolhome** [comment]
Same issue. Probably related with #292 as well.
