### ISSUE TITLE
Remote connection isn't really closed

### ISSUE THREAD

**Issue by carloast82** [icetee/remote-ftp#296]
Hi,
when I close remote connection (i disconnect anche close panel) and local Project Folder, i find a bug if I open a new Local Project (without FTP connection settings).
When i save a new file in my new project, old connection start and this file is automatically uploaded by ftp connection of previous project on previous remote server project folder.
If i quit Atom before and open a new Project Folder this bug there isn't.

bye!

**Comment by jpxd** [comment]
Should be fixed in the latest release
