### ISSUE TITLE
Upload is not working anymore

### ISSUE THREAD

**Issue by masics** [icetee/remote-ftp#298]
After recent update "upload" command is not working anymore. It just doing nothing.

**Comment by wallybhoy** [comment]
I have noticed this also.

**Comment by bloodhound01** [comment]
Same problem. Thought I was going crazy. Syncing doesn't upload either.

**Comment by Tanmccuin** [comment]
Also can confirm this.

**Comment by asturur** [comment]
as version 0.7.20 upload works fine for me.

**Comment by ghost** [comment]
version 0.7.20
I can download but can't upload . I am new to remote-ftp. No error messages.
Edit: Issue was about permissions. I can write to areas with a given write permission to connected user.
But an error message would be good.

**Comment by arzhed** [comment]
+1

**Comment by LopezNathan** [comment]
+1

**Comment by jimmaaay** [comment]
Is anyone still having this issue? As I cannot seem to replicate it

**Comment by hatzopoulos** [comment]
Thanks for posting. Reopen if you have any issues with the latest version.
