### ISSUE TITLE
Installing “Remote-FTP@0.4.7” failed.

### ISSUE THREAD

**Issue by sendyputra** [icetee/remote-ftp#30]
I got error installing remote-ftp on install package 

<pre>
npm WARN `git config --get remote.origin.url` returned wrong result (https://github.com/Benvie/harmony-collections.git) undefined
npm WARN `git config --get remote.origin.url` returned wrong result (https://github.com/Benvie/harmony-collections.git) undefined
npm ERR! git clone https://github.com/Benvie/harmony-collections.git undefined
npm ERR! git clone https://github.com/Benvie/harmony-collections.git undefined
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "c:\\Users\\Me\\AppData\\Local\\atom\\app-0.176.0\\resources\\app\\apm\\bin\\\\node.exe" "c:\\Users\\Me\\AppData\\Local\\atom\\app-0.176.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\Me\\AppData\\Local\\atom\\app-0.176.0\\resources\\app\\apm\\.apmrc" "--userconfig" "C:\\Users\\Me\\.atom\\.apmrc" "install" "C:\\Users\\ME~1\\AppData\\Local\\Temp\\d-115030-6336-1d4rga6\\package.tgz" "--target=0.20.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.35
npm ERR! npm  v2.3.0
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR! 
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.
</pre>

**Comment by grenierdev** [comment]
`npm ERR! Please check if you have git installed and in your PATH.`

Please install Git and try again. Atom needs Git to acces custom packages and does little to tel it's users.
