### ISSUE TITLE
Read ssh config file

### ISSUE THREAD

**Issue by rasschaert** [icetee/remote-ftp#301]
I've got a ton of configuration in my ~/.ssh/config file, which is currently not used by this package.
The ssh2 module upstream doesn't parse this file by design, but the author hints to some other node modules that can do this in https://github.com/mscdex/ssh2/issues/70.

It would be great if this package could use my ssh config file for sftp connections.

**Comment by jpxd** [comment]
Feel free to submit a PR :)

**Comment by martinosorb** [comment]
I'm also interested in this enhancement. For me, it's the easiest way to do ssh tunnelling through a gateway.

**Comment by ilessiivi** [comment]
I made a PR #834 to satisfy my own needs for this. Please test if it works for you too.

**Comment by rgarrigue** [comment]
So... was the PR merged ? We've servers with internal name resolution behind a bounce, remote-ftp can't deal with it as is.
