### ISSUE TITLE
Avoid having client-side project to manage server-side projects

### ISSUE THREAD

**Issue by ilanbiala** [icetee/remote-ftp#302]
All of my work is stored on a server, and creating an empty folder just to store an ftpconfig seems really unnecessary. Is there any way to just make it so that I can connect to a server and edit everything in a folder as if it's local without having anything other than SSH/SFTP configs defined in a home directory or something?

**Comment by jpxd** [comment]
Sorry, this is the way how Remote-FTP works.....
