### ISSUE TITLE
Show hidden files does not show hidden folders like .git

### ISSUE THREAD

**Issue by mikehancoski** [icetee/remote-ftp#304]
If I toggle show hidden files on i still can not see .git

I also can not see my .gitignore I am can not figure out how to replicate the files issue though 

the folders seems to be every folder

I have  turned off all my file hiding and I can see the hidden folders and files if I just open a local directory

**Comment by ariamckinley** [comment]
This is odd, I just installed this addon myself and I can see both my .git directories and .gitignore files in my remote directory.

**Comment by jpxd** [comment]
On local or remote? FTP or SFTP?

**Comment by pagestyles** [comment]
Same here, neither see .htaccess nor other hidden files remote via FTP on OSX or Windows
Only see them local.

Tested some hosters:
In some hosters the hidden files are displayed apparently normal like other files else, others seem to actually hide them completely.
For some hosters I see the hidden files remote via remote-ftp, others not.
In many FTP programs, there is a function to force the display of hidden files.
Maybe this is an approach?

**Comment by hatzopoulos** [comment]
Linking https://github.com/mgrenier/remote-ftp/issues/244

**Comment by jpxd** [comment]
Should work now
