### ISSUE TITLE
Remote FTP: Error: Timed out while making data connection

### ISSUE THREAD

**Issue by nygkin** [icetee/remote-ftp#306]
I am getting this error after about 10 seconds after it says it connected.  I assume it has something to do with the connTimeout.  If you can help me out I would greatly appreciate it.  My .ftpconfig is the default ftp config with the host, user, and pass set to the proper things.  

{
    "protocol": "ftp",
    "host": "#########.com",
    "port": 21,
    "user": "####",
    "pass": "#######",
    "promptForPass": false,
    "remote": "/",
    "secure": false,
    "secureOptions": null,
    "connTimeout": 10000,
    "pasvTimeout": 10000,
    "keepalive": 10000
}

**Comment by jpxd** [comment]
Did you try to set the keepalive to a lower one? Can you post the developer console output after the timeout?

**Comment by Rho-bur** [comment]
Hi,
I am getting the same error. I have installed it yesterday, it worked, then today it didn't.
It fails to connect entirely.
The error is "Remote FTP: Error: Timeout while connecting to server"
Thee is no problem with the FTP I can connect with Filezilla easily with the same credentials.
Tried to uninstall the install again, increase connTimeout, no luck, the error persists.
In config.cson appears : "Remote-FTP": {}

**Comment by capitanfindusfi** [comment]
Hi, same problem here.
@Rhogit did you find a solution so far?

**Comment by Rho-bur** [comment]
Not yet, since I don't get any other error message to pinpoint the issue.
Using remote edit for the moment :-(

**Comment by capitanfindusfi** [comment]
Don't know if it can help, but from the ATOM dev console this is what I get:

```
< 220 (vsFTPd 3.0.2)
< 331 Please specify the password.
< 230 Login successful.
< 211-Features:
< EPRT\r\n EPSV\r\n MDTM
< PASV\r\n REST STREAM\r\n SIZE\r\n TVFS\r\n UTF8
< 211 End
< 200 Switching to Binary mode.
< 227 Entering Passive Mode (172,16,25,7,180,244).
< 200 NOOP ok.
< 225 No transfer to ABOR.
< 200 NOOP ok.
```

**Comment by jhossipoff** [comment]
Haven't used Atom for a week and now I get this error. 

Anyone found a solution?

**Comment by waldemarm** [comment]
I had the same error and the problem was related to the FTP server setup. FTP server accepted connections only in the 'Active' mode, however Atom FTP use passive mode. I am not sure if there is an option in the .ftpconfig file which will allow to use active mode instead of passive. 
In my case I've reconfigured FTP server and the firewall to allow passive FTP and that solved the issue.

**Comment by samifouad** [comment]
Seems like you hit the nail on the head @waldemarm. It's described here: #40 

This plugin only works in passive mode. If anyone who commented is on passive mode and still have connection problems, please create new issue. I'm going to close this to keep things tidy.
