### ISSUE TITLE
0.4.7 not working

### ISSUE THREAD

**Issue by theRichu** [icetee/remote-ftp#31]
Hello,

It is not working after update to 0.4.7

I connect sftp to my server.

uploading progress bar is never end.

My atom version is 0.177 and OS is Mac 10.10.2

**Comment by pruge** [comment]
+1 me too

**Comment by aureliojargas** [comment]
+1
The upload bar never stops and the remote file gets truncated (zeroed).
Conecting, listing files and downloading is working fine.

Tested on my Mac (Yosemite) and on Windows 7. Both with latest Atom 0.177.

**Comment by ghost** [comment]
It isn't working for me either.  Just tried again with . 0.4.8 and no luck.

**Comment by grenierdev** [comment]
Can you guys open up the console `CTRL+ALT+I` (on Windows) and post the error here?

**Comment by luizpaulo165** [comment]
+1 me too. I'm using Windows 8.

**Comment by grenierdev** [comment]
Can you guys run the following snippet in your atom's developer tool? Paste the resulting line.

``` js
atom.project.remoteftp.connector.put(
    "/path/to/file/you/want/to/upload",
    function () { console.log('Completed', arguments); },
    function () { console.log('Progress', arguments); }
);
```

This line will try to upload a file and will print some debug in the console.

**Comment by aureliojargas** [comment]
@mgrenier New plugin version 0.6.0 is working fine. Thanks for the update! :+1: 

I'm using Atom 0.182.0 in Windows 7.

**Comment by grenierdev** [comment]
@luizpaulo165 @brocknessmonster @theRichu @prugel Is it fixed on your side too?

**Comment by luizpaulo165** [comment]
I do not have this problem. I am using a macbook now.It is working properly.
