### ISSUE TITLE
Download on folder click

### ISSUE THREAD

**Issue by JohJohan** [icetee/remote-ftp#311]
Hello,

Is there a way to build a feature that when a folder is loaded i dont have to click on reload to update the folder, but instead open and close the folder to update the files inside that folder.

**Comment by jpxd** [comment]
In the remote view?

**Comment by JohJohan** [comment]
Hello,

Thank you for you replay.
What i mean is that when you already opend a folder. It synced all the files, now if you want to update those files you have to right click on the folder and hit refresh, is there a way to make it so that you can just close and open the folder to reload?

I hope i have expleand it good enough, else i will hear it.

**Comment by jpxd** [comment]
It already works that way. If you close and reopen a folder in the remove view, its content list is refreshed.
