### ISSUE TITLE
SFTP not listing remote contents

### ISSUE THREAD

**Issue by jimtryon** [icetee/remote-ftp#314]
Whenever I connect with an sftp connection, I can't see the directory structure on the remote.  It works well with an ftp connection, but unable to get it working with sftp.  I set the path to empty in the configuration file and nothing shows.

The port for my specific server is 2222 instead of 22.  I don't know if that makes a difference.  

I appreciate any help in resolving this issue.

**Comment by snigel1** [comment]
+1, on a regular port 22 connection

**Comment by mharding7va** [comment]
Same here. Port 2222 not show remote folder contents for SFTP.

**Comment by jpxd** [comment]
This should not depend on a port. Can you post your .ftpconfig files (without credentials of course)?

**Comment by mharding7va** [comment]
I agree and don't think the port matters, but no sure.  Here is the .ftpconfig contents.  If you need access to an sftp server I can set one up for you to test.

{
    "protocol": "sftp",
    "host": “hosting_server.com”,
    "port": 2222,
    "user": “username”,
    "pass": “password”,
    "promptForPass": false,
    "remote": "public_html/files_go_here”,
    "agent": "",
    "privatekey": "",
    "passphrase": "",
    "hosthash": "",
    "ignorehost": true,
    "connTimeout": 10000,
    "keepalive": 10000,
    "keyboardInteractive": false
}

**Comment by mharding7va** [comment]
BTW.  It works fine.  It uploads files on save as it should.  I just can't see the files in the treeview.

**Comment by jpxd** [comment]
The problem lies within the remote path. Try to use an absolute one if you can (e.g. `/var/www/public_html/files_go_here`).
But yeah... this is a bug somehow, that Remote-FTP ignores the working directory and depends on absolute paths with SSH

**Comment by mharding7va** [comment]
YEAH!  That did it? Had to use the entire document root.  Since I am on a shared server the path is /home/account_name/public_html/files_go_here.

Thanks!

**Comment by jpxd** [comment]
Great! As a quick fix, it will be mentioned somewhere in the README...
