### ISSUE TITLE
Auto connect on save

### ISSUE THREAD

**Issue by nbdamian** [icetee/remote-ftp#316]
Could we add a setting in the .ftpconfig that allows the plugin to reconnect to the FTP server on save if the connection has been disconnected?

**Comment by JamesCoyle** [comment]
There is already a feature in the settings for this.

**Comment by jpxd** [comment]
Off topic:
@mgrenier Could you please add @JamesCoyle to the collaborators on the repository? I guess he's the only one actively responding to issues here.... This way he could close answered questions himself.
