### ISSUE TITLE
On timeout, clear panel

### ISSUE THREAD

**Issue by nbdamian** [icetee/remote-ftp#317]
On data transfer timeout (or some timeout that causes disconnection), the ftp sidebar should not maintain, but clear and have the initial "Connect, edit configuration or close panel" text.

**Comment by JamesCoyle** [comment]
Perhaps this should be an option? I personally prefer having the treeview remain so I can easily click on files and the FTP reconnects. Returning to the connect screen would be really annoying for me.

**Comment by isherwood** [comment]
The problem, at least in my case, is that the visual indication that the connection has failed is inconspicuous. I've often found myself troubleshooting a problem after I've already fixed it due to a failed sync. It needs to be much more clear that the connection has closed.

**Comment by bencarrr** [comment]
@isherwood I literally had the same problem just now, I was stumped for a good 2 hours on this one. I think there should be a clearer indication of transfer failures or timeouts, like a popup box.

**Comment by jpxd** [comment]
I think we do reconnect automatically on timeout now 🤔
So there is no point in this anymore

**Comment by JamesCoyle** [comment]
Well if that's the case there may be a bug. Last time I used it it disconnected and didn't reconnect on save or on opening files so I had to manually disconnect and reconnect.
