### ISSUE TITLE
Warn user when files are being modified. (feature request???)

### ISSUE THREAD

**Issue by Suilied** [icetee/remote-ftp#320]
Most of the times this tool replaces the workflow of: editting file -> upload said file via filezilla or whatever -> go to your terminal session / webpage / custom app -> reset to confirm changes. So for me it was jarring when I connected to my remote folder it would overwrite my local changes that I wanted to upload with the old files that were present on the remote server. Sometimes this is what you want, sometimes it isn't. IMHO the tool should at the very least ask, or keep a log of the last 20 operations or something. Took me a while to figure out that my local changes had essentially been reverted. 

I'm not sure if a semi-feature request like this is allowed here, I'll remove it if it's inappropriate.

**Comment by JamesCoyle** [comment]
That is kinda intended behavior. If you open a file it will download it and overwrite any file with the same name. If you want to upload local changes first you need to open the local versions and save those so they are uploaded.
