### ISSUE TITLE
Prevent .ftpconfig from uploading itself (to protect passwords)

### ISSUE THREAD

**Issue by ol1s** [icetee/remote-ftp#322]
Think it would be sensible to automatically prevent the .ftpconfig file from being uploaded in order to prevent passwords from being uploaded into public access.

**Comment by Sancho-Panza** [comment]
+1

Had to remove a whole github repository once, cause I forgot to add it to my .gitignore...

**Comment by mattomalley** [comment]
+1

**Comment by mario-fehr** [comment]
+1

**Comment by wsoyka** [comment]
+1

**Comment by mosscla** [comment]
+1

**Comment by SakuraOran** [comment]
Put this in your .htaccess in the root of your site:

```
<files .ftpconfig>
    <IfModule mod_authz_core.c>
        Require all denied
    </IfModule>
    <IfModule !mod_authz_core.c>
        Order allow,deny
        Deny from all
    </IfModule>
</files>
```

**Comment by jpxd** [comment]
You can use the `.ftpignore` (works like `.gitignore`) file for this.
