### ISSUE TITLE
Remote FTP: Connection closed

### ISSUE THREAD

**Issue by ghost** [icetee/remote-ftp#324]
Can not connect to SFTP, keep getting this message "Remote FTP: Connection closed".

**Comment by jmrose** [comment]
npm install ssh2@0.4.14

**Comment by ghost** [comment]
Thanks, but I can't execute the workaround proposed in #325 ...
Is there anything else could be done to make atom connect with FTP ?

Thanks

**Comment by jpxd** [comment]
When it was the problem from #325, it should be fixed in the latest release
