### ISSUE TITLE
某些FTP连不上

### ISSUE THREAD

**Issue by 758915145** [icetee/remote-ftp#328]
我有一个虚拟主机，没有独立ip那种虚拟主机，使用remote ftp连接得上，但是实际上是连接失败的（不显示目录、无法上传）。

连接时的一些提示：
<-220-Microsoft FTP Service\r\n220********_FTP!
<331 Password requIred
<230-**_******
<230 User logged In
<211-Extended features supported:\r\n LANG EN_\r\n UTF8
<AUTH TLS;TLS-C;SSL;TLS-P;\r\n PBSZ\r\n PROT C;P;\r\n CCC\r\n HOST\r\n SIZE\r\n MDTM\r\n REST STREAM\r\n211 END
<200 Type set to I.
<277 Entering Passlve Mode(_****)
<125 Data connection already open; Transfer starting.
<226 Transfer complete

上传时提示：
<550 Access is denied.

**Comment by jpxd** [comment]
Can you resubmit this issue in english please? I can't understand and Google Translator isn't helping really much...
