### ISSUE TITLE
Files randomly truncated at up/download

### ISSUE THREAD

**Issue by mattomalley** [icetee/remote-ftp#330]
As of a few months ago any CSS file over 100kb seems to be truncated on upload. Is anyone else experiencing this?

**Comment by DeanmvSG** [comment]
Yep! I get this as well.  It seems like as if the FTP upload "closes" before the file is finished uploading.

**Comment by carloslfu** [comment]
Same issue and causes my code to be broken :(

**Comment by jpxd** [comment]
Limited to FTP or SFTP too?

**Comment by Deanmv** [comment]
@jpxd I am using strictly SFTP and it is happening

**Comment by DeanmvSG** [comment]
@jpxd I am using SFTP and it is happening, not tested with just FTP.

**Comment by mattomalley** [comment]
I'm experiencing this with SFTP uploads.

**Comment by makayjozsef** [comment]
FTP too.

**Comment by jimmaaay** [comment]
I've been getting this while using SFTP at work. I've hopefully created a solution for this issue, when uploading via SFTP, which I shall test at my workplace over a week or so. If you want to try it out check out my fork.

**Comment by DeanmvSG** [comment]
@jimmaaay I merged your changes into the plugin yesterday and ran it all day at work and it seemed to work perfectly.  Although there were cases where the bar doesn't go all the way across (which used to be a sure fire sign that it was truncating) the file was still uploading completely.

I'll keep an eye on it over the next few days but so far so good!

**Comment by jimmaaay** [comment]
Hey update to my previous comment, I have created a pull request which should stop any truncation on upload with SFTP.

**Comment by jpxd** [comment]
Should be fixed with #446
