### ISSUE TITLE
no reaction

### ISSUE THREAD

**Issue by ghost** [icetee/remote-ftp#331]
I cannot open config file
<img width="1088" alt="2016-03-31 17 07 26" src="https://cloud.githubusercontent.com/assets/6612982/14169495/1bc44156-f763-11e5-8095-99b1ab321b2e.png">

clicked create sftp config file but nothing created

**Comment by Deanmv** [comment]
You need to have a "project" (drag a file into the app) first if not the file does not know where to write to.
