### ISSUE TITLE
Can't view settings to hide local tree view

### ISSUE THREAD

**Issue by daviddripps** [icetee/remote-ftp#332]
I click into the Package settings and ...nothing
![screen shot 2016-04-01 at 7 40 02 pm](https://cloud.githubusercontent.com/assets/543895/14223992/8ec6db08-f841-11e5-8392-da2700bc0598.png)

**Comment by Deanmv** [comment]
You have to do it on the page "before".  Just click on "Packages" and then it will show the settings button on the list view.  All packages work this way.

**Comment by daviddripps** [comment]
I swear that option wasn't there yesterday :) Thanks!
