### ISSUE TITLE
Prompt for pass needs to be more dynamic.

### ISSUE THREAD

**Issue by Spillmaker** [icetee/remote-ftp#334]
Other sftp-clients will continue to prompt for password, until keyboard-interactive ends and user is logged inn.

This is not the case for this package, and makes issues for people with custom login-protocols.

In my case, this disables the possibility to use this package on servers where 2FA is activated.

The normal login-procedure for a standard ssh/sftp-server is:

> Username:
> Password:

However at servers with 2FA, the procedure is similiar to this:

> Username:
> Password:
> Verification code:

Password can still be auto-filled, but remote-ftp needs to prompt the user for all of the unknown lines in keyboard-interactive. Verification-code need to pop up as a prompt that the user needs to fill in.

It appears that remote-ftp ignores the "Verification-code:" Text and assumes it was wrong password, thus failing with wrong password/all auth tried error.

I suggest that promptForPass should have the function of prompting whenever, and not only assume its the password its requesting.

Read more about 2FA here https://www.digitalocean.com/community/tutorials/how-to-protect-ssh-with-two-factor-authentication

**Comment by jpxd** [comment]
Hmm, good feature request, but I don't think Remote-FTP's current ssh module (https://github.com/mscdex/ssh2) supports this... If you see a possibility, feel free to submit a PR :)
