### ISSUE TITLE
upload monitored files

### ISSUE THREAD

**Issue by giovannigiordano** [icetee/remote-ftp#335]
Like on sublime i need to upload monitored files when edited

**Comment by Deanmv** [comment]
https://github.com/jimmaaay/remote-ftp 👍

**Comment by jpxd** [comment]
I believe you need the feature described in #312 which was just merged

**Comment by giovannigiordano** [comment]
Thanks a lot. I needed this feature.

Il mercoledì 27 aprile 2016, Jan notifications@github.com ha scritto:

> Closed #335.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub<
> https://ci3.googleusercontent.com/proxy/JH4umjpRKL_9V6smyJ8BDUodQPeA5t83-jKuVUzrSCMOaZnta4scSFmyjnnFhw2Fw2Kex5-0t9jQglxk872v324f4NEvyQSF0FOcCfjcvdfcrdpNNtM6tZdQ7ITK6CYvboEjetazcFy2le8NuUmQd3lGQpkKFg=s0-d-e1-ft#https://github.com/notifications/beacon/AOcb4H1z5JEpiWI-U8SXjODq59aIB3Njks5p78u5gaJpZM4IA794.gif

## 

http://www.giovannigiordano.net
