### ISSUE TITLE
Include ssh tunneling

### ISSUE THREAD

**Issue by andreas-schreiber** [icetee/remote-ftp#336]
Hi all,
I have to connect via terminal to a distant computer via 
ssh -l USERNAME -L 7777:COMPUTER:22 GATE
in order to later use the following config file
{
    "protocol": "sftp",
    "host": "localhost",
    "port": 7777,
    "user": "USERNAME",
    "pass": "",
    "promptForPass": true,
    "remote": "REMOTE_DIR",
    "agent": "",
    "privatekey": "",
    "passphrase": "",
    "hosthash": "sha256",
    "ignorehost": true,
    "connTimeout": 10000,
    "keepalive": 10000,
    "keyboardInteractive": true
}

Is there a way to incorporate tunneling into remote-ftp? Or am I missing a different more elegant approach?

best wishes,
AS

**Comment by jpxd** [comment]
Sorry, currently there is no better way to approach this.
