### ISSUE TITLE
Check if changes are reflected on server after upload

### ISSUE THREAD

**Issue by anand-mishra** [icetee/remote-ftp#337]
Gives an illusion of successful upload/changes/write on the remote server when it actually failed doing so. 
## Steps to reproduce the bug
1. Create a file `/home/username/testfile.txt` on remote sftp server with a user `username` and allow only read permission to it.
2. Setup `.ftpconfig` to use user `username` with required credentials to access `/home/username/testfile.txt`
3. Connect to the server download the file `/home/username/testfile.txt` for editing.
4. Edit the file and upload/save the changes.
## Possible remedy

Compare `md5/sha` signatures of local and remote file, to make sure the upload went successfully otherwise prompt the user with a failure message.

**Comment by samifouad** [comment]
There is a planned feature that will address this problem. Detailed in the comments here: #20
