### ISSUE TITLE
Option for remote file to be opened in new tab

### ISSUE THREAD

**Issue by nahuelhds** [icetee/remote-ftp#338]
Hi! The package is very good! Congrats for that!
This is a feature request.

It would be nice for some cases to have the option to open the files in new tab with it custom name.
Right now if I open local/file.php and then remote/file.php, the second file is open over the first one. Even if I close the second one and I re-open the first one, I see the remote content and not the actual one (the local). Hope not been too confusing.

My idea is to be able to have two tabs: local file and remote file. In that way I could, for example, run some diff functions.

Not always I want modify only the remote file as I'm forced right now.

Thanks in advance

**Comment by jpxd** [comment]
When you open a remote file, it is downloaded to your local project directory and overwrites the local one. A side-by-side view (local vs remote) is currently not possible. Feel free to submit a PR :)
