### ISSUE TITLE
The FTP won't work properly

### ISSUE THREAD

**Issue by albertxbrandt** [icetee/remote-ftp#339]
I can't edit or download files on the server I am connected to.
Here is an image of the error
http://prntscr.com/aryev1
http://prntscr.com/aryf9w
How do I fix this?

**Comment by jpxd** [comment]
Can you post the developer console output?

**Comment by hatzopoulos** [comment]
Closing old issue ticket. Feel free to reopen @alleg0 if you still have problems and can provide some more info.
