### ISSUE TITLE
Toggle View is not working

### ISSUE THREAD

**Issue by fseminario** [icetee/remote-ftp#34]
I tried toggle, connect, disconnect, with no results. Nothing changes in the GUI.

v0.177.0

**Comment by grenierdev** [comment]
Have you check [#27 Remote FTP wont start](https://github.com/mgrenier/remote-ftp/issues/27) ?

**Comment by fseminario** [comment]
Checked out the existing ticket and it helped me figure out that for some reason the version that I was downloading was 0.3. Even though the current version is 0.4. I just tried downloading it directly from you git and dropping it in the /users/fjs/.atom/packages/ folder and then it worked. 

weird that it wouldn't update it from the setting / packages view. 

Anyway, glad its working now. Thanks!
