### ISSUE TITLE
Plug-in won't connect to server,

### ISSUE THREAD

**Issue by AceKatz** [icetee/remote-ftp#340]
"Could not process .ftpconfig," "Error: Invalid host hash algorithm: undefined"

I can provide my ftpconfig if requested.

![screen shot 2016-04-15 at 1 54 41 pm 2](https://cloud.githubusercontent.com/assets/3629426/14570309/a3e80cf2-0311-11e6-9282-ea77b5ceace4.png)

**Comment by kevineleven** [comment]
I am seeing the exact same error as @AceKatz after upgrading.

Atom 1.7.2
Remote-FTP 0.7.20

Any help greatly appreciated. Until the upgrade it was working like a charm - great package!

_EDIT_ I updated the hosthash value in the config similar to others in this issue: https://github.com/mgrenier/remote-ftp/issues/321

@AceKatz see issue 321. Fixed the problem for me.

**Comment by AceKatz** [comment]
That worked perfectly, thanks a lot!

**Comment by SoyArpad** [comment]
can you send me your configuration?, i have the same problem

**Comment by JamesCoyle** [comment]
@AceKatz If you solved the issue it would be helpful if you could close it.
