### ISSUE TITLE
remote-ftp doesn't download the whole file when I open it

### ISSUE THREAD

**Issue by makayjozsef** [icetee/remote-ftp#342]
Sometimes when I open a remote file (php, css, etc.) for editing remote-ftp doesn't download the whole file, instead truncate it after a random line or character number. I tried to find a pattern in this problem but it's very accidental.

Atom 1.6.1
Remote-FTP 0.7.20

**Comment by jpxd** [comment]
FTP or SFTP ?
Please respond in #330
