### ISSUE TITLE
RemoteFTP does not stay disconnected, reconnects on save

### ISSUE THREAD

**Issue by yaliya** [icetee/remote-ftp#346]
I have this issue whenever i save a file. It keeps reconnecting  me to the server in my ftpconfig file even after i disconnect. To make it even worse, i created a local project on my drive and was working on a index.php file. When i hit save remote ftp connected and overwrote my index.php file on the server :(

**Comment by JamesCoyle** [comment]
There is an option in the remote ftp settings called `Auto Upload On Save`. Switch that to `only when connected`
