### ISSUE TITLE
Retry action on connection drop.

### ISSUE THREAD

**Issue by rezaxdi** [icetee/remote-ftp#349]
Hi,

remote-ftp doesn't reconnect automatically if connection drops for example when I change wi-fi connection. So it shows uploading message for ever and I have to disconnect manually and save again.

**Comment by StefanBoettcherASMB** [comment]
also annoying since after disconnect => connect it tries to upload all files again

**Comment by johnisanerd** [comment]
This would be fantastic!

**Comment by icetee** [comment]
I think that's already done #591.
