### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by dkomando** [icetee/remote-ftp#35]
[Enter steps to reproduce below:]
1. Basically have an internal IP saved in a project. I am connected to a different network where this IP does not exist. Without the Remote-FTP package toggled on it seems like it is trying to connect on a save or file open.
2. Love the plugin but I think it would benefit greatly from the Atom JSHint plugin.

**Atom Version**: 0.177.0
**System**: Microsoft Windows 8.1 Enterprise
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.4.8
### Stack Trace

Uncaught TypeError: undefined is not a function

```
At C:\*\.atom\packages\Remote-FTP\node_modules\ssh2\lib\client.js:136

TypeError: undefined is not a function
  at C:\*\.atom\packages\Remote-FTP\node_modules\ssh2\lib\client.js:136:9

```
### Commands

```
     -0:15.6 core:paste (atom-text-editor.editor)
     -0:13.9 core:save (atom-text-editor.editor)
```
### Installed Packages

``` coffee
# User
angularjs, v0.1.0
atom-jshint, v1.5.0
atom-lint, v0.20.1
atom-minjs, v0.2.12
change-case, v0.4.0
coffee-lint, v0.7.3
color-picker, v1.4.4
ember-cli-helper, v0.5.0
ember-snippets, v1.0.0
file-icons, v1.4.9
jsformat, v0.7.18
language-apache, v1.2.0
language-arduino, v0.2.1
language-nginx, v0.4.0
less-autocompile, v0.3.3
linter, v0.11.1
linter-csslint, v0.0.11
linter-htmlhint, v0.0.8
linter-jshint, v0.1.0
linter-jsonlint, v0.1.2
minifier, v0.2.0
minimap, v4.1.3
Remote-FTP, v0.4.8
space-tab, v0.1.0


/cc @atom/core
```

**Comment by grenierdev** [comment]
1. The presence of the sidebar does not dictate how the plugin behaves. If it's hidden or not does not change the save's behavior. If you want to disable this behavior temporarily, just rename the `.ftpconfig` to something else.
2. `[...] benefit greatly from the Atom JSHint plugin.` Can you enlighten me how it would benefit ?

**Comment by dkomando** [comment]
1. Okay will do.
2. Sure thing. JSHint gives suggestions for how Javascript could be written better. When I look at the code, a lot of suggestions come up in nearly every JS file I opened. From missing semicolons to suggestions of dot notation.

Again, I appreciate your work and this plugin but ultimately had to disable it due to it uploading blank or 0 kb

**Comment by dkomando** [comment]
1. Okay will do.
2. Sure thing. JSHint gives suggestions for how Javascript could be written better. When I look at the code, a lot of suggestions come up in nearly every JS file I opened. From missing semicolons to suggestions of dot notation.

Again, I appreciate your work and this plugin but ultimately had to disable it due to it uploading blank or 0 kb

**Comment by dkomando** [comment]
Sorry got cut off . Due to the plugin uploading 0 kb files through sftp to my server. Even though the file was 50+ kb.

I will say, you have really designed the only FTP/SFTP plugin I want to use with Atom though.
