### ISSUE TITLE
Weird behaviour after disabling temporary

### ISSUE THREAD

**Issue by alesub** [icetee/remote-ftp#350]
First of all, this is a great package, I can't live without it.

There's a strange issue when disabling it though: I had to disable it for a project that didn't have an ftpconfig file because it wanted to upload the files to the previous project. After enabling it again, it started to upload every file twice. After uninstalling and installing it again, it says "connecting", "connection close" right away, without connecting. I re-created the ftpconfig file including all its paramenters, and now the error I get is "Error: Invalid host hash algorithm: undefined".

Thanks!

**Comment by jpxd** [comment]
"it wanted to upload the files to the previous project"
Reloading Atom should fix the problem, but a recent PR throws away the connection when the project changes
Please reopen the issue when the issue still exists

**Comment by alesub** [comment]
Yes, I actually tried re-installing atom and this package, but the problem persist. It only happens with sftp though, ftp connections work correctly.

**Comment by jpxd** [comment]
The fix was just published under an hour ago, maybe you could manually try the suggestion in #325

**Comment by alesub** [comment]
I updated the package and restarted atom, the problem remains the same. Here's the ftpconfig (without actual credentials which are tested on a standard sftp client). The connection says "connection open" and "connection closed" right away.

```
{
    "protocol": "sftp",
    "host": "****",
    "port": 2222,
    "user": "****",
    "pass": "****",
    "promptForPass": false,
    "remote": "/",
    "agent": "",
    "privatekey": "",
    "passphrase": "",
    "hosthash": "",
    "ignorehost": false,
    "connTimeout": 10000,
    "keepalive": 10000,
    "keyboardInteractive": false
}

```

**Comment by jpxd** [comment]
Can you please open the developer console and post the output here?

**Comment by alesub** [comment]
You can consider this issue solved, after restaring the pc I now can connect to sftp normally. Thanks for your hard work, this package is the best!
