### ISSUE TITLE
Symlink

### ISSUE THREAD

**Issue by de1eted** [icetee/remote-ftp#351]
When select symlink, jump to target folder. 
Now i have duplicate folders in local project folder:
- _local
- site1
  - local (symlink to _local)
- site2
  - local (symlink to _local)

In WinSCP when i click symlink, focus move to target folder

**Comment by jpxd** [comment]
Currently symlinks are broken anyway. But they are followed on the server so clientside it looks like a folder. Would be a nice feature to have, but currently the symlinks have to be fixed in general. (#279)
