### ISSUE TITLE
Ubuntu 15.10 When I open a file its a empty file

### ISSUE THREAD

**Issue by ArdiArtani** [icetee/remote-ftp#352]
Hello, i have Atom and remote-ftp installed in my Ubuntu 15.10.

I connected to my host i can see all my folders and files in the treeview but when i open a file its a empty file nothing on it ???

Atom 1.7.2
Remote-ftp 0.8.0

**Comment by jpxd** [comment]
FTP or SFTP ? Please post the output of the developer console.

**Comment by ArdiArtani** [comment]
FTP

Output developer console:

Window load time: 2029ms
::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
< 220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------\r\n220-You are user number 5 of 1000 allowed.\r\n220-Local time is now 11:17. Server port: 21.\r\n220-This is a private system - No anonymous login\r\n220-IPv6 connections are also welcome on this server.\r\n220 You will be disconnected after 15 minutes of inactivity.
< 331 User ideviceb OK. Password required
< 230 OK. Current restricted directory is /
< 211-Extensions supported:\r\n EPRT\r\n IDLE\r\n MDTM\r\n SIZE\r\n MFMT\r\n REST STREAM\r\n MLST type_;size_;sizd_;modify_;UNIX.mode_;UNIX.uid_;UNIX.gid_;unique_;\r\n MLSD\r\n AUTH TLS\r\n PBSZ\r\n PROT\r\n ESTA\r\n PASV\r\n EPSV\r\n SPSV\r\n ESTP\r\n211 End.
< 200 TYPE is now 8-bit binary
< 227 Entering Passive Mode (173,254,28,90,157,130)
< 150 Accepted data connection
< 226-Options: -a -l \r\n226 47 matches total
< 227 Entering Passive Mode (173,254,28,90,194,221)
< 150 Accepted data connection\r\n226-Options: -a -l \r\n226 17 matches total
< 227 Entering Passive Mode (173,254,28,90,166,82)
< 150 Accepted data connection\r\n226-Options: -a -l \r\n226 33 matches total
< 227 Entering Passive Mode (173,254,28,90,167,244)
< 150 Accepted data connection
< 226-Options: -a -l \r\n226 9 matches total
< 550 Can\'t change directory to /public_html/filedeo/ad300.html: Not a directory
< 250 OK. Current directory is /
< 227 Entering Passive Mode (173,254,28,90,182,212)
< 150 Accepted data connection
< 226-File successfully transferred\r\n226 0.019 seconds (measured here), 26.57 Kbytes per second
< 200 S OK
< 200 Zzz...
< 550 Can\'t change directory to /public_html/filedeo/ad300.html: Not a directory
< 250 OK. Current directory is /
< 227 Entering Passive Mode (173,254,28,90,186,166)
< 150 Accepted data connection
< 226-File successfully transferred\r\n226 0.000 seconds (measured here), 4.72 Mbytes per second
< 200 S OK
< 550 Can\'t change directory to /public_html/filedeo/ad729.html: Not a directory
< 250 OK. Current directory is /
< 227 Entering Passive Mode (173,254,28,90,183,137)
< 150 Accepted data connection
< 226-File successfully transferred\r\n226 0.011 seconds (measured here), 30.35 Kbytes per second
< 200 S OK
< 200 Zzz...

**Comment by ArdiArtani** [comment]
I fixed the problem, the host files were getting downloaded and stored in my home directory but the opened file had the wrong path to the file. 

I opened the config folder and edit the application.json, I deleted the first **InitialPaths**

`[{"initialPaths":["atom://.atom/config"]},{"initialPaths":["/home/user/.atom"]}]`

New application.json
`[{"initialPaths":["/home/user/.atom"]}]`

**Comment by ArdiArtani** [comment]
I fixed the problem, the host files were getting downloaded and stored in my home directory but the opened file had the wrong path to the file. 

I opened the config folder and edit the application.json, I deleted the first **InitialPaths**

`[{"initialPaths":["atom://.atom/config"]},{"initialPaths":["/home/user/.atom"]}]`

New application.json
`[{"initialPaths":["/home/user/.atom"]}]`
