### ISSUE TITLE
Can this plugin be used to work locally and sync remotely (folder mapping)?

### ISSUE THREAD

**Issue by dallanlee** [icetee/remote-ftp#353]
I've been using Sublime Text but I think I want to switch to Atom. Atom seems to have plugins to do everything I do with Sublime and then some. But, an essential part of my workflow is editing files locally, then on save, the remote file is replaced and I refresh to browser to see the changes (on the remote staging server). I do this in Sublime with [Sublime SFTP](https://wbond.net/sublime_packages/sftp) by "mapping" the local and remote folders. 

Can this be done with Remote FTP for Atom? Thanks!

**Comment by jpxd** [comment]
Yes, there is a setting for auto-upload-on-save in the package settings (see the screenshot in the README)

**Comment by dallanlee** [comment]
I'm sorry. I thought I looked through it thoroughly enough and didn't see anything. Thanks, @jpxd

**Comment by thankachankarun** [comment]
How would can i control the mapping between the local and remote folders? It seems to be creating remote folders copy in the root of the local project. I want to map it to a particular folder in my local project
