### ISSUE TITLE
Removing One Letter

### ISSUE THREAD

**Issue by zeom** [icetee/remote-ftp#356]
This plugin removes first letter of file when i try to update any file.Is this a bug only for me or anyone else facing with this issue too?

**Comment by ranea** [comment]
same problem

EDIT: i fixed it.  I was using SFTP template configuration options. Replace it with FTP template configuration options [here](https://github.com/mgrenier/remote-ftp#configuration-in-projects-ftpconfig-file)

**Comment by jimmaaay** [comment]
I can't remember if this still is an issue. If you're still seeing it, let me know and I'll reopen the issue.
