### ISSUE TITLE
Possibility to make an ignore list

### ISSUE THREAD

**Issue by rafaelrp** [icetee/remote-ftp#36]
Possibility to make an ignore list, when i upload an entire folder all files was uploaded, would nice feature to add an ignore list.

**Comment by josephmiclaus** [comment]
+1 
can't promise when exactly, but if nobody is working on this, i'd like to take a look at it in June sometime.

**Comment by grenierdev** [comment]
I think this ignore list should be per-project (not in the package settings). I had in mind to add a new file `.ftpignore` similar to the `.gitignore` that uses the same ignore pattern.

Is this what you had in mind ?

**Comment by josephmiclaus** [comment]
Yes, I had thoughts in that direction too.

I'm not sure though, how hard it is to implement the same ignore pattern that .gitignore uses.

**Comment by hatzopoulos** [comment]
Checkout either of these
- https://github.com/kaelzhang/node-ignore
- https://github.com/mafintosh/ignore-file
- https://www.npmjs.com/package/fstream-ignore

**Comment by PawelGIX** [comment]
+1

**Comment by Asbra** [comment]
What's the status on this?
Would be great if it would parse .gitignore and/or a .ftpignore as in #117 
Coloring based on differences to local copy and ignored/not would be excellent.

**Comment by feliksby** [comment]
+1

**Comment by cshanejennings** [comment]
+1 and agreed on .ftpignore following a .gitignore similar syntax would probably be the "least unexpected" approach

**Comment by alucidwolf** [comment]
+1 on this one as well, would be an awesome feature to ignore, or "cloak" like Dreamweaver does so certain files do not upload when pushing a folder or syncing

**Comment by linuz90** [comment]
Loving Remote-FTP, but the inability to ignore files and folders makes it hard to use it as the only FTP package. Any progress on this?

**Comment by 4ley** [comment]
I would love to have that feature. Created another ticket before discovered this one. [#430](https://github.com/mgrenier/remote-ftp/issues/430)

**Comment by josephmiclaus** [comment]
@Asbra @cshanejennings @Saiyanomaly @linuz90 @4ley 

I've updated the PR [.ftpignore feature from issue #36](https://github.com/mgrenier/remote-ftp/pull/117). That should do the job (for now).

**Comment by jpxd** [comment]
Merged @miclaus PR
