### ISSUE TITLE
Feature: Option to display FTP tree-view on the right side

### ISSUE THREAD

**Issue by KolyaKorruptis** [icetee/remote-ftp#364]
Maybe there already is a simple way that I'm not aware of, but an option would be appreciated.

**Comment by ghost** [comment]
It looks like that this option is already implemented in `tree-view.js`, but not active or not done.

```
atom.config.onDidChange('tree-view.showOnRightSide', function () {
    if (self.isVisible()) {
        setTimeout(function () {
            self.detach();
            self.attach();
        }, 1);
    }
});
```

**Comment by ubergeekzone** [comment]
just change this code around line 239 in tree-view.js, it will make remote-ftp show on the right.

```js
this.panel = atom.workspace.addLeftPanel({item: this}); // change to addRightPanel	
```

**Comment by icetee** [comment]
Please check new Remote-FTP [version](https://github.com/mgrenier/remote-ftp/releases/tag/v1.0.0). Supported new Dock / Pane methods. (Require Atom >=1.17.0)
