### ISSUE TITLE
Could not process .ftpconfig (Error: PPK MAC mismatch)

### ISSUE THREAD

**Issue by ghost** [icetee/remote-ftp#370]
hi,
trying to connect to my server using ssh private key but I get the following error:

> Could not process .ftpconfig (Error: PPK MAC mismatch)

Here is my .ftpconfig file:

```
{
    "protocol": "sftp",
    "host": "ipAddress",
    "port": 22,
    "user": "user",
    "pass": "",
    "promptForPass": false,
    "remote": "/",
    "agent": "",
    "privatekey": "F:\\sshkeys\\private.ppk",
    "passphrase": "passphrase",
    "hosthash": "",
    "ignorehost": true,
    "connTimeout": 10000,
    "keepalive": 10000,
    "keyboardInteractive": false
}
```

Any help, please :)

**Comment by jimmaaay** [comment]
I'm guessing you're on windows? If so you're entering the privatekey path wrong. It'd need to be something like `F:/sshkeys/private.ppk`
