### ISSUE TITLE
When opening files they should come from the server — Not the local filesystem

### ISSUE THREAD

**Issue by Arcrammer** [icetee/remote-ftp#371]
My company just lost revenue because I opened a file within a project that was stored on my computer from about a week ago. They don't use version control but they have back-ups. Because Remote-FTP didn't grab the newest version of the file within Atom the old version was uploaded. More details are available if needed as to how I opened the files.

**Comment by jpxd** [comment]
Sorry to hear this... When you want to work with the current server version, use the Remote-FTP tree view and not Atom's one. When you double click a file in the Remote-FTP tree view it will be updated and opened.
In the package preferences you can select "Hide Local When Displayed" & "Show View On Startup" to use the Remote-FTP tree view in projects with a .ftpconfig.
