### ISSUE TITLE
Configuration of local directory path

### ISSUE THREAD

**Issue by poofeg** [icetee/remote-ftp#376]
I want to deploy single directory from project. How to configure local directory path?
It is possible to configure multiple directories? For example:

```
project
|-dir_one -> sftp://remote/path/one
|-dir_two -> sftp://remote/path/two
|-dir_local_only
|-README
```

**Comment by jimmaaay** [comment]
The best way to do this would be to have a `.ftpconfig` file in each directory. And then open each in atom in separate windows or in the same window if you have the multiple hosts feature ticked in settings.
