### ISSUE TITLE
Enable transfer with character encoding translation

### ISSUE THREAD

**Issue by GrahamHannington** [icetee/remote-ftp#385]
I want to use Atom with the remote-ftp package to edit text files that are stored on a remote IBM z/OS UNIX file system (a mainframe). The native character encoding of text files on z/OS UNIX is EBCDIC; more specifically, in my case, EBCDIC code page 1047.

Currently (please correct me if I'm wrong about this), remote-ftp uses binary ("image") transfer. From the Atom console:

> 200 Representation type is Image

This means that the z/OS FTP server does not perform any character translation, which means that my text files appear garbled in Atom.

Could you please enhance remote-ftp to enable this use case? (Or point me to the existing documentation for this feature that I've missed? :smile:)

One possibility: in the `.ftpconfig` file, allow a new setting for specifying one or more "post-login commands". For example, for my specific use case:

```
TYPE ASCII
SITE SBDataconn=(IBM-1047,ISO8859-1)
```

I understand that you might want to create a separate setting for the transfer ("representation") type, but an option to specify site-specific post-login commands (as shown above) would also be extremely useful. For example, some text files on the same file system might be encoding using a different EBCDIC code page (such as 037); I could have a separate project, with a different `.ftpconfig` file, with the correct `SITE` command, for those.

In case it occurs to you: I'd prefer to have the text files translated during transfer than add support for EBCDIC encoding to Atom.

**Comment by jimmaaay** [comment]
This would be relevant to your other open issue #386.
