### ISSUE TITLE
how to specify local path different than the current project path

### ISSUE THREAD

**Issue by chrisduong** [icetee/remote-ftp#387]
Hi,

When I wanted to keep tracked of **remote files** within sub path of the current project, I don't see any configuration allow to do that.

Thanks for reading.

**Comment by christophevouillamoz** [comment]
+1
Need it too

**Comment by isherwood** [comment]
Same here. I'd like to have two different directory paths open on connect.

**Comment by jimmaaay** [comment]
@chrisduong I'm not sure I understand fully, could you please clarify by what you mean?

**Comment by jimmaaay** [comment]
Okay never mind I get it now. Duplicate of #361
