### ISSUE TITLE
Unreliable

### ISSUE THREAD

**Issue by fulldecent** [icetee/remote-ftp#388]
I edit remote files using remote-ftp as well as Coda.

Every time that I edit remote files with Atom I will first quit and then reopen.

There have been some occasions when remote-ftp will open the older, local file, rather than getting the newer remote file. This has been painful and led to data loss.

**Comment by fulldecent** [comment]
Have others seen this as well?

**Comment by jimmaaay** [comment]
The package currently has no feature to check if theres a newer file on the server.

**Comment by jpxd** [comment]
Linking to #450
