### ISSUE TITLE
console

### ISSUE THREAD

**Issue by czmole** [icetee/remote-ftp#390]
Maybe someone else asked before but I can not find it so here it is :) Is there any way to activate a console for the plugin?
I mean a console to show what's happening that a file was saved, etc, a console of all FTP transactions (like the FTP plugin for Notepad++ https://db.tt/pidC485t)
Asking this because for example if a file does not have write privileges I have no way to see that file was not actually saved. 

Thank you!

**Comment by jpxd** [comment]
The complete FTP output can be found in the Developer console and a summary about the last uploads & downloads in the Remote-FTP Tree view
