### ISSUE TITLE
Feature: show the progress when upload a local file to remote server

### ISSUE THREAD

**Issue by mars-base** [icetee/remote-ftp#391]
Hi, Could you develop a new feature that show the progress when upload a local file to remote server? I've used a plugin named SFTP of Sublimetext, when you save a file, the plugin can show a point progress at the bottom of the sublimetext window. That's very helpful to know the status of the file transfering, succeded or failed.

**Comment by ghost** [comment]
This feature already exists:

Look at the bottom of TreeView (strg+opt+o on Mac) – there are status messages. You will see a progress bar during uploads and success/failure messages.

The package shows you the last 20 messages. Drag the first message up to display the rest.
