### ISSUE TITLE
watch function not work

### ISSUE THREAD

**Issue by xralphack** [icetee/remote-ftp#392]
I add a path in watch array like this, "./wp-content/themes/xxx/style.css" as in Gulp. But file did not upload.

**Comment by SavageCore** [comment]
Try removing the leading `.` worked for my setup

**Comment by jimmaaay** [comment]
Hey @xralphack. Are you still having an issue? I worked on the majority of the watch functionality and would be happy to try and help out :)

**Comment by RonHolt** [comment]
Hey @jimmaaay I'm having trouble with it too.
I use a SASS process running in a separate terminal window to compile my *.scss files to my main style.css.

What I end up having to do is save my style.scss file, then switch to my style.css and save to trigger an SFTP upload from Atom.

It is my understanding that the purpose of watch is to watch to see if there was a change to that file (i.e. being recompiled by the SASS process running in the background) and upload it to the server via SFTP every time it is changed. (Am I wrong?)

I have tried a whole bunch of variations on adding the "watch" setting to my .ftpconfig file and nothing seems to upload the style.css file to the remote server as expected (without manually switching to it and saving).

Here are some examples of what I have tried:

```
"watch": ["./style.css"]
"watch": ["/style.css"]
"watch": ["style.css"]
"watch": ["./wp-content/themes/xxx/style.css"] // the Remote path, not the Local
"watch": "./style.css" // same but testing without brackets
"watch": "/style.css"
"watch": "style.css"
```

Am I doing it wrong? If so, what's the proper settings protocol?

Or does the terminal SASS process just not trigger as a "save"? (I tested this by editing the same file in a different text editor and saving and that didn't seem to work either)

Would love to cut out having to save two different files to preview my changes on my remote server every time I make a minor change. (cmd+s once vs. cmd+s, cmd+1, cmd+s; minor gripe, I know, but 2 keystrokes are better than six when repeated hundreds of times per day.)

P.S. I'm using the latest version of remote-ftp: v0.8.3

**Comment by RonHolt** [comment]
Ok, darn it, I knew it would be something stupid like this...

I had just updated remote-ftp and it seemed to be fully functional, but I just tried closing and reopening Atom and creating a new SFTP file at now it works.

When in doubt, turn it off and back on again. Duh.

Thanks for the additional feature!

**Comment by uncleGena** [comment]
For me, the reason was that I misunderstood "watchTimeout" parameter and increased that value. 
500 ms is just enough.
