### ISSUE TITLE
Watch ignore and wildcard

### ISSUE THREAD

**Issue by ColonelBundy** [icetee/remote-ftp#393]
Please add a wildcard option like:

```
"watch": ["./compiled/**/*.js"]
```

And watchignore

```
"watchIgnore": ["./server/node_modules/*"]
```

This would make this the perfect ftp for atom.

**Comment by jpxd** [comment]
Hi,
watch now supports globs
and since #117 there is a beta version of an .ftpignore file (similar to .gitignore)
