### ISSUE TITLE
Once installed, the package is not listed in the Package List

### ISSUE THREAD

**Issue by rushl** [icetee/remote-ftp#396]
Once installed, the package isn't listed when you go to Settings, and click Packages. It does appear at the top of the list immediately after installation, but on a restart it is no longer visible. The only way to edit settings or uninstall is to find the package on the Install page. On Atom 1.8.0.

**Comment by jpxd** [comment]
Seems to be an Atom issue and not an issue specifically bound to this package. Please submit an issue to the Atom team
