### ISSUE TITLE
While opening FTP tree view, Atom tree view also shown. 

### ISSUE THREAD

**Issue by prakaashkpk** [icetee/remote-ftp#397]
When you press the shortcut key, "ctrl + opt + o", it opens up the atom tree view along with the FTP tree view. 
(Atom tree is accessible by "ctrl + \"  or "cmd+k, cmd+b").

**Comment by JamesCoyle** [comment]
Do you have the `Hide local while displayed` option disabled?

**Comment by prakaashkpk** [comment]
Thanks. Seems to be working now.
