### ISSUE TITLE
FTP active mode

### ISSUE THREAD

**Issue by sofixa** [icetee/remote-ftp#40]
I'm not exactly sure that's an issue(maybe it's just not implemented as a feature), but i can't find how to set the FTP connection mode to active, and not passive(since the server i work on's config refuses passive connections). I couldn't find anywhere a full list of the config options for the connections, so i type with mode, type, connMode, connType.. nothing. Is there a way to connect in passive mode?

**Comment by grenierdev** [comment]
This plugin uses [node-ftp](https://github.com/mscdex/node-ftp) and thus suffer from the same limitations. Unless node-ftp adds support for active connection, it will not be a planned feature fore Remote-FTP.

I'm not aware for other ftp package for nodejs. Maybe in the future Remote-FTP will use an other ftp client.
