### ISSUE TITLE
Feature request: Ignore specific files when doing "Sync local -> remote"

### ISSUE THREAD

**Issue by pmrotule** [icetee/remote-ftp#402]
It would be nice to be able to ignore specific files when you "Sync local -> remote". For instance, .ftpconfig is being uploaded which is not useful.

**Comment by ivanvujisic** [comment]
Even worse, I tried "Sync local -> remote" with "protocol": "sftp" and "privatekey": "/home/ivan/.ssh/gcloud" in the .ftpconfig file so it just fails to sync

**Comment by abumalick** [comment]
Duplicate of #36

**Comment by josephmiclaus** [comment]
I've updated the PR https://github.com/mgrenier/remote-ftp/pull/117

**Comment by jpxd** [comment]
See the PR #117
