### ISSUE TITLE
Uncaught Error: privateKey value does not contain a (valid) private key

### ISSUE THREAD

**Issue by ivanvujisic** [icetee/remote-ftp#403]
Not an issue for me, just to explain weird settings of .ftpconfig

The error below is false (Uncaught Error: privateKey value does not contain a (valid) private key), and you only have to add "agent": "ssh" to the .ftpconfig
1. .ftpconfig file at /home/ivan/.atom contains:

{
    "protocol": "sftp",
    "host": "testwebrtc.vujisic.com",
    "port": 22,
    "user": "ivangcloud",
    "promptForPass": false,
    "remote": "/",
    "agent": "",
    "privatekey": "/home/ivan/.ssh/gcloud",
    "passphrase": "",
    "hosthash": "",
    "ignorehost": true,
    "connTimeout": 10000,
    "keepalive": 10000,
    "keyboardInteractive": false,
    "watch": []
}
1. private key file exists and I'm using it login to my server like this:
   ssh -l ivangcloud testwebrtc.vujisic.com

**Atom Version**: 1.8.0
**System**: Ubuntu 14.04.4
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.8.3
### Stack Trace

Uncaught Error: privateKey value does not contain a (valid) private key

```
At /home/ivan/.atom/packages/Remote-FTP/node_modules/ssh2/lib/client.js:148

Error: privateKey value does not contain a (valid) private key
    at Client.connect (/home/ivan/.atom/packages/Remote-FTP/node_modules/ssh2/lib/client.js:148:13)
    at ConnectorSFTP.module.exports.ConnectorSFTP.connect (/home/ivan/.atom/packages/Remote-FTP/lib/connectors/sftp.js:78:13)
    at Client.module.exports.Client.doConnect (/home/ivan/.atom/packages/Remote-FTP/lib/client.js:280:18)
    at Client.module.exports.Client.connect (/home/ivan/.atom/packages/Remote-FTP/lib/client.js:196:9)
    at Client.<anonymous> (/home/ivan/.atom/packages/Remote-FTP/lib/remote-ftp.js:133:29)
    at /home/ivan/.atom/packages/Remote-FTP/lib/client.js:109:14
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
```
### Commands

```
     -0:01.3.0 remote-ftp:connect (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "remote-sync"
    ]
  },
  "Remote-FTP": {
    "hideLocalWhenDisplayed": true
  }
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.8.3
git-commit, v1.5.2
jshint, v1.8.5

# Dev
No dev packages
```

**Comment by jimmaaay** [comment]
If you're still having this issue leave a comment and I'll reopen.

**Comment by matrixfox** [comment]
~~Not sure what happened. Connected via SFTP and was redirected here...~~

Figured it out. Had to read though 100 lines of errors to find this out... Like really!

Uncaught Error: privateKey value does not contain a (valid) private key

**Comment by onurtimur** [comment]
I am experiencing the same issue, how did you resolve it ?

**Comment by AshutoshSajan** [comment]
I am facing the same issue. privateKey value does not contain a (valid) private key.
Please help me. I am using windows 10 and git bash.

**Comment by ccall48** [comment]
I too am getting this error on mac and linux.
I tried a converted key to pem format as well but it doesn't seem to work either...

Am I doing something silly?

**{SOLVED}**
I was being silly... it is your 'ssh private key' location for server not the 'ssh public key' seems to work fine now 👍

**Comment by NoodleOfDeath** [comment]
I am running `SFTP v1.12.10` in `VSCode 1.64.2 (Universal)` on **Mac OS X Monterey** and I needed to specify the key name as `privateKeyPath` instead of `privateKey` to resolve this issue.

**Comment by Vuyisanani** [comment]
I am also getting the same issue, trying to ssh from Azure service connection (Linux vm) to AWS server (Linux)

`[error]Error: Failed to connect to remote machine. Verify the SSH service connection details. Error: privateKey value does not contain a (valid) private key.`
