### ISSUE TITLE
Remote FTP keeps trying to connect even on wrong project

### ISSUE THREAD

**Issue by deanc** [icetee/remote-ftp#407]
Steps to reproduce:
1. Start atom with no project folders open and install remote-ftp
2. Create local directory
3. Add local directory as project folder
4. Toggle remote-ftp window on and create configuration and connect
5. Save a file and make sure it has changed on remote
6. Add any other project folder
7. Remove original project
8. Toggle ftp pane off
9. Try and save file on second project

What should happen:

> The second project should behave as a normal project and save locally as there is no .ftpconfig for that project.

What does happen:

> It tries to connect to the ftp and save even though the project has no .ftpconfig and also not even the original ftp sync'd directory is present.

**Comment by oztalha** [comment]
I think issue [#389](https://github.com/mgrenier/remote-ftp/issues/389) and this are related. To me, the problem is, in case of multiple local folders open, it always considers the first/top one as the active one.

**Comment by jimmaaay** [comment]
See #469
