### ISSUE TITLE
I can't see remote hidden files

### ISSUE THREAD

**Issue by Sizuji** [icetee/remote-ftp#417]
Hello, thank you very much for your package, but I noticed one bug. I checked "Show hidden files" in package's settings and I can't see hidden files on remote host. Could you help me with this issue? Thanks.

**Comment by theConscience** [comment]
Seriously, it will be very nice if it starts working :)

**Comment by hatzopoulos** [comment]
Linking https://github.com/mgrenier/remote-ftp/issues/244
