### ISSUE TITLE
Local file overwrites without warning if I download same file from remote 

### ISSUE THREAD

**Issue by gauravr-dev** [icetee/remote-ftp#419]
There should be a cache kind of thing to view remote files instead of overwriting the local copy.

**Comment by ryanleichty** [comment]
I had the same issue and it ruined some of my files...

**Comment by newelement** [comment]
Thats basically the only main feature this lacks for me. The ability to edit a remote file without overwriting the local version would be nice.

**Comment by jpxd** [comment]
Duplicate to #265
