### ISSUE TITLE
Remote FTP: Error: Hostname/IP doesn't match certificate's altnames

### ISSUE THREAD

**Issue by JValck** [icetee/remote-ftp#423]
After installing the package and trying to connect to the FTP server I always get the error: 
`Remote FTP: Error: Hostname/IP doesn't match certificate's altnames.` 

After doing some research I found that this was due to node.js, so I adapted the configuration file:

```
{
    "protocol": "ftp",
    "host": "example.com",
    "port": 21,
    "user": "user",
    "pass": "pwd",
    "promptForPass": false,
    "remote": "/site/www",
    "secure": "normal", 
    "secureOptions" : "{rejectUnauthorized:false}"
}
```

I added `{rejectUnauthorized:false}` to the `secureOptions` as this was suggested in the node.js docs. Unfortunately this does not solve the error message. When using FileZilla, I don't have issues with connecting to the server.

**Comment by jpxd** [comment]
Use the secure options from the wiki
 https://github.com/mgrenier/remote-ftp/wiki/Settings#usage-of-self-signed-certs

**Comment by JValck** [comment]
But the server does not support SFTP

**Comment by arafatx** [comment]
> But the server does not support SFTP

Old but to help others: 

That is what he said, use the secure options (`secureOptions`) for FTP.

`"secureOptions": { "rejectUnauthorized": false}`
