### ISSUE TITLE
Cropped first symbol of directory name after download

### ISSUE THREAD

**Issue by piligrimnick** [icetee/remote-ftp#424]
When i try to open some file through sftp connection, after downloading this Atom create new folder with name with cropped first symbol, sometimes with 2 symbols. Tried to reinstall Remote-FTP and Atom, nothing changed. Can you help me?

**Comment by piligrimnick** [comment]
![2016-07-11 17 57 24](https://cloud.githubusercontent.com/assets/20161497/16729873/1da626be-4791-11e6-8708-584fb537a9d6.png)

**Comment by jimmaaay** [comment]
@bogish Are you still having this issue in the latest update? If so please leave a comment and I'll reopen the issue.
