### ISSUE TITLE
Remote-FTP randomly connects

### ISSUE THREAD

**Issue by kartagis** [icetee/remote-ftp#425]
Hello,
At times, Remote-FTP randomly connects to my sFTP server. The most recent incident happened today, when I added project folder which has nothing to do with the sFTP. Other times, it's random. I can provide any info needed.

I'm on Mac El Capitan 10.11.3 Atom v1.8.0.

**Comment by jpxd** [comment]
When auto connect is enabled an you save something in a directory wich contains a .ftpconfig Remote-FTP connects. You can disable it in the package preferences. If this isn't your issue, please reopen
