### ISSUE TITLE
Remote FTP: Error: read ECONNRESET

### ISSUE THREAD

**Issue by Jonathanmav** [icetee/remote-ftp#429]
Hello,

I'm successfully connect to my server but remote-ftp fails to make the listing of these files on the ftp and it shows me the error: "Remote FTP : Error : read ECONNRESET" a few second later

My configuration file is correct so I don't know why I got this.

Someone already have this problem ?

**Comment by mhakes** [comment]
I have the same problem. 
While establishing an ftp connection I can see it hit the site via the CPanel ftp users page, it lasts  for about 3 seconds then the ECONNREST error. Not a problem with for me in  Sublime Text or Notepad++
Unfortunately the inability to ftp makes atom unusable.

**Comment by ghost** [comment]
I've same problem and if i use an Mobile connexion, this problem is fixed.

**Comment by dquartino** [comment]
Same here, unable to connect and list folders on OVH servers.

**Comment by paul2903** [comment]
any update here?

**Comment by hatzopoulos** [comment]
@jimmaaay is this similar to https://github.com/nodejs/node/issues/3595 ?  The connection on the other end idles and the connection error is not handled maybe somewhere.

**Comment by hatzopoulos** [comment]
Sounds like you folks are timing out on bad/slow connections and your server is disconnecting midway through.

**Comment by hatzopoulos** [comment]
Closing. See https://github.com/mgrenier/remote-ftp/issues/585#issuecomment-266694435
