### ISSUE TITLE
Add option to exclude dirs from sync

### ISSUE THREAD

**Issue by 4ley** [icetee/remote-ftp#430]
I would like to define `.git` or `node_modules` as excluded from sync.

**Comment by 4ley** [comment]
Related: [#36](https://github.com/mgrenier/remote-ftp/issues/36) and [#259](https://github.com/mgrenier/remote-ftp/issues/259)

**Comment by josephmiclaus** [comment]
I've updated the PR https://github.com/mgrenier/remote-ftp/pull/117

**Comment by jpxd** [comment]
See the PR for updates
