### ISSUE TITLE
Watch option -> Glob file selectors

### ISSUE THREAD

**Issue by micene09** [icetee/remote-ftp#431]
Hi, i'm using this awesome atom package for production...and sometime i have to watch (upload on change) several files in a folder.

Can you implement the glob file selector ? Adding this functionality will be awesome.

Just use this node package to do it easly: https://github.com/isaacs/node-glob

Thank you for the great job you are doing!

**Comment by jpxd** [comment]
Since #446 the watch feature should allow globs
