### ISSUE TITLE
connects multiple times when uploading multiple files

### ISSUE THREAD

**Issue by UziTech** [icetee/remote-ftp#432]
# Steps to reproduce
1. Make sure you are not connected
2. select multiple files in treeview
3. right click and select Upload
# Expected

Connects to ftp server once and uploads files
# Actual

Connects once for each file selected then uploads all the files

**Comment by jimmaaay** [comment]
Fixed in the dev branch. Will be in the next release. If there are still any issue then please open a new issue.
