### ISSUE TITLE
Seeing this error everytime when i am toggling tree view

### ISSUE THREAD

**Issue by maximumver** [icetee/remote-ftp#433]
Remote Ftp has an option of auto-hide local treview when ftp view is visible.
So i've enabled it.
When i'm turn off ftp tree view with package short key, default local treeview becomes visible again.
So i toggle off it too, because i need more space. with Ctrl + \
And everything is ok.

When in second moment i'm using a shortkey to show again treeview of Remote-FTP i see this error msg. 
At first glance it does nothing to me. I am just closing this msg. But it appears again and again when i switch between toggle on/off between ftp and local trees.

Steps:
1. show ftp tree (package auto hides local treeview, there is an option)
2. hide ftp tree ( and i can see local treeview again)
3. hide local tree view too. (no active tree view now)
4. show ftp tree view ( pop-ups an error)

`TypeError: Cannot read property 'destroy' of null at TreeView.module.exports.TreeView.detach (C:\Users\Admin\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\tree-view\lib\tree-view.js:439:17) at hideLocalTree (C:\Users\Admin\.atom\packages\Remote-FTP\lib\views\tree-view.js:9:65) at TreeView.module.exports.TreeView.attach (C:\Users\Admin\.atom\packages\Remote-FTP\lib\views\tree-view.js:213:4) at TreeView.module.exports.TreeView.toggle (C:\Users\Admin\.atom\packages\Remote-FTP\lib\views\tree-view.js:233:9) at atom-workspace.atom.commands.add.remote-ftp:toggle (C:\Users\Admin\.atom\packages\Remote-FTP\lib\remote-ftp.js:117:19) at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Admin\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:260:29) at C:\Users\Admin\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:3:61 at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Admin\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16) at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Admin\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22) at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\Admin\AppData\Local\atom\app-1.8.0\resources\app.asar\src\window-event-handler.js:98:36) at HTMLDocument.<anonymous> (C:\Users\Admin\AppData\Local\atom\app-1.8.0\resources\app.asar\src\window-event-handler.js:3:61)`

**Comment by maximumver** [comment]
I am still getting this.
And i've found that i am not the only one.
Last 2 comments.

https://github.com/atom/tree-view/issues/390

**Comment by jimmaaay** [comment]
@maximumver I've implemented a workaround for this in the dev branch. I plan on pulling this into the next update in the next few days.

Update: The workaround is in 0.9.0

**Comment by gilad905** [comment]
This still happens to me with 0.9.0 (Atom 1.11.1).
The same steps from @maximumver 's report can be taken to reproduce.
I am also getting the `Remote FTP: See issue #433` message, although I don't know how to view the more specific error message (e.g `TypeError: Cannot read property...` from @maximumver 's report).

**Comment by jimmaaay** [comment]
@gilad905 So what are you seeing when you toggle tree view. Is it just the info popup? If so that should be happening as there is a bug which I couldn't fix so I just made a workaround to only show the info window once.

**Comment by gilad905** [comment]
@jimmaaay if you follow the same step as in @maximumver 's report:
1. show ftp tree.
2. hide ftp tree -> here, local treeview pops up.
3. hide local tree view -> no side pane visible.
4. show ftp tree view -> pop-ups an error.
GOTO step 1. and the cycle goes on like this.

The error pop up doesn't disturb me - the problem for me is that **the local tree view will always re-open on step 2**. Although it was already manually hidden before (step 3). This is annoying because most of the time I wish no side pane will be visible, at all.

Thanks! Gilad.
