### ISSUE TITLE
Downloaded files are all empty

### ISSUE THREAD

**Issue by charliepage88** [icetee/remote-ftp#439]
I'm not sure if this is just a permissions issue I've overlooked - but I can connect fine to my server. But as soon as I download any file, doesn't matter where (tried chmoding 777 on the server too), the file is empty. Both in the local directory and if I open it from the remote connection.

**Comment by jimmaaay** [comment]
@charliepage88 Are you using sftp or ftp?

**Comment by BraulioOC** [comment]
Same here, OS X Yosemite, Atom 1.9.9 
After update any file I download is empty and don´t create the file in the system

**Comment by MagdiElmowafy** [comment]
Same here, OS X Yosemite, Atom 1.9.9 & 1.10.0

**Comment by MagdiElmowafy** [comment]
Finally, the package works perfectly, the reason was because the package run without opening a project.
Just open one, connect to your server, and it will work like a charm.

**Comment by BraulioOC** [comment]
Deleting .ftpconfig file and creating new one work for me, "watchTimeout" property was missing in olders versions

**Comment by jimmaaay** [comment]
If anyone is still having issues, leave a comment and I will reopen the issue.

**Comment by Blunderproof** [comment]
I am still having this issue connecting to an Amazon EC2 instance over the sftp protocol.
