### ISSUE TITLE
Unexpected token c

### ISSUE THREAD

**Issue by QwertyZW** [icetee/remote-ftp#440]
Hi I'm just trying out atom for the first time.

This config file makes remote-ftp complain about the windows path I'm putting into privatekey field.
Unfortunately I don't know how to enable stack traces with atom. 

Error is : "Unexpected token c"

config is

`{
    "protocol": "sftp",
    "host": "192.168.0.12",
    "port": 22,
    "user": "user",
    "pass": "pass",
    "promptForPass": false,
    "remote": "/",
    "agent": "",
    "privatekey": "C:\cygwin\home\id_rsa",
    "passphrase": "",
    "hosthash": "",
    "ignorehost": true,
    "connTimeout": 10000,
    "keepalive": 10000,
    "keyboardInteractive": false,
    "watch": []
}
`

**Comment by jpxd** [comment]
You have to double escape the backslashes in the private key path (like `C:\\cygwin\\....`). Otherwise they will be treated as escape sequences.
