### ISSUE TITLE
Too many errors

### ISSUE THREAD

**Issue by peternowell** [icetee/remote-ftp#441]
I'm a new Atom user, and I'm absolutely loving it so far. But I need SFTP for this project, so I've been trying remote-ftp. Unfortunately I'm frequently getting "Timed out while waiting for handshake" errors, and even when it successfully connects, after the first time I upload something, no other uploads go through. They all just stay in the Queue. Then I'll try to re-connect, which may or may not timeout. It's a frustrating cycle. I know that the configuration works because sometimes it connects.

Any ideas about how to solve this? I'm dying to move off Sublime Text, but Sublime SFTP is infinitely more usable right now. :(

**Comment by jimmaaay** [comment]
@peternowell If you're having issues still I'd be happy to try and help. In the mean time I will close the isuse.
