### ISSUE TITLE
remote file edit with tree view

### ISSUE THREAD

**Issue by isharasjc** [icetee/remote-ftp#442]
Better if we can have,

1) Save remote sessions, so we can work in multiple remote servers.

2) File open not working in tree-view sometime.

Ex:- NotePad++ NppFTP plugin

**Comment by jimmaaay** [comment]
1. Currently multiple hosts feature is being tested in the dev branch
2. Is the error still happening?

Update: In 0.9.0 multiple hosts feature is in beta.
