### ISSUE TITLE
Refresh after folder deletion

### ISSUE THREAD

**Issue by e404** [icetee/remote-ftp#444]
When deleting a remote directory, the **parent directory** won't get refreshed.
This results in the deleted directory being **still displayed**.
**After manually refreshing** the parent directory, the removed dir is gone.

Would be great if the extension refreshes automatically.

**Comment by jpxd** [comment]
SSH or FTP? Works for me with FTP

**Comment by e404** [comment]
I tried it with SFTP and this doesn't work. Should be just a minor fix.

**Comment by jimmaaay** [comment]
@e404 Are you still having this issue? I can't reproduce the error.

**Comment by e404** [comment]
Sorry, I can't tell – not using the extension anymore.

**Comment by jimmaaay** [comment]
@e404 Fair enough.
