### ISSUE TITLE
package.json: set ssh2 dependency to ^0.5 to enable ECDSA/ECDH support

### ISSUE THREAD

**Issue by Darkspirit** [icetee/remote-ftp#445]
https://github.com/mscdex/ssh2/wiki/Changes-from-0.4.x-to-0.5.x
- Support for ECDH for key exchange (node v0.12+).
- Support for ECDSA keys (both for server host keys and private keys for user authentication) (node v5.2.0+).

In our /etc/ssh/sshd_config (OpenSSH on Ubuntu 16.04 server) we have:
HostKey /etc/ssh/ssh_host_ecdsa_key
\# generated with ssh-keygen -t ecdsa -b 521 -N "" -o -f /etc/ssh/ssh_host_ecdsa_key

KexAlgorithms ecdh-sha2-nistp521
Ciphers aes256-gcm@openssh.com,chacha20-poly1305@openssh.com
MACs hmac-sha2-512-etm@openssh.com

**Comment by Darkspirit** [comment]
But https://github.com/mgrenier/remote-ftp/pull/325 could be still a problem. (I don't know.)

(Only) With the latest stable Atom, I am able to connect to my server, if 
i change ssh2 to "^0.5" in ~/.atom/packages/Remote-FTP/package.json,
run "apm install" in that folder (to load ssh2 0.5.0),
set hosthash to sha1 in .ftpconfig,
and change my sshd_config to "MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-512".

I tried to set ssh2 to *, but then "apm install" wont load anything (=no 0.5.0)

Atom    : 1.9.8
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

**Comment by Darkudorus** [comment]
I set ssh2 to 0.5 in /home/myusername/.atom/packages/Remote-FTP/packages.json
and ran apm install in that folder, so ssh2 0.5.0 was loaded.
Then I set hosthash to sha1 in .ftpconfig.

Aug 13 11:29:50 web sshd[11440]: Connection from ***.***.***.*** port 53430 on ***.***.***.*** port 22
Aug 13 11:29:50 web sshd[11440]: debug1: Client protocol version 2.0; client software version ssh2js0.1.6
Aug 13 11:29:50 web sshd[11440]: debug1: no match: ssh2js0.1.6
Aug 13 11:29:50 web sshd[11440]: debug1: Enabling compatibility mode for protocol 2.0
Aug 13 11:29:50 web sshd[11440]: debug1: Local version string SSH-2.0-OpenSSH_7.2p2
Aug 13 11:29:50 web sshd[11440]: debug1: permanently_set_uid: 106/65534 [preauth]
Aug 13 11:29:50 web sshd[11440]: debug1: list_hostkey_types: ecdsa-sha2-nistp521 [preauth]
Aug 13 11:29:50 web sshd[11440]: debug1: SSH2_MSG_KEXINIT sent [preauth]
Aug 13 11:29:50 web sshd[11440]: debug1: SSH2_MSG_KEXINIT received [preauth]
Aug 13 11:29:50 web sshd[11440]: debug1: kex: algorithm: ecdh-sha2-nistp521 [preauth]
Aug 13 11:29:50 web sshd[11440]: debug1: kex: host key algorithm: (no match) [preauth]
Aug 13 11:29:50 web sshd[11440]: fatal: Unable to negotiate with ***.***.***.*** port 53430: **no matching host key type found. Their offer: ssh-rsa [preauth]**
Aug 13 11:29:50 web sshd[11440]: debug1: do_cleanup [preauth]
Aug 13 11:29:50 web sshd[11440]: debug1: monitor_read_log: child log fd closed
Aug 13 11:29:50 web sshd[11440]: debug1: do_cleanup
Aug 13 11:29:50 web sshd[11440]: debug1: Killing privsep child 11449
Aug 13 11:29:50 web sshd[11440]: debug1: audit_event: unhandled event 12

**Comment by Darkudorus** [comment]
https://github.com/mscdex/ssh2-streams/blob/master/README.md
"ecdsa-sha2-nistp521 (node v5.2.0 or newer)"

https://github.com/atom/atom/issues/8395
/usr/share/atom/resources/app/apm/bin/node -v
v0.10.40

holy...

**Comment by jimmaaay** [comment]
Hey I'll have a look and see what I can do.

**Comment by jimmaaay** [comment]
Just to let you know it may take a while as I will need to setup some tests to make sure that this does not recreate the issue #325

**Comment by jimmaaay** [comment]
@TerraX-net This should work now in 0.9.2. As ssh2 has dependency has been set to ^0.5
