### ISSUE TITLE
Package activation is slow & dirty fix

### ISSUE THREAD

**Issue by jpxd** [icetee/remote-ftp#45]
The activation time (according to timecop) in the current version
![screenshot 2015-02-22 20 34 43](https://cloud.githubusercontent.com/assets/10384363/6319989/7eafc76e-bad2-11e4-8814-38c7774e63a2.png)
For some people it isn't that much, but if you have lots of plugins it sums up pretty fast....
I've done some profiling and found that most time is spent in the part:
`var SFTP = require('./connectors/sftp');` in client.js
I didn't dig any further yet but use a simple and dirty hack for me now:

```
// lazy deps loading...
var SFTP = {};
var FTP = {};
setTimeout(function(){ SFTP = require('./connectors/sftp'); }, 1);
setTimeout(function(){ FTP = require('./connectors/ftp'); }, 1);
```

I just wanted to mention this here. I know its dirty and shouldn't be done this way. But since the client first gets initiated when you connect to a server, the required dependencies should be loaded in the meantime and don't block all other packages and the window.

This breaks (at least in my case) nothing and the plugin is still working.

This little hack brought the activation time to
![screenshot 2015-02-22 20 36 00](https://cloud.githubusercontent.com/assets/10384363/6320009/5c004aee-bad3-11e4-84a4-bbb5202485dc.png)

Any ideas to do the activation async in a _good_ way in the release version ?

**Comment by grenierdev** [comment]
Your little hack is only fooling the timecop. The actual user experience is still stalled 193ms.

Probably will move the loading of sub-plugin only when called instead of the activation.
