### ISSUE TITLE
File "Watching" no longer works.

### ISSUE THREAD

**Issue by nrthbound** [icetee/remote-ftp#456]
Before, I could compile down my SASS and it would upload the watched CSS file just fine, now it just completely ignores it.

**Comment by jimmaaay** [comment]
Can you paste your .ftpconfig file into here. And remove any sensitive information.

**Comment by nrthbound** [comment]
{
    "protocol": "sftp",
    "host": "[redacted]",
    "port": 22,
    "user": "[redacted]",
    "pass": "[redacted]",
    "promptForPass": false,
    "remote": "[redacted]",
    "agent": "",
    "privatekey": "",
    "passphrase": "",
    "hosthash": "",
    "ignorehost": true,
    "connTimeout": 9000,
    "keepalive": 9000,
    "keyboardInteractive": false,
    "watch": [
    "includes/css/styles.css"
    ]
}

**Comment by jimmaaay** [comment]
Is the includes folder in the root of the project? If so try adding `./` before it

**Comment by nrthbound** [comment]
Tried your change, still not working. It worked great before this recent update.

**Comment by jimmaaay** [comment]
Shouldn't be anything effecting the watch functionality in the most recent update. Just double checking have you got this in your config now

```
"watch":[
"./includes/css/styles.css"
]
```

**Comment by nrthbound** [comment]
Yup, sure do.

**Comment by jimmaaay** [comment]
Can you try restarting atom?

**Comment by nrthbound** [comment]
I've done that, as well as restarting the machine. I'll dig around a little more and try a few more things and report back.

**Comment by jimmaaay** [comment]
Okay then let me know what happens. I'll see if I can reproduce the issue.

**Comment by nrthbound** [comment]
Still not having any luck here. I think the other thing I miss is it would tell you when it couldn't find a file that was being watched. Now all it says is it's "Added Watch Listeners" and doesn't actually tell you if the file is found or not. 

I've tested this by adding a file to the watch list that doesn't even exist, and it gave no warnings or errors.

**Comment by jimmaaay** [comment]
Unfortunately I can't seem to reproduce the error at all from my end. 

And the message is now due to the library that is being used for the watch implementation. Originally it was made with `fs.watch` but there were some issues, the main one being it would emit the rename event when that had not occurred. So now it's using the npm package `chokidar` which has been a lot more reliable. 

I am planning on adding some more debug features into the plugin so it will be easier to diagnose these issues in the future.

**Comment by nrthbound** [comment]
I've reverted back to 0.8.3 and File Watching works fine again. Thanks.

**Comment by johnsontb** [comment]
The watch function has completely stopped working for me. 
{
    "protocol": "ftp",
    "host": "[redacted]",
    "port": 21,
    "user": "[redacted]",
    "pass": "[redacted]",
    "promptForPass": false,
    "remote": "[redacted]",
    "secure": false,
    "secureOptions": null,
    "connTimeout": 10000,
    "pasvTimeout": 10000,
    "keepalive": 10000,
    "watch":[
        "./theme/assets/css/_.css",
        "./theme/assets/js/_.js"
    ],
    "watchTimeout":500
}

**Comment by jimmaaay** [comment]
Try putting an asterisk in front of the extension so. `./theme/assets/js/*.js`
