### ISSUE TITLE
Could not process: Unexpected token in pass

### ISSUE THREAD

**Issue by stubbies** [icetee/remote-ftp#458]
Using v `0.8.8` I'm getting an unexpected token `[` from the `pass` string.

Example:

```
{
    "protocol": "ftp",
    "host": "***.**.**.*",
    "port": 21,
    "user": "********",
    "pass": "j&{<d\[~6-RK[)w%",
    "promptForPass": false,
    "remote": "/",
    "secure": false,
    "secureOptions": null,
    "connTimeout": 10000,
    "pasvTimeout": 10000,
    "keepalive": 10000,
    "watch": []
}
```

**Comment by jimmaaay** [comment]
I believe you need to escape your backslash. Try `"pass": "j&{<d\\[~6-RK[)w%",`

See [here](http://stackoverflow.com/questions/19176024/how-to-escape-special-characters-in-building-a-json-string)

Edit: Link
