### ISSUE TITLE
Feature request: add Git colour change

### ISSUE THREAD

**Issue by shintaroid** [icetee/remote-ftp#459]
In local, when I edited any file version controlled by `Git` that file will change colour in Tree View. I wonder whether it's possible to add that feature to `remote-ftp`?

By the way, this project is really nice, thanks for you guys' great work!

**Comment by drizko** [comment]
+1

**Comment by davegallant** [comment]
This would be awesome. Also, Git-diff showing each changed line would be even better.

**Comment by jimmaaay** [comment]
Unfortunately I don't think this would be possible, but I'd loved to be proved wrong as it is a great idea.

**Comment by jasaronson** [comment]
+1

**Comment by jpxd** [comment]
See #650
