### ISSUE TITLE
ftpignore

### ISSUE THREAD

**Issue by wsqy** [icetee/remote-ftp#463]
How to make ftpignore file effective? Iwant to ignore some file in remote-ftp, I writtend _.py[cod] \n log/_ like gitignore,but I feel terrible not working.....
how can i do??

**Comment by ghost** [comment]
I am also having some problems with the .ftpignore file. When I rightclick my local project folder and select "Sync local -> remote" the ignored files are also uploaded.

**Comment by dfaulhaber** [comment]
I love the idea of the ignore file, though can this ignore whole directories as well?

**Comment by jimmaaay** [comment]
The ignore feature is built upon the npm package ignore [https://www.npmjs.com/package/ignore](https://www.npmjs.com/package/ignore). So any pattern it excepts should be accepted by Remote FTP

**Comment by jimmaaay** [comment]
If you have any more issue leave a comment.

**Comment by ghost** [comment]
I am sorry, but I think this is not completly solved. My ignored files are still uploaded to the server.

Steps to reproduce:
1. Create the ignore file via "Packages -> Remote-FTP -> Create ignore File"
2. This default file contains two lines with ".ftpconfig" and ".DS_Store" which shall be ignored
3. Create the ftpconfig via "Packages -> Remote-FTP -> Create FTP config file"
4. Fill in your config
5. Right click your local folder in Atom and select "Sync local -> remote"
6. The .ftpconfig file is transfered to the remote server although it should be ignored.

**Comment by jimmaaay** [comment]
@joergmoldenhauer You are correct. I can't seem to get it to work at all. I'm not sure how it is meant to work if I'm honest it would really need to be integrated with the ftp & sftp connectors themselves.

**Comment by oztalha** [comment]
this bug is an extremely important security branch as the passwords (of those who authenticate with a password) will be revealed.

**Comment by jimmaaay** [comment]
@oztalha I understand that this could be a security breach but from what I can see the feature will need quite a bit of work to get functioning correctly.

**Comment by jpxd** [comment]
The `.ftpignore` wasn't working at all! 
Since the latest update and (02b9f7e637e6244206035ef77c957922e095addb) it should work as intended, but currently only for `sync-local -> remote`

**Comment by qbadev** [comment]
it would be great if it could be working while saving files. 
Recently I had been connected to server, and made local changes to .ftpconfig (which I have added to my .ftpignore) putting into it some password :) and then saved, and the file was sent to remote server.

**Comment by TheTimmaeh** [comment]
Sadly the issue still persists. All files mentioned in .ftpignore get uploaded to the server when I edit them. Also I cannot exclude certain remote folders from getting downloaded, e.g. symlinks.

**Comment by stay-open-it** [comment]
Any news about this?
