### ISSUE TITLE
Remote FTP: Error: All configured authentication methods failed

### ISSUE THREAD

**Issue by MallTo-Silence** [icetee/remote-ftp#465]
Server shutdown password, you can not connect to the server.
`
{
    "protocol": "sftp",
    "host": "192.168.1.105",
    "port": 22,
    "user": "**",
    "pass": "",
    "remote": "/",
    "agent": "",
    "privatekey": "/root/.ssh/id_rsa",
    "passphrase": "",
    "hosthash": "",
    "ignorehost": true,
    "connTimeout": 10000,
    "keepalive": 10000,
    "keyboardInteractive": true,
    "watch": [],
    "watchTimeout": 500
}

`
 This is my profile.

**Comment by jimmaaay** [comment]
Is the private key read only?

**Comment by jimmaaay** [comment]
I'm gonna close this, if you are still having issues just leave a reply
