### ISSUE TITLE
Connecting with Multiple Projects

### ISSUE THREAD

**Issue by allendotson** [icetee/remote-ftp#469]
When using multiple projects, connecting to the FTP server always connects to the first project, regardless of what project is currently selected or being worked on.

To reproduce:
Add multiple project folders.
Select one of them and connect.
You'll see that it connects the first project, not the selected one.

**Comment by simon-bueler** [comment]
I'm facing the same issue

**Comment by working-name** [comment]
Confirmed, only the first project folder is taken into account when clicking edit configuration for example. That's regardless of which actual project is selected.

**Comment by shylor** [comment]
Same issue here.

**Comment by Yi-Z0** [comment]
This feature is very useful.

**Comment by jimmaaay** [comment]
There is a feature in the dev branch to allow multiple hosts thanks to @zxwef. Planning on testing a bit more before pushing live, but if anyone plans on using this feature they will need to enable it in the packages settings. 

![remote-ftp-settings](https://cloud.githubusercontent.com/assets/9059048/18892279/e1e1abfa-8500-11e6-830a-b89daaf64f7d.png)

**Comment by working-name** [comment]
Awesome. Thank you much @jimmaaay and @zxwef

**Comment by jimmaaay** [comment]
This is now in 0.9.0, its in beta still. So should be able to have multiple projects in one window and the package will connect to the project which has selected file(s) in the tree view. 

Note it may break if you have files selected across different projects. 

Edit: Also if there are any errors please open a new issue.

**Comment by slarcher** [comment]
Multiple hosts was never really an issue when using a package such as project-viewer. I used remote ftp + project viewer without any issues - every project has it's own ftp config file - all working in same window - no issues what so ever.
