### ISSUE TITLE
Does not properly handle errors

### ISSUE THREAD

**Issue by phawxby** [icetee/remote-ftp#47]
When a serious connection error occurs and triggers the close handler sftp2.js does not correctly handle it. The UI appears as still connected but becomes unresponsive.

```
self.ssh2.on('close', function () {
    self.disconnect();
    self.emit('closed');
});
self.ssh2.on('error', function (err) {
    self.emit('error', err);

    // err.code == "ECONNRESET"
});
```

**Steps to reproduce**
1. Connect to an sftp server
2. Disconnect from the internet (I just pulled out my network cable)
3. Refresh a folder and wait
4. The error handle will run
5. The close handler will run, however the UI appears as still connected which obviosuly does not work. From that point it becomes pretty much unresponsive.

**Comment by grenierdev** [comment]
Merged
