### ISSUE TITLE
OVH Personal 14 web server, cannot connect using Remote FTP

### ISSUE THREAD

**Issue by Wokkipannu** [icetee/remote-ftp#470]
I've created an empty folder and created the .ftconfig there with the right details. Connecting with the host, port, user and password on FileZilla connects and lists files just fine, but Remote FTP says "Remote FTP: Connected" but fails to list anything and just gives an error "Remote FTP: Error: read ECONNRESET".

I've tried changing the remote folder to different locations, but without success. The same error occurs.

**Comment by jimmaaay** [comment]
Do you know if the server tries to point FTP connections to certain directories?

**Comment by Wokkipannu** [comment]
I have no clue how the OVH FTP works, but this is what appears when I connect with FileZilla.

Status: Connection established, waiting for welcome message...
Status: Insecure server, it does not support FTP over TLS.
Status: Logged in
Status: Retrieving directory listing...
Status: Directory listing of "/" successful

So based on that, I have the remote set to "/".

**Comment by jimmaaay** [comment]
Perhaps try a different port number. Another thing you could try is in filezilla's settings under debug, tick show raw directory listing and change the debugging level to 4 and reconnect to the server. It may give some more information that could be useful.

**Comment by Wokkipannu** [comment]
In debug mode, here's what came out. It seems like the directory should be correctly set, as it is / and the port has to be 21, since this is not SFTP?

```
Status: Connection established, waiting for welcome message...
Trace:  CFtpControlSocket::OnReceive()
Response:   220-Bienvenue,
Response:   220-
Response:   220-    On Vous Héberge ?
Response:   220-
Response:   220-Vous êtes connecté sur.
Response:   220 This is a private system - No anonymous login
Trace:  CFtpControlSocket::SendNextCommand()
Command:    AUTH TLS
Trace:  CFtpControlSocket::OnReceive()
Response:   500 This security scheme is not implemented
Trace:  CFtpControlSocket::SendNextCommand()
Command:    AUTH SSL
Trace:  CFtpControlSocket::OnReceive()
Response:   500 This security scheme is not implemented
Status: Insecure server, it does not support FTP over TLS.
Trace:  CFtpControlSocket::SendNextCommand()
Command:    USER user
Trace:  CFtpControlSocket::OnReceive()
Response:   331 User user OK. Password required
Trace:  CFtpControlSocket::SendNextCommand()
Command:    PASS **********
Trace:  CFtpControlSocket::OnReceive()
Response:   230-User user has group access to:  users     
Response:   230 OK. Current restricted directory is /
```

**Comment by jimmaaay** [comment]
Yeah the default port number is 21 for FTP connections. Make sure that the protocol in the `.ftpconfig` file is also set to `ftp`.

**Comment by Wokkipannu** [comment]
"protocol": "ftp",
"port": 21,

These should be set correctly.

**Comment by BondaCB** [comment]
I'm having the same issue. 
I can't access the host via the package, and i'm trying with 21 port, ftp protocol, and listing none,, "/", "/www/", etc. Anything works.

With filezilla the site is listed properly, and sublime text ftp plugin works also correctly on the same computer and with the same configuration (protocol, port and path). 

I'm only having this issue with atom.

**Comment by lip2502** [comment]
Same problem. Actually Remote FTP doesn't list the remote ftp folder... But I still get a pop up message to indicate that the connection was successful with the remote server :(

A fix or little help would be much appreciated 😄 

This extensions is awesome, I so badly wanna use it !

**Comment by dquartino** [comment]
Up ! 

Same problem here. I love your plugin, but i cant use it with my OVH servers.

Please do something :D

**Comment by jpxd** [comment]
If the problem persists with the latest update please reopen

**Comment by dquartino** [comment]
The problem is still not resolved for me.

The only workaround for the moment is this fix :
go to .atom\packages\Remote-FTP\node_modules\ftp\lib\connection.js
on line 106 change socket.setKeepAlive(true); -> socket.setKeepAlive(false);

From @shahafan #585
