### ISSUE TITLE
Feature Request: Upload Current File

### ISSUE THREAD

**Issue by dylan-k** [icetee/remote-ftp#471]
The sftp-deployment package has one feature that would be better to have in the more robust remote-ftp package. That feature is the ability to "uploadCurrentFile" without having to locate it in the sidebar. Would it be possible to implement something like that?

**Comment by jimmaaay** [comment]
If you open the command palette, ctrl + shift + p or cmd + shift + p on mac and search for upload selected it will do what you're looking for.
