### ISSUE TITLE
Multiple Selection of Files and Folder in Remote Tree

### ISSUE THREAD

**Issue by andreknieriem** [icetee/remote-ftp#473]
Hey there.

for deleting some files, I often use multi-selection of Files and folder in the remote tree in Aptana Studio. In your great extension, you can only select one file/folder. Maybe a mulit-selection is possible!

Thanks!

**Comment by jimmaaay** [comment]
Are you on mac? If so there should be a fix for selecting multiple files in the dev branch. No shift support unfortunately though.

**Comment by andreknieriem** [comment]
Alright, this works, Shift Support would be great too :)

**Comment by jimmaaay** [comment]
Should be sorted in 0.9.0. Will create a new issue regarding shift support.
