### ISSUE TITLE
Remote FTP tree IIS server: folders ok, files undefined 

### ISSUE THREAD

**Issue by Carlos-Freire** [icetee/remote-ftp#474]
Hi everybody:

I’m new Atom user and my problem is: the remote-ftp package list as undefined all files on Windows IIS server(*).
But the folders - where the files are - appear ok.
When I try download some file: <550 /www/undefined: No such file or directory.
No problems with the .ftpconfig and the all local files (asp).

In picture below, left side is local tree, right side is remote tree.

![local_remote_tree](https://cloud.githubusercontent.com/assets/21251764/18714155/3e902806-7feb-11e6-97ee-7fe27d742a04.jpg)

(*) Only IIS server... ok on Linux server.
Thanks a lot for any help (and sorry about my english).

Just in time: I tried with atom-commander... also not work.
In fact it got worse ... the atom-commander even view any files, only folders.:o(]

![commander_view](https://cloud.githubusercontent.com/assets/21251764/18714286/a75b58a6-7feb-11e6-8341-1095cd10425b.jpg)

I even suspect that the cause is some security setting on the server... it's possible?

Carlos

**Comment by Carlos-Freire** [comment]
My suspicions proved correct ... the server support (www.infolink.com.br) said:

"Our Windows hosting servers have a security system on the FTP layer, where the communication firstly goes through a Linux server, which filters the connections, allowing only the FTP commands genre. Some applications try to commands that are not supported, and then present failures.”
"Even I - when try to access some of our servers - it's also limited to using the FTP client to correct pages / code because a vast majority of applications display error when trying to list the remote directory or even edit the files.”
[Google Translation].

Conclusion? Nothing to do, I think ... !:o(]

**Comment by jimmaaay** [comment]
This sounds like more of an issue for the npm package ftp[https://www.npmjs.com/package/ftp](https://www.npmjs.com/package/ftp) which remote ftp uses for FTP connections. However I will have a look to see what can be done.
