### ISSUE TITLE
Feature Request: Multiple Host settings

### ISSUE THREAD

**Issue by slarcher** [icetee/remote-ftp#477]
One thing missing - and I claim as rather useful - is multiple host support. Currently, each project can handle only one FTP connection (host). It would be nice to have the ability to add multiple hosts per project. Ideally, there should be a "label" setting to name each setting accordingly ("remote server", "dev server"). Then, instead of having a single "Connect" button there could be multiple with the label name eg. "Connect to {remote server} / Connect to {dev server}".

**Comment by hatzopoulos** [comment]
See duplicates #122 and #212 and PR #464
