### ISSUE TITLE
EMPTY FOLDER

### ISSUE THREAD

**Issue by martinsbicudo** [icetee/remote-ftp#478]
The FTP folder appears empty , could help me ?

**Comment by jimmaaay** [comment]
@martinsbicudo Firstly do you get a message saying `Remote FTP: Connected`? Secondly does the server you're connecting to show up as empty in other FTP programs e.g FileZilla?

**Comment by EvanHerman** [comment]
@jimmaaay I too am  having the same problem. Other programs do not see the directories as empty. Using the same configuration between programs.

**Comment by jimmaaay** [comment]
Are you defining a remote directory other than  `/` in the config file?

**Comment by EvanHerman** [comment]
No, I am not. I've tried both with and without a remote directory. Each leads to an empty directory.

**Comment by jimmaaay** [comment]
@EvanHerman What protocol are you using?
