### ISSUE TITLE
pageant setup

### ISSUE THREAD

**Issue by rares-lupascu** [icetee/remote-ftp#484]
hey

if i want to login using the already loaded pk in pageant wouldn't this config work?

```
{
    "protocol": "sftp",
    "host": "1.1.1.1",
    "port": 22,
    "user": "root",
    "pass": "",
    "promptForPass": false,
    "remote": "/",
    "agent": "pageant",
    "privatekey": "",
    "passphrase": "",
    "hosthash": "",
    "ignorehost": true,
    "connTimeout": 10000,
    "keepalive": 10000,
    "keyboardInteractive": false,
    "watch": [],
    "watchTimeout": 500
}
```

**Comment by jimmaaay** [comment]
To be honest I have no idea I haven't used pageant, you'd have to try it. I'd be glad to hear how you get on with it, if you do so.

**Comment by rares-lupascu** [comment]
u need to put in the putty key path and passphrase which for me seems redundant since i already put it into pageant ... if i need to put it again why bother setting pageant as agent?

**Comment by jimmaaay** [comment]
@wowzaaa I've had a quick read through and it looks as though programs that work with pageant, from what I can see putty and filezilla, have to be specifically setup to use the keys from pageant, which Remote FTP is not setup to do.

**Comment by rares-lupascu** [comment]
> "agent": "", // string - Path to ssh-agent's UNIX socket for ssh-agent-based user authentication. Windows users: set to 'pageant' for authenticating with Pageant or (actual) path to a cygwin "UNIX socket." Default: (none)

in this case ... for me ... a windows and a pageant user ... how is the agent option useful?

**Comment by jimmaaay** [comment]
Didn't know that it was in the readme. Frankly I don't know. I'd have to do some research on Pageant first before I can be of much help.

Edit: Grammar

**Comment by rares-lupascu** [comment]
no worries @jimmaaay ... i thought it was a cool feature that i would love to use ... i already do with filezilla and putty

**Comment by hatzopoulos** [comment]
@wowzaaa 
Using pageant works perfectly for me. My key is loaded in `Pageant` and my remote-ftp config is as follows, with no password.

``` json
{
    "protocol": "sftp",
    "host": "example.com",
    "port": 22,
    "user": "hatzopoulos",
    "pass": "",
    "remote": "/var/www/vhosts/example.com",
    "agent": "pageant",
    "privatekey": "",
    "passphrase": "",
    "hosthash": "",
    "ignorehost": true,
    "connTimeout": 10000,
    "keepalive": 10000
}
```

**Comment by rares-lupascu** [comment]
this is the first type of config i tried .. u can acutally see it in the first post ... and i was told something like : "every login option failed"

**Comment by rares-lupascu** [comment]
so i have to systems ... the one in the office uses RAM Disk while the laptop doesn't ... that means that on the office computer Pageant is installed on a mounted drive while on the latop it is in C:
i do not know if this has any influence

**Comment by hatzopoulos** [comment]
> i do not know if this has any influence

As long as pagent is installed and your key is loaded on each of the computers you're running atom on - you should be fine. 

Perhaps your key has a passphrase, as apposed to a passwordless key, in which case you will be prompted by Pageant for that password when loaded but then subsequent usage should be passwordless. Or perhaps it's your server setup. It's hard to tell from here.

**Comment by rares-lupascu** [comment]
well it is the same key ... but at home i have a laptop with a standard setup ... everythin installed in C:progrma files
at the office i have a work station with 64Gb out of which 32gb i use with ram disk ... so pageant is installed on that virtual drive 

but the both use the same key ... with a passphrase ... at home it works ... at the office i need to specify the key and passphrase

**Comment by jimmaaay** [comment]
@wowzaaa Could you try having pageant installed on the physical drive instead of the RAM disk? Or if you haven't got so already try it with Atom to the RAM disk.
