### ISSUE TITLE
How to add multiple ftp servers

### ISSUE THREAD

**Issue by Nik99** [icetee/remote-ftp#493]
How to add multiple ftp servers in .ftpconfig ? I didn't found anything in the documentation.

**Comment by jimmaaay** [comment]
If you enable multiple hosts in the settings of the package you can have multiple projects in the same window, which each have their own .ftpconfig file

**Comment by Nik99** [comment]
Oh, i was thinking that the client could upload the same project on multiple servers by adding them in the config.
Would be nice to see

**Comment by jimmaaay** [comment]
That's currently not a feature of the plugin

**Comment by Nik99** [comment]
Why do not add it ? :+1:

**Comment by jimmaaay** [comment]
It would probably be alot of work to make sure there are no conflicts. You'd also run into the issue of which remote tree you would display to the user. Or would you have 2 trees at that point? 

But currently there are more pressing amends to make to the package

**Comment by Nik99** [comment]
Of course i'm not saying that it's needed right now bot of course, it will be very cool to have.
For the three problem, you could just tab the panel like "Host 1" and "Host 2". (I know it's not only "just", it's a lot of work, i'm a dev too.) 
Most of the devs have two different servers, (backup/dev and production common) so it would be cool to have a double upload on file save without having to sync all the files between both.

**Comment by slarcher** [comment]
Nik99,
you can achieve this by commenting out different settings.
For example:

{
/\*  ------------------
    REMOTE ON
    ------------------
*/
    "protocol": "ftp",
    "host": "",
    "port": 21,
    "user": "",
    "pass": "",
    "promptForPass": false,
    "remote": "/",
    "secure": false,
    "secureOptions": null,
    "connTimeout": 10000,
    "pasvTimeout": 10000,
    "keepalive": 10000,
    "watch": [""],
    "watchTimeout": 500

/\*  ------------------
    DEV OFF

```
"protocol": "ftp",
"host": "",
"port": 21,
"user": "",
"pass": "",
"promptForPass": false,
"remote": "/",
"secure": false,
"secureOptions": null,
"connTimeout": 10000,
"pasvTimeout": 10000,
"keepalive": 10000,
"watch": [""],
"watchTimeout": 500
------------------
```

*/

}

I do agree with Nik99 that a multiple host connection solution would be a big milestone.
Something for the 'remote' future probably.

**Comment by jpxd** [comment]
Duplicate to #122
