### ISSUE TITLE
How can we disable "watch"?

### ISSUE THREAD

**Issue by tekvsakdan** [icetee/remote-ftp#499]
How can we disable "watch"? This is in my .ftpconfig

> ```
> "watch": [],
> "watchTimeout": 500
> ```

The reason why I wanted to do that is because remote-ftp overwrite automatically some remote files with local files and copy files I don't want.

Now I'm clearing local folder to prevent this from happening again.

**Comment by frankIT** [comment]
I got the same problem. I tough that empty the list with an empty array [] would disable the sync option. But unfortunately after edit a local file, it uploaded of all the modified files. Fortunately I had a backup, but I think this behaviour should be better documented since seems to be quite risky!

**Comment by tekvsakdan** [comment]
I guess the current workaround is to put non existing folder to "watch" settings

> ```
> "watch": ["./non-existing-folder/"]
> ```

But I would prefer an option to completely disable syncing by default.

**Comment by jimmaaay** [comment]
If you're saving files in the editor, by default remote ftp will upload them. You can change the behaviour of this in the packages settings under Auto Upload On Save. 

The watch config will watch files / folders for changes and upload them automatically without having to save files in the editor.

**Comment by jimmaaay** [comment]
But this is something that probably should be more clearly explained in the readme. I will update it at some point

**Comment by tekvsakdan** [comment]
I understand what "watch" means, but as @frankIT wrote, empty array [] should not do anything. Now it uploads entire local folder to remote site and overwrite remote files without any notice.

**Comment by jimmaaay** [comment]
@zajc So when you're connected to the server in atom and edit any of the files they get uploaded? If so can you try editing the files in a different client and see if the files have been uploaded. If they haven't been uploaded then it would be something else instead of the 'watch' option in the config.

**Comment by tekvsakdan** [comment]
The scenario was like that:
- day 1: I worked with file XYZ on location B and when I saved the file was uploaded to location A (remote site) as expected
- day 2,3: I work on a location A with file XYZ
- day 4: I connected with remote ftp to location A and than I open the file from remote site (location A) as I'm always doing, and then shock, the file was the same as on day 1

Than I figure it out remote-ftp overwrite remote files with files from day 1 from location B and also copied files I don't want on the remote site. It happened after the last remote-ftp (7-14 days ago) update  0.9.0.

Now I'm deleting files from location B before connecting with remote-ftp just in case to prevent this from happening again.

The problem is this setting which enables "watch" by default.

> "watch": []

**Comment by jimmaaay** [comment]
Did you download the file from the remote on day 4 in your case?

**Comment by tekvsakdan** [comment]
I double clicked on a file on a remote site tree and the file(s) was(were) already changed (overwritten).

**Comment by jimmaaay** [comment]
I'll have a look to see if this is watch causing the issue, but I doubt it is as when there is nothing in the array then it doesn't enable the watch functionality.

**Comment by rusanter** [comment]
I think any tool that uploads a file to remote side should make a comparison with a known snapshot of remote before overwriting. And then a user should decide what to do: overwrite, merge or download remote copy. This is a point where a tool can loose its speed significantly.
But it is a basic protection and must have.

**Comment by jimmaaay** [comment]
@ru-santer I believe that is a proposed enhancement. It would be useful if there was an option to do that.

**Comment by jpxd** [comment]
"File comparison before upload" has been suggested in a bunch of other issues. Closing this one.
