### ISSUE TITLE
Files seen as folders in Atom 1.12.0 (beta 0 and beta 1)

### ISSUE THREAD

**Issue by DeanmvSG** [icetee/remote-ftp#501]
I can't open any files remotely on the latest Atom betas as all of the files (and folders) are seen as folders and so they just "expend".

For example in this screenshot the `.json` and the `.htm` file aren't openable as Remote-FTP thinks they are folders.  

Same version of plugin (0.9.0) works fine in Atom 1.11.0 (and 1.11.1).

Screenshot of error:
<img width="165" alt="screen shot 2016-10-12 at 21 49 46" src="https://cloud.githubusercontent.com/assets/15265711/19327247/eb0f0580-90c5-11e6-8a73-8b188d4cac54.png">

Same files locally obviously work as normal files:
<img width="177" alt="screen shot 2016-10-12 at 21 51 20" src="https://cloud.githubusercontent.com/assets/15265711/19327277/076773d4-90c6-11e6-8382-5dbe8bbab69b.png">

**Comment by jimmaaay** [comment]
Will have a look. Thanks for pointing this out

**Comment by DeanmvSG** [comment]
@jimmaaay Cool 👍  If you need me to test anything if you can't reproduce then let me know.

**Comment by gdevdeiv** [comment]
Same is happening to me, files are showing up as empty folders.. weird. My actual version of Atom is 1.11.2.

**Comment by DeanmvSG** [comment]
@gdevdeiv Mine has worked perfectly in the non beta (1.11.x) version of Atom.  It was only the move to 1.12.x that seemed to break the plugin.  Maybe it is a setting then?

**Comment by jimmaaay** [comment]
Should be fixed in 0.9.1, if you were using SFTP. If anyone is having the same issue when using FTP please create a new issue.

**Comment by DeanmvSG** [comment]
@jimmaaay Seems to be working great, thanks!

**Comment by zodit** [comment]
This bug is not fixed in Atom 1.19.0 and Remote-Ftp 1.1.4. Some servers are working fine, others don't.
All files are downloaded as empty folders.

**Comment by DeanmvSG** [comment]
@zodit This was quite an old issue but it has cropped up again recently.  You're probably better off looking at #925 which is a more up to date version of the "same" bug
