### ISSUE TITLE
Download is creating a new parent folder combining the project folder and the downloaded folder

### ISSUE THREAD

**Issue by dethell** [icetee/remote-ftp#503]
First time using remote-ftp. I'm using multiple hosts mode and when I download a file or a folder, instead of putting the file in the matching project folder it creates a new folder above the project folder level that is a combination the current project + the downloaded folder name.

E.g.: project folder is "myproject" and I'm downloading "webroot/index.php". remote-ftp creates a folder named "myproject\webroot" in the parent folder of my project folder with the desired file instead.

So I have to go and move the downloaded files to their correct place delete all these added folders.

**Comment by jimmaaay** [comment]
Hi there, I've fixed the issue in a slightly different way. Which will be released in 0.9.3

**Comment by jimmaaay** [comment]
fix in 0.9.3 which is released now
