### ISSUE TITLE
Folders withput content

### ISSUE THREAD

**Issue by NachoLambardi** [icetee/remote-ftp#505]
Config Ftp file load the folders but without content. I'm using Atom editor.

**Comment by jimmaaay** [comment]
So are you saying that no files show in the folders?

**Comment by NachoLambardi** [comment]
Hi, thanks for replying. Yes, the folders are empty.

El lunes, 17 de octubre de 2016, jimmaaay notifications@github.com
escribió:

> So are you saying that no files show in the folders?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
> https://ci6.googleusercontent.com/proxy/tmfDrEnjtpIaLqXqe1hR2tS_hleDkE1s1r0t0FZ57jLNRMDe9JepVbAwnn0C8nJJqoi9w-9GGLFNqyDWeI9nvpaV1U71KziVELcxLu68OaxcDo0HqIeX9wQzz77QZwqNBQcjYNaWYXqeLY3__Dw8RMFnpuM3mg=s0-d-e1-ft#https://github.com/notifications/beacon/ARVUDiMBR9f0yMGQ5a0sXmbWwtRFPQfrks5q06v0gaJpZM4KXyuV.gif

## 

Nacho Lambardi

**Comment by jimmaaay** [comment]
What protocol were you using to connect to the server? If it was sftp can you try updating the plugin to 0.9.1

**Comment by NachoLambardi** [comment]
I'll try updating. I wanna thanks for taking your time for replying.
I'll search it and tell you how was it. :)

Nacho Lambardi

2016-10-28 9:45 GMT-03:00 jimmaaay notifications@github.com:

**Comment by NachoLambardi** [comment]
Hi Jim,
It's working, i updated the latest version 0.9.4. Thanks for replying and
for your time.
I'm a developer from Argentina, nowadays working in two bigs projects with
PHP and MYSQL. What about you?
Nice to meet you, :)
Have a great day
Nacho

Nacho Lambardi

2016-10-28 10:03 GMT-03:00 Juan Ignacio Lambardi ignaciolambardi@gmail.com
:

**Comment by jimmaaay** [comment]
@NachoLambardi No problem. That's cool :) and work mainly on front end projects in the UK.
