### ISSUE TITLE
.ftpconfig needs improved error handling or documentation for "privatekey"

### ISSUE THREAD

**Issue by brentpayton** [icetee/remote-ftp#509]
Windows 10
Package version 0.9.0
Attempting to connect via sftp using an openssh private key
Used example .ftpconfig file at https://atom.io/packages/Remote-FTP as a reference

********************Problem 1

If the path to the private key is entered in standard Windows format with \, an error is generated when connecting.

Workaround:  use / instead of \

Could not process .ftpconfig
SyntaxError: Unexpected token s
Close All
Could not parse .ftpconfig
Expected four digits after '\u'.
    "privatekey": "C:\users[username][. . . ][open ssh key filename]"

********************Problem 2

If the openssh private key filename contains spaces, they are converted automatically to underscores and an error is displayed when connecting.

Workaround:  rename private key file so it has underscores instead of spaces (likely that just removing spaces will work as well.)

fs.js:584 Uncaught Error: ENOENT: no such file or directory, open 'C:\users[username][. . . ][open ssh key filename shown with underscores when file uses spaces]'fs.openSync @ fs.js:584module.(anonymous function) @ ELECTRON_ASAR.js:158fs.readFileSync @ fs.js:431fs.readFileSync @ ELECTRON_ASAR.js:426module.exports.Client.doConnect @ C:\Users[username].atom\packages\Remote-FTP\lib\client.js:262(anonymous function) @ C:\Users[username].atom\packages\Remote-FTP\lib\client.js:719jQuery.event.dispatch @ C:\Users[username].atom\packages\Remote-FTP\node_modules\jquery\dist\jquery.js:4435elemData.handle @ C:\Users[username].atom\packages\Remote-FTP\node_modules\jquery\dist\jquery.js:4121jQuery.event.trigger @ C:\Users[username].atom\packages\Remote-FTP\node_modules\jquery\dist\jquery.js:4350(anonymous function) @ C:\Users[username].atom\packages\Remote-FTP\node_modules\jquery\dist\jquery.js:4901jQuery.extend.each @ C:\Users[username].atom\packages\Remote-FTP\node_modules\jquery\dist\jquery.js:374jQuery.fn.jQuery.each @ C:\Users[username].atom\packages\Remote-FTP\node_modules\jquery\dist\jquery.js:139jQuery.fn.extend.trigger @ C:\Users[username].atom\packages\Remote-FTP\node_modules\jquery\dist\jquery.js:4900$.fn.trigger @ C:\Users[username].atom\packages\Remote-FTP\node_modules\space-pen\lib\space-pen.js:606module.exports.PromptPassDialog.onConfirm @ C:\Users[username].atom\packages\Remote-FTP\lib\dialogs\prompt-pass-dialog.js:50PromptPassDialog.atom.commands.add.core:confirm @ C:\Users[username].atom\packages\Remote-FTP\lib\dialogs\prompt-pass-dialog.js:44module.exports.CommandRegistry.handleCommandEvent @ command-registry.coffee:256(anonymous function) @ command-registry.coffee:1module.exports.KeymapManager.dispatchCommandEvent @ C:\Users[username]\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\atom-keymap\lib\keymap…:580module.exports.KeymapManager.handleKeyboardEvent @ C:\Users[username]\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\atom-keymap\lib\keymap…:388module.exports.WindowEventHandler.handleDocumentKeyEvent @ window-event-handler.coffee:81(anonymous function) @ window-event-handler.coffee:1
C:\Users[username]\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\jquery\dist\jquery.js:8630 POST https://is.gd/create.php?format=simple 400 ()send @ C:\Users[username]\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\jquery\dist\jquery.js:8630jQuery.extend.ajax @ C:\Users[username]\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\jquery\dist\jquery.js:8166(anonymous function) @ notification-issue.coffee:43_tickCallback @ internal/process/next_tick.js:103
C:\Users[username]\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\jquery\dist\jquery.js:3256 Uncaught (in promise) Object {readyState: 4, responseText: "Error: Please enter a valid URL to shorten", status: 400, statusText: "error"}

********************Problem 3
Example .ftpconfig at https://atom.io/packages/Remote-FTP does not explain "ignorehost"
    "ignorehost": true,

**Comment by jpxd** [comment]
We definitely need a better documentation...
Syntax errors in the .ftpconfig are handled better by now.
I'd be happy if you could help with the documentation and submitted a PR :)
Linking to #7
