### ISSUE TITLE
sftp with agent on linux

### ISSUE THREAD

**Issue by gevatter** [icetee/remote-ftp#51]
I run atom 0.184 with remote-ftp from the repo.

I startet the ssh-agent by running "ssh-add" and entering my passphrase.

Now I want to connect to a server. I created a sftp-config, changed host and user and removed the password.

For agent i tried the path $SSH_AUTH_SOCK returns, like /tmp/ssh-xxxxxxxxxxxx/agent.dddd. I tried leaving this field empty also.

But nothing happens when I hit connect. No error, but no connection either. Am I missing something?

**Comment by phawxby** [comment]
There's a bug in the currently published version, in the meantime try these instructions:
https://github.com/mgrenier/remote-ftp/issues/49#issuecomment-75949581

@mgrenier please can you publish an updated package?

**Comment by gevatter** [comment]
I already use a clone from the repo and checked if it is up to date before opening this issue. Connecting with username and password is also working fine. 

But not if i try it with the agent. There isn't any error message at all, just no connection.

I am not even sure, if it is a bug or if I am to stupid to find out to what value i have to set the setting "agent" to.

**Comment by gevatter** [comment]
Nevermind, tried it again today and it worked by entering the path to the socket.

Sorry for the noise.
