### ISSUE TITLE
TIMEOUT error on every first connect

### ISSUE THREAD

**Issue by EchoSixteen** [icetee/remote-ftp#511]
Every time I connect to my SFTP server for the first after booting my laptop, after about 5 seconds a TIMEOUT error occurrs - without fail. After reconnecting it works fine for the rest of the day.

OSX 10.11.6
Atom and Remote-FTP up-to-date.

Let me know if there is any other information you need.

**Comment by jimmaaay** [comment]
@EchoSixteen Could you try updating to 0.9.2 and let me know if you're problem persists?

**Comment by EchoSixteen** [comment]
Hey jimmaaay! (Nice name :P)

Bad news - I've updated to 0.9.2 and the issue persists...

**Comment by EchoSixteen** [comment]
Hello again,

This morning the connection didn't drop, even though nothing has changed from yesterday when I posted. 

Let me know if there's any more information you need.

**Comment by jimmaaay** [comment]
Okay, I'll probably implement some sort of auto reconnect on a timeout error with sftp. As I have no idea what would be causing this.

**Comment by EchoSixteen** [comment]
@jimmaaay - I discovered a caveat to this issue.

If I use the panel button to connect to my SFTP server, the timeout does not occur. Only if I use the keyboard shortcut does it disconnect.

Specifically, I am referring to the buttons that appear in the FTP panel, where the file tree appears once connected.

Hope that helps.

**Comment by jpxd** [comment]
Okay, please test the latest update (which will be released in the next hours) if this still an issue for you and reopen if the problem persists. The sftp keepalive should be working again.
