### ISSUE TITLE
Upload to remove server when saved and compiled

### ISSUE THREAD

**Issue by querysol** [icetee/remote-ftp#514]
Hello,
thank you for you package!

How can I save, compile and automatically upload style.css to remove server?

I have style.scss file, after saving it I need to upload style.css to server. Does it possible?

Thanks!

**Comment by DeanmvSG** [comment]
You can use the "Watch" feature in your `.ftpconfig` file.  The readme has a pretty good example of them:

```
"watch":[ // array - Paths to files, directories, or glob patterns that are watched and when edited outside of the atom editor are uploaded. Default : []
        "./dist/stylesheets/main.css", // reference from the root of the project.
        "./dist/stylesheets/",
        "./dist/stylesheets/*.css"
    ],
```
