### ISSUE TITLE
File that are in the parent directory of .ftpconfig are uploaded

### ISSUE THREAD

**Issue by lemarcantoine** [icetee/remote-ftp#515]
I have 2 folders in my project one called "ftp" which contains the .ftpconfig and an other one which is the parent of the "ftp" folder. When I change a file into the parent folder it gets uploaded and it didn't do it in ancient releases.

http://puu.sh/rW6oD/8c1e086b4d.png

**Comment by tekvsakdan** [comment]
Check this issue #499

**Comment by jpxd** [comment]
I thing the two folders are the problem...
Try to use only one folder in your project until multi folder is completly supported.
