### ISSUE TITLE
Can not connect with sftp, Windows 10 pro

### ISSUE THREAD

**Issue by probablyVincentIp** [icetee/remote-ftp#517]
- Windows 10 Professional
- Remote-FTP 0.9.0
- atom 1.11.2

```
{
    "protocol": "sftp",
    "host": "myhost.example.com",
    "port": 18765,
    "user": "myuser",
    "pass": "mypass",
    "promptForPass": false,
    "remote": "/",
    "agent": "",
    "privatekey": "C:\Users\username\Documents\development\websites\ssh_key",
    "passphrase": "33SuPerStrongPass",
    "hosthash": "",
    "ignorehost": true,
    "connTimeout": 10000,
    "keepalive": 10000,
    "keyboardInteractive": false,
    "watch": [],
    "watchTimeout": 500
}
```

The port number is provided by my host when I try to connect I get following error: 
`Could not process .ftpconfig` `Syntaxerror unexpected token U`

Any ideas?

**Comment by jimmaaay** [comment]
You will need to escape your privateKey path. The file gets treated as JSON so the below should do the trick.

`"privatekey": "C:\\Users\\username\\Documents\\development\\websites\\ssh_key"`
