### ISSUE TITLE
"No transfer time exceeded"

### ISSUE THREAD

**Issue by martinmahs** [icetee/remote-ftp#526]
"No transfer time exceeded" has startet appearing, making me have to disconnect and reconnect all the time

**Comment by jimmaaay** [comment]
Can you paste your .ftpconfig below. Removing any sensitive information

**Comment by martinmahs** [comment]
Hi Jimmaaay,

Thanks for quick reply, and excellent plugin – really the reason that enables us to use Atom, so great work! :)

Here’s an example of one of my connections, but I’ve noticed it on all my connections (I have about 15 projects) since updating to latest 0.9.2 a few days ago.
It just gives the 421 error a lot, and I have to disconnect and then reconnect (Any chance to get buttons for this that are not way up in the file-menu? – perhaps a thin bar over the status-bar ;) )

Anyway, here’s one of my connections:
{
    "protocol": "ftp",
    "host": "*****_",
    "port": 21,
    "user": “**_**_",
    "pass": "**_***",
    "promptForPass": false,
    "remote": "/",
    "secure": false,
    "secureOptions": null,
    "connTimeout": 10000,
    "pasvTimeout": 10000,
    "keepalive": 10000,
    "watch": []
}

Thanks so much for taking the time!
Love the plugin otherwise :)

**Comment by jimmaaay** [comment]
Not sure there's a whole lot that can be done regarding the 421 error as I believe that is pushed out by the server itself. Maybe try changing the settings on the server to allow for a higher time without transfers?

However I should be able to add in some sort of automatic reconnect on a 421 error.

**Comment by martinmahs** [comment]
Hi again, 

Thanks for looking into it.
A reconnect / auto-reconnect would be super useful, as it's quite a hassle to go to menu>packages>remote-ftp>disconnect every time - and it completely looses all functionality once it get the 421 error.

The weird thing is, that i control most of the servers i connect to, so it running FileZilla on all of them, and it has not been a problem before i updated. 

I even have my laptop (Which is running 0.9.1 of remote-ftp connect to the same server and it does not experience the 421 at all. 
On my desktop running 0.9.2 it happens after approx 5 mins of inactivity even though i can see it's sending the keepalives... very strange...

**Comment by jimmaaay** [comment]
Could you open up the developer console and see if there is anything unusual popping up in there, as ftp details get logged there

**Comment by martinmahs** [comment]
Sure, here's the latest :)
< 220-FileZilla Server version 0.9.41 beta\r\n220-written by Tim Kosse (Tim.Kosse@gmx.de)\r\n220 Please visit http://sourceforge.net/projects/filezilla/
client.js:278 < 331 Password required for ******
client.js:278 < 230 Logged on
client.js:278 < 211-Features:\r\n MDTM\r\n REST STREAM
client.js:278 <  SIZE\r\n MLST type_;size_;modify_;\r\n MLSD\r\n UTF8\r\n CLNT\r\n MFMT\r\n211 End
client.js:278 < 200 Type set to I
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,158)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
36client.js:278 < 200 OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,159)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
3client.js:278 < 200 OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,160)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
3client.js:278 < 200 OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,161)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
4client.js:278 < 200 OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,162)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
8client.js:278 < 200 OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,163)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
client.js:278 < 200 OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,164)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
2client.js:278 < 200 OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,165)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
4client.js:278 < 200 OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,166)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
5client.js:278 < 200 OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,167)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,168)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
2client.js:278 < 200 OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,169)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
2client.js:278 < 200 OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,170)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
client.js:278 < 200 OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,171)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
3client.js:278 < 200 OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,172)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
client.js:278 < 200 OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,173)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
client.js:278 < 200 OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,174)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,175)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
client.js:278 < 200 OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,176)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,177)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
3client.js:278 < 200 OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,178)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
15client.js:278 < 200 OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,179)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
client.js:278 < 200 OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,180)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
client.js:278 < 200 OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,80)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
3client.js:278 < 200 OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,81)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
2client.js:278 < 200 OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,82)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
client.js:278 < 200 OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,83)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,84)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,85)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
3client.js:278 < 200 OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,86)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
client.js:278 < 200 OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,87)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
3client.js:278 < 200 OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,88)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
7client.js:278 < 200 OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,89)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,90)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
4client.js:278 < 200 OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,91)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,92)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
client.js:278 < 200 OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,93)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
3client.js:278 < 200 OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,94)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
2client.js:278 < 200 OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,95)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
2client.js:278 < 200 OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,96)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
2client.js:278 < 200 OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,97)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,98)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
4client.js:278 < 200 OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,99)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
2client.js:278 < 200 OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,100)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
5client.js:278 < 200 OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,101)
client.js:278 < 150 Connection accepted\r\n226 Transfer OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,102)
client.js:278 < 150 Connection accepted\r\n226 Transfer OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,103)
client.js:278 < 150 Connection accepted\r\n226 Transfer OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,104)
client.js:278 < 150 Connection accepted\r\n226 Transfer OK
client.js:278 < 550 CWD failed. "/_********_.**_/**_/**_***_.**_": directory not found.
client.js:278 < 250 CWD successful. "/" is current directory.
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,105)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
client.js:278 < 200 MODE set to S.
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,106)
client.js:278 < 150 Connection accepted\r\n226 Transfer OK
client.js:278 < 550 CWD failed. "/*********_.**_/**_/**_***_/**_***_.**_": directory not found.
client.js:278 < 250 CWD successful. "/" is current directory.
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,107)
client.js:278 < 150 Connection accepted\r\n226 Transfer OK
client.js:278 < 200 MODE set to S.
6client.js:278 < 200 OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,108)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
2client.js:278 < 200 OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,109)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
client.js:278 < 200 OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,110)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
2client.js:278 < 200 OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,111)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
client.js:278 < 200 OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,112)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
2client.js:278 < 200 OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,113)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
3client.js:278 < 200 OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,114)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
119client.js:278 < 200 OK
client.js:278 < 421 No-transfer-time exceeded. Closing control connection.
client.js:278 < 220-FileZilla Server version 0.9.41 beta\r\n220-written by Tim Kosse (Tim.Kosse@gmx.de)\r\n220 Please visit http://sourceforge.net/projects/filezilla/
client.js:278 < 331 Password required for ******
client.js:278 < 230 Logged on
client.js:278 < 211-Features:\r\n MDTM\r\n REST STREAM\r\n SIZE\r\n MLST type_;size_;modify_;\r\n MLSD
client.js:278 <  UTF8\r\n CLNT
client.js:278 <  MFMT\r\n211 End
client.js:278 < 200 Type set to I
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,115)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
client.js:278 < 550 CWD failed. "/_********_.**_/**_/**_***_/**_***_.**_": directory not found.
client.js:278 < 250 CWD successful. "/" is current directory.
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,116)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
client.js:278 < 200 MODE set to S.
client.js:278 < 550 CWD failed. "/*********_.**_/**_/**_***_/**_***_.**_": directory not found.
client.js:278 < 250 CWD successful. "/" is current directory.
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,117)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
client.js:278 < 200 MODE set to S.
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,118)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,119)
client.js:278 < 150 Connection accepted\r\n226 Transfer OK
7client.js:278 < 200 OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,120)
client.js:278 < 150 Connection accepted\r\n226 Transfer OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,121)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,122)
client.js:278 < 150 Connection accepted\r\n226 Transfer OK
client.js:278 < 550 CWD failed. "/*********_.**_/**_/**__/std.css": directory not found.
client.js:278 < 250 CWD successful. "/" is current directory.
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,123)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
client.js:278 < 200 MODE set to S.
7client.js:278 < 200 OK
client.js:278 < 550 CWD failed. "/_********_.**_/**_/**__/_*****_.css": directory not found.
client.js:278 < 250 CWD successful. "/" is current directory.
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,124)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
client.js:278 < 200 MODE set to S.
6client.js:278 < 200 OK
client.js:278 < 227 Entering Passive Mode (_,_,_,_,195,125)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
client.js:278 < 227 Entering Passive Mode (_,_,_,*,195,126)
client.js:278 < 150 Connection accepted
client.js:278 < 226 Transfer OK
119client.js:278 < 200 OK

It of course did it again - so it's very reproducable.
Laptop i still connected. Have never seen the 421 before on 0.9.1 or ealier.

**Comment by martinmahs** [comment]
Btw: is there any way to install v.0.9.1 again? 
It's really buggin me this evening with two different projects open and they both keep timing out so that when om working on project 1, and tabbing over to project 2 it's timed out with error 421, and viceversa :)

**Comment by martinmahs** [comment]
Yeah sorry to be a bother... :( Just googled it and managed to download 0.9.1 from here - overwrite in the package and recopy the node-modules folder. Working with 0.9.1 again and it seems to work fine.

Let me know if you need anymore info in regards to this issue - i'll help any way i can.

**Comment by martinmahs** [comment]
Not sure if it helpt, but found out that in earlier versions i.e 0.9.1 - it actually gets the 421 error after a while (So I think you're right that it's normal behavior for FileZilla etc.) but i never noticed becuase it just reconnects automatically whenever i save something or navigates the treeview (in 0.9.1 and below). This is not the behavior in 0.9.2 where it just stays disconnected and I have to manually disconnect and reconnect. Maybe this helps in tracking it down?

Again, sorry to bother you so much - let me know if I should just shut up and let you work ;)

**Comment by BondaCB** [comment]
I'm having this issue as well.
Before updating, if the server was on 421 the plugin re-connected to the server and uploaded the file.
Now, the file is not uploaded, and is put in some kind of upload queue. When you disconnect and re-connect again, all queued files get uploaded at once.

Also @martinmahs , I usally keep the FTP sidebar open, and there you can disconnect and reconnect just using the right click instead of navigating via the packages menu to do so.

**Comment by Blarx** [comment]
[error](http://joxi.ru/V2VgvzpIOnVaAv)
@martinmahs, for fast reconnect:
1. Alt+Ctrl+I -> Console
2. Put

``` javascript
atom.project.remoteftp.connect(true)
```

**Comment by jimmaaay** [comment]
Should auto reconnect when 0.9.3 is released

**Comment by jimmaaay** [comment]
0.9.3 is released now
