### ISSUE TITLE
Ignore files on save

### ISSUE THREAD

**Issue by carloast82** [icetee/remote-ftp#527]
Hi,
could be possible add to .ftpconfig file a param to set a list of files / directory to ignore on save?
for example an .htaccess on local that i don't want upload on save to remote server..
Bye!

**Comment by ghost** [comment]
Just started using it. Also wondering how to exclude files or folders, e.g. .sass-cache folders.

**Comment by ghost** [comment]
Aah figured it out. If you go to the packages dropdown menu and go into remote-ftp, there will be an option called "create ignore file". Then just wrote .htaccess or whatever else's name for the ignore. I stopped it from uploading my sass-cache folder and some other unwanted files. Just note it is still in beta.

**Comment by jimmaaay** [comment]
Yes, you can use the ignore file to not upload files when syncing form local to remote
