### ISSUE TITLE
Notifications dont go away

### ISSUE THREAD

**Issue by SakuraOran** [icetee/remote-ftp#539]
https://gyazo.com/61ead4a02a7ebb6dd056855ee9f9bc55
this is only since the last update, is happening to a friend too, they wont go away unless you manually close them

**Comment by jimmaaay** [comment]
My bad, I'll sort this out now

**Comment by jimmaaay** [comment]
Should be fine in 0.9.4, which I just pushed out. Sorry for the issue.
