### ISSUE TITLE
421 timeout

### ISSUE THREAD

**Issue by mitkosaxa** [icetee/remote-ftp#548]
Hi, 
after last couple updates we noted a problem with name "421 timeout".
After that we need to disconnect and connect again, all files that we have saved before are waiting to be uploaded.
Can anyone help us ?
Thanks !!!

**Comment by devnox** [comment]
I saw this bug too. Its very frustrating :(

**Comment by jimmaaay** [comment]
@mitkosaxa sorry I'm not sure what you mean could you clarify

**Comment by jsieber** [comment]
I'm also seeing this behavior that started I believe two updates ago. My session now times out and I'm unable to transfer files either direction until I disconnect and reconnect. This did not happen with the same server previously. 

Now I need to verify that status of each upload or download in the small status bar as they only work until the connection times out.

**Comment by devnox** [comment]
@jimmaaay the problem is that we need to reconnect so we can upload files. The session times-out often!

Thanks.

**Comment by mitkosaxa** [comment]
Hi @jimmaaay the problem is the same as @jsieber-aca. 
![error](https://cloud.githubusercontent.com/assets/20345715/20263586/23d9118a-aa70-11e6-978c-98c3053d3118.jpg)
After that I need to reconnect.

**Comment by QwertyZW** [comment]
@Chukatuk @iffkaa @devnox  @mitkosaxa Do you actually not save anything for half an hour before this happens? or does it happen with a much shorter/more frustrating time frame? What ftp server are you connecting to? (Name and version)

**Comment by mitkosaxa** [comment]
Hi @QwertyZW , I think the time frame is shorter than half an hour. I use Apache Server - 2.4.16.

**Comment by Chukatuk** [comment]
@QwertyZW it happens after a couple of minutes ( the frustrating time frame =] ). 
Apache/2.4.23 (Unix)

**Comment by rbrtsluk** [comment]
I'm getting an ETIMEDOUT error trying to connect to sftp which never happen until latest update.

**Comment by QwertyZW** [comment]
@mitkosaxa  @Chukatuk  Just to be clear, I'm assuming that you guys are using ftp and not sftp, correct? Because I haven't seen this error on sftp. So I'm actually asking about the ftp server daemon you're connecting to (is it this https://mina.apache.org/ftpserver-project/ ?) , not the http application server. I'm assuming that you guys are using ftp and not sftp. For example on Ubuntu Xenial the default ftp server is this https://help.ubuntu.com/lts/serverguide/ftp-server.html. And the default sftp server would be OpenSSH (because sftp -> ftp over ssh).

**Comment by mitkosaxa** [comment]
@QwertyZW I'm using ftp to uploading files on shared hosting.

**Comment by QwertyZW** [comment]
@mitkosaxa could you link me the service you're using if it's public (and you don't mind)?

**Comment by mitkosaxa** [comment]
@QwertyZW I'm using different shared hosts located in USA, Bulgaria, Canada, Germany and the problem is same. 
- http://www.inmotionhosting.com/
- https://www.ukhost4u.com/
- https://hosteurope.de/
- http://superhosting.bg/

This is short list of hosts that I use.

Thanks

**Comment by QwertyZW** [comment]
@mitkosaxa  Nice. Will look into this tonight (or some time in the near future) hopefully.

**Comment by jsieber** [comment]
This issue appears to be fixed in version 0.9.4 for me. It is now automatically connecting again. I'm connecting to a Filezilla Server using explicit FTP over TLS.

**Comment by QwertyZW** [comment]
@rbrtsluk, @mitkosaxa  can you post your .ftpconfig s here?

**Comment by Chukatuk** [comment]
@QwertyZW im using ftp, not sftp, yes.
I dont know how to check which daemon we have and my access on the cpanel is limited. I found the server info using phpinfo(). Could you give me a hint on how to check?
We are renting some VPNs, i think, im not the IT guy in our company and we dont get the information...
If it helps, i've been using the plugin for something like 6 months already and the only problem i had was syncing the wrong way xD
By the way, thank you for your time on this

PS Sorry but cant grant you access to the server

**Comment by mitkosaxa** [comment]
Hi, my .ftpconfig file is default with only change host and password.

**Comment by rbrtsluk** [comment]
@QwertyZW yeh sure but my problem is with sftp and it doesn't really matter what settings I have it times out with ETIMEDOUT error if I'm not using remote-ftp any longer than 2mins.
{
    "protocol": "sftp",
    "host": "bootstraptemplate03.worldsecuresystems.com",
    "port": 22,
    "user": "bootstraptemplate03.worldsecuresystems.com/myemail/dw",
    "pass": "",
    "promptForPass": false,
    "remote": "/",
    "local": "/Volumes/Sierra/Users/luke/Websites/Business Catalyst/BC Bootstrap Template",
    "agent": "",
    "privatekey": "",
    "passphrase": "",
    "hosthash": "",
    "ignorehost": false,
    "connTimeout": 10000,
    "keepalive": 10000,
    "keyboardInteractive": false,
    "watch": ["stylesheets/_.css","/_.html","/_.htm","Templates/_.dwt","ModuleTemplates/_/_.tpl","Layouts/_.html","js/_.js","_System","images","Layouts"],
    "watchTimeout": 500
}

**Comment by QwertyZW** [comment]
@Chukatuk  I don't need access to your server, lol. Try upgrading to version 0.9.4 see if the problem persists @mitkosaxa  @Chukatuk 

To check your ftp daemon version you can do this:
`ftp <ip>`  for the default port (21)
![ftpversion](https://cloud.githubusercontent.com/assets/8478946/20354353/de4a0016-abeb-11e6-9aaf-9153998d6031.PNG)

@rbrtsluk  to check your ssh daemon version you can do this
`sftp -v <ip>` for the default port (22)
![sftpversion](https://cloud.githubusercontent.com/assets/8478946/20354426/15e755e6-abec-11e6-8610-c3667c06de85.PNG)

**Comment by mitkosaxa** [comment]
Hi, the problem start with version 0.9.2 and up.
Here is my daemon version for FTP port 21:
![ftp](https://cloud.githubusercontent.com/assets/20345715/20380120/b7da943c-aca8-11e6-9d7a-a718faedfd8e.jpg)

**Comment by rbrtsluk** [comment]
@QwertyZW Sorry mate im not sure how to do this

**Comment by QwertyZW** [comment]
@rbrtsluk  you on windows or mac?

**Comment by rbrtsluk** [comment]
Mac

**Comment by jimmaaay** [comment]
So are people using 0.9.4 and remote tree isn't automatically reconnecting on a 421 error?

**Comment by mitkosaxa** [comment]
I think so .

**Comment by jsieber** [comment]
@jimmaaay 0.9.4 is automatically reconnecting for me. The two previous versions were giving me problems.

**Comment by QwertyZW** [comment]
@rbrtsluk  http://www.macworld.co.uk/feature/mac-software/get-more-out-of-os-x-terminal-3608274/
