### ISSUE TITLE
Have the same git highlighting that the normal tree view has

### ISSUE THREAD

**Issue by SimonBiggs** [icetee/remote-ftp#55]
When I have tree view on a local directory from a git repository the tree highlights changes. It would be great if this functionality could be ported across to ftp tree.

**Comment by iKonrad** [comment]
Yes, I agree. Highlighting when the item is selected would be very useful and nicer from UX point of view.

**Comment by SimonBiggs** [comment]
I was talking about the git repository colouring. Orange for updated file. Greyed out when in the .gitignore green for new file.

**Comment by grenierdev** [comment]
Sadly, this feature require the use of git CLI on the server-side. Most FTP server dont accept custom command and thus would not be supported in the FTP.

For the SFTP connector, it might be possible to send the required command to the server and add the highlight to the remote view. Anyone up for the task?

**Comment by SimonBiggs** [comment]
In the end I just x forwarded my atom screen from the remote computer. A
bit laggy, but did what I was after
