### ISSUE TITLE
Auto connect when pressing CTRL+S (Windows)

### ISSUE THREAD

**Issue by hadhc** [icetee/remote-ftp#551]
Hi, I'm having this annoying issue where remote-ftp keep on connecting automatically every time i'm saving local files using 'CTRL+S' command. Is this a feature or a bug? I tried to look where to disable it (if it's a feature), but couldn't find it anywhere.

**Comment by jimmaaay** [comment]
You will need to edit the setting auto upload on save in the packages settings.
