### ISSUE TITLE
Local files sync automatically to sftp server

### ISSUE THREAD

**Issue by hadhc** [icetee/remote-ftp#552]
Hi, my local files sometimes will sync automatically to server without me doing anything. Is it a feature where i can disable it or is it a bug? I just want to use remote-ftp to easily look at the files on my server, i do not want to sync the local files using it (i use git deploy for that).

**Comment by htho** [comment]
Hi,

I am having the same issue.

It should work with ftpignore.
It doesnt seem to work correctly yet: See Bug #463

**Comment by nicolasbadia** [comment]
Check out the package setting. There is an option `Auto Upload On Save` which seem to be `always` by default. I suggest you to set it to `never`.

**Comment by jpxd** [comment]
What @nicolasbadia said.
