### ISSUE TITLE
Ability to set access privileges

### ISSUE THREAD

**Issue by romainschmid** [icetee/remote-ftp#554]
Hi, 

I want to use Atom to be able to upload files to an EV3 Lego robot. It works fine, but I need to change the permissions to 774 in order to be able to execute the python script files I upload. 
Is it possible to do it already ? If not, that would be cool.

Thanks !

**Comment by jpxd** [comment]
Yes, its possible but sadly not documented yet.... 
You can set the `filePermissions` option to `0774` in the .ftpconfig.
