### ISSUE TITLE
All file icons show as folders

### ISSUE THREAD

**Issue by winfamy** [icetee/remote-ftp#556]
Absolutely no idea what caused this one

[http://i.imgur.com/o8NtqCA.png](http://i.imgur.com/o8NtqCA.png) for screenshot.
Behavior only started today, and there's no errors being thrown.

Connected over SFTP and haven't made any changes on the server recently.

**Comment by skoskosko** [comment]
I had same problem but after updating to 0.9.4. this bug disappeared on my system.

**Comment by jimmaaay** [comment]
Update the package and should be fine
