### ISSUE TITLE
Remote FTP: Error: Handshake failed: no matching client->server cipher

### ISSUE THREAD

**Issue by tbett** [icetee/remote-ftp#559]
Just upgraded from 0.9.0 to 0.9.4.  Worked flawlessly in 0.9.0 but after the update when using the same config file I receive the below error ... Nothing changed on the server end, just upgrade Atom package.

Remote FTP: Error: Handshake failed: no matching client->server cipher

**Comment by tbett** [comment]
@jimmaaay - regarding your SSH upgrade comment on issue #561. Is there a resolution to this cipher issue or what configuration changes do I need make to make remote-ftp 0.9.4 operable again.  Thanks?

**Comment by jimmaaay** [comment]
@tbett Any chance you can install remote ftp from the dev branch and add `"cipherFix": true` to the `.ftpconfig` file and see if that solves your issue. If you need help installing it I can provide some instructions.

**Comment by tbett** [comment]
Yes, will do this asap.  Please provide dev branch package install steps (Win)

**Comment by jimmaaay** [comment]
@tbett Have you got git & npm installed in the command prompt?

**Comment by tbett** [comment]
Not on this machine but I've used apm remote-ftp@{version} to install previous versions of remote-ftp before.

**Comment by tbett** [comment]
@jimmaaay I've installed the dev branch version of remote-ftp and added the config parm "ciperFix": true to the .ftpconfig file.  It works!!!!  I do not get the cipher error.  Thank you for this update and helping to maintain this package!!

**Steps to install atom git package**
- uninstall previous instances of package
- download package from git (zip)
- unpack in directory c:\users\{username}\.atom\packages\{package}
- run npm install from within package directory above

**Comment by mwithers2010** [comment]
I can confirm that this fix works. Had same issues as @tbett and have been following this thread to get mine working again, too.
