### ISSUE TITLE
[Remote-FTP 0.9.4] [Atom 1.12.1] File saving not working

### ISSUE THREAD

**Issue by natinusala** [icetee/remote-ftp#560]
Even tho the UI and FTP logs say that the file has been saved, the file is not uploaded to the server ; when I refresh it, the modifications are not there. Other FTP clients are working fine.

I would be glad to provide some logs if you tell me where to find them !

**Comment by jpxd** [comment]
Sounds like a permission problem on the remote end.
Please reopen if this is still important for you.
