### ISSUE TITLE
Files appearing as folders in remote-ftp directory list

### ISSUE THREAD

**Issue by tbett** [icetee/remote-ftp#561]
Regardless of file type all files are being listed as a folder and are unable to be opened/edited.  The Atom tree view is fine only the remote-ftp file list is affected.

![image](https://cloud.githubusercontent.com/assets/11159897/20229455/82eaa416-a824-11e6-80a5-95223ab9f866.png)

I've uninstalled / reinstalled both remote-ftp and atom.  No difference after reinstallation.

Thanks for any help!

**Comment by sidharthms** [comment]
Any solution to this? I'm not able to create use RemoteFTP at all because of this. Files are not being synced and all the files in new projects are being treated as folders :/

**Comment by yamataka** [comment]
When I update to 0.9.4, it resolved.

**Comment by jimmaaay** [comment]
Are people having this issue with 0.9.4?

**Comment by sidharthms** [comment]
Yea upgrading to 0.9.4 seems to fix it.

**Comment by tbett** [comment]
ok, upgrading to 0.9.4 may be a good route but when doing so I end up getting a cipher error.  See issue [#559](https://github.com/mgrenier/remote-ftp/issues/559).  This just seems to be snowballing.  Thanks!

**Comment by jimmaaay** [comment]
@tbett To stop this error from happening the ssh2 library had to be upgraded from 0.4 to 0.5. This is probably why you're having issue #559

**Comment by tbett** [comment]
@jimmaaay regarding your comment about the SSH library.  Is there a resolution to this issue or what configuration changes do I need make to solve the cipher issue #559  Thanks I really do appreciate your help.
