### ISSUE TITLE
Privatekey auth not working

### ISSUE THREAD

**Issue by dreamorosi** [icetee/remote-ftp#562]
First off I'd like to state that I might be wrong, but due to the scarce documentation I resorted to open an issue.

I'm trying to connect to my server using sftp protocol on a non standard port with private key based authentication instead of password based. My .ftpconfig file looks like this
```
{
    "protocol": "sftp",
    "host": "{HOST}",
    "port": {NON-STANDARD_PORT},
    "user": "{USER}",
    "pass": "",
    "promptForPass": false,
    "remote": "{REMOTE_DIR}",
    "local": "",
    "agent": "",
    "privatekey": "~/.ssh/id_rsa",
    "passphrase": "",
    "hosthash": "",
    "ignorehost": true,
    "connTimeout": 10000,
    "keepalive": 10000,
    "keyboardInteractive": false,
    "watch": [],
    "watchTimeout": 500
}
```
What I'm not sure about is whether I'm making a mistake in the settings or is a remote-ftp issue. I should mention that if I try to connect from command line with the exact same parameters I can access properly, so either I'm wrong or there's an issue in the package.
`sftp {USER}@{HOST} -p {NON-STANDARD_PORT}`

The message I get when I try to connect within Atom is **Remote FTP: Error: All configured authentication methods failed** 

The only thing I could get from the documentation are that the key has to be OpenSSH format (which is) and that instead of inserting the actual key I have to use its path (which I'm sure it's correct).

**Comment by netonessa** [comment]
I had the same problem. Turns out it doesn't support "~" in the privatekey field. Changed it to "/home/ben/.ssh/id_rsa" and it seems to be working fine now! (Turn on "promptForPass" so it will ask for the passphrase)

**Comment by dreamorosi** [comment]
Hey @neto-ben thank you for the advice, you made my day!
For future reference I'm on MacOs and `Users/{MyName}/.ssh/id_rsa` did the trick for me.

Anyway I still think that the package should support the ~ as well, as it's fairly standard.

**Comment by jlk34n** [comment]
Is there a known issue w/ Windows paths? I'm getting a syntax error and not sure if it's the pathname or the contents of the keyfile?

**Comment by jimmaaay** [comment]
@dreamorosi You probably do have a fair point that the package should support `~`. I'll create a new issue for this. 

Also thanks @neto-ben for helping out.

**Comment by olafghanizadeh** [comment]
Had the samme issue and found this :)

**Comment by BitsOnBeat** [comment]
I have "Error: Cannot parse privateKey: Unsupported key format" but I'm sure it's correct, same for config
