### ISSUE TITLE
No matching host key format

### ISSUE THREAD

**Issue by xiangxing** [icetee/remote-ftp#566]
In SFTP case.

Whenever a server uses SSH-DSS algorithm to connect, you get this error : "No matching host key format"

I added in .atom/packages/Remote-FTP/lib/connectors/sftp.js : `self.info.algorithms = { "serverHostKey": ['ssh-dss'] };` after `self.info = info;` at line 27 in `ConnectorSFTP.prototype.connect` method.

Maybe, you should make it possible to add algorithms in the config file.

I hope it can help.

[EDIT] It works perfectly for me with that little hack…

**Comment by jimmaaay** [comment]
I believe the only host hashes available are md5 and sha1. See the ssh package. [here](https://www.npmjs.com/package/ssh2)

**Comment by xiangxing** [comment]
Thank you for your answer jimmaaay. The line i wrote works perfectly for me. Look for "algorithms" [here](https://github.com/mscdex/ssh2)

**Comment by jimmaaay** [comment]
Sorry I see what you mean now. Currently in the dev branch I've enabled every algorithm possible with `"cipherFix": true` in the config. This should sort your issue out. I'm wondering if this is the best solution as not everyone will know the algorithims for the server their using.

**Comment by jpxd** [comment]
Fixed in 648e85628ec21b6d3c854cbce4fd72b585c2f725
