### ISSUE TITLE
Recent update shows directories not files

### ISSUE THREAD

**Issue by EvanHerman** [icetee/remote-ftp#569]
All of my files are now displayed as directories instead of actual file, which prevents me from opening any of them.

**Comment by yamataka** [comment]
When I updated to 0.9.4, it's OK.

**Comment by jimmaaay** [comment]
@EvanHerman What version are you running? Was a problem with versions before 0.9.3 I believe.

**Comment by EvanHerman** [comment]
@jimmaaay I was running 0.9.3, but updated to 0.9.4 this morning and this issue now seems to be resolved.

Thanks so much for the fast resolution.

Evan
