### ISSUE TITLE
Project-Specific Settings for Multiple Projects

### ISSUE THREAD

**Issue by bhall7** [icetee/remote-ftp#573]
Hi,

I have two Atom projects (each in different folders): Dev, Prod. In each folder, there is a different `.ftpconfig` file for each corresponding project with different FTP settings based on whether it is in Dev or Prod.

Unfortunately, **remote-ftp** doesn't seem to recognize the multiple project config files, and instead only pulls from the first Dev config file.

How can I accommodate multiple settings for multiple projects within **remote-ftp**?

**Comment by egohost** [comment]
Under Settings -> Remote FTP -> Multiple Hosts you can enable this option.
