### ISSUE TITLE
Still stops responding after "No transfer time exceeded"

### ISSUE THREAD

**Issue by martinmahs** [icetee/remote-ftp#574]
Hi, 

After updating from v.0.92 to v.0.94 the former issue of not automatically reconnecting after "No transfer time exceeded" has returned..
Very frustrating... :(

I suspect other users experience that same but reports that the plugin becomes unresponsive which is technically true :) After "No transfer time exceeded" occurs, you can't navigate, save or anything else until you manually disconnect and connect again..

Any thoughts?
Again i'd like to thank you for an otherwise excellent plugin! :)

**Comment by jimmaaay** [comment]
@martinmahs Are you able to reproduce the error? If so can you open the dev tools in atom and it should list the server responses in the console. If you could paste them below that would be helpful.

**Comment by martinmahs** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/9629481/20481231/696ee172-afe6-11e6-8f77-37369ff19001.jpg)

Hope this helps... same behavior after a while of inactivity - notice the last thing is the "421 error" i bottom left corner... After this happens, nothing works until you disconnect and connect again.

**Comment by jimmaaay** [comment]
Sorry just to confirm, when you get a 421 it doesn't try to automatically reconnect?

**Comment by martinmahs** [comment]
You will love this :) I just reinstalled my computer (Got a new one) and installed atom and newest 0.9.4 of Remote-FTP - new behavior: 
When 421 occurs, it does reconnect but collapses the tree-view which is really annoying, but at least it reconnects :) Does that make sense?
