### ISSUE TITLE
Can't create new file on folders via ftp

### ISSUE THREAD

**Issue by OmarPinedaD** [icetee/remote-ftp#575]
Last week i can create new files via ftp but now i click to add file and nothing happen.

**Comment by jimmaaay** [comment]
@OmarPinedaD What platform are you using?

**Comment by OmarPinedaD** [comment]
Hi @jimmaaay, its in atom.io

**Comment by OmarPinedaD** [comment]
I already saw that the problem is not with Remote FTP, the problem is with some themes for Atom.io do not let you see the file creation window or folder, an apology
