### ISSUE TITLE
Stopped working after upgrade to Mac OS Sierra

### ISSUE THREAD

**Issue by jimsimoy** [icetee/remote-ftp#578]
It was working perfectly when I was still in EL Capitan, but after I installed Sierra it stopped working.

**Comment by jimmaaay** [comment]
Could you try reinstalling the plugin?

**Comment by jimsimoy** [comment]
Hi, re-installed the plugin (remove and install) several times, but still not working.
my procedure is as follows:
- install plugin
- after installation, close atom.io application and re-open
- create project folder
- create sftp config file, nothing happens, at this point the config file is not created, that is one issue.

second scenario:
- open existing project folder i used when the plugin was still working in El Capitan OS. (there is already an existing sftp config file on this folder)
- when I click connect, nothing happens

**Comment by jimmaaay** [comment]
Could you open up devtools / inspector and see if anything is showing in the console?

**Comment by jimsimoy** [comment]
Hi, thank you for your responses and for the devtools/inspector suggestion, i should have thought of that in the first place, but weirdly the plugin is working again, I noticed it working back after the atom application was updated to 1.12.6. i'm very happy now that the plugin is working again. :)
