### ISSUE TITLE
Entering Passive Mode, no upload

### ISSUE THREAD

**Issue by mitusbe** [icetee/remote-ftp#580]
Everything has always worked perfectly on macOS.

Now I have: Atom 1.12.4, Remote FTP 0.94 and macOS Sierra 10.12.1.
Remote FTP doesn't work anymore.

Connection is established, Noop command to keep connection alive succeed and the first minute everything gets uploaded. But then I see the log: "< 227 Entering Passive Mode (176,62,..." and the uploading progress keeps showing it's uploading but nothing happens. The upload doesn't work and keeps showing it uploads.

If I reconnect again the edits get's uploaded but than minutes later there's again the same issue. "< 227 Entering Passive Mode (176,62,..." and nothing gets uploaded anymore with again the uploading progress showing uploading.

Is there a solution? A reinstall didn't do anything.
Thanks.

**Comment by jimmaaay** [comment]
@mitusbe The only thing I can think to try off the top of my head would be to try changing the `pasvTimeout` option in the config

**Comment by samifouad** [comment]
I believe you're experiencing this because your server is set to active mode. As explained here ( #40 ) that is incompatible with this package. FTP server needs to be in passive mode.

I'm going to close this to keep things tidy, but please create an issue if you're still having issues!
