### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by Bezdekm** [icetee/remote-ftp#581]
In the developer console of Atom i see the error:

Failed to require the main module of 'Remote-FTP' because it requires one or more incompatible native modules (fsevents).
Run `apm rebuild` in the package directory and restart Atom to resolve.

but amp rebuild doesn't helped. Can you help me please?

**Comment by zebapy** [comment]
@Bezdekm why did you close this? did you figure out what was wrong? @jimmaaay Im getting this same issue. I tried `apm rebuild`, restarting, and re-installing plugin

**EDIT** Just saw Atom had an update for 1.12.4, which fixed this for me.

**Comment by jimmaaay** [comment]
@zebapy What OS are you using?

**Comment by zebapy** [comment]
@jimmaaay  El capt 10.11.1

Sorry about that. You can close this. Atom update fixed it.

**Comment by kikoseijo** [comment]
Needs to open again, same problem with lattest version of atom.
Im using Sierra 10.12.1
