### ISSUE TITLE
Support ~ in privateKey path

### ISSUE THREAD

**Issue by jimmaaay** [icetee/remote-ftp#583]
Support the character `~` in file paths. 
E.g `~.ssh/privateKey` shortened version of `/Users/Jimmy/.ssh/privateKey`. See #562

**Comment by shelbyKiraM** [comment]
This. Not allowing `~/.ssh/id.pem` is the WORST POSSIBLE THING, when collaborating using remote-ftp. No two users have the same username (the HUGE majority of the time). Please, please, PLEASE!

**Comment by icetee** [comment]
Next version will be available. https://github.com/icetee/remote-ftp/commit/2be9fc8526e119e8db0765f45a2ee32caad11c42
