### ISSUE TITLE
Package not loaded: cannot find module

### ISSUE THREAD

**Issue by codeline** [icetee/remote-ftp#586]
Remote-FTP fails to load upon application launch (Atom 1.12.5) with error:

Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.
**Remote-FTP 0.9.4**
fsevents@1.0.15 – Cannot find module 'Users/USERNAME/.atom/packages/Remote-FTP/node_modules/fsevents/lib/binding/Release/electron-v1.3-darwin-x64/fse.node'

I have already tried reinstalling and also rebuilding - no success. Only downgrading Atom to 1.11.2 helps.

**Comment by jimmaaay** [comment]
Is there is a npm-debug.log file in the packages folder?

**Comment by gh0st** [comment]
@jimmaaay I don't have an npm-debug.log in ~/.atom/packages/Remote-FTP. I am getting this same error.
Atom 1.12.6
Remote FTP 0.9.4
macOS 10.12.1

**Comment by jpxd** [comment]
Had the same error. There is a button to recompile the modules which fixes the error messages.
