### ISSUE TITLE
Make sftp defaults and setup smarter

### ISSUE THREAD

**Issue by dantman** [icetee/remote-ftp#59]
There are a number of defaults and behaviours of sftp that could work better.
- If the `port` option is removed, default to the default ssh port (22).
- Paths should accept `~` to refer to the current user's home directory, especially `privatekey` so keys in `~/.ssh/` can easily be used without hardcoding the absolute path.
- When not specified `user` should default to the current user's name like `ssh` does.
- When `privatekey` is not set remote-ftp should attempt to use the same key `ssh` uses (typically `~/.ssh/id_rsa`) instead of allowing the connection to fail with an "Available authentication methods: publickey".
- For settings like `user`, `privatekey`, etc... that are left as an empty string in the file created by remote-sftp an empty string should be considered equivalent to not being set. To disable the smart behaviour an explicit boolean `false` should be required.

**Comment by flobiwankenobi** [comment]
+1

**Comment by grenierdev** [comment]
I mainly use FTP and sometimes SFTP when I absolutely need it. @dantman you seem like someone that deal with SFTP quite a lot. Are you up to the task and implementing some of the tweaks you are suggesting?
