### ISSUE TITLE
Sync local -> remot, doesn't remove remote files

### ISSUE THREAD

**Issue by harabara** [icetee/remote-ftp#594]
Hey, it's just me or it doesn't remove remote files not present in local folder?

**Comment by jimmaaay** [comment]
No, I believe it's not designed to do so

**Comment by harabara** [comment]
Which is a pity. I am working on react up, and every new build creates files with a unique hash in name, like app.ddfbe82a3f611c6f1efc.js.
In this scenario remote-ftp's Sync is not much of a help because remote folder is quickly getting bloated.
Can I ask for this feature? 
Thank you
