### ISSUE TITLE
Remote FTP: Error: read ECONNRESET

### ISSUE THREAD

**Issue by paul2903** [icetee/remote-ftp#595]
Suddently I'm not able to connect through FTP and I'm getting the error response below:
`Remote FTP: Error: read ECONNRESET`
I have tried to connect using other tools like Notepad++ or FileZilla and it works but through Atom I'm not able to establish the connection. Any thought? is there any log I can provide?

**Comment by paul2903** [comment]
FYI: I've tried the suggestion in https://github.com/mgrenier/remote-ftp/issues/251 but it didn't work for me.

**Comment by jimmaaay** [comment]
@paul2903 Are you still experiencing the issue?

**Comment by jimmaaay** [comment]
Could you open up the inspector / dev tools and try connecting to the server. And if anything shows up in the console could you paste it below.

**Comment by paul2903** [comment]
Thanks for checking @jimmaaay ! I'm getting the following:
`< 220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------\r\n220-You are user number 6 of 500 allowed.\r\n220-Local time is now 13:58. Server port: 21.\r\n220-This is a private system - No anonymous login\r\n220 You will be disconnected after 15 minutes of inactivity.
client.js:291 < 331 User odentis_public@khalira.com  OK. Password required
client.js:291 < 230-Your bandwidth usage is restricted\r\n230 OK. Current restricted directory is /`

**Comment by paul2903** [comment]
And sometimes this:
`< 220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------\r\n220-You are user number 8 of 500 allowed.\r\n220-Local time is now 14:02. Server port: 21.\r\n220-This is a private system - No anonymous login\r\n220 You will be disconnected after 15 minutes of inactivity.
client.js:291 < 331 User odentis_public@khalira.com  OK. Password required
client.js:291 < 230-Your bandwidth usage is restricted\r\n230-OK. Current restricted directory is /\r\n230 90332 Kbytes used (4%) - authorized: 2048000 Kb`

**Comment by paul2903** [comment]
and sometimes nothing relevant:
`< 220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------\r\n220-You are user number 10 of 500 allowed.\r\n220-Local time is now 14:04. Server port: 21.\r\n220-This is a private system - No anonymous login\r\n220 You will be disconnected after 15 minutes of inactivity.
client.js:291 < 331 User odentis_public@khalira.com  OK. Password required`

just the ECONN error response

**Comment by paul2903** [comment]
Just FYI - I'm using Godaddy and this is happening when I use my home internet.
If I use my phone internet it works fine. I have tried to restart everything it's still not working but I'm not able to understand what's going on here. I have reinstalled Atom just in case but still not working.
In notepad++ FTP is working fine with both connections.

**Comment by socratesone** [comment]
Mentioned this on #251, but I figured I'd duplicate it here:
I was also having this issue. Turns out the server I was using didn't support SCP/SFTP, so I had to do it over plain old vanilla FTP. Working fine, now.

**Comment by paul2903** [comment]
Hi. Thanks for contributing with the issue.
I thought this could be related to Godaddy but I have been using this for a
long time and never has issues before and I'm not aware of any change on
the server side. In addition to this, on notepad++ it's working fine.

**Comment by dylanholmes222** [comment]
I am experiencing the same issue. All my clients with a Godaddy host have this issue, was working a month ago no problems. Can still connect to their Godaddy hosts via other FTP clients. Here is what I see in the console with the inspector:

< 220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------\r\n220-You are user number 7 of 500 allowed.\r\n220-Local time is now 17:04. Server port: 21.\r\n220-This is a private system - No anonymous login\r\n220 You will be disconnected after 15 minutes of inactivity.
client.js:291 

< 331 User jolt@solarsurgedirect.com OK. Password required

**Comment by johnmarlow007** [comment]
Hi all.
I have the exact same issue. I can connect to my ftp fine with notepad++ and filezilla, but I get the same error every time I connect with Atom. My server is also with godaddy...
I even deleted all the atom installation folders and reinstalled it, but same behavior.
If it helps, when I get to the Cpanel, I can see the idle ftp connection that atom started.
God help the brilliant minds that are hunting this bug !!!
Best of luck!

**Comment by dylanholmes222** [comment]
#585 is the same issue.

**Comment by alupkasix** [comment]
I have this same issue, which unfortunately prevents me from using Atom altogether. My site is also hosted on Go Daddy and FTP still works fine in Dreamweaver. Any update on this, or suggested workarounds? Thanks!

**Comment by dylanholmes222** [comment]
Working for me today! 

EDIT:
Scratch that, I was connected briefly (for ~1 min) then I received the ECONNRESET error. I was able to download new files from the server and save for that glorious minute.

**Comment by kotevcode** [comment]
#585 I've posted a fix for it, enjoy.

**Comment by paul2903** [comment]
Closing this issue.
Fixed in #585 by @shahafan
