### ISSUE TITLE
SFTP connection issues with new ssh2 version

### ISSUE THREAD

**Issue by alesub** [icetee/remote-ftp#596]
I'm getting the following error after updating this package:

> Remote FTP: Error: Handshake failed: no matching key exchange algorithm

Before the upgrade the connection was working fine.

Thanks for this great utility!

**Comment by jpxd** [comment]
Mhmm the ssh2 package version has been incremented on 28 Oct 2016 from 0.4 to 0.5.
Linked to https://github.com/mscdex/ssh2/issues/495
We probably could use the workaround from that issue

**Comment by jpxd** [comment]
Would be great if anyone submitted a PR :)

**Comment by jpxd** [comment]
Should be fixed :)
@alesub Please reopen if the problem persists

**Comment by alesub** [comment]
You rock!

**Comment by Scotchester** [comment]
Hi, I'm still encountering this issue. I'm running remote-ftp 0.10.5 on Atom 1.14.3 on Windows, in case that makes a difference.

**Comment by valaxy** [comment]
@Scotchester Maybe this will help: use the workaround from **jpxd**

> Mhmm the ssh2 package version has been incremented on 28 Oct 2016 from 0.4 to 0.5.
> Linked to mscdex/ssh2#495
> We probably could use the workaround from that issue

Pay attention that, you should add to:

```javascript
conn.connect({
    algorithms: {
        kex: ssh2s.constants.ALGORITHMS.SUPPORTED_KEX,
    }
});
```

**Comment by Scotchester** [comment]
@valaxy Thanks for the suggestion. I messed around with it for a bit, but I'm having a hard time figuring out where I would add that code. Is that supposed to go somewhere in the remote-ftp source?

Still having the issue on Atom 1.18.0, remote-ftp 1.1.3, on Windows 7.
