### ISSUE TITLE
Passive vs active mode connections

### ISSUE THREAD

**Issue by interbiznw** [icetee/remote-ftp#605]
Is there a way to not connect in passive mode?

**Comment by alarcia** [comment]
Please, this. I was going to open an issue.
In the last days I've been struggling to connect to FTP in my corporate network. Through other tools, I've discovered that using active mode does the trick, I don't care why, I'm no network expert.
Thanks a lot.

**Comment by amitmarty-gmail** [comment]
Please see #239 apparently it is not possible Currently.

**Comment by alarcia** [comment]
Well, time to use another editor, thanks folks! Best of luck.
