### ISSUE TITLE
Azure webapp FTP connection issue

### ISSUE THREAD

**Issue by prashanthmadi** [icetee/remote-ftp#609]
Azure webapps have ftp username as `web_app_name\deployment_user_id`

Escape `\` while using this plugin in .ftpconfig file 
 ex : `web_app_name\\deployment_user_id`

**Comment by hatzopoulos** [comment]
Thanks for the reminder, we should update the docs. Linking to issue #7.

For anyone else, the config is [`json`](http://www.json.org/) so it must follow that syntax.

![image](https://cloud.githubusercontent.com/assets/1771931/21908476/e42de038-d8e1-11e6-99de-28879dab9ad6.png)
