### ISSUE TITLE
"watch" doesn't work with files on network location

### ISSUE THREAD

**Issue by jandever** [icetee/remote-ftp#610]
The "watch" works fine with files on a local disk. But when the files are on a shared network location disk, the "watch" doesn't work. Although manually uploading works fine.

Both with the same .config
{
    "protocol": "ftp",
    "host": "000.000.00.00",
    "port": 21,
    "user": "***",
    "pass": "***",
    "remote": "/DIR/DIR/SITE.COM/",
    "secure": false,
    "secureOptions": null,
    "connTimeout": 10000,
    "pasvTimeout": 10000,
    "keepalive": 10000,
    "watch":[
        "./public/assets/css/style.css"
    ],
    "watchTimeout":500
}

Maybe this is the same issue in #456

**Comment by nrthbound** [comment]
I've had the same problem for quite sometime. It used to work in older versions, then when the watcher was changed, it stopped. Not sure what the deal is.

**Comment by hatzopoulos** [comment]
Thanks for reporting, do you still have the same issues using your LAN while using the latest version of remote-ftp?

**Comment by jandever** [comment]
Updated to 0.10.1 and the problem still occurs.

**Comment by samifouad** [comment]
There was a known issue with the watcher that should be resolved with the release that came out today: **v0.10.6**

So please upgrade to the latest version, if anyone is still having problems, please create an Issue with some details. :)
