### ISSUE TITLE
how to set upload on save

### ISSUE THREAD

**Issue by gurptop** [icetee/remote-ftp#612]
I use the SFTP protocol, the configuration file generated, without the option of on save upload,

**Comment by icetee** [comment]
Hi,
there is such a setting, but only globally.

`
"Remote-FTP":  
autoUploadOnSave: "never"
`

**Comment by wilblack** [comment]
Where/how do you set "autoUploadOnSave"?

**Comment by icetee** [comment]
Hi, @wilblack 

Settings view > Packages > remote-ftp > Settings OR atom config file.
![remote_ftp_settings](https://cloud.githubusercontent.com/assets/1855340/21462054/01380986-c958-11e6-913a-ac18343bf24b.PNG)

**Comment by jpxd** [comment]
What @icetee said. In the future maybe even in the .ftpconfig per project (see #645)
