### ISSUE TITLE
Cannot Access Files

### ISSUE THREAD

**Issue by mistakenCynic** [icetee/remote-ftp#617]
<img width="1680" alt="screen shot 2016-12-28 at 4 43 32 pm" src="https://cloud.githubusercontent.com/assets/12587231/21533337/13583ef4-cd1f-11e6-9c37-1812be45ffb8.png">

When I use Filezilla to access my files, it works just fine using the exact same host, port, username, and password settings and nothing else but I come across this weird issue when using this package. I'd love some advice, thanks.

**Comment by vladislav-plotnikoff** [comment]
If you use windows on ftp server, try set "remote" property to "C:/"

**Comment by samifouad** [comment]
That webhost I believe sets you up with an active mode FTP server. As explained in this issue ( #40 ) that mode is not supported. You can request passive mode from your host, as that will be more reliable and is more widely supported by clients out there.

Closing issue, but if you're still experiencing issues please create an issue!
