### ISSUE TITLE
Warn if remote file newer than local file

### ISSUE THREAD

**Issue by johnmarlow007** [icetee/remote-ftp#619]
A great option would be that before uploading the file, the plugin should warn in case the remote file is newer (or at least different in size) than the local one. 
It is crucial when more developers work on the same file and one of them modifies a file without the other one knowing and obviously he overwrites the changes making the work annoying.
It happened to a lot of people, including myself :)

**Comment by jpxd** [comment]
The same has been already suggested for the other direction (if the remote file would overwrite the newer local file).
@artitmedia There is a thing called *git* which some people use to manage projects with multiple devs 😉

**Comment by johnmarlow007** [comment]
I know, but whatever I tried to do using GIT didn't work or maybe I could not get my head around how it works yet. So I just need a simple option (exactly like Dreamweaver) to warn us if a file is different (or newer) than the remote one. :) 
But thanks for reminding me about git, I would like to contribute to some projects indeed, but never had the time to properly study how it works, since I never used it. But I will try some more, it might be useful...

**Comment by jpxd** [comment]
Duplicate to #450
