### ISSUE TITLE
Disconect and don't reconnect on new save

### ISSUE THREAD

**Issue by MiquelAdell** [icetee/remote-ftp#62]
Hi,

I'm not sure if this is a feature request. A bug report or just me not knowing how to use Remote FTP.

The thing is that sometimes I need some folder synced or sometimes I don't.

I assumed that the commands: Remote FTP connect and disconnect where what I needed.

The problem is that, although disconnect works and I get the "Remote FTP: Connection closed" message. The next time I save a file on a project with a valid .ftpconfig file I get "Remote FTP: Connecting...", "Remote FTP: Connected" and the file gets uploaded.

Is there any way to temporally not sync a project other than removing (or renaming) .ftpconfig?

Thanks!

**Comment by fseminario** [comment]
@MiquelAdell you beat me to it! 

I would second this. I just want to work locally and not upload to my ftp during some stages. I disconnect but it will automatically reconnect.

**Comment by TobiasTerhechte** [comment]
I would also like this feature. :+1:

**Comment by grenierdev** [comment]
New settings available to disable the `autoUploadOnSave` since e85bd4aa157810d4daacbd00c4ef46c50eccddb9
