### ISSUE TITLE
[feature request] upload successful notification

### ISSUE THREAD

**Issue by breadlesscode** [icetee/remote-ftp#620]
Hi guys,

I love your plugin! It improved my workflow by 200%. 

Can you implement a notification for a successful upload? Like you do it if the connection established successfully.

Greeting =)

**Comment by jpxd** [comment]
Sorry, but that would result in too much notifications much when using the automatic upload feature and saving often. But you can see the transfer status of your files in the status bar at the bottom of the Remote-FTP view (you can resize it if you like it larger).

**Comment by jpxd** [comment]
See also #636
