### ISSUE TITLE
Remote file permissions default to rw-rw-rw

### ISSUE THREAD

**Issue by stefKdu77** [icetee/remote-ftp#625]
Yo, very good stuffs but I'm currently moving from El captain to Sierra.

A strange thing has appeared with **sftp** facility :

posix rights are now always changed to -rw-rw-rw- on the server ...
With El capitain posix rights were always kept as the original on the server were.

1) example : original file on the server
-rwxr-xr-x 1 root root 17 Jan  6 23:28 essai

2) local uploaded in project :
-rw-r--r--  1 stef  staff  17 Jan  6 23:35 essai

3) After saving to the server :
-rw-rw-rw- 1 root root 17 Jan  6 23:36 essai

Any idea about what is wrong with Sierra.
That is very annoying ...

I have tested with the local sftp client on Sierra and posix rights are correctly set up.

In all case, many thanks for your really good job.

Cheers,

**Comment by jpxd** [comment]
Hi @stefKdu77 
this doesn't have anything to do with Mac OS Sierra.
A little time ago, a file permission feature was added but it has not been documented in the README... :/
When there is no `filePermissions` option set in the .ftpconfig, the permission defaults to `0666 `.

See the line here: https://github.com/mgrenier/remote-ftp/blame/a1abd216ee276a9ff484f74b780620c8df442d42/lib/client.js#L389

I think the default behavior should be to keep the original permissions if the option is not set, but currently all you can do is set `filePermission` the option or submit a PR which fixes this behavior and / or mentions the new option in the README :)

**Comment by jpxd** [comment]
See #611
