### ISSUE TITLE
[feature-request]Support sudo command

### ISSUE THREAD

**Issue by Heroes84** [icetee/remote-ftp#627]
Hi I have feature-request. I'm using atom to view remote files, and edit configuration files in php project such as database config, mail config etc. Some of files cannot be save without sudo command, beacuse for security I login user that is difrenet that www-data user. So I propose to add support for sudo command. I see this that:
* Adds fields to .ftpconfig called sudo with true or false, default false
* when is true, when if atom want save file or list files adds sudo to executes command, and if server want password send password in "password" field.

**Comment by moriyas1984** [comment]
I also would like to use the feature.
The package is very useful but I am concerned I have to store my password in the .ftpconfig file by plain-text for security reasons.

**Comment by jpxd** [comment]
Sorry, but that won't be possible with ftp & sftp...
@Heroes84 If you want to edit write access restricted configs, i suggest you just use your root user as user in the .ftpconfig. But if there is a permission problem with e.g. your webroot, which belongs to www-data, i suggest you just add your personal user to the www-data group and make the webroot directory group-writable.
@moriyas1984 You can use the password prompt feature for this (you will be asked for the password at every connection attempt) or just use a private key (for ssh) and/or a keyagent.
Hope this helps :)
