### ISSUE TITLE
Cannot see content of remote connection after successfull connection

### ISSUE THREAD

**Issue by Stefanbracke** [icetee/remote-ftp#629]
macos , fresh ATOM installation, connection succeeds, shows directoryfolder at top (with caret) but everything else is blank.

Feedback from server:
< 331 User {user} accepted, provide password.
< 230 User {user} logged in.
< 211-Features supported
<  MDTM\r\n MLST Type*;Size*;Modify*;Perm*;Unique*;\r\n REST STREAM\r\n SIZE\r\n TVFS\r\n211 End
< 200 Type set to I.
< 227 Entering Passive Mode (172,26,20,1,243,125)
< 150 Opening BINARY mode data connection for \'/bin/ls\'.
< 226 Transfer complete.
< 200 NOOP command successful.  (repeated every x seconds.Not "Zzzz" though?)

**Comment by Stefanbracke** [comment]
[
	{
		"name": "Remote-FTP",
		"version": "0.9.4"
	},
	{
		"name": "about",
		"version": "1.7.0"
	},
	{
		"name": "archive-view",
		"version": "0.62.0"
	},
	{
		"name": "atom-bootstrap3",
		"version": "1.2.12"
	},
	{
		"name": "atom-dark-syntax",
		"version": "0.27.0",
		"theme": "syntax"
	},
	{
		"name": "atom-dark-ui",
		"version": "0.52.0",
		"theme": "ui"
	},
	{
		"name": "atom-light-syntax",
		"version": "0.28.0",
		"theme": "syntax"
	},
	{
		"name": "atom-light-ui",
		"version": "0.45.0",
		"theme": "ui"
	},
	{
		"name": "autocomplete-atom-api",
		"version": "0.10.0"
	},
	{
		"name": "autocomplete-css",
		"version": "0.13.1"
	},
	{
		"name": "autocomplete-html",
		"version": "0.7.2"
	},
	{
		"name": "autocomplete-plus",
		"version": "2.31.4"
	},
	{
		"name": "autocomplete-snippets",
		"version": "1.11.0"
	},
	{
		"name": "autoflow",
		"version": "0.27.0"
	},
	{
		"name": "autosave",
		"version": "0.23.1"
	},
	{
		"name": "background-tips",
		"version": "0.26.1"
	},
	{
		"name": "base16-tomorrow-dark-theme",
		"version": "1.3.0",
		"theme": "syntax"
	},
	{
		"name": "base16-tomorrow-light-theme",
		"version": "1.3.0",
		"theme": "syntax"
	},
	{
		"name": "block-cursor",
		"version": "0.13.1"
	},
	{
		"name": "bookmarks",
		"version": "0.42.0"
	},
	{
		"name": "bottom-dock",
		"version": "0.4.4"
	},
	{
		"name": "bracket-matcher",
		"version": "0.82.2"
	},
	{
		"name": "color-picker",
		"version": "2.2.3"
	},
	{
		"name": "command-palette",
		"version": "0.39.0"
	},
	{
		"name": "deprecation-cop",
		"version": "0.54.1"
	},
	{
		"name": "dev-live-reload",
		"version": "0.47.0"
	},
	{
		"name": "emmet",
		"version": "2.4.3"
	},
	{
		"name": "encoding-selector",
		"version": "0.22.0"
	},
	{
		"name": "exception-reporting",
		"version": "0.40.0"
	},
	{
		"name": "file-icons",
		"version": "2.0.7"
	},
	{
		"name": "find-and-replace",
		"version": "0.202.2"
	},
	{
		"name": "fuzzy-finder",
		"version": "1.4.0"
	},
	{
		"name": "git-diff",
		"version": "1.1.0"
	},
	{
		"name": "git-plus",
		"version": "7.0.5"
	},
	{
		"name": "go-to-line",
		"version": "0.31.0"
	},
	{
		"name": "grammar-selector",
		"version": "0.48.2"
	},
	{
		"name": "gulp-control",
		"version": "0.5.0"
	},
	{
		"name": "gulp-manager",
		"version": "0.2.19"
	},
	{
		"name": "image-view",
		"version": "0.60.0"
	},
	{
		"name": "incompatible-packages",
		"version": "0.26.1"
	},
	{
		"name": "indent-guide-improved",
		"version": "1.4.11"
	},
	{
		"name": "keybinding-resolver",
		"version": "0.35.0"
	},
	{
		"name": "language-c",
		"version": "0.54.0"
	},
	{
		"name": "language-clojure",
		"version": "0.22.1"
	},
	{
		"name": "language-coffee-script",
		"version": "0.48.0"
	},
	{
		"name": "language-csharp",
		"version": "0.13.0"
	},
	{
		"name": "language-css",
		"version": "0.40.1"
	},
	{
		"name": "language-gfm",
		"version": "0.88.0"
	},
	{
		"name": "language-git",
		"version": "0.15.0"
	},
	{
		"name": "language-go",
		"version": "0.43.0"
	},
	{
		"name": "language-html",
		"version": "0.47.1"
	},
	{
		"name": "language-hyperlink",
		"version": "0.16.1"
	},
	{
		"name": "language-java",
		"version": "0.24.0"
	},
	{
		"name": "language-javascript",
		"version": "0.122.0"
	},
	{
		"name": "language-json",
		"version": "0.18.3"
	},
	{
		"name": "language-less",
		"version": "0.29.6"
	},
	{
		"name": "language-make",
		"version": "0.22.2"
	},
	{
		"name": "language-mustache",
		"version": "0.13.0"
	},
	{
		"name": "language-objective-c",
		"version": "0.15.1"
	},
	{
		"name": "language-perl",
		"version": "0.37.0"
	},
	{
		"name": "language-php",
		"version": "0.37.3"
	},
	{
		"name": "language-property-list",
		"version": "0.8.0"
	},
	{
		"name": "language-python",
		"version": "0.45.1"
	},
	{
		"name": "language-ruby",
		"version": "0.70.2"
	},
	{
		"name": "language-ruby-on-rails",
		"version": "0.25.1"
	},
	{
		"name": "language-sass",
		"version": "0.57.0"
	},
	{
		"name": "language-shellscript",
		"version": "0.23.0"
	},
	{
		"name": "language-source",
		"version": "0.9.0"
	},
	{
		"name": "language-sql",
		"version": "0.25.0"
	},
	{
		"name": "language-text",
		"version": "0.7.1"
	},
	{
		"name": "language-todo",
		"version": "0.29.1"
	},
	{
		"name": "language-toml",
		"version": "0.18.1"
	},
	{
		"name": "language-xml",
		"version": "0.34.12"
	},
	{
		"name": "language-yaml",
		"version": "0.27.1"
	},
	{
		"name": "line-ending-selector",
		"version": "0.5.0"
	},
	{
		"name": "link",
		"version": "0.31.2"
	},
	{
		"name": "markdown-preview",
		"version": "0.158.8"
	},
	{
		"name": "metrics",
		"version": "1.1.2"
	},
	{
		"name": "minimap",
		"version": "4.25.7"
	},
	{
		"name": "notifications",
		"version": "0.65.1"
	},
	{
		"name": "one-dark-syntax",
		"version": "1.5.0",
		"theme": "syntax"
	},
	{
		"name": "one-dark-ui",
		"version": "1.6.2",
		"theme": "ui"
	},
	{
		"name": "one-light-syntax",
		"version": "1.5.0",
		"theme": "syntax"
	},
	{
		"name": "one-light-ui",
		"version": "1.6.2",
		"theme": "ui"
	},
	{
		"name": "open-on-github",
		"version": "1.2.1"
	},
	{
		"name": "package-generator",
		"version": "1.0.1"
	},
	{
		"name": "pigments",
		"version": "0.37.0"
	},
	{
		"name": "platformio-ide-terminal",
		"version": "2.2.2"
	},
	{
		"name": "project-manager",
		"version": "3.3.3"
	},
	{
		"name": "qolor",
		"version": "0.4.1"
	},
	{
		"name": "settings-view",
		"version": "0.243.1"
	},
	{
		"name": "snippets",
		"version": "1.0.4"
	},
	{
		"name": "solarized-dark-syntax",
		"version": "1.0.5",
		"theme": "syntax"
	},
	{
		"name": "solarized-light-syntax",
		"version": "1.0.5",
		"theme": "syntax"
	},
	{
		"name": "spell-check",
		"version": "0.68.4"
	},
	{
		"name": "status-bar",
		"version": "1.4.1"
	},
	{
		"name": "styleguide",
		"version": "0.47.2"
	},
	{
		"name": "symbols-view",
		"version": "0.113.1"
	},
	{
		"name": "sync-settings",
		"version": "0.8.1"
	},
	{
		"name": "tabs",
		"version": "0.103.0"
	},
	{
		"name": "timecop",
		"version": "0.33.2"
	},
	{
		"name": "tree-view",
		"version": "0.210.0"
	},
	{
		"name": "update-package-dependencies",
		"version": "0.10.0"
	},
	{
		"name": "welcome",
		"version": "0.35.1"
	},
	{
		"name": "whitespace",
		"version": "0.35.0"
	},
	{
		"name": "wrap-guide",
		"version": "0.38.2"
	}
]

**Comment by jpxd** [comment]
Duplicate to #643
