### ISSUE TITLE
Keep alive not working

### ISSUE THREAD

**Issue by tominal** [icetee/remote-ftp#642]
I don't know if it's just me, but I just installed the latest version of atom remote-ftp on my new Windows 10 ssd and I'm getting 2 deprecations and keep alives aren't working anymore.

![](https://i.atomik.info/0fff48.png)

**Comment by tominal** [comment]
The deprecated calls have been cleared, but the keep alive issue still remains and I'm not quite sure it has anything to do with my VPS.

**Comment by jpxd** [comment]
Yeah, keepalive is a problem...
See #193
