### ISSUE TITLE
Update “remote-ftp@0.10.0” failed.

### ISSUE THREAD

**Issue by elebumm** [icetee/remote-ftp#647]
The new 0.10.0 update wasn't able to update and gave me this output:

`Unable to download https://www.atom.io/api/packages/remote-ftp/versions/0.10.0/tarball: 404`

I tried uninstalling and when I tried to reinstall it gives me the same error. 

I love this atom package, thank you for the constant updates! 😊

**Comment by bockaerts** [comment]
I'm having the same problem.

**Comment by eWholesaler** [comment]
Same

**Comment by elebumm** [comment]
Currently, I went back to version 0.9.4 by going into my terminal and doing:

`apm install remote-ftp@0.9.4`

If anyone is looking to use this plugin before there is a patch.

**Comment by czmole** [comment]
Same problem here, using atom 1.14.0-beta2

**Comment by masiama** [comment]
Same

**Comment by tominal** [comment]
Same here

**Comment by jpxd** [comment]
Sorry! Fixed by now!
This was caused by a bad apm publish.
