### ISSUE TITLE
Package preferences missing

### ISSUE THREAD

**Issue by R-Crow** [icetee/remote-ftp#649]
I keep looking for the package preferences that is shown on the package settings, however it is missing and is not in the atom settings either.

<img width="618" alt="screenshot-settings" src="https://cloud.githubusercontent.com/assets/12498067/22177655/c5e76632-dfe7-11e6-957f-56cf17867a72.png">

Nothing like this image from the packages settings was found. Nor any instructions on how to get there.

**Comment by jpxd** [comment]
The package settings can be opened (on Mac, other OS should be similar) via `Atom -> Preferences -> Packages -> Settings Button in the Remote-FTP box`

**Comment by R-Crow** [comment]
Ah! Apologies, the package settings were at the very top before the read me, I kept glancing over them. Just in case someone else needs help seeing it however..

![capture](https://cloud.githubusercontent.com/assets/12498067/22184932/54461fb8-e0a1-11e6-90b7-43b6ea69dd2b.PNG)
