### ISSUE TITLE
Failed to load remote-ftp plugin 

### ISSUE THREAD

**Issue by vad23klev** [icetee/remote-ftp#657]
On Atom load :

Cannot find module 'fs-plus', 
Linux arch 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux
Atom    : 1.14.0-dev-9ca20a586
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

**Comment by jpxd** [comment]
Can you re-install the Remote-FTP package, please?

**Comment by jpxd** [comment]
Please reopen if the problem persists after reinstalling.
