### ISSUE TITLE
Can connect, but will not change the file on the server.

### ISSUE THREAD

**Issue by schmolzp** [icetee/remote-ftp#659]
##So I am using an SFTP and I have set up the .ftpconfig file with all that is needed to connect. It connects great. However, I do get this error notification. Not sure if that is related to my problem, though.
![screen shot 2017-01-24 at 1 08 58 pm](https://cloud.githubusercontent.com/assets/4573987/22260196/4f7a63c2-e236-11e6-98fa-41d699ef7361.png)

Once it is connected and I make edits, I save the file and it is supposed to upload, but it doesn't change the file on the server. I try to manually upload the file and it doesn't change it. Do you know what is going on here? Thanks for any help you can provide.

**Comment by jpxd** [comment]
Can you please post your `.ftpconfig` file (without pw), and the developer console output after the error occurs?
Are there any symlinks involved in your working directory on the server?

**Comment by schmolzp** [comment]
So I believe there is an issue with the server I'm using. It's pretty old, so I switched to another server. Now everything works as expected. Thanks for this package!
