### ISSUE TITLE
Uncaught TypeError: Cannot read property '_pasvSocket' of null

### ISSUE THREAD

**Issue by Monitob** [icetee/remote-ftp#66]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.188.0
**System**: Mac OS X 10.10.2
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.6.2
### Stack Trace

Uncaught TypeError: Cannot read property '_pasvSocket' of null

```
At /Volumes/Data/nfs/zfs-student-2/users/2013/jbernabe/.atom/packages/Remote-FTP/lib/connectors/ftp.js:316

TypeError: Cannot read property '_pasvSocket' of null
  at /Volumes/Data/nfs/zfs-student-2/users/2013/jbernabe/.atom/packages/Remote-FTP/lib/connectors/ftp.js:316:19

```
### Commands

```
     -6:49.0 editor:indent (atom-text-editor.editor)
  2x -6:46.8 core:save (atom-text-editor.editor)
     -5:52.1 settings-view:check-for-package-updates (a.btn-issue.btn.btn-error)
     -5:07.5 remote-ftp:disconnect (atom-workspace.workspace.scrollbars-visible-always.theme-predawn-syntax.theme-predawn-ui.find-visible)
     -4:56.8 remote-ftp:create-ftp-config (atom-workspace.workspace.scrollbars-visible-always.theme-predawn-syntax.theme-predawn-ui.find-visible)
  5x -4:34.3 core:delete (atom-text-editor.editor)
  3x -4:32.9 core:paste (atom-text-editor.editor)
  3x -4:17.8 core:save (atom-text-editor.editor)
     -4:07.6 remote-ftp:connect (ul.list-inline.tab-bar.inset-panel)
     -1:24.2 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack.remove)
     -0:38.8 core:backspace (atom-text-editor.editor)
  2x -0:38.4 core:save (atom-text-editor.editor)
  3x -0:28.5 core:backspace (atom-text-editor.editor)
     -0:17.6 core:save (atom-text-editor.editor)
     -0:12.4 remote-ftp:connect (atom-text-editor.editor)
     -0:02.8 remote-ftp:disconnect (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "themes": [
      "predawn-ui",
      "predawn-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.6.2
linter, v0.12.0
linter-php, v0.0.12
minimap, v4.7.1
predawn-syntax, v0.1.3
predawn-ui, v0.3.8

# Dev
No dev packages
```

**Comment by Monitob** [comment]
Issu solved, with a another path

**Comment by marcelkuhla** [comment]
@Monitob How you have solved it ?

**Comment by bluxu** [comment]
I'm also getting this issue and don't know how to solve it. The error doesn't seem to harm functionality too much, though it does stop the connection being kept alive.

Any advice @Monitob or @mgrenier? 

Thanks for the superb package btw!

**Comment by Monitob** [comment]
Hello, this is not a problem in the ftp service, this a path problem. In my case I 've got a wrong path to my files. Check your ftp-config with the right information.

**Comment by bluxu** [comment]
@Monitob - thanks for your reply. I can confirm that the path is correct. It works most of the time, but this error crops up seemingly at random part way through a session. Maybe @mgrenier can shed some light?

**Comment by 78points** [comment]
My ftp-config is ok and still error:
TypeError: Cannot read property '_pasvSocket' of null
  at /Users/admin/.atom/packages/Remote-FTP/lib/connectors/ftp.js:315:19
