### ISSUE TITLE
Unable to Upload Recursively

### ISSUE THREAD

**Issue by nbdamian** [icetee/remote-ftp#660]
After the latest update, it won't upload all sub-folders when uploading a folder.

**Comment by jpxd** [comment]
Did you use `Sync local -> Remote` or `Upload` ?

**Comment by nbdamian** [comment]
Just Upload.

On Wed, 2017-01-25 at 02:40 -0800, Jan wrote:

Did you use Sync local -> Remote or Upload ?

**Comment by CubixSystem** [comment]
Definitely, it won't upload all sub-folders when uploading a folder.
I'm trying Sync local -> Remote and Upload
Dev tools console is clear and sometimes "Remote FTP: Some transfers failed
There were 0 successful out of an expected 1." error appear

**Comment by CubixSystem** [comment]
I'm trying to decremental downgrade
At 0.9.4 recursive uploads work as expected
@nbdamian you can execute `apm install Remote-FTP@0.9.4` to rollback to old version

**Comment by CubixSystem** [comment]
After several tests I can tell that this broken since 0.9.5

**Comment by CubixSystem** [comment]
Maybe this commit is reason "Remove recursion from dirs traverse" a1abd216ee276a9ff484f74b780620c8df442d42

**Comment by jpxd** [comment]
Fixed in 076e0de420489b6f8825b8808643d029d3f022a8

**Comment by morrow95** [comment]
Experiencing this same issue and have the latest installed.

Files upload fine.
A single folder with files in it uploads fine.
A folder with other folders and files/folders within those does NOT upload and fails.

folder
  - folder
      - file
      - file
  - folder
      - file
      - file
  - file
  - file

I am right clicking on the top folder and choosing upload.
