### ISSUE TITLE
Where's the remote view?

### ISSUE THREAD

**Issue by Code-Divine** [icetee/remote-ftp#661]
In version 9.something once you connect to the ftp server you've got another panel from the left which displayed the remote ftp directory. Now when you connect it's says it's successful but that panel is not displayed and I can't find a way how to display it.

**Comment by jpxd** [comment]
Did you try `Packages -> Remote-FTP -> Toggle` from the menu?
In the package settings there is also a setting called "Show view on startup" which you can enable.

**Comment by Code-Divine** [comment]
That toggle did the trick. Thanks. Show view on startup is enabled but it doesn't seem display the remote tree view. I need to manually use that toggle option from the menu
