### ISSUE TITLE
Can't make a new file

### ISSUE THREAD

**Issue by lukecywon** [icetee/remote-ftp#662]
When I right click and click "_Add File_" the dialog comes out fine but when i enter a filename and hit ``enter`` the new file does not appear in the file list.

**Comment by jpxd** [comment]
Can't reproduce this... Any errors in the Developer console? Do you have the right access rights on the remote to create the file?

**Comment by lukecywon** [comment]
This is the error in the dev console: ``< 550 Can\'t create directory: File exists`` although the file does not exist and I do have access rights on the remote.

**Comment by jpxd** [comment]
Seems more like an error on your FTP servers side.. Could be that a file with the same name is hidden :/

**Comment by lukecywon** [comment]
But this works fine when I created a file on the server using ``Noteplus++``. (Using a plugin)

**Comment by lukecywon** [comment]
I uninstalled and reinstalled ``Remote-FTP`` and this still can't make a file on the remote.

**Comment by lukecywon** [comment]
I just switched hosting provider and it works now
