### ISSUE TITLE
Tree view no longer toggles after update

### ISSUE THREAD

**Issue by tmrouse** [icetee/remote-ftp#666]
Hello, after updating to the latest version when i add a project folder and connect it used to toggle to the server tree view but now it does not do it intill i manually click toggle on remote ftp is there a way to make it switch over auto like it did before thanks!

**Comment by samifouad** [comment]
Check out #652 

Does that sound like what you're having a problem with? If it is, I was able to work out a fix if you look at [my most recent comment there](https://github.com/mgrenier/remote-ftp/issues/652#issuecomment-275813158).

**Comment by samifouad** [comment]
The fix should be in the latest version. I recommend updating and test to see if the issue is resolved.

**Comment by tmrouse** [comment]
Sorry for very late reply but i had been using a older version new version this is still not fixed.
