### ISSUE TITLE
Watch does not work I guess

### ISSUE THREAD

**Issue by giacomomasseron** [icetee/remote-ftp#669]
Hi,
I have a ftpconfig file like that:

    {
        "protocol": "ftp",
        ...
        "promptForPass": false,
        "remote": "/httpdocs",
        "local": "",
        "secure": false,
        "secureOptions": null,
        "connTimeout": 10000,
        "pasvTimeout": 10000,
        "keepalive": 10000,
        "watch": [
            "./tests/"
        ],
        "watchTimeout": 500
    }

Now If I add a file in the local "tests" folder, I don't see the file in atom and it is not uploaded on the server.
Do you know why it happens?

**Comment by samifouad** [comment]
You may be having an issue where you're mistaking the local for the remote treeview. I was recently having issues where the wrong view was being opened and so I made all these changes expecting them to be uploaded when I pressed save, but nothing changed on the remote website.

I would say verify which treeview this is happening on by adding this code:

```
.remote-ftp-view {
  background-color: #000;
}
```

in the atom stylesheet located at **File** -> **Stylesheet** in the menu. Then the remote treeview will appear with a black background color and the local treeview will retain the Atom default style.

If you are actually in the local treeview, you can **right-click** on the folder your file is in and click **Sync local -> remote**

Good luck!

**Comment by giacomomasseron** [comment]
I had noticed that, but in this case I don't know what the "watch" directive does.

I mean, when I open atom and I connect to FTP server with this plugin, another treeview is opened, and I can work online from that treeview.
So why should I continue to use the local folder treeview? I guess I am missing something, but I don't know what is it.

**Comment by samifouad** [comment]
Maybe someone with more knowledge of this can correct me if I'm wrong, but what I guessed was due to the nature of the plugin's design, it requires a project which means a local tree for said project. And then when you connect online and edit a file, it places the files you open in the local project folder (visible from local treeview) and once you press save, it uploads the file. 

The local treeview shouldn't be part of the workflow of this plugin, because you're essentially supposed to work right out of the remote view.

Maybe I'm wrong, but that's how I use this plugin. Avoid local treeview (and treat it like a temp folder) & stick to remote treeview.

**Comment by samifouad** [comment]
Here is the info about the watch option from the example:

```
"watch":[ // array - Paths to files, directories, or glob patterns that are watched and when edited outside of the atom editor are uploaded. Default : []
        "./dist/stylesheets/main.css", // reference from the root of the project.
        "./dist/stylesheets/",
        "./dist/stylesheets/*.css"
    ],
```

After a quick test, it seems to be working for me. It took manually refreshing the remote treeview but the new file as well as the changes in them were uploaded thanks to the folder being watched.

**Comment by giacomomasseron** [comment]
I did what you said. I don't work with local treeview but I work with plugin treeview.

So the problem remains: if I add a file to the local treeview ("watched"), it is not uploaded on remove server.

**Comment by samifouad** [comment]
I'm mistaken. You're right. If the file does not get edited by Atom, it will not upload. 

You can force it with **right-click** on the folder your file is in and click **Sync local -> remote** until this bug is resolved.

**Comment by samifouad** [comment]
@GiacomoK I believe I have resolved the bug. I will submit a pull request and hopefully it will make it to the next update. :)

**Comment by giacomomasseron** [comment]
Ok, let's wait.

**Comment by samifouad** [comment]
If you want to add it to your local copy of remote-ftp until a future update, check out the changes in the pull request:

https://github.com/mgrenier/remote-ftp/pull/679/files

**Comment by jpxd** [comment]
Should be resolved in the latest update :)

**Comment by imtiazwazir** [comment]
Still not working

**Comment by dlepera** [comment]
To me this solution don't work:
Https://github.com/mgrenier/remote-ftp/pull/679/files

I backed to previous code changing this ',' to '+' and works fine.
Perhaps is necessary verify if the user configure the path using '.' on start. If yes, concatenate the string is correct, if not the first option is the correct.

**Comment by RvWensen** [comment]
Same here, its not working. It keeps uploading.

**Comment by icetee** [comment]
@RvWensen Please write more information. (Tipp: Don't use `./` prefix, the base path is the project folder) https://github.com/icetee/remote-ftp/issues/1172#issuecomment-394139468

**Comment by RvWensen** [comment]
@icetee tnx for the quick replay!

i did this:
 `
"watch":[
        "./css/*.css"
    ]
`
So thats wrong you say? could you please tell me what i could put there?
I also tried without . and without ./

**Comment by icetee** [comment]
I tested MacOS, `remote-ftp v2.2.0` with FTP and FTPS and works. I simple add in ftpconfig this:
```
"watch": [
    "styles/*.less"
],
```

Versions:
```
Atom    : 1.27.2
Electron: 1.7.15
Chrome  : 58.0.3029.110
Node    : 7.9.0
```

**Comment by RvWensen** [comment]
Hi Icetee,

I tryied a lot, but i keeps running in too a uploading loop.
I did a clean install removed al other plugin's but watch keep's uploading.

i use ATOM 1.27.2 and Remote ftp 2.2.0
