### ISSUE TITLE
Uncaught Could not read `.ftpconfig` file

### ISSUE THREAD

**Issue by arsent** [icetee/remote-ftp#67]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.188.0
**System**: Mac OS X 10.10.2
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.6.2
### Stack Trace

Uncaught Could not read `.ftpconfig` file

```
At /Users/ars/.atom/packages/Remote-FTP/lib/remote-ftp.js:102

undefined
```
### Commands

```
     -0:01.8 remote-ftp:connect (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-light-ui",
      "atom-light-syntax"
    ],
    "disabledPackages": [
      "jshint"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.6.2
atom-beautify, v0.23.1
atom-django, v0.2.1
dash, v1.1.0
linter-php, v0.0.12
linter-phpcs, v0.0.12
php-getters-setters, v0.3.0
react, v0.10.1

# Dev
No dev packages
```

**Comment by ZachSB** [comment]
Save the .ftpconfig file and try connecting again.

**Comment by Spottybadrabbit** [comment]
![screen shot 2015-08-01 at 9 07 57 am](https://cloud.githubusercontent.com/assets/6477696/9022099/58910aca-382c-11e5-9947-a389102bc995.png)
Uncaught Could not read .ftpconfig file
/Users/cyrillutterodt/.atom/packages/Remote-FTP/lib/remote-ftp.js:110
The error was thrown from the Remote-FTP package. This issue has already been reported.

Same error

**Comment by uzielweb** [comment]
How can I connect to multiple FTP accounts?
The file config is reseted ever and ever.
This is bad :(

**Comment by petervansark** [comment]
I'm getting this error when there's more than one project folder open in Atom.
Removing project folders so there is only one with a .ftpconfig file solved the issue for me.

**Comment by ghost** [comment]
Yes petevanshark I removed all project folders and it worked for me too

**Comment by kideny** [comment]
tks，终于成功解决这个问题了，哇咔咔。
如果发现项目文件夹下面无法生成.ftpconfig文件，请将项目文件夹全部删掉，然后重新添加项目文件夹就可以啦。

**Comment by kideny** [comment]
话说，这算是我用atom碰到的第一个坑吗？
我打汉字歪果仁看得懂吗，要不要趁机做个广告，宣传一下我的自媒体小博客（ http://www.jicker.cn ）呢。

**Comment by diiegg** [comment]
I have the same error, i cant connect to the file :(

**Comment by jimmcclintock** [comment]
Ditto

**Comment by varesa** [comment]
This still happens. 

It seems that there is no support for multiple projects. My first project did not have a .ftpconfig file in it nor did I want it to have one.

Also it should not throw uncaught exceptions to the user so creating a missing .ftpconfig does not really "solve" this issue.

**Comment by ghost** [comment]
Trying to make a first connection, no idea how to start working with this package. Looks very promising.

**Comment by thejohnsmith** [comment]
### _I found a fix!_
1. Remove all other folders in your project tree and make sure there's only one project with the .ftpconfig in the root.
2. Then Connect _(Packages/Remote-FTP/Connect)_

**Comment by blooski** [comment]
That may work, removing all other projects, but it is not practical.  I have many projects, and sometimes want to have more than one open at the same time.
