### ISSUE TITLE
Install failed on windows 10

### ISSUE THREAD

**Issue by a16yaswantht** [icetee/remote-ftp#672]
I got this issue while installing. 
Installing “Remote-FTP@0.10.4” failed.Hide output…

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\Yaswanth\\AppData\\Local\\atom\\app-1.13.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Yaswanth\\AppData\\Local\\atom\\app-1.13.1\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Yaswanth\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Yaswanth\\.atom\\.apmrc" "install" "C:\\Users\\Yaswanth\\AppData\\Local\\Temp\\d-117031-14892-jk0r\\package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=ia32" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! syscall getaddrinfo

npm ERR! getaddrinfo EAI_AGAIN registry.npmjs.org:443
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Yaswanth\AppData\Local\Temp\apm-install-dir-117031-14892-1afavj8\npm-debug.log
[operation_log.txt](https://github.com/mgrenier/remote-ftp/files/742758/operation_log.txt)

**Comment by jpxd** [comment]
This is a DNS error from the npm registry: "EAI_AGAIN actually means a temporary failure in name resolution or simply the name server returned a temporary failure indication. It will ask you to try again later."
Try to re-install.
