### ISSUE TITLE
It may be unsecure to show password in .ftpconfig file

### ISSUE THREAD

**Issue by shintaroid** [icetee/remote-ftp#675]
In `.ftpconfig` file we have to provide `"pass"` attribute. But I doubt if it is secure since anyone who 'happened' to see my file will know my password. In Linux there is even no sign of typing on the screen when asking password, let alone showing it anywhere.

Asking password when log in may be more secure.

**Comment by jpxd** [comment]
Please use `"promptForPass": true` in the `.ftpconfig` to achieve this. You could also use a private key to connect via SSH. In the future even encrypted passwords might be possible (see #597)
