### ISSUE TITLE
SFTP connection attempt failed: Unsupported server host key algorithm: ecdsa-sha2-nistp256

### ISSUE THREAD

**Issue by frankIT** [icetee/remote-ftp#676]
I recive this error when i try to connect to a sftp server.
Tried with auth key pairs, password login, and ask for password on connect. Always the same error.
If I try to connect to the server using sftp from cli, anything works fine.

**Comment by jpxd** [comment]
Did it work before with Remote-FTP?

**Comment by frankIT** [comment]
Don't know, I already used ftp succesfully, but that's the first try with sftp

**Comment by wenjonsommers** [comment]
Same issue here. If I remove these three server keys from client.js then it works.

'ecdsa-sha2-nistp256',
'ecdsa-sha2-nistp384',
'ecdsa-sha2-nistp521',

**Comment by jpxd** [comment]
I don't understand it... These are in there even by default (even if they are not set from Remote-FTP, see https://github.com/mscdex/ssh2-streams#ssh2stream-methods).

**Comment by jpxd** [comment]
The algorithm list was introduced because of #559

**Comment by galaxybing** [comment]
Upgradde your Atom, such as 1.7.4 to 1.14.3. it works!

**Comment by wenjonsommers** [comment]
That's right. I hadn't realized my version of Atom was out of date.

**Comment by jpxd** [comment]
@wenjonsommers So you say it works in the current version? 🙏

**Comment by wenjonsommers** [comment]
Yep. Sure does.

**Comment by jpxd** [comment]
Perfect :)
