### ISSUE TITLE
Upload gets stuck

### ISSUE THREAD

**Issue by Hagvan** [icetee/remote-ftp#680]
When I actively edit my files on a website, often the upload gets stuck for a long time and the upload bar is lagging. After I reconnect everything uploads just fine. It's not a big deal, but annoying.

**Comment by samifouad** [comment]
What is the "**connTimeout**" setting from your **.ftpconfig** file?

If everything is okay after a reconnect, you could be experiencing a timeout while you're editing.

Do you know if something similar happens when using any other ftp client? If you got no problems there, that helps to rule out some kind of network or firewall issue.

**Comment by Hagvan** [comment]
I had the default 10000, I'll try to change it to 100000 and see what happens.

**Comment by Hagvan** [comment]
It didn't help. I can recreate this issue then I save the file without changes and try to open another file afterwards.

**Comment by samifouad** [comment]
Do you have any other FTP/SFTP client so you can test to see if this is a computer/network issue?

Something like WinSCP or FileZilla?

There is even a chance this could be a server-related issue. Are you able to access/edit the server configuration? Testing another client and if that client works okay, that could rule out a server problem.

If you do have access to the server, look for a connection timeout setting there as well. If the setting is too low, it will kick you off the server like you're experiencing.

**Comment by StefanBoettcherASMB** [comment]
hey @samifouad,

the same issue started to appear after an update. the timeout seems to occur more often and the reconnect itself does not work like it used to. this also occurs on multiple servers and different internet connections.

trying 0.10.7 now...

**Comment by StefanBoettcherASMB** [comment]
my problem is probably https://github.com/mgrenier/remote-ftp/issues/591

**Comment by icetee** [comment]
Duplicate #591
