### ISSUE TITLE
fs.js:951

### ISSUE THREAD

**Issue by redimongo** [icetee/remote-ftp#684]
Unsure what this means, but here is the error.

```
[Enter steps to reproduce below:]

1. Uploading a document. - or maybe downloading a folder (I am  unsure as I am doing both currently.)

**Atom Version**: 1.13.1
**Electron Version**: 1.3.13
**System**: Microsoft Windows 10 Home
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package, v0.10.5


### Stack Trace

Uncaught Error: ENOTDIR: not a directory, scandir 'C:\Users\russe\Documents\ipet\index.php'

```
At fs.js:951

Error: ENOTDIR: not a directory, scandir 'C:\Users\russe\Documents\ipet\index.php'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:571:28)
    at Client.traverseTree (file:///C:/Users/russe/.atom/packages/Remote-FTP/lib/client.js:586:31)
    at file:///C:/Users/russe/.atom/packages/Remote-FTP/lib/client.js:699:18
    at tryApply (file:///C:/Users/russe/.atom/packages/Remote-FTP/lib/connectors/ftp.js:16:14)
    at error (file:///C:/Users/russe/.atom/packages/Remote-FTP/lib/connectors/ftp.js:125:13)
    at file:///C:/Users/russe/.atom/packages/Remote-FTP/lib/connectors/ftp.js:147:33
    at final (C:\Users\russe\.atom\packages\Remote-FTP\node_modules\ftp\lib\connection.js:476:11)
    at Object.cb (C:\Users\russe\.atom\packages\Remote-FTP\node_modules\ftp\lib\connection.js:513:11)
    at Parser.<anonymous> (C:\Users\russe\.atom\packages\Remote-FTP\node_modules\ftp\lib\connection.js:117:20)
    at emitTwo (events.js:106:13)
    at Parser.emit (events.js:191:7)
    at Parser._write (C:\Users\russe\.atom\packages\Remote-FTP\node_modules\ftp\lib\parser.js:59:10)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Parser.Writable.write (_stream_writable.js:220:11)
    at Socket.ondata (C:\Users\russe\.atom\packages\Remote-FTP\node_modules\ftp\lib\connection.js:273:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

### Commands

```
  3x -4:42.2.0 core:move-down (input.hidden-input)
     -4:39.8.0 core:move-up (input.hidden-input)
     -4:39.5.0 snippets:next-tab-stop (input.hidden-input)
     -4:39.5.0 snippets:expand (input.hidden-input)
     -4:39.5.0 editor:indent (input.hidden-input)
  4x -4:33.8.0 core:copy (input.hidden-input)
  5x -4:32.5.0 core:backspace (input.hidden-input)
     -4:30.4.0 core:save (input.hidden-input)
  2x -4:02.8.0 editor:newline (input.hidden-input)
     -4:01.0 core:paste (input.hidden-input)
     -4:00.4.0 editor:newline (input.hidden-input)
  2x -3:59.1.0 core:backspace (input.hidden-input)
  2x -3:57.1.0 editor:newline (input.hidden-input)
     -3:53.9.0 core:save (input.hidden-input)
     -3:36.8.0 remote-ftp:sync-with-local (span.name.icon.icon-file-text)
     -3:31.8.0 remote-ftp:upload-selected (span.name.icon.icon-file-text)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "limited"
  }
}
```

### Installed Packages

```coffee
# User
Remote-FTP, v0.10.5 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.3 (active)
metrics, v1.1.3 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages

**Comment by samifouad** [comment]
What sort of troubleshooting steps have you done already?

If you're trying to pull down remote code into the local directory, have you tried deleting the local cache? Changing the local directory? Etc?

**Comment by jpxd** [comment]
Is caused by #112
