### ISSUE TITLE
A way to edit permission values of files in context menus

### ISSUE THREAD

**Issue by GrantGryczan** [icetee/remote-ftp#685]
You should be able to right-click any file in the project's tree view, and then click on a permissions button, opening up a menu to change the read, write, and execute permissions for owner, group, and public. Instead of using a simple UI, you should also be able to directly enter any numeric permission value.

Here is an example from FileZilla.
![image](https://cloud.githubusercontent.com/assets/14056899/22723646/278b94ea-ed8e-11e6-8967-f4daaf0f02fa.png)

**Comment by samifouad** [comment]
That's definitely a good idea for a feature to save time!

If you've got experience with Javascript, you should hack it together and submit a pull request. Atom is essentially a giant web app powered by node. Getting this feature done with the Atom/Remote-FTP code is a mountain not too high to climb!

**Comment by andrew98103** [comment]
i'll look into it later this week if i can find the time.

**Comment by GrantGryczan** [comment]
Though I now use WinSCP instead of FileZilla, which automatically reuploads my files when I save them (retracting my need to use this), I think other people would still find it helpful for this feature to be implemented.

**Comment by icetee** [comment]
I started develop it. https://github.com/icetee/remote-ftp/commit/413b12dbddfc04cec197473a1872688dfd085a4f

**Comment by icetee** [comment]
Next version will be included. Thanks for the idea.

![permissions](https://user-images.githubusercontent.com/1855340/30405297-49a5f9cc-98eb-11e7-95f1-624741c80c11.JPG)

**Comment by GrantGryczan** [comment]
Awesome!
