### ISSUE TITLE
Hidden files

### ISSUE THREAD

**Issue by pinguinjkeke** [icetee/remote-ftp#69]
Is there an ability to show dot (hidden) files?

**Comment by jerometan1** [comment]
Yes, I want this feature too. Thanks.

**Comment by pinguinjkeke** [comment]
Ok. I don't know the right atom packages archiecture right now to make a settings dialog for choose an option.

Open Settings -> Open config folder
navigate to ./.atom/packages/Remote-FTP/lib/ and open directory.js file.
Find "if (name == '.' || name == '..')" (line 113 for me) and change it to "if (name == '..')"

Restart atom and now you can see things were hidden! It's working. Tested for a 15 minutes.

Now I wanna to add config option and commit this little feature.

**Comment by pinguinjkeke** [comment]
Windows is showing hidden files. How to do the same on OS X?

**Comment by hatzopoulos** [comment]
Duplicate of https://github.com/mgrenier/remote-ftp/issues/8

**Comment by pinguinjkeke** [comment]
Open Settings, open Config folder.
packages/Remote-FTP/node_modules/ftp/lib/connection.js
There are 4 lines begins with cmd = 'LIST:

> cmd = 'LIST';
> cmd = 'LIST';
> cmd = 'LIST ' + path;
> cmd = 'LIST ' + path;

Change them:

> cmd = 'LIST -al';
> cmd = 'LIST -al';
> cmd = 'LIST -al ' + path;
> cmd = 'LIST -al ' + path;

(last two lines have a whitespace before end quote)
It's working even with SFTP for me!

OR
On some FTP servers you can add .ftpaccess file to the root with contents 

> ListOptions "-la"

**Comment by grenierdev** [comment]
As @hatzopoulos said, it's a duplicate of #8 which is a feature that is somewhat planned.
