### ISSUE TITLE
SCP support

### ISSUE THREAD

**Issue by Cr4xy** [icetee/remote-ftp#696]
Would be great, then one wouldn't need to install a FTP server on a fresh linux.
https://en.wikipedia.org/wiki/Secure_copy

**Comment by samifouad** [comment]
I use SFTP and that doesn't require a dedicated FTP server on a fresh linux box. As long as you install OpenSSH (which you're already using if you use SCP) then you can slightly tweak the configuration and get started with this package and securely connecting to your server with SSH keys only. No separate FTP server needed.

Here's a good guide on this topic: https://www.digitalocean.com/community/tutorials/how-to-use-sftp-to-securely-transfer-files-with-a-remote-server

**Comment by Cr4xy** [comment]
Thanks alot! :+1:
