### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by grenierdev** [icetee/remote-ftp#7]
- Configuration file : [node-ftp](https://github.com/mscdex/node-ftp#methods), [TLS](http://nodejs.org/api/tls.html#tls_tls_connect_options_callback), [ssh2](https://github.com/mscdex/ssh2)
- How to
- Shortcut

**Comment by buschtoens** [comment]
Would be highly appreciated, because right now I don't know how to use your package.

**Comment by grenierdev** [comment]
@buschtoens I added a **Getting started** in the readme that should get you up and ready.

**Comment by buschtoens** [comment]
Thank ya,

The problem is, I already tried exactly that. But nothing seems to happen.
I use Windows 8.1 64bit.

**Comment by grenierdev** [comment]
Can you elaborate on what step does _nothing_?
- `Remote-FTP` not present in `Packages` : try disabling/enabling the plugin
- Sidebar not toggling : try reload the editor with `CTRL+ALT+R`
- `Connect` does nothing : if your using FTP, open the console `CTRL+ALT+I` and search the FTP log for error

**Comment by grenierdev** [comment]
@buschtoens might be related to #21

**Comment by buschtoens** [comment]
Sorry for not responding sooner. Will look into that this evening.
Am 22.01.2015 19:17 schrieb "Michael Grenier" notifications@github.com:

**Comment by hatzopoulos** [comment]
@mgrenier 

In regards to

> Configuration file : node-ftp, TLS, ssh2

How about a section documenting both config types and then borrow the descriptions off of node-ftp and ssh2's respective options and inline them as comments and edit as needed. For example:

### SFTP Configuration Options

``` javascript
{
    "protocol": "sftp",
    "host": "example.com", // string - Hostname or IP address of the server. Default: 'localhost'
    "port": 22, // integer - Port number of the server. Default: 22
    "user": "user", // string - Username for authentication. Default: (none)
    "pass": "pass", // string - Password for password-based user authentication. Default: (none)
    "remote": "/",
    "agent": "", // string - Path to ssh-agent's UNIX socket for ssh-agent-based user authentication. Windows users: set to 'pageant' for authenticating with Pageant or (actual) path to a cygwin "UNIX socket." Default: (none)
    "privatekey": "", // mixed - Buffer or string that contains a private key for either key-based or hostbased user authentication (OpenSSH format). Default: (none)
    "passphrase": "", // string - For an encrypted private key, this is the passphrase used to decrypt it. Default: (none)
    "hosthash": "", // string - 'md5' or 'sha1'. The host's key is hashed using this method and passed to the hostVerifier function. Default: (none)
    "ignorehost": true,
    "connTimeout": 10000, // integer - How long (in milliseconds) to wait for the SSH handshake to complete. Default: 10000
    "keepalive": 10000 // integer - How often (in milliseconds) to send SSH-level keepalive packets to the server (in a similar way as OpenSSH's ServerAliveInterval config option). Set to 0 to disable. Default: 10000
}
```

### FTP & FTPS Configuration Options

``` javascript
{
    "protocol": "ftp",
    "host": "example.com", // string - The hostname or IP address of the FTP server. Default: 'localhost'
    "port": 21, // integer - The port of the FTP server. Default: 21
    "user": "user", // string - Username for authentication. Default: 'anonymous'
    "pass": "pass", // string - Password for authentication. Default: 'anonymous@'
    "remote": "/",
    "secure": false, // mixed - Set to true for both control and data connection encryption, 'control' for control connection encryption only, or 'implicit' for implicitly encrypted control connection (this mode is deprecated in modern times, but usually uses port 990) Default: false
    "secureOptions": null, // object - Additional options to be passed to tls.connect(). Default: (null) see http://nodejs.org/api/tls.html#tls_tls_connect_options_callback
    "connTimeout": 10000, // integer - How long (in milliseconds) to wait for the control connection to be established. Default: 10000
    "pasvTimeout": 10000, // integer - How long (in milliseconds) to wait for a PASV data connection to be established. Default: 10000
    "keepalive": 10000 // integer - How often (in milliseconds) to send a 'dummy' (NOOP) command to keep the connection alive. Default: 10000
}
```

**Comment by tracker1** [comment]
`privatekey` should probably note that the string should be a file path to the private key...  I know it should have been my first choice, but I encoded the private key file with `\n` and put that in... it was after I determined that it really is supposed to be a path.

**Comment by jpxd** [comment]
The README says 

> Buffer or string that contains a private key for either key-based or hostbased user authentication (OpenSSH format)

It should have worked if you had left out the `\n`s or escaped them properly

**Comment by wasikuss** [comment]
But `Wiki > Settings` says:

> key: set privatekey to the path to your private key, set passphrase if key is encrypted

**Comment by jpxd** [comment]
Funny...
We use the mscdex/ssh2 module for SFTP. The keyparser used there expects a buffer or a string in the OpenSSH format
BUT: We seem to support both path and key if I understand this line correctly: https://github.com/mgrenier/remote-ftp/blob/96bfd7d9a46d7b2b15ac32362c129c78c0b57a2e/lib/client.js#L170

**Comment by wasikuss** [comment]
@jpxd no, line means that if `privatekey` is set then read file that it targets to. so `remote-ftp`  supports only path

**Comment by jpxd** [comment]
Ah you`re right. I'll update it in the README
