### ISSUE TITLE
Sync from local subfolder (e.g. "dist") instead of from project root folder?

### ISSUE THREAD

**Issue by ooloth** [icetee/remote-ftp#704]
Thanks for the great plugin!

Is there a way to specify a local subfolder (rather than the root project directory) as the local root folder when uploading to the remote server? I easily changed the remote folder target to a subfolder using the "remote" setting in the ftpconfig file, but when I try to do the same with the "local" setting (by setting it to "dist" or "/dist"), it doesn't seem to work. 

I'd like to sync my local "dist" subfolder with the remote subfolder. At the moment, all uploads from my local "dist" subfolder are being placed into a newly created "dist" folder within the remote subfolder. 

Is there a way to stop this "dist" folder from being created on the remote side?

**Comment by jpxd** [comment]
Sorry, there is no option for this currently and you can't change the upload root directory, but it is a valid use case and there is an open issue for it: #361

**Comment by ooloth** [comment]
Okay, thanks for the response anyway.
