### ISSUE TITLE
File within watch list not being uploaded

### ISSUE THREAD

**Issue by ICJR** [icetee/remote-ftp#706]
I am using the sass-compiler plugin, partial .scss files are being uploaded on save but the compiled style.css file is not being uploaded. This occurred after recent update. I have the watch configuration set correctly, stylesheet is being compiled correctly its just not being uploaded.

**Comment by ICJR** [comment]
Assuming this is why 

> // TODO: Add fix for files which are uploaded from a glob selector
> // don't upload files watched, they will be uploaded by the watcher
> // doesn't work fully with new version of watcher

**Comment by samifouad** [comment]
@ICJR & @querysol

Watch is not working after upgrading to v0.10.6? Interesting because this update actually included a fix for watch because it was not working. Hopefully this is a quick fix via setting change.

What OS are you on and can you post the setting you have for watch?

**Comment by jrrdnx** [comment]
Same issue for me after upgrading today to v0.10.7, on macOS 10.12.3. My watch path is watching a css directory with Sass files are compiled:

```
"watch":[
    "./assets/css/"
],
```

I should mention that files in my watch directory were uploaded correctly before the upgrade (v0.10.5).

**Comment by samifouad** [comment]
Can you remove the period before the slash and see if that resolves the issue? I believe relative addressing may be incompatible with the fix that was made to watch in this latest version.

So by changing `"./assets/css/"` to `"/assets/css/"` you _should_ no longer have an issue.

You can verify this is the problem by going to:

**View** -> **Developer** -> **Toggle Developer Tools**

And once you're connected to your remote, type this into console and hit return to get the path that Remote-FTP is trying to watch:

`atom.project['remoteftp-main'].client.watch.addListeners().watchDataFormatted`

If you're getting an extra period or missing a slash in the path that's being returned, then the relative addressing is definitely the problem.

In the mean time, if you're still experiencing issues with watch and changing the path is not helping, I recommend you right-click on the local folder and **Sync local -> remote** This will do essentially the same thing without the automagic uploading.

**Comment by ICJR** [comment]
I tried altering the watch path including the option you listed above. My watch setting is simple 
> "./" 

I create/drag in images etc. they all upload the only real issue is the compiled style.css file that is compiled by https://atom.io/packages/sass-compiler

**Comment by UncleGena** [comment]
Removal point before slash helped me (v0.10.7)

**Comment by jpxd** [comment]
@ICJR
So you say some files are automatically uploaded by the watcher but only your compiled CSS files are not?
Can you post your .ftpignore file please ?

**Comment by ICJR** [comment]
All files are automatically uploaded, i tested the watch list by replacing images, adding new files, changing watch directory etc. it is just the compiled CSS file that is giving me problems. .ftpignore file is empty for now, only working on frontend.

I reverted to a previous version of the plugin and compiled CSS file is being uploaded with same settings i posted above so its definitely a change in recent update. 
https://github.com/ICJR/remote-ftp

**Comment by jrrdnx** [comment]
Removing the period before the slash fixes the auto-upload issue for me for compiled css files, although I'm receiving a transfer notification for each file despite the "Enable Transfer Notifications" setting being toggled off.

**Comment by ICJR** [comment]
Just updated to 10.7 and it now works with my current config including the period before forward slash. Didn't try without since it worked right after update. Thank you.

**Comment by ICJR** [comment]
Spoke too soon, just relaunched Atom and i am having the same issue. Going to see if its caused by other plugins.

**Comment by robhuska** [comment]
I too started having this issue with a recent update. changing my watched directory from "./assets/css" to "/assets/css" did fix it. But now I am getting a notifications for every file that gets compiled. This is very distracting. I even have the "Enable Transfer Notifications" turned off. Not sure these are the notifications I am see though, because I do not get them when saving standard files.

See screenshot:
<img width="2048" alt="screen shot 2017-02-23 at 9 26 09 am" src="https://cloud.githubusercontent.com/assets/2412155/23262965/a4095b6a-f9aa-11e6-9d43-2d9980dff21a.png">

For now, I have downgraded to 0.10.5 and changed my watch list back to "./assets/css/". This allows my files to auto upload and not have the huge notifications.

**Comment by oueryemchi** [comment]
I have the exact issue, I did what **robhuska** suggested and have the same behaviour...

**Comment by robhuska** [comment]
Has there been any progress on this? Remote FTP has not been updated since these issues have started. I am currently running v0.10.5 still and have had an update for v0.10.7 since I downgraded. Just hoping to see some sort of resolve here. Thanks.

**Comment by icetee** [comment]
Related #724 and #820
