### ISSUE TITLE
Requiring $ from atom is no longer supported.

### ISSUE THREAD

**Issue by jpxd** [icetee/remote-ftp#71]
Requiring `$` from `atom` is no longer supported. If you are using `space-pen`, please require `$` from atom-space-pen-views. Otherwise require `jquery` instead: `{$} = require 'atom-space-pen-views'` or `$ = require 'jquery'` Add `"atom-space-pen-views": "^2.0.3"` to your package dependencies. Or add `"jquery": "^2"` to your package dependencies.

**Comment by grenierdev** [comment]
Merged pull request #98
