### ISSUE TITLE
HELP-WANTED: how to increase tree-view font size ??

### ISSUE THREAD

**Issue by tweed** [icetee/remote-ftp#711]
OBJECTIVE: increase font size of remote-ftp's tree-view

I'm am able to use styles.less to increase my local view's font size
I cannot find the file  "remote-ftp.less" on my windows 10 box
though on github remote-ftp.less it's there and has this in it
.ftptree-view-resizer
thinking that suggests i should be able to increase font size

would very much like to have the remote view tree show me bigger fonts 

Could i get some help please
- need to find the correct file to edit on my windows machine and what to put for css/less.
OR, the method that will allow me to increase the font size of the remote tree-view

THANKS!!!

**Comment by tweed** [comment]
Hoping for help on finding a way to increase font size of tree-view - WAY too small

**Comment by icetee** [comment]
Try:

**1. Way**

Add the focus on the tree and press [CTRL + "plus"] key combinate.

**2. Way**

Add CSS rule in your "global" styles.less file (File > Stylesheet)

Example:
```
.remote-ftp-view.ftptree-view-resizer.tool-panel {
    font-size: 16px;
}
```

I close this issue. If there is still a problem I can open it.
