### ISSUE TITLE
.ftpignore

### ISSUE THREAD

**Issue by jonathansigg** [icetee/remote-ftp#714]
How to setup the .ftpignore file????????????

**Comment by nilssolanki** [comment]
From what it looks like, it works like a .gitignore file. See: https://git-scm.com/docs/gitignore

**Comment by carl-alberto** [comment]
currently, it is not yet documented from anywhere in the repo, tried using the .gitignore patterns but it seems my .git and .ftpignore is still being uploaded to my server even if I have the .ftpignore setuped

**Comment by mismosmi** [comment]
Would be really nice to have some doc here. For me it seems to work for single files but not for folders or patterns and also only for local -> remote sync, not for local <- remote.

**Comment by icetee** [comment]
The new version is capable of handling this.
