### ISSUE TITLE
CTRL + \ to hide remote-ftp's tree view along with the local tree.

### ISSUE THREAD

**Issue by veganaiZe** [icetee/remote-ftp#717]
It would be nice to be able to easily hide remote-ftp's tree view at the same time (with the same command) as the regular (local) tree view.

**Comment by abhishekdeshkar** [comment]
@veganaize  : How did you hide remote-ftp's tree view ? For me using CTRL + \ hides the local tree view :/

**Comment by veganaiZe** [comment]
@abhishekdeshkar : I click **Packages** -->> **Remote-FTP** -->> **Toggle** or I use _CTRL_+_ALT_+_O_

**Comment by abhishekdeshkar** [comment]
@veganaize  : Thanks mate! They should really mention in the documentation.

**Comment by veganaiZe** [comment]
@abhishekdeshkar : No problem.  It is mentioned in the Readme.md file.  If it isn't clear enough, consider forking the repo, improving the docs, and then issuing a pull-request. -- that's the beauty of open source software (and git/github).

**Comment by veganaiZe** [comment]
Why closed?

**Comment by icetee** [comment]
@veganaize I think this is a special need. Due to the [dock](http://blog.atom.io/2017/04/12/atom-1-16.html) it maybe unnecessary.

Add your **init.coffee**:
```coffee
atom.commands.add 'atom-text-editor', 'user:tree-views-toggle', ->
  workspaceView = atom.views.getView(atom.workspace);
  atom.commands.dispatch(workspaceView, 'tree-view:toggle');
  atom.commands.dispatch(workspaceView, 'remote-ftp:toggle');
```

And your **keymap.cson**:
```coffee
'atom-workspace atom-text-editor:not([mini])':
    'ctrl-shift-o': 'user:tree-views-toggle'
```

Hope to help.

**Comment by veganaiZe** [comment]
Okay.  Thank you.  It's nice to know why things happen.
