### ISSUE TITLE
Feature request: Clear cache on closing/connecting

### ISSUE THREAD

**Issue by onlineidentity** [icetee/remote-ftp#722]
We are working on a remote project with 2 people. Everytime I open the project, I manually have to clear to local stored files, because the other person could have changed them. Would be great if remote-ftp cleares the local stored files after closing atom or when connecting to the remote server.

**Comment by icetee** [comment]
Simply close the local tree and use only Remote-FTP tree.
Is this a solution to the problem?

The local files is not "cache" in Atom philosophy.

I close this issue. If there is a problem, open it again.
