### ISSUE TITLE
Watch folders not working after update

### ISSUE THREAD

**Issue by oueryemchi** [icetee/remote-ftp#724]
I am struggling to get my watched folders to update for compiled files. when I save a foo.less files it is uploaded. the compiled foo.css is not watched and therefore not uploaded!

Please assist..thanks
A

**Comment by newelement** [comment]
Looks like SFTP connections in general is not working after update.

**Comment by imtiazwazir** [comment]
+1 watch is not working

**Comment by ArturV1z** [comment]
Had the same problem. Found out that having "./public" in watch was wrong. Changed that to full path folder eg. "/public/assets/js/"(linux) "./public/assets/js/"(windows) and watchers started to work.

**Comment by rttmax** [comment]
+1
