### ISSUE TITLE
Uncaught TypeError: Class constructor Connector cannot be invoked without 'new'

### ISSUE THREAD

**Issue by DeanmvSG** [icetee/remote-ftp#729]
Unfortunately this doesn't throw a error that lets me instantly create an issue but when trying to connect to a site in Atom 1.16 beta, the plugin says connecting and then just "does nothing".  When looking at console the error is thrown at this line - https://github.com/mgrenier/remote-ftp/blob/master/lib/connectors/sftp.js#L15

Atom: 1.16.0-beta0
Electron: 1.3.13
Chrome: 52.0.2743.82
Node: 6.5.0

![screen shot 2017-03-13 at 10 32 04](https://cloud.githubusercontent.com/assets/15265711/23850673/56486b6e-07d8-11e7-8b1e-28e9d07937a5.png)

To note: this works fine in Atom 1.15, it is only 1.16 that it seems to fail.  At a guess it could be linked to https://github.com/atom/atom/pull/13823?

**Comment by icetee** [comment]
+1

**Comment by DeanmvSG** [comment]
@icetee Tried the fix this morning and seems to be working fine! 👌

**Comment by mstearne** [comment]
Still broken for me on Atom Beta 1.16.0-beta0. This bug doesn't exist on
Atom stable so I have been using Remote-FTP with that without problem. So I
don't think it is a Remote-FTP bug so will wait until the next Atom beta.
