### ISSUE TITLE
Auto upload on save -> only when connected results in no upload at all

### ISSUE THREAD

**Issue by working-name** [icetee/remote-ftp#733]
Don't know what to provide to help you, I have a server connected, I double click the remote file, erase everything in it, hit CMD + S, local copy is saved, but not uploaded. I have to right click it and select "Sync local -> remote".

Update: changing it to always has no effect either.

**Comment by udine1981** [comment]
Unfortunately, same issue here. All is good but not the automatic upload on save.
Same with Atom 1.15 on my Windows 10 x64 or my Linux Mint Serena x64 computers.
Thx.

Edit : After lot of tricks, it's working but notifications not !

**Comment by kelexel** [comment]
Actually, this seems to happen to me only after a certain period of time.
I mean, I can fire Atom, remote connect to my ftp/sftp folder, work as usual, save files (that will be saved remotely).
But than, let's assume I take a coffee break (I'm only human after all), coming back a few mins later, and starting work again... 
When this time I will save, it will not save to the remote host anymore.
As if something (timeout to server?) expired, but Remote FTP isn't aware of it.
To fix, I need to manually disconnect & reconnect, and it works fine again.

**Comment by icetee** [comment]
Related #591
