### ISSUE TITLE
Upload after manual save in Atom 1.15 fails

### ISSUE THREAD

**Issue by rsangle** [icetee/remote-ftp#734]
Hi,

I updated Atom to 1.15 yesterday and since then when I try to manually save a remote file, it fails with the message "Remote FTP: Upload Error Failure" and in the panel, there's a message that says "Uploading ... " that never goes away. 

Thanks!

**Comment by nanna-dk** [comment]
Same issue here...

**Comment by icetee** [comment]
@nanna-dk What does the console say?

**Comment by ghost** [comment]
I'm having similar issue except for the "Uploading" dialog. I opened Atom and connected to my server successfully. When I open a file from the server, it (and it's parent folder) saves to the local directory. When I edit the file and hit save, it gives the `Remote FTP: Upload Error Failure` error. I've been trying to sort this out for a few hours but i've gotten nowhere. It's happening on my work and home computers.

It was working fine a few days ago and I haven't changed anything at all. I just opened it back up.

**Comment by icetee** [comment]
@blakewenloe You use simple FTP, if yes, please go to settings page (Packages > remote-ftp) and set on Debug Response and open dev tool (View > Developer > Toggle Developer Tools). And try again upload. Do you get something wrong, what the say console?

**Comment by ghost** [comment]
Shortly after my comment I rebooted my server and now it's working again. I'm still not entirely sure what caused this but it doesn't appear to be the package's issue.
