### ISSUE TITLE
Local Network Support?

### ISSUE THREAD

**Issue by robert-m** [icetee/remote-ftp#741]
Hello! Any chance you can add support for local network folders (Windows 10)? I have my projects stored locally on my laptop but also need to push modified files on Save to a local network folder **without** using FTP/SCP. 

Reason being is that we have a dev web server setup where everyone can test/view their changes if they don't have one setup on their local machine.

Thank-you!

**Comment by bullet92** [comment]
Hi, i suggest you to install a little FTP server on that machine or to enable the Microsoft FTP server:
Press WIN+R, type OptionalFeatures.exe  in the window and click OK.
Go to Internet Information Service > FTP Server > and select FTP Service.
You will also need to go to Web Management Tools and select IIS Management Console
Once finished press again  WIN+R, type InetMgr.exe in the window and click OK.
Add one FTP site trough the panel on your left, put your info like site name, the path that you’d like to serve and click Next. At binding and SSL settings, select “No SSL” (you are working in local safe lan, right?) and click Next. Select Anonymous for authentication for simple config, select Anonymous users for authorization and enable the read and write permissions.

Bye!

**Comment by icetee** [comment]
Attach the local network folder in Windows (and open). Click right click and Open with Atom. Any changes will be made.
