### ISSUE TITLE
sFTP config per project

### ISSUE THREAD

**Issue by picarda** [icetee/remote-ftp#743]
Hello,
How we can choose the sFTP/FTP we want to connect?

Best.

**Comment by DeanmvSG** [comment]
From the command menu type "Create" and pick either "Create SFTP config file" or "Create FTP config file"!

**Comment by ghost** [comment]
I'm having a problem managing multiple sftp connections too. 
Not sure if it's more of a problem at the plugin level, or maybe with atom.
occasionally "project folders" that I've added lose the different[project folder?] icon, and just appear as a normal folder. "connect" seems to just use the first .ftpconfig it finds, not the one nearest the [project]folder I have selected
