### ISSUE TITLE
local -> remote functionality

### ISSUE THREAD

**Issue by derek-baxter** [icetee/remote-ftp#754]
Hello,

I was wondering if it's possible to add a feature, so when you local -> remote. It will delete the files that are no longer there.

For example. I delete a file on my local folder. I forget about deleting it on the server as well. Then later I local -> remote the root and I was hoping all the old files would get deleted, however they stayed there. So I have to go through and check which files are no longer needed

**Comment by derek-baxter** [comment]
@icetee Why was this a dup? where is it duplicated?

**Comment by icetee** [comment]
I associate with this #725
I'm wrong?

**Comment by derek-baxter** [comment]
You're not wrong. Just didn't see a reference before. Thanks.
