### ISSUE TITLE
"watch": no longer working after update?

### ISSUE THREAD

**Issue by adcar** [icetee/remote-ftp#759]
Just updated this package and I noticed that files under watch are no longer being automatically uploaded to the remote server.

Version I'm on : 0.10.7

**Comment by adcar** [comment]
It's working for me now, not sure why, but it is, probably a problem with my web server or something.

**EDIT:** I was using `./css/style.min.css` in my .ftpconfig.  When I changed it to `/css/style.min.css`everything worked perfectly.

**Comment by RonHolt** [comment]
Thanks @MD5HashBrowns - removing the dot fixed it for me as well.
