### ISSUE TITLE
The connection to AWS Ec2 Ubuntu is too slow !!

### ISSUE THREAD

**Issue by waelwalid** [icetee/remote-ftp#761]
i have as instance on AWS and i`m working with php designer IDE but it is not support laravel framework so i`m going to use ATOM and i can say it is very nice , i was used it to connect via ftp to GoDaddy host and it was work perfectly but on AWS Ec2 
Atom is unusable !! 

this issue related to Atom in general or related to this package ?
is there anyone knows anything to solve it or make it better ?

**Comment by icetee** [comment]
I do not know. It is not certain that the Atom has the problem.
