### ISSUE TITLE
ftp pane / panel location

### ISSUE THREAD

**Issue by ghost** [icetee/remote-ftp#762]
I've installed this plugin on multiple computers.
For some reason, one of the most recent installs opens the **remote-ftp pane/panel to the LEFT of the file-tree**.
Any idea how that could have happened or how to fix/change it?
I've had a really hard time searching for this - pane and panel seem pretty ambiguous in atom text forums, and often only refer to text editing areas; there are plenty of instructions for moving panes/panels that only work for text areas when I try them.

*side note: I did compile this latest [atom] instance, because it was for i386, which atom.io doesn't offer binaries for.

**Comment by icetee** [comment]
Please check new Remote-FTP [version](https://github.com/mgrenier/remote-ftp/releases/tag/v1.0.0).
