### ISSUE TITLE
[Enhancement] Hide tree when disconnected

### ISSUE THREAD

**Issue by henriquecm** [icetee/remote-ftp#765]
When remote-ftp disconnected from ftp hide the tree then show the four buttons that appear before you connect on startup.

It would be a good improvement because many and many times the ftp disconnected and i was trying to save without know that it wasn't sync to my server because that message below tree don't caught my attention.

**Comment by icetee** [comment]
There is an automatic connection already since v1.1.3 #591
I think it's the same.
