### ISSUE TITLE
Files/directories download with only the last few characters in the name or just show the file extension

### ISSUE THREAD

**Issue by kfjustis** [icetee/remote-ftp#768]
Whether I choose to _download_ or _Sync local <- remote_, file and directory names become corrupted. Either the first few characters will be missing or the entire file name will be gone leaving only the extension.

Although the directory structure and files appear to be corrupted, opening them one by one works fine. The individual files load as they should, just the names are messed up. I'm unable to sync back up to remote, but that may have something to do with my server permissions.

I'm using sftp with the following config file:

    {

        "protocol": "sftp",
        "host": "hostname.amazonaws.com",
        "port": 22,
        "user": "username",
        "pass": "pword",
        "promptForPass": false,
        "remote": "/home/username/",
        "secure": true,
        "secureOptions": null,
        "connTimeout": 10000,
        "pasvTimeout": 10000,
        "keepalive": 10000

    }

Local directory after _Sync local <- remote_: 

![Imgur](http://i.imgur.com/MllmBus.png)

**Comment by icetee** [comment]
This has been repaired. The new release will be good.
Thanks for reported issue!
