### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by sumantaparida** [icetee/remote-ftp#770]
Remote FTP: Connection failed
Error: read ECONNRESET

**Comment by newelement** [comment]
I'm not getting it to work at all on 1.16

**Comment by dquartino** [comment]
fix:
go to .atom\packages\Remote-FTP\node_modules\ftp\lib\connection.js
on line 106 change socket.setKeepAlive(true); -> socket.setKeepAlive(false);

and 

go to .atom\packages\Remote-FTP\lib\connectors\ftp.js
comment line 48 self.ftp._socket.setKeepAlive(self.info.keepalive > 0);

Can't find the sources for those fixes, but I had noted them just in case ;)

**Comment by icetee** [comment]
Try this:
Set keepalive value 0 in .ftpconfig

**Comment by levanigongadze** [comment]
go to
` .atom\packages\Remote-FTP\node_modules\ftp\lib\connection.js`
on line 106 change
`socket.setKeepAlive(true); to socket.setKeepAlive(false);`

on .ftpconfig change
`"keepalive": 1000, to "keepalive": false,`
