### ISSUE TITLE
After updating atom/ftp package the local and remote panels swapped sides

### ISSUE THREAD

**Issue by TeapotNickS** [icetee/remote-ftp#775]
After updating both Atom and the package the remote and local panels have swapped places and I can see a way to get them back to the correct way around.
![screen shot 2017-04-19 at 08 45 15](https://cloud.githubusercontent.com/assets/15928482/25168959/46926d38-24dd-11e7-9846-553fbebfb550.png)

**Comment by icetee** [comment]
Hi, thanks for report issue.

Try to new Remote-FTP [version](https://github.com/mgrenier/remote-ftp/releases/tag/v1.0.0).
This version Supported Dock / Pane method.
