### ISSUE TITLE
Request : multiple connection files / profiles

### ISSUE THREAD

**Issue by morrow95** [icetee/remote-ftp#783]
Would like to request the option to select from multiple connection files / profiles.  I primarily use Atom for web editing and often I have the need to publish files from the same project to multiple domains.  It would be nice if we could add multiple .ftpconfig files and then have the option to select from them when we upload and or sync local -> remote.  This is kind of a deal breaker for me as I do this soo often... I like to test files on a live 'test' domain before putting things on the production domain as well as other use cases for this.

As I see it the only way I could accomplish this is editing the .ftpconfig file each time I wanted to go back and forth between different domains which would be a pain.. especially with different private keys, passphrases, etc for sftp.

**Comment by ffuentes** [comment]
Yes, that would be great +1.

**Comment by ffuentes** [comment]
This seems to be duplicated with #493.

**Comment by icetee** [comment]
Multi rsa_id #834
Global config #275
