### ISSUE TITLE
Inability to create ftpconfig

### ISSUE THREAD

**Issue by mjcreative** [icetee/remote-ftp#785]
I've followed the instructions, created a new package, added a default index.html file and then when I go to create Ftp Config file absolutely nothing happens. I can toggle the FTP panel, when I hit edit configuration it brings up a blank ftpconfig file. So I tried saving a new file with the configuration options in my package. Then hit connect and nada. Am I doing something wrong or is there a bug somewhere?

**Comment by icetee** [comment]
Hi,

For a new project, create a .ftpconfig file. If it is empty, it must be deleted before it is created.
If that does not help then a configuration file pattern is found [here](https://github.com/mgrenier/remote-ftp).
