### ISSUE TITLE
How to disable timeout?

### ISSUE THREAD

**Issue by ZeroMorale** [icetee/remote-ftp#788]

**Comment by sircon-john** [comment]
I also want to know how to disable timeout, as a temporary workaround to the ongoing bug.
I'm writing this while using version 0.10.7

**Problem**
There is currently i bug in Remote FTP (it has actually been there for months) where if you timeout (no operation for 1800 seconds) there is no automatic reconnect.
There is a warning, but it is barely visible in the bottom left corner (font size 10px or so..)
The only way to reconnect is to go to the Atom menu "Packages" -> "Remote FTP" -> "Connect"

**The solution**
Make Remote FTP reconnect automatically on saving the file (auto push to server), and on refresh/request file list in the tree view. This was the default behaviour ca 1 year ago.

Also discussed here:
https://github.com/mgrenier/remote-ftp/issues/591

**Comment by icetee** [comment]
Duplicate #591
