### ISSUE TITLE
Remote-FTP uploads/downloads files/folders 

### ISSUE THREAD

**Issue by kartagis** [icetee/remote-ftp#789]
The previous bug #584 has been closed, but it still applies.

![screenshot 2017-05-11 12 04 51](https://cloud.githubusercontent.com/assets/1607518/25941507/774708e6-3642-11e7-878b-dac0caf5a47c.png)

Whenever I open a remote file then edit and save it, it also saves locally. I don't think this is desired behaviour. What it should do is clean-up after syncing to remote.

**Comment by icetee** [comment]
I think you're wrong. Atom is basically working on a project, repository, no "temp" files. We can't determine where it originally came from the file.

If you delete it after synchronization, it will be deleted from the repository... Not a good idea.
