### ISSUE TITLE
Can't find menu that "Sync local to remote"

### ISSUE THREAD

**Issue by HoyeongKim** [icetee/remote-ftp#795]
![question](https://cloud.githubusercontent.com/assets/21984563/26137599/36fdd0f6-3afe-11e7-8f78-09d1c1276ffc.jpg)

hi.
i update my ATOM editor to 1.17.0 recently
and i can't find menu that "Sync local to remote" after update ATOM editer.
but, the menu "Sync remote to local" is exist and i can use it.

how can i do?
thanks

**Comment by konhasaurusrex** [comment]
Currently a unfixed problem. I have downgraded my Atom version, until a suitable fix has been found/made.

**Comment by clonge** [comment]
Temporary solution:

https://github.com/mgrenier/remote-ftp/issues/796#issuecomment-302129404
