### ISSUE TITLE
Atom 1.17 update breaks repo

### ISSUE THREAD

**Issue by AlexNodex** [icetee/remote-ftp#796]
After an update to Atom 1.17 this morning (MacOS) there is no longer an "Upload" option on a file /folder when I right click (cmd click)

I've also noticed that Atom has taken it upon itself to create a "Project" pane, perhaps this has something to do with it?

**Comment by noxd3v** [comment]
Same problem with update 1.17 (Windows 7 32bit). 
No upload button, cannot sync, probably have something to do with these panes

**Comment by AlexNodex** [comment]
As a quick workaround you can highlight the file/folder and "Ctrl + shift + u" which will perform the upload.

Hope this isn't a permanent issue!

**Comment by noxd3v** [comment]
That doesn't work for me, hope they'll resolve the issue quickly

**Comment by tokn** [comment]
Replicated on macOS Sierra 10.12.4 this morning. I suspect that Atom have moved things around. As a work around old versions of Atom are available on Atom.io

**Comment by dtsdev** [comment]
Quick "permanent" fix before it comes in official plugin update. It's based on @McNuggetSauce solution for remote-sync, but works with this one as well.

Open `remote-ftp.cson` (.atom/packages/Remote-FTP/menus) and change line 3
- from `'.tree-view.full-menu': [`
- to `'.tool-panel.tree-view': [`

Restart Atom, done.  Hope it helps.

**Comment by garrottkai** [comment]
Uploading now also does not respect the directory structure of the local project -- everything gets dumped in the remote project root.

**Comment by dtsdev** [comment]
@garrottkai Works fine on my side, regardless whether it's a file, directory, or entire project. Maybe try disable and re-enable the package? Anyone else have similar problem?

**Comment by cjwijtmans** [comment]
please fix this? i cant upload now.

**Comment by nbdamian** [comment]
This is fixed in the latest commit, however is yet to be published.
To fix this, download the master branch, replace your package (.atom/packages/remote-ftp) with the master branch. Open the directory in terminal and run "npm install"

**Comment by firestar300** [comment]
Thanks for the quick fix @dtsdev

**Comment by cjwijtmans** [comment]
The fix is not working anymore...

**Comment by paokodo** [comment]
@dtsdev It's ok.

**Comment by teknosains** [comment]
the fix Doesnt work...

**Comment by timothymarois** [comment]
Doesn't look like a real patch is coming anytime soon. Might just go back to sublime text. There isn't even any alternative packages for FTP.

**Comment by JavierAgueroCL** [comment]
Great solution, work form me
