### ISSUE TITLE
cant upload

### ISSUE THREAD

**Issue by fausto160792** [icetee/remote-ftp#797]

**Comment by OrlanRepo** [comment]
:+1:

**Comment by orlanrepo** [comment]
No upload button when right clicking in Project tree view (context menu). After update to Atom v 1.17.0.

**Comment by Psype** [comment]
Also, when I save my sass, it generates matching css.
But even if the generated css folder and its content is watched, those files are not uploaded =/

**Comment by slarcher** [comment]
![screen shot 2017-05-18 at 3 07 29 pm](https://cloud.githubusercontent.com/assets/4286800/26187378/d2a9d3a0-3bdb-11e7-9680-b46b62214e21.png)
upload **& download** links are missing in tree view. Please fix asap makes the tool unusable.

**Comment by juliesunset** [comment]
I've the same issue here...

**Comment by mmason33** [comment]
I'm running into the missing upload option as well

**Comment by fausto160792** [comment]
I´m using filezilla again.

**Comment by icetee** [comment]
#798 Check this answer.
