### ISSUE TITLE
Atom 1.17 remote FTP panel is now on the left of the normal tree view

### ISSUE THREAD

**Issue by tokn** [icetee/remote-ftp#798]
As described - Atom 1.17.0 on macOS Sierra 10.12.4 the FTP panel used to sit on the right of the local tree view but now they're the other way around which has messed with my flow a bit. Can't see anyway to get this swapped back.

I'll roll Atom back for a bit anyway - great package guys

**Comment by daviddunnington** [comment]
![atom](https://cloud.githubusercontent.com/assets/19631764/26150561/cbc25fb6-3af6-11e7-983a-776f12dfd7f3.PNG)
I have the same issue. Anyone have a solution?

**Comment by redimongo** [comment]
Hi yes this is an issue for windows users too, and it's affecting my work flow, yes am OCD about the order my panels are in.

**Comment by noxd3v** [comment]
I wonder why don't they integrate ftp as core package

**Comment by tokn** [comment]
I guess that Atom have made these changes and the plugin community will update their stuff accordingly - i've noticed for example that a lot of my plugins which feed data into the status bar aren't working now on 1.17. I guess Atom must have moved sections around centrally.

@webjoyable I think the philosophy with Atom is "here's the editor" and that's it - then you add in everything which you need. It does seem to be very extensible in its nature, and the contributors on this plugin have done a great job. I guess the trade off for the community being able to make what they want of it is this slight fragmentation when it comes to updates.

**Comment by noxd3v** [comment]
They should probably announce up front what they're changing so contributors could be aware of the dependencies of their plugins. Nonetheless, Atom is awesome, and this FTP plugin also

**Comment by adcar** [comment]
Not only does this affect workflow but it is also no longer possible to perform `local --> remote` actions anymore.

**Comment by noxd3v** [comment]
Plugin is not usable until author adapts to these pane changes

**Comment by tokn** [comment]
@MD5HashBrowns That's a separate issue, #796 there's a fix suggested in there now too
https://github.com/mgrenier/remote-ftp/issues/796#issuecomment-302129404 by @dtsdev

**Comment by daviddunnington** [comment]
As a temp fix I have just rolled back to 1.16.0 and all is ok. I couldn't work that way any longer everything felt backwards lol. Here's a link for the older version if anyone else needs it https://github.com/atom/atom/releases

**Comment by MeanThirteen** [comment]
@daviddunnington thanks for pointing out the temporary solution for this, upload works for me now too

**Comment by slarcher** [comment]
@daviddunnington thanks mate will try that straight away.

**Comment by slarcher** [comment]
@webjoyable I highly agree with you about making FTP part of core

**Comment by icetee** [comment]
Try this PR #772.
Please accept PR @jpxd

**Comment by icetee** [comment]
Please check new Remote-FTP [version](https://github.com/mgrenier/remote-ftp/releases/tag/v1.0.0).

**Duplications:**
Missing features. File tree upload/download gone. #832
Upload is gone #830
Where is the "Upload"-Context-Menu-Entry for folder #829
sync local ->remote and upload options no longer present #825 
Can't upload new file from local to remote #823 
"Upload" option no longer shows in tree view #817
Panel showing on wrong side and can not sync local to remote #814
upload button? #808
*right click* ->Upload file missing? #804
Atom 1.17 - Upload/Download missing from context menu #801
cant upload #797 
Atom 1.17 update breaks repo #796
Can't find menu that "Sync local to remote" #795 
Where's the upload file option? #777
