### ISSUE TITLE
Config option for base directory

### ISSUE THREAD

**Issue by nickwest** [icetee/remote-ftp#80]
A new config option to set the base directory which would then be the base of the tree view instead of starting at root.

^ Primary feature request, Secondary suggestions v

Having the ability to navigate outside the base would be a plus. A right click context menu item on the base directory that lets you select any parent directory to be set as the new base directory would be great, or maybe just a set root as base option.

Then similarly a right click context menu on the child directories to set one of them as the new base would be the way to go in the opposite direction.

**Comment by grenierdev** [comment]
I do not really understand your first request. In the config file, you can specify a `remote` path to which is the remote-root path.

As for the secondary request, this package was created to have a way to browse remote files in-sync with the local files. And I'll probably just stick with this goal for now. Thank you for your suggestion.

**Comment by finkenmann** [comment]
Hmmm... sorry i’m an absolute newby, if i should open a new thread, please move this post. I have a similar wish like nickwest. I work mostely on Drupal Projects with many nested folders. 95% of the work is inside the Sass directory.
sites
- all
  - themes
    - mytheme
      - sass
        The tree of files and folders is very long, takes a lot of width from the cascading and is quite confusing. Before i had a similar workflow in Coda. The good in Coda is, if i double click a folder it opens and shows as root, the parent folders disapear. This keeps the structure of my working directory very clean. I know that i can choose in the ftp-settings the path to the directory i’m working in, but like i said, sometimes i have to switch up 3 or 4 levels, and if i declare the SASS directory as root, i dont have the possibility to move up. Is there a way to bring in the same functionality in your package like coda has? Double click opens the folder you click and shows as root, simple click on a triangle opens the folder like here. So i have always two possibilities how i wana jump around. To go back in coda, if i opend a directory by double click, there is on top of the tree a little pulldown, were i can flip up in the hierarchy. Sorry for my bad english, i hope you understand my wish ;-)

Thanks for your faboulos job you did already. After i found this package i quit Coda immediatly and i’m thrilled from Atom.

**Comment by wasikuss** [comment]
Take a look into https://atom.io/packages/temporary-root :)
