### ISSUE TITLE
Atom 1.17 - Upload/Download missing from context menu

### ISSUE THREAD

**Issue by tbugler** [icetee/remote-ftp#801]
After upgrading to Atom 1.17 I lost the FTP Upload/Download option in the context (right-click) option when in the Folder pane.

Win 10 / Atom 1.17

**Comment by John-C2** [comment]
I have the same issue on Mac.  Seems to be related to the overall problem referenced in #798 with Atom 1.17 breaking this plugin.  I downgraded temporarily to 1.16 to avoid the issue.

**Comment by ManuDevil** [comment]
Same here. No upload menu on 1.17...

**Comment by icetee** [comment]
@ManuDevil Check this #772

**Comment by vedtam** [comment]
same here unfortunately.

**Comment by tbugler** [comment]
This resolved my issue
https://github.com/mgrenier/remote-ftp/issues/796#issuecomment-302129404

**Comment by dikylung** [comment]
@tbugler comment, fix the issue for me
