### ISSUE TITLE
*right click* ->Upload file missing?

### ISSUE THREAD

**Issue by aawnu** [icetee/remote-ftp#804]
I can't upload images and stuff through this plugin anymore?

https://gyazo.com/e78255fc55998114177a0d4efc10692f

**Comment by andriy063** [comment]
Same problem in Atom version 1.17.0
Here is temporary solution https://github.com/mgrenier/remote-ftp/issues/796#issuecomment-302129404

**Comment by RonHolt** [comment]
Nice, just did the fix you linked to and it worked. Thanks!
