### ISSUE TITLE
Order side panel

### ISSUE THREAD

**Issue by AlienFX** [icetee/remote-ftp#805]
Hi @mgrenier 
Sorry to disturb you but since this morning my Remote-FTP panel is fixed on Left, and after I have my tree-view... Impossible to switch them position. I want tree-view, and after Remote-FTP. 

Please, can you tell me how can I change the position of them ? 
Thank you in advance !

![capture d ecran 2017-05-22 a 14 58 24](https://cloud.githubusercontent.com/assets/195319/26295969/25c552e6-3eff-11e7-9336-d3225a0c581e.png)

**Comment by UVLabs** [comment]
I was just about to post this also, I would rather if my FTP showed to the right of my working project @mgrenier

**Comment by spiskommg** [comment]
same issue, it also prevents me from uploading files on local machine to remote.

Could it be related to the recent Atom update that added the collapsible tab for the local tree view? i only noticed that last week for the first time.

**Comment by Zilus** [comment]
Confirmed.
Also happening

**Comment by nbdamian** [comment]
From what I can tell, this is caused by the latest update in Atom, changing the Tree-view to use a dock, instead of a panel. What needs to be done in the plugin is to use a dock as well.
When I have time, i'll look into this deeper.

**Comment by itayganor** [comment]
Same here!

**Comment by icetee** [comment]
Update Remote-FTP. 🔨
