### ISSUE TITLE
upload button?

### ISSUE THREAD

**Issue by GeneralCan** [icetee/remote-ftp#808]
hey, there used to be an upload option when you right clicked on a file, is that gone? how can we upload images and other media through this plugin? thanks

**Comment by ekfuhrmann** [comment]
I'm on Atom 1.18.0-beta0 and I too can no longer find the `upload` option within the context menu.

Just saw #804

**Comment by misterHippo** [comment]
Downloaded Atom (ver 1.17.1 x64) & Remote-ftp (0.10.7) today for the first time. No apparent way to upload file from context menus. :(

Download is there :) 

Should we assume it's coming back? (Based on the assumption it was there in the first place)

**Comment by Ekrynox** [comment]
Hello
To fix the problem, go to (.atom/packages/remote-ftp/menus) and open `remote-ftp.cson`
Then replace :
     line 3:   `'.tree-view.full-menu': [`   by   `'atom-text-editor, .tool-panel.tree-view .file':[`
     line 8:   `'.tree-view.multi-select': [`   by   `  '.tool-panel.tree-view .header.list-item':[`

Then just restart Atom.

**Comment by haa-jp** [comment]
Thanks, Ekrnox!
updating the remote-ftp.cson worked for me :D

**Comment by misterHippo** [comment]
Ah! I found that file yesterday, and was trying to work out what was wrong with it. I thought the reference may have been wrong.

Thanks for the fix :)

**Comment by ParkerD13** [comment]
Hey guys, unfortunately @Ekrynox 's workaround did not work for me. I got Atom 1.17.2 ia32 (Win7-64) and remote ftp 0.10.7. I just downloaded the actual git package (oddly enough 0.10.2) and switched the content of "remote-ftp.cson". Line No. 3 would probably have been enough, but I am on schedule and try it later.

**Comment by ParkerD13** [comment]
> ...Ekrynox 's workaround did not work for me...

The Error btw is described here: https://github.com/mgrenier/remote-ftp/issues/677

**Comment by ekfuhrmann** [comment]
@ParkerD13 The updated, working plugin can be downloaded from this repo in the current master branch. Just download the zip here, and replace your .atom/packages/Remote-FTP file with the zip you downloaded and it should be good after restarting Atom.

See https://github.com/mgrenier/remote-ftp/issues/796#issuecomment-303288019. Sounds like it should be updated in atom relatively soon as well.

**Comment by misterHippo** [comment]
@ParkerD13 
Just for reference, I tried the above and it worked. But I should point out that where he's used the word "by", he meant the word "to":

**line 3:** 
_Change_
'.tree-view.full-menu': [ 
_to_ 
'atom-text-editor, .tool-panel.tree-view .file':[

**line 8:** 
_Change_
'.tree-view.multi-select': [ 
_to_ 
'.tool-panel.tree-view .header.list-item':[

Give that a shot if you're still stuck.
