### ISSUE TITLE
Transfer ownership

### ISSUE THREAD

**Issue by grenierdev** [icetee/remote-ftp#813]
I feel it's a bit overdue as I haven't been working on this project for quite a while now. And honestly, it's been awhile since I haven't work with FTP/SFTP for my day to day job.

So I'd like to transfert this repo on someone else account. @jpxd, you seem to be the most active in this project. Would you like to take the ownership of the project ?

**Comment by jpxd** [comment]
@mgrenier Sorry, but I don't really use the plugin anymore on a regular basis and currently don't have spare time to actively maintain it...

**Comment by grenierdev** [comment]
@jimmaaay are you interested ?

**Comment by grenierdev** [comment]
@icetee welcome to the project.

**Comment by robhuska** [comment]
Yes!!! I'm so glad someone is going to take over maintaining this package! Thank you!

**Comment by icetee** [comment]
If you really want to pass it, I'd love to take it. @mgrenier

**Comment by ghost** [comment]
I'd say @icetee

**Comment by grenierdev** [comment]
The project will be transfered to @icetee. All I ask is that you mention the previous collaborators in the readme for future reference.

Thank you for your time and support !

**Comment by grenierdev** [comment]
@icetee, you'll need to remove your fork from your github account before I can transfer the project. Github wont allows me since you have a `remote-ftp` repo.

**Comment by icetee** [comment]
@mgrenier I removed. Thanks.

**Comment by icetee** [comment]
@mgrenier Do I have to say something on atom.io site?

**Comment by grenierdev** [comment]
I don't think you have to. The Atom Package Manager will most likely recognize you as the new owner.

Might be a good idea to post something on the forum to let the community know that remote-ftp is still in active development.

It's your show now :)
