### ISSUE TITLE
Panel showing on wrong side and can not sync local to remote

### ISSUE THREAD

**Issue by martin-wahlberg** [icetee/remote-ftp#814]
Panel showing on wrong side and can not sync local to remote. Can only sync the other way.

![image](https://cloud.githubusercontent.com/assets/26740919/26478642/e27c0cf6-41cd-11e7-9e1d-87bb9f7a20a3.png)

![image](https://cloud.githubusercontent.com/assets/26740919/26478651/ee33ea64-41cd-11e7-8232-36757b434d69.png)
![image](https://cloud.githubusercontent.com/assets/26740919/26478660/fc9a030e-41cd-11e7-87c0-750f7bb96a27.png)

**Comment by alecmanabat** [comment]
I am having this exact same problem as well

**Comment by edgardeloire** [comment]
Same problem with latest Atom version 1.17.2

**Comment by clonge** [comment]
Temporary solution:

https://github.com/mgrenier/remote-ftp/issues/796#issuecomment-302129404
