### ISSUE TITLE
autoconnect

### ISSUE THREAD

**Issue by jarvis-owl** [icetee/remote-ftp#816]
Hej,

I really like this package and use it often.
Is there any possibility to let atom/remote-ftp connect automatically, when a .ftpconfig containing folder/project is opened?

First world problems.

sincerely,
jarvis

**Comment by icetee** [comment]
If re-open project (has .ftpconfig) and save the file, then automatically upload file.
Press "Toogle" shortcuts [Ctrl + Alt + o] once. If re-opened projet, it must be there.

**Comment by rivorra** [comment]
Can this behavior do it per project? Instead of a general plug-in option
Best regards, 
Raúl.
