### ISSUE TITLE
"Upload" option no longer shows in tree view

### ISSUE THREAD

**Issue by AlbertMN** [icetee/remote-ftp#817]
The _Upload_ option when right-clicking a file / folder is gone for me.
I am using the latest version of the package and also the latest version of Atom (just grabbed from atom.io today)
![image](https://cloud.githubusercontent.com/assets/11600207/26559863/ab4d18e6-44b2-11e7-81e4-7abc63482891.png)

**Comment by mohdhazwan** [comment]
same here.

**Comment by kovendi** [comment]
same here.

**Comment by lundmorten** [comment]
Have you tried this temporary solution? https://github.com/mgrenier/remote-ftp/issues/796#issuecomment-302129404

**Comment by AlbertMN** [comment]
@lundmorten Thanks - works fine.

**Comment by ananurdiana** [comment]
Thank you @lundmorten , it's working...
