### ISSUE TITLE
Upload Notifications

### ISSUE THREAD

**Issue by robhuska** [icetee/remote-ftp#820]
So, since I upgraded from 0.10.5 to 0.10.7 I started getting notifications every time I saved a compiled file. I tried turning off the setting "Enable Transfer Notifications", but that did not work. Here is what I have been seeing.

<img width="2048" alt="notifications" src="https://cloud.githubusercontent.com/assets/2412155/26601102/a5482716-454c-11e7-9f79-b4f4696f12de.png">

To fix this I went in to the `lib/client.js` file and changed lines 61-67 from this:
```
          watcher
          .on('change', (path) => {
            self.watch.queueUpload.apply(self, [path]);
	    atom.notifications.addInfo('Remote FTP: Change detected in: '+ path, {
	      dismissable: false,
	    });
          });
```
to this:
```
          watcher
          .on('change', (path) => {
            self.watch.queueUpload.apply(self, [path]);
            if (atom.config.get('Remote-FTP.enableTransferNotifications')) {
	      atom.notifications.addInfo('Remote FTP: Change detected in: '+ path, {
	        dismissable: false,
	      });
            }
          });
```
This now allows the Transfer Notifications setting to turn them off. If this was not the intent of that setting can someone let me know? And if it was, can someone else help to get this code pushed to this plugin? I am relatively new to the git pull request stuff.

I know that the developer is not actively working on this anymore, I have been following along with the other few bugs that have cropped up since Atom 1.17 was released. Thanks!

**Comment by robhuska** [comment]
Ok, so I believe I actually did it right this time... I found that the setting I was messing with is not for those watch notifications. They are for something else (though they don't seem to work anyway...but that's a different issue that I am not as concerned with).

What I now did to disable this was created a new setting in the `lib/config-schema.json`:
```
  "enableWatchFileChangeNotifications":{
    "type":"boolean",
    "default":false
  }
```

Then in the `lib/client.js` I changed the if statement that I added from my last comment here to this:
```
          watcher
          .on('change', (path) => {
            self.watch.queueUpload.apply(self, [path]);
            if (atom.config.get('Remote-FTP.enableWatchFileChangeNotifications')) {
	      atom.notifications.addInfo('Remote FTP: Change detected in: '+ path, {
	        dismissable: false,
	      });
            }
          });
```

Now, could I get someones assistance to get this code pushed to the plugin?

**Comment by icetee** [comment]
@robhuska  If you have time, can you test it?
If it's okay, it can be closed.

**Comment by robhuska** [comment]
Sure, I assume I need to pull the pr branch to test this?

**Comment by icetee** [comment]
Yes!

```
git clone https://github.com/mgrenier/remote-ftp
cd remote-ftp
git fetch
git checkout pr
apm link --dev .
atom --dev
```

**Comment by robhuska** [comment]
Yep the new watch file toggle works. I also like how you reconfigured the settings file. Just a heads up, in the pr branch you have Enable Dock Integration twice.

**Comment by icetee** [comment]
I think it has to delete the old Remote-FTP configuration. (File > Config)

**Comment by robhuska** [comment]
Is that something that I will need to do on my local, or is that something that you will take care of in the repo? Thanks again for integrating this, and for taking over the maintenance of this package. It was long over due for some updates! Good work @icetee.

**Comment by icetee** [comment]
Yep.
Open "global" `~/.atom/config.cson` in local config and delete oldschool Remote-FTP specifics settings.
Unfortunately only manual. I do not think it can be automated.
