### ISSUE TITLE
Can't upload new file from local to remote

### ISSUE THREAD

**Issue by ananurdiana** [icetee/remote-ftp#823]
Hello,

I'm using remote-ftp on my atom to work between my pc and my development server. But now I can't upload new file from my pc to my development server. **Sync local --> remote** menu doesn't appear.

Please advice.

Thank you.
![2017-06-01 11_47_15-project j__dev_nodejs_ea atom](https://cloud.githubusercontent.com/assets/8108244/26664956/230a185c-46c0-11e7-95a4-181de1d05eba.png)

**Comment by kctteam** [comment]
+1 Upload / download doesn't appear.

**Comment by clonge** [comment]
+1 same here

**Comment by clonge** [comment]
Temporary solution:

https://github.com/mgrenier/remote-ftp/issues/796#issuecomment-302129404

**Comment by ananurdiana** [comment]
Thank you @HenchmenMedia ,
