### ISSUE TITLE
Is Totally Borked. until i reinstalled. also hide remote view doesn't work 

### ISSUE THREAD

**Issue by KrissiBT** [icetee/remote-ftp#824]
not sure what the issue was.
suddenly it started to no refresh the remote dir. tried making a new atom instance of the project folder.
anyways yea i reinstalled. now it works 
also i cant hide the remote view tab..... the button does nothing.
anyway thanks for a great tool 👍

**Comment by venatiodecorus** [comment]
I'm on Atom 1.17.2 on macOS Sierra 10.12.4. I installed the plugin and created a new project and tried to toggle open the panel and nothing was happening, but no errors or anything in the console. So I removed the version installed through apm and checked out the dev branch, and that seems to be working now. Figured I'd just let you know, fyi.

**Comment by AnndreaJ** [comment]
The same thing is happening to me. @venatiodecorus can you explain what you mean when you say "checked out the dev branch" I'm a few months into coding and don't quite understand how that works. I have also removed the apm version but I still need to connect to FTP obviously.

**Comment by venatiodecorus** [comment]
@AnndreaJ I removed the Remote-FTP plugin via the Atom settings interface, then went to ~/.atom/packages and used git to clone the repo from there, and switched it over to the dev branch.

```
cd ~/.atom/packages
git clone https://github.com/mgrenier/remote-ftp.git
git checkout dev
```
You'll need to have git installed obviously.

**Comment by AnndreaJ** [comment]
Oh, okay I'm with you. Thanks Mate

**Comment by icetee** [comment]
Please check new Remote-FTP [version](https://github.com/mgrenier/remote-ftp/releases/tag/v1.0.0).
Reproducible the new version?

**Comment by icetee** [comment]
Related of #839
