### ISSUE TITLE
.ftpignore not working

### ISSUE THREAD

**Issue by Gregorianpics** [icetee/remote-ftp#826]
I tried with .ftpignore, that .ftpconfig was ignored for the upload to the server. It didn't really work. I filled it in correctly in the .ftpignore but it was still uploaded on my server. That's a big bug of security, as the FTP connection details are uploaded to the server an any person could get them and abuse them.

**Comment by icetee** [comment]
Hi, thanks for report issue.
In theory complete since 1.1.0 version #875, if it did not succeed your issue, I re-open it.
