### ISSUE TITLE
text file busy after creating a script using this tool

### ISSUE THREAD

**Issue by MZLAKg2aGGFs8yi** [icetee/remote-ftp#828]
after creating a script on the server using this tool, modifying the script, save and exit, chmod, it appears a Text file busy error and cannot run.

**Comment by icetee** [comment]
Hi,

check the .ftpconfig file.

> "filePermissions":"0644" // string - Permissions for uploaded files. WARNING: if this option is set, previously set permissions on the remote are overwritten!

I think takes executable. After modified set `chmod +x SCRIPTNAME.sh` but, uncomfortable.
