### ISSUE TITLE
Randomly ignores "upload on save"

### ISSUE THREAD

**Issue by timothymarois** [icetee/remote-ftp#833]
Occasionally I'll be saving files, and will notice no changes to the FTP. I'll toggle it back on, and notice the upload status is not pushing the file when it is saved. I have to "disconnect" then "reconnect" for it to resolve its issue. I usually switch between projects in multiple Atom windows, and that may have some effect to it, but it is annoying not knowing which file did not make it to the FTP.

**Comment by fransstudio2** [comment]
Same problem with me. I usually just press ctrl-alt-c to just "connect" again and then save again.

**Comment by icetee** [comment]
@timothymarois Maybe related timeout issue? #591

**Comment by timothymarois** [comment]
Yeah I believe this could be a timeout issue. It happens when I minimize for a bit and go back, and I also noticed when I flip between projects and open up other ftps, sometimes it unreliable as it may timeout and not save anymore either. I'll close this for now. But wish it would reconnet once I save CTRL+S should also reconnect if FTP exist for the "on-save" method. That would really help just incase its disconnected have a fallback.
