### ISSUE TITLE
FTPS/SFTP with Azure Web app and eclipse plugin

### ISSUE THREAD

**Issue by joysjoseph** [icetee/remote-ftp#835]
HI,
We are trying to use Eclipse Azure plugin for Developing/deploying  a java Web App/web service on azure. The  Azure web app( contains a java REST web services), running/deployed on Tomcat 8.
Issue:
We are not able to deploy from Eclipse with SFTP/FTPS.
As per the logs/alerts , it seems the SFTP/FTPS is not running on port 22 of the Web app.
But regular FTP is working and able to connect with port 21 of the web app.

How will we enable/configure the SFTP for the web App?
Eclipse plugin will allow Deployment with SFTP/FTPS?

**Comment by icetee** [comment]
If you use Eclipse, you should not be doing that much. Try [this](https://bugs.eclipse.org/bugs/).

If you have an Atom editor and Remote-FTP plugin, try generate SFTP config file. No use simple FTP config.
