### ISSUE TITLE
New version is Updated, not working..!

### ISSUE THREAD

**Issue by krkmzugur** [icetee/remote-ftp#837]
New version is Updated, not working..! Version 1.

**Comment by icetee** [comment]
What is the experience?
You use MacOS? #802
Have a log the console?

**Comment by krkmzugur** [comment]
I'm using the Atom editor. The error I get is the following Remote FTP: page-contact.php could not upload. I am using Windows 10 operating system. This version has been updated.

**Comment by krkmzugur** [comment]
How do I manually install the old version. ?

**Comment by krkmzugur** [comment]
Ctrl + S keyboard on , this error show

 Uncaught TypeError: atom.workspace.getActivePaneItem(...).getFileName is not a function

It's very uncomfortable. If you have any knowledge about the solution, please be glad if it helps.

**Comment by KenoLeon** [comment]
@krkmzugur : New version broke both My windows and Mac Atom installs. I did a[ clean reinstall of atom](https://discuss.atom.io/t/how-to-completely-uninstall-atom-from-windows/17338/5) last night on windows 10 and that solved it for me, on OS X uninstalling just the package (as opposed to atom itself) and reinstalling seems to work.

**Comment by icetee** [comment]
> How do I manually install the old version. ?

Commands:
```
apm remove remote-ftp
apm install remote-ftp@0.10.7
```

**Comment by krkmzugur** [comment]
Thanks. Atom re-uninstalling now, works.
