### ISSUE TITLE
I get a bug message after update all Atom.

### ISSUE THREAD

**Issue by conghieu711** [icetee/remote-ftp#838]
https://screenshot.net/7012wtl
----------------
Remote-FTP 1.0.0

binding@unknown – Cannot find module '/Users/hieuhuynh/.atom/packages/Remote-FTP/node_modules/fsevents/lib/binding'
binding@unknown – Cannot find module '/Users/hieuhuynh/.atom/packages/Remote-FTP/node_modules/fsevents/lib/binding'
binding@unknown – Cannot find module '/Users/hieuhuynh/.atom/packages/Remote-FTP/node_modules/fsevents/lib/binding'
binding@unknown – Cannot find module '/Users/hieuhuynh/.atom/packages/Remote-FTP/node_modules/fsevents/lib/binding'
binding@unknown – Cannot find module '/Users/hieuhuynh/.atom/packages/Remote-FTP/node_modules/fsevents/lib/binding'
binding@unknown – Cannot find module '/Users/hieuhuynh/.atom/packages/Remote-FTP/node_modules/fsevents/lib/binding'

**Comment by icetee** [comment]
Duplicate #802
