### ISSUE TITLE
Plugin doesn't do anything anymore

### ISSUE THREAD

**Issue by ghost** [icetee/remote-ftp#839]
Atom version: 1.17.0
MacOS version: 10.12.5
Current Remote-FTP version: 1.0.0

I updated from Remote-FTP version 0.10.7 (wich worked) to Remote-FTP version 1.0.0 since I saw it supported the new Atom Dock (From Atom version: 1.16.0). However, the plugin doesn't work anymore.

It doesn't toggle, it doesn't create a new (S)FTP config file in a project. 

I have tried several times by reinstalling the plugin, restarting Atom, restarting macOS, but won't work. Problem is reproducible.

I have tried the (possible) solution provided here: https://github.com/mgrenier/remote-ftp/issues/824#issuecomment-306384144, but that doesn't work.

**Comment by kevit-development** [comment]
I have fixed this issue for myself, I downloaded the 0.10.7 release from GitHub (.zip), placed these files in ~/.atom/packages/RemoteFTP, but it gave me a error "FS-plus" module not found (something like that). So, I updated it to 1.0.0 trough Atom's package updater and replaced all files in ~/.atom/packages with the files from 0.10.7.

Now it works.

**Comment by icetee** [comment]
Write something on the dev tool?
`View > Developer > Toogle Developer tool`

And please check "incompatible-packages". #802

I check MacOS 10.12 and Atom 1.17.2, it works.

**Comment by ghost** [comment]
```
Failed to require the main module of 'Remote-FTP' because it requires one or more incompatible native modules (binding, binding, binding, binding, binding, binding).
Run `apm rebuild` in the package directory and restart Atom to resolve.
```
Thrown in `events.js:110` `listeners[i].call(self, arg1);`


Possible duplicate of https://github.com/mgrenier/remote-ftp/issues/802

**Comment by icetee** [comment]
> I have fixed this issue for myself, I downloaded the 0.10.7 release from GitHub (https://github.com/mgrenier/remote-ftp/archive/v0.10.7.zip), placed these files in ~/.atom/packages/RemoteFTP, but it gave me a error "FS-plus" module not found (something like that). So, I updated it to 1.0.0 trough Atom's package updater and replaced all files in ~/.atom/packages with the files from 0.10.7.

You must specify such a command: `npm install` (Missing node_modules folder)

**Comment by ghost** [comment]
>> I have fixed this issue for myself, I downloaded the 0.10.7 release from GitHub (https://github.com/mgrenier/remote-ftp/archive/v0.10.7.zip), placed these files in ~/.atom/packages/RemoteFTP, but it gave me a error "FS-plus" module not found (something like that). So, I updated it to 1.0.0 trough Atom's package updater and replaced all files in ~/.atom/packages with the files from 0.10.7.

> You must specify such a command: npm install (Missing node_modules folder)

This is a dirty fix. Fresh install of 1.0.0 gives https://github.com/mgrenier/remote-ftp/issues/839#issuecomment-309367553.

Incompatible-packages gives:
```
Remote-FTP 1.0.0
binding@unknown – Cannot find module '/Users/kevin/.atom/packages/Remote-FTP/node_modules/fsevents/lib/binding'
binding@unknown – Cannot find module '/Users/kevin/.atom/packages/Remote-FTP/node_modules/fsevents/lib/binding'
binding@unknown – Cannot find module '/Users/kevin/.atom/packages/Remote-FTP/node_modules/fsevents/lib/binding'
binding@unknown – Cannot find module '/Users/kevin/.atom/packages/Remote-FTP/node_modules/fsevents/lib/binding'
binding@unknown – Cannot find module '/Users/kevin/.atom/packages/Remote-FTP/node_modules/fsevents/lib/binding'
binding@unknown – Cannot find module '/Users/kevin/.atom/packages/Remote-FTP/node_modules/fsevents/lib/binding'
```

**Comment by icetee** [comment]
It must be rebuilt this package, because changes dependencies, which requires the build. This is not necessarily the fault of the code.

For me, Atom immediately offered this opportunity in editor. (Incompatible-packages view)

If it fails command `apm rebuild` try remove node_modules folder:
`rm -rf ~/.atom/packages/Remote-FTP/node_modules`

**Comment by conghieu711** [comment]
Thank you so much, it work for me ;)

**Comment by ghost** [comment]
> It must be rebuilt this package, because changes dependencies, which requires the build. This is not necessarily the fault of the code.
For me, Atom immediately offered this opportunity in editor. (Incompatible-packages view)

Worked!

**Comment by liammac** [comment]
Atom version: 1.18.0
MacOS version: 10.12.5
Current Remote-FTP version: 1.0.0

Solution is not working here.

apm rebuild doesn't actually appear to do anything but also throws no errors, Incompatible-packages displays the same 
`Remote-FTP 1.0.0

binding@unknown – Cannot find module '/Users/lmacinnes/.atom/packages/Remote-FTP/node_modules/fsevents/lib/binding'
binding@unknown – Cannot find module '/Users/lmacinnes/.atom/packages/Remote-FTP/node_modules/fsevents/lib/binding'
binding@unknown – Cannot find module '/Users/lmacinnes/.atom/packages/Remote-FTP/node_modules/fsevents/lib/binding'
binding@unknown – Cannot find module '/Users/lmacinnes/.atom/packages/Remote-FTP/node_modules/fsevents/lib/binding'
binding@unknown – Cannot find module '/Users/lmacinnes/.atom/packages/Remote-FTP/node_modules/fsevents/lib/binding'
binding@unknown – Cannot find module '/Users/lmacinnes/.atom/packages/Remote-FTP/node_modules/fsevents/lib/binding'`

but does not present a rebuild button

**Comment by reneruiz** [comment]
I tried apm rebuild with makes Incompatible-Packages to report success, but now I get this error:

[Enter steps to reproduce:]

1. Start Atom
2. That's it.

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 1.0.0


### Stack Trace

Failed to load the Remote-FTP package

```
At Cannot find module 'fs-plus'

Error: Cannot find module 'fs-plus'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/Remote-FTP/lib/remote-ftp.js:11:15)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:887:35)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:158:34
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app/src/package.js:144:18)
    at PackageManager.module.exports.PackageManager.loadAvailablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:565:22)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:479:25
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app/src/config.js:321:22)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:473:25)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:812:34
```

**Comment by icetee** [comment]
@reneruiz If cannot find, then wrong installed. Try re-install.

**Comment by reneruiz** [comment]
Re-install fixed it. 👍

**Comment by Meloncon** [comment]
I can't seem to get the 

```
Failed to require the main module of 'Remote-FTP' because it requires one or more incompatible native modules (binding, binding, binding, binding, binding, binding).
Run `apm rebuild` in the package directory and restart Atom to resolve.
```

message to go away, even with the above suggestions. (apm rebuild in package directory, blowing away node_modules directory, etc.) I've also tried uninstalling and reinstalling Remote-FTP with no luck. Same message every time in developer console. Package simply isn't working for me right now. Any other ideas anyone? Thanks and let me know if you'd like any additional info!

Additional Info: macOS Sierra 10.12.5 with Atom 1.18.0 x64

**Comment by icetee** [comment]
@Meloncon try this
```
apm remove remote-ftp
apm install remote-ftp
```

**Comment by Meloncon** [comment]
Thanks @icetee for the suggestion. However, it didn't seem to help. Same error message as before. :(

**Comment by icetee** [comment]
[Did you try that?](https://github.com/mgrenier/remote-ftp/issues/839#issuecomment-309371225)

**Comment by shelbyKiraM** [comment]
Still getting

    Failed to require the main module of 'Remote-FTP' because it requires one or more incompatible native modules (binding, binding, binding, binding, binding, binding).
    Run `apm rebuild` in the package directory and restart Atom to resolve.

I've tried leaving Atom open and running (in the Remote_Ftp dir) `rm -rf node_modules`, `apm rebuild`. It didn't work but I didn't look for the error.

Quit Atom, ran `apm remove remote-ftp`, `app install remote-ftp`. Restarted and checked the console and got above error. Ran `app rebuild`. Same error. `rm-rf node_modules` and `app rebuild`. `node_modules` folder didn't come back. Quit and restart, same error but still no node_modules folder. 
On macOS 10.11.6

Still not working across reboot but `node_modules` folder came back.

**Comment by mohammedhammoud** [comment]
I've tried all of the above "solutions". I'm still getting:
```
Failed to require the main module of 'Remote-FTP' because it requires one or more incompatible native modules (binding, binding, binding, binding, binding, binding).
Run `apm rebuild` in the package directory and restart Atom to resolve
```

**Comment by icetee** [comment]
@blacRose @iktw @nicolasroger17

Have you seen the original solution?
https://github.com/icetee/remote-ftp/issues/839#issuecomment-309366257

If it does not work then try it `apm rebuild-module-cache`

**Comment by nicolasroger17** [comment]
Just tried it. Still no.

**Comment by icetee** [comment]
> Just tried it. Still no.

Can I look at Team Viewer?
(Email address in my profile)

**Comment by nicolasroger17** [comment]
It's my work laptop, I don't have the permission to do that sorry.
I can give you more logs if you tell me how to get to them.

**Comment by icetee** [comment]
Please try this
`CMD + Shift + P (Commad palette)` and type `Incompatible packages` and try to there build again.

It worked with me originally in macOS.

**Comment by nicolasroger17** [comment]
```

Incompatible Packages
Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.Rebuild Packages
Package Settings
Remote-FTP 1.1.1

binding@unknown – Cannot find module '/Users/blabla/.atom/packages/Remote-FTP/node_modules/fsevents/lib/binding'
binding@unknown – Cannot find module '/Users/blabla/.atom/packages/Remote-FTP/node_modules/fsevents/lib/binding'
binding@unknown – Cannot find module '/Users/blabla/.atom/packages/Remote-FTP/node_modules/fsevents/lib/binding'
binding@unknown – Cannot find module '/Users/blabla/.atom/packages/Remote-FTP/node_modules/fsevents/lib/binding'
binding@unknown – Cannot find module '/Users/blabla/.atom/packages/Remote-FTP/node_modules/fsevents/lib/binding'
binding@unknown – Cannot find module '/Users/blabla/.atom/packages/Remote-FTP/node_modules/fsevents/lib/binding'
```

**Comment by icetee** [comment]
There is a rebuild button there. Try it when done you will have a restart button.

**Comment by nicolasroger17** [comment]
Now it's throwing when I launch atom.

```js
Error: Cannot find module 'fs-plus'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/Users/nicolas/.atom/packages/Remote-FTP/lib/remote-ftp.js:11:15)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:887:35)
```

**Comment by icetee** [comment]
Okay, now the `node_modules` folder is missing / deficient.
```
apm uninstall remote-ftp
apm install remote-ftp
```

**Comment by nicolasroger17** [comment]
Sweet. It's working now. Thx.

**Comment by icetee** [comment]
> Sweet. It's working now. Thx.

Cheers!

**Comment by shelbyKiraM** [comment]
`Shift-Command-P`, `Incompatible Packages`, and `Rebuild Packages` worked for me, too. Many thanks from the ice cream gallery.

**Comment by icetee** [comment]
I close this issue. The 2.0.0 version supported Atom Filesystem Watcher. No need for `chokidar` package.
