### ISSUE TITLE
 How do I get the FTP Remote window to the right?

### ISSUE THREAD

**Issue by sametsirinel** [icetee/remote-ftp#841]
I am quite used to having the panel on the right side, so what should I do in order for the panel to be on the right side? I searched quite a bit but I could not get a result, please help.

**Comment by icetee** [comment]
`Settings > Packages > Remote-FTP > Settings button` check Dock integration and move "Remote-FTP" tab to right side. CSS design is still to be expected.

**Comment by sametsirinel** [comment]
https://i.hizliresim.com/RPB5BG.png i cant see

**Comment by icetee** [comment]
> https://i.hizliresim.com/RPB5BG.png i cant see

Last option "Use New Dock Integration"

**Comment by sametsirinel** [comment]
this is not working. now not open connecting window

**Comment by icetee** [comment]
What version do you use (Atom)?

**Comment by sametsirinel** [comment]
i dont know but i think so last version , because i was install last night

**Comment by sametsirinel** [comment]
if you want to come my pc , and try your self with teamweaver

**Comment by icetee** [comment]
oke

**Comment by icetee** [comment]
This option adds new pane to the existing dock for the tree view. Maybe dock hide? Move the cursor left side and click the arrow.

**Comment by sametsirinel** [comment]
check your mail pls

**Comment by icetee** [comment]
htomy92@gmail.com

**Comment by sametsirinel** [comment]
Ty for help
