### ISSUE TITLE
watch ain't working

### ISSUE THREAD

**Issue by babakzarrinbal** [icetee/remote-ftp#844]
i've tried every possible path to file or the directory 
after auto compiling of less file , css file won't get uploaded

keep up the good work ...

**Comment by robertluedke** [comment]
If you're using Windows and you have a path like "./dev/less/", then remove the dot to get "/dev/less/" and it should work again. :)

**Comment by icetee** [comment]
Change this [line](https://github.com/mgrenier/remote-ftp/commit/0074a1b8ad1aab91c3172a9664a5d9ee47b132f4) or wait for new release 🙊
