### ISSUE TITLE
Using "env" for "agent" in .ftpconfig doesn't seem documented

### ISSUE THREAD

**Issue by BenKennish** [icetee/remote-ftp#849]
I found out through reading one of these GitHub issues that it's possible to use the string "env" for "agent" in .ftpconfig and it then seems to take the path for the ssh-agent UNIX socket from the SSH_AUTH_SOCK environment variable.

However, I can't see this in the documentation so perhaps this should be noted somewhere prominent.

Cheers, Ben

**Comment by icetee** [comment]
Maybe you could send a pull request for this?

**Comment by zlibra** [comment]
Hey,
I have made a pull request (https://github.com/icetee/remote-ftp/pull/911) for this.

**Comment by icetee** [comment]
Thanks @zlibra
