### ISSUE TITLE
Remote FTP: Could not get project path

### ISSUE THREAD

**Issue by linky00** [icetee/remote-ftp#860]
Get this error every time it starts up. 
![image](https://user-images.githubusercontent.com/17803813/27654345-daa13e26-5c39-11e7-9ac5-aa0e6a227f75.png)
Not really sure where to check the 'logs'; could anyone point me in the right direction?

**Comment by icetee** [comment]
Disable Multiple hosts in settings view. It does not really work with me.

**Comment by linky00** [comment]
I... well, I kinda need it. I have multiple hosts. And it still works perfectly well, it's just that weird message.

**Comment by icetee** [comment]
I'll check.

**Comment by linky00** [comment]
Don't worry too much about it if there are more pressing issues, it still works correctly, it's just that error message that says to report it.

**Comment by jprusik** [comment]
I get this error if I open a new window (with no files or folders), or if I'm restoring to a state with no folders loaded (Multiple Hosts is set to false). Basically, it looks like this error will also show up if atom gets into a state where the project tab has no contents:
![remote ftp error](https://user-images.githubusercontent.com/1556494/33966527-e1d4b588-e02d-11e7-8d24-881d3450f57a.PNG)

**Comment by icetee** [comment]
@jprusik yes, I have this at the new Atom. I'll fix it soon.
