### ISSUE TITLE
Uncaught Error: Remote FTP: getConfigPath returned false, but expected a string

### ISSUE THREAD

**Issue by NetRally** [icetee/remote-ftp#864]
[Enter steps to reproduce:]

0. When Atom starts, all is functionally. Then:
1. Open new window
2. Connect to remote FTP

Edit: Remote FTP works only with previous Project only, unable to connect when new created

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [Remote-FTP](https://github.com/mgrenier/remote-ftp) package 1.0.0

### Stack Trace

Uncaught Error: Remote FTP: getConfigPath returned false, but expected a string

```
At C:\Users\Andrew\.atom\packages\Remote-FTP\lib\client.js:122

Error: Remote FTP: getConfigPath returned false, but expected a string
    at Client.readConfig (/packages/remote-ftp/lib/client.js:122:47)
    at /packages/remote-ftp/lib/views/tree-view.js:212:30)
    at HTMLDivElement.dispatch (/packages/project-manager/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/project-manager/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -1:03.9.0 remote-ftp:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.3 
atom-bootstrap3 1.2.12 
autoclose-html 0.23.0 
laravel 0.7.1 
project-manager 3.3.5 
Remote-FTP 1.0.0 
```

**Comment by icetee** [comment]
Related #621
