### ISSUE TITLE
FTP panel no long loads

### ISSUE THREAD

**Issue by ShawnFuller** [icetee/remote-ftp#871]
I updated my packages:
Remote-FTP
busys-signal
color-picker
docblockr
git-plus
intentions
linter
linter-php
linter-ui-default
simple-drag-drop-text

The developer console displays the following message:
Failed to require the main module of 'Remote-FTP' because it requires one or more incompatible native modules (binding, binding, binding, binding, binding, binding).
Run `apm rebuild` in the package directory and restart Atom to resolve.

**Comment by armantaherian** [comment]
Same here after update to 1.18.0.

**Comment by icetee** [comment]
Please check #839 issue.
