### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by darkogerguric** [icetee/remote-ftp#874]
Is there any way to disable timeout?
Host claims that server is not cutting connection, but after few minutes need to restart connection to get edits uploaded.

**Comment by icetee** [comment]
Hi, check [this](https://github.com/icetee/remote-ftp/commit/38988053434e484563d4e5c050e7272693d8816f) commit and `lib/client.js`, `lib/connectors/ftp.js` changes. Or wait for new release. Expected this week!

**Comment by darkogerguric** [comment]
Thank you, I will wait for update, feels more safe!
