### ISSUE TITLE
v 1.1.0 Transfer issue : Failed to change directory

### ISSUE THREAD

**Issue by Jozzeh** [icetee/remote-ftp#876]
Remote FTP version 1.1.0 -- OS : Windows 10 -- Connection type : FTP

_(note: this probably affects sftp as well)_  
When clicking a file in the remote pane, there is always an error notification that pops up in Atom which reads:

> Remote FTP: Connection failed
> 550 Failed to change directory.

I have investigated and the error is triggered in the client.js file around line 531... 
`self.connector.on('response', ......`

When a file is double-clicked in the 'remote pane', the get-function is called in ftp.js .    
The first thing the get-function tries, is to cwd the path ( see line 167 and after in ftp.js ).  
This fails because it is a file and not a directory --> leads to  --> response emit 550 Failed to change directory.  

After the error, it goes to the root directory and then downloads the file locally.   
**So except for an error notification when downloading a file, everything works.**

## **Quick fix**  
I have temporary made a change to client.js line 532 to suppress the error notification : 

`if (code === 550 && !/No such file or directory/.test(text) && !/Failed to change directory/.test(text)) {`

Although this is probably not the best way to go if anyone else is experiencing this issue, this could be a quick fix .   

A better solution would be to somehow detect if the path has a filename at the end and skip the first cwd directly to the file.

**Comment by Jozzeh** [comment]
**Update**  : Just tested on SFTP connection, and this issue is not an issue on SFTP connections .

**Comment by icetee** [comment]
> Update : Just tested on SFTP connection, and this issue is not an issue on SFTP connections .

SFTP is an encrypted protocol. You can not see communication. ;)

**Comment by konhasaurusrex** [comment]
The hot-fix that worked for me was, adding this to rule 532:
`!/Can't change directory to/.test(text)`

PS. this is not a bug, just bad testing.
