### ISSUE TITLE
Add folder does not work

### ISSUE THREAD

**Issue by Jozzeh** [icetee/remote-ftp#877]
Remote FTP version 1.1.0 -- Local OS : Windows 10 -- Connection type : FTP -- Remote OS : Linux

Test 1. When creating a new folder (right mouse click a folder in the remote panel -> add folder) , the folder is not created on the remote.  (no error or success notifications, no special console logs)

Test 2. Create a folder locally, right click it, and choose 'Upload' leads to a success notification, but does not create the folder on the remote server. 

Test 3. --> Create a file in the local folder and choose to upload the file. This results in an error notification 'could not upload' and the console logs : 553 Could not create file

**EDIT**   
**This issue is only on FTP connections. On SFTP-connections, all 'tests' above succeed at what they should do.**

**Comment by aaronvalavi** [comment]
I faced to the same situation. Surprisingly, it works for some directories and not for the others. The problem started after upgrading to v1.1.0

**Comment by icetee** [comment]
Is the new version solved the problem?

**Comment by aaronvalavi** [comment]
Thanks Icetee. Yes, once I updated that to v1.1.1, it worked with no problem. Today, I updated it to 1.1.2 and it works great. Thanks a lot.
Still don't know where the problem was.

**Comment by icetee** [comment]
It was a wrong condition :confused:
Thanks for answer!
