### ISSUE TITLE
[Feature Request] .ftpconfig directory listing options

### ISSUE THREAD

**Issue by PhilsLab** [icetee/remote-ftp#879]
I am unable to edit files like `.htaccess` as they are not listed via FTP connection.

My feature request intends to add an option to .ftpconfig like:
`"directoryListingOptions": "-la",`

**Comment by icetee** [comment]
You should also see the hidden files! Is the path good?

**Comment by icetee** [comment]
Settings View > Remote-FTP > Set on the **Show hidden files**
