### ISSUE TITLE
"Hide Local When Displayed" is displayed twice in settings

### ISSUE THREAD

**Issue by ThomasOrlita** [icetee/remote-ftp#881]
![remote-ftp-bug](https://user-images.githubusercontent.com/17808846/27866581-42921124-6197-11e7-9be0-0e5702b440bf.png)

**Comment by icetee** [comment]
Read changes #875.

> **Renewed configuration**
> The biggest change is perhaps a the configuration file was completely renewed. It is necessary to delete the previous configuration settings in ~/.atom/config.cson. (Only Remote-FTP specific settings.)
> 
> Sorry, keep up with the times.

Check your configuration file!
