### ISSUE TITLE
Problem with directory creation after the latest update to version 1.1.0

### ISSUE THREAD

**Issue by aaronvalavi** [icetee/remote-ftp#884]
I continuously receive a "Timeout" error. I even increased the time in the config file. But, some directories upload to destination and surprisingly some others do not. As well, sync to remote did not worked.
I could not find any error log or any logic explanation. All the files and directories access permissions and ownerships are OK.

**Comment by icetee** [comment]
Is the latest version also defective?

What type of "timeout"?

**Comment by aaronvalavi** [comment]
It's been fixed in 1.1.1
Thanks
