### ISSUE TITLE
Delete File with Same Name As Folder Breaks Sub-Files

### ISSUE THREAD

**Issue by lgiancol** [icetee/remote-ftp#888]
Hi, I found an issue when creating a file, deleting it, creating a folder, then trying to open a file within that folder.  If you create a file called, "test" but realize you meant to create a folder so you delete it, then create a folder called, "test" and make a file inside of that folder and try to open it, it provides an, "Uncaught Error: EExist: file already exists" error.  I realize the image shows it's out of date but even after updating it this still occurs.

![image](https://user-images.githubusercontent.com/17090716/27911141-fa324338-6225-11e7-9906-912a95fe0850.png)

EDIT: To fix this I had to delete the original file I created locally and then it opened the file in the folder!

**Comment by icetee** [comment]
Thanks for report, but duplicate. Soon it will be focused.
Related #112
