### ISSUE TITLE
Failed to require - version 1.1

### ISSUE THREAD

**Issue by nicolasroger17** [icetee/remote-ftp#892]
Hey, I'm getting this error in the console.
Failed to require the main module of 'Remote-FTP' because it requires one or more incompatible native modules (binding, binding, binding, binding, binding, binding).
Run `apm rebuild` in the package directory and restart Atom to resolve.

I tried to run `apm rebuild` and restart but it did not fix it.

**Comment by nicolasroger17** [comment]
I'm on atom 1.18.0.

**Comment by icetee** [comment]
Did they have that? #839

**Comment by nicolasroger17** [comment]
Hey.
I just uninstalled and reinstalled it.
Then I tried removing `node_modules` and ran `apm rebuild`.
Restarted atom, but the problem is still there.

**Comment by icetee** [comment]
Let's continue to the original issue. #839
