### ISSUE TITLE
Dock integration looks broken for version >= 1.1.1

### ISSUE THREAD

**Issue by Akimkin** [icetee/remote-ftp#893]
After update from 1.1.0 to 1.1.1 (and 1.1.2 afterwards) "Use New Dock Integration" setting is not respected anymore, FTP view is always displayed as an "old-style" panel.

Atom version is 1.18.0, Linux x64.

**Comment by icetee** [comment]
Did not affect the changes. Try re-install and check devtools. Error will be elsewhere.

**Comment by Akimkin** [comment]
Tried reinstalling, restarting atom and both of those (like deleting a package, restarting Atom & installing package again). Console contains no error messages, but FTP view is still shown via `<atom-panel>` instead of `<atom-dock>`. Any specific stuff to check where error can occur?

**Comment by Akimkin** [comment]
**Update:** complete removal of the "Remote-FTP" section from my `~/.atom/config.cson` resolved the issue for me. The content I had in this section before editing was:
`  "Remote-FTP":`
`    beta: {}`
`    notifications: {}`
`    useNewDockIntegration: true`

Sorry, I probably had some config problem during package update.

**Comment by icetee** [comment]
All right. Thanks for signaling! 😃
