### ISSUE TITLE
Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.

### ISSUE THREAD

**Issue by titan-rmiller** [icetee/remote-ftp#895]
For Remote-FTP 1.1.2 I now have the error: "Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom." This is causing me to be unable to use Remote-FTP at all. Is there anyone that knows what is causing this or how to fix it?

binding@unknown – Cannot find module '/Users/twms2/.atom/packages/Remote-FTP/node_modules/fsevents/lib/binding'
binding@unknown – Cannot find module '/Users/twms2/.atom/packages/Remote-FTP/node_modules/fsevents/lib/binding'
binding@unknown – Cannot find module '/Users/twms2/.atom/packages/Remote-FTP/node_modules/fsevents/lib/binding'
binding@unknown – Cannot find module '/Users/twms2/.atom/packages/Remote-FTP/node_modules/fsevents/lib/binding'
binding@unknown – Cannot find module '/Users/twms2/.atom/packages/Remote-FTP/node_modules/fsevents/lib/binding'
binding@unknown – Cannot find module '/Users/twms2/.atom/packages/Remote-FTP/node_modules/fsevents/lib/binding'

**Comment by icetee** [comment]
Check this #839
