### ISSUE TITLE
Updates always revert back to upload on save

### ISSUE THREAD

**Issue by tbugler** [icetee/remote-ftp#897]
After each update the configuration reverts back to "Upload on save", which can have undesirable results. 
Can the default be changed to never?

**Comment by icetee** [comment]
Check out the plugin settings, globally applicable. First option item.
But [README.md](https://github.com/icetee/remote-ftp) turns out.

**Comment by tbugler** [comment]
That was my point... it is/was globally set. The update to 1.0 and then 1.1 each resulted in it reverting back to always upload on save (not keeping the setting).

**Comment by icetee** [comment]
Sorry, I figured it aside. The configuration file has been renewed.
Check this issue #875.
