### ISSUE TITLE
Package needs rebuilt after every update

### ISSUE THREAD

**Issue by robhuska** [icetee/remote-ftp#899]
I know this project has taken new ownership and @icetee is doing awesome cleaning up all the bugs! But I have one that has started cropping up recently. With every new update, Remote-FTP needs to be recompiled because Atom says its currently compiled for an older version of Atom.

**Comment by icetee** [comment]
I suspect that the [chokidar](https://github.com/paulmillr/chokidar) package is the problem. I'm trying to simply upgrade dependencies, if it's a solution.

Connects #839
