### ISSUE TITLE
'Incompatible native modules' error

### ISSUE THREAD

**Issue by chaance** [icetee/remote-ftp#905]
Failed to require the main module of 'Remote-FTP' because it requires one or more incompatible native modules (binding, binding, binding, binding, binding, binding).
    Run `apm rebuild` in the package directory and restart Atom to resolve.

I did exactly as instructed and ran `apm rebuild` from `.atom/packages/Remote-FTP/` and am still getting the same error after a restart. Disabled all of my other packages with no luck. This just started happening after updating to 1.1.3.

**Comment by chaance** [comment]
Also, I followed all recommendations in issue #839 and rebuilt pacakges from `Incompatible Packages` view. Same error appears consistently even after `rm -rf` the `node-modules` folder. Uninstalled and reinstalled the package completely, still nothing. :(

**Comment by icetee** [comment]
Just rebuild from `Incompatible Packages` view. Do not do anything else.

**Comment by chaance** [comment]
Thank you. Not sure where I went wrong earlier but it's working now.

**Comment by twifty** [comment]
I just came across this issue myself after updating atom, with a package I'm currently developing. Running `apm rebuild` from the package directory did not work, however running rebuild from `Incompatible Packages` view did.

Can anybody explain what this error actually is and what causes it?
