### ISSUE TITLE
Tree view multi-select not work?

### ISSUE THREAD

**Issue by jan-vince** [icetee/remote-ftp#912]
Hi, I can't download (or upload) more than one file or folder at once.

Even when I select two folders and hit menu Download/Upload, only last item is processed.

There is no issue about this - is this only me having this problem?

**Comment by icetee** [comment]
Multi-select is not supported yet. But uploading must go.

**Comment by jan-vince** [comment]
When I select multiple files in TreeView and hit Upload in context menu, only last selected item is uploaded?

Is this problem with my setup or this is the one that is not supported yet?

*I am on MacOS Sierra + Atom 1.18.0 x64 + remote-ftp 1.1.3*

**Comment by icetee** [comment]
Does the new version work from local TreeView to multi-select upload?

Multiple selection support under testing.
https://github.com/icetee/remote-ftp/commit/06dd7169eb8275309f4eb222c6b81b08ad54329d

**Comment by jan-vince** [comment]
I can select multiple files/folders and upload them at once.

So for me this works :)
