### ISSUE TITLE
Windows 10: sftp download file function creates only folders

### ISSUE THREAD

**Issue by 2brainapp** [icetee/remote-ftp#914]
Hi, 

I'm using remote-ftp plugin version 1.1.3 on july 2017 22nd. 
If i try to download any file from the remote server, in my local folder, instead of the downloaded file, i have a folder. 
I.e.: (website remote folder) /www/index.php >> double-click to download and edit >> in my local folder the plugin creates a new FOLDER named "index.php"
Obviusly i can't edit it.

Thank you for any help.

**Comment by UVLabs** [comment]
same issue here

**Comment by mikl-p** [comment]
Hi!
same issue here
macOS 10.12.5
remote-ftp plugin version 1.1.4

**Comment by lite244** [comment]
Hello.
Same issue on Ubuntu, 
Atom 1.19.2 x64, 
Remote-FTP 1.1.3

**Comment by icetee** [comment]
I fixed https://github.com/icetee/remote-ftp/commit/5da89cab245206bde4e27177052838cf8294b4ba. Next release will be included.
