### ISSUE TITLE
persian filename

### ISSUE THREAD

**Issue by mostafamemariani** [icetee/remote-ftp#919]
hi
i have persian php filenames that corrupts when it has downloaded .
it seems filenames does not support utf-8
![image](https://user-images.githubusercontent.com/6501140/28556338-f5226680-711a-11e7-847e-0f11f6cddec9.png)

**Comment by icetee** [comment]
Do you want to see the console to see if the file names are right there?
I check on macOS and use Emoji. All is well.

The server may return incorrectly. (Please check)

![screenshot 2017-07-25 16 27 06](https://user-images.githubusercontent.com/1855340/28577317-b471a88a-7156-11e7-8658-873deadd7d5d.png)

**Comment by icetee** [comment]
Check this hotfix https://github.com/icetee/remote-ftp/commit/98de9b02410e33273ffed337e1cb55f87f743fee
Release is expected later.

**Comment by mostafamemariani** [comment]
thanks 
bug is fixed
