### ISSUE TITLE
Need a password prompt feature eagerly!

### ISSUE THREAD

**Issue by lightingland** [icetee/remote-ftp#92]
.ftpconfig keep the host ftp information but I don't want the password be stored just like that. How about prompt me a blank input when start connecting? Or there it is just I can't figure it out. Anyone can show me how? Thanks.

**Comment by grenierdev** [comment]
This is not implemented but might be in the future.

**Comment by wasikuss** [comment]
Take a look into https://github.com/wasikuss/remote-ftp
when you add `"prompt_for_pass": true,` to .ftpconfig then you will need enter password on each remote session ( until closed )

**Comment by StephenNeate** [comment]
Thanks @wasikuss  for that item, the added security of password prompt you have done is ideal and works a treat.

**Comment by jpxd** [comment]
Fixed in PR #176
