### ISSUE TITLE
Downloading file from FTP which is already on local

### ISSUE THREAD

**Issue by UVLabs** [icetee/remote-ftp#923]
before I could have downloaded a file from ftp and start working on it immediately and it would overwrite the one locally but now spits and error saying the file already exists locally and then it still goes ahead with the behaviour before, the only issue is it's sending out this error...

![image](https://user-images.githubusercontent.com/10324144/28757288-0b97bb00-754d-11e7-96f7-b2c69bca05d2.png)

The package used to do this automatically before...

**Comment by vol4ikman** [comment]
same here

**Comment by jonatasu** [comment]
Same here

**Comment by wanprabu** [comment]
Got the same problem

**Comment by ryandroid226** [comment]
Same issue here

**Comment by icetee** [comment]
It is related #925 and #936. Because you always want to download a folder (incorrectly), this error message will come up. The previous version works well.

**Comment by bay-lylekarstensen** [comment]
I cannot even use the remote ftp anymore due to this bug.
