### ISSUE TITLE
Double clicking on remote file doesn't open it anymore..

### ISSUE THREAD

**Issue by franciscocalmon** [icetee/remote-ftp#925]
Latest version, double clicking on remote file doesn't open it anymore...

**Comment by franciscocalmon** [comment]
Update ! 
The file becomes a Directory.. and I can't open..
Atom 1.18.0
remote-ftp 1.1.4

![screen shot 2017-07-31 at 6 07 40 pm](https://user-images.githubusercontent.com/29186109/28768496-3020b160-761b-11e7-9d7d-8f461e052ec2.png)

**Comment by franciscocalmon** [comment]
Another Update.
With files already existent locally, you get a warning and then it opens. New files are transformed into Directories and you can't open..

**Comment by david-pivonka** [comment]
Same issue here. Downgrading to older version

**Comment by wizrd969** [comment]
fix pls

**Comment by jonatasu** [comment]
Same here.

**Comment by theMasix** [comment]
Same BUG here . fix plssss

**Comment by benjamenjohnsondev** [comment]
+1.

Double click remote creates directory in local - expected result is open file

**Comment by salarmzn** [comment]
same here

**Comment by karlunar** [comment]
+1
It runs a list command on the ftp-server and then tries to download the file from that diretory (which doesn't exist)

**Comment by Devon-Developer** [comment]
Same here also!

**Comment by Joyr1d3r** [comment]
yep. the same problem, fix it please!

**Comment by Joyr1d3r** [comment]
still, is there any way to downgrade to older version of package?

**Comment by david-pivonka** [comment]
Of course, uninstall current remote-ftp and use this command in console `apm install remote-ftp@1.1.3` and restart Atom.

**Comment by RayFungHK** [comment]
if you receive any error on open remote-ftp file or folder, please clean your local project folders and files and sync again.

**Comment by icetee** [comment]
I unpublished 1.1.4 version, try re-install.

**Comment by karlunar** [comment]
Can't remember if I had 1.1.3 before but I have the same problem with 1.1.3 as I did with 1.1.4. FYI

**Comment by benjamenjohnsondev** [comment]
Can confirm @karlunar above except I get an error before it opens the file:

Error: Remote FTP Transfer issue
550 Can't change directory to /public_html/global/css/admin/screen.css:  Not a directory

**Comment by alabamenhu** [comment]
Agree with Karlunar, the problem occurs in both 1.1.3 and 1.1.4.  I had to drop down to 1.1.2 to solve the issue.
