### ISSUE TITLE
make .ftpconfig more flexible

### ISSUE THREAD

**Issue by 2manyvcos** [icetee/remote-ftp#926]
Hi there,

I have a server which I usually access via it's local IP.
When I am not at home I always need to change the .ftpconfig to the hostname or public IP in order to access it, which is annoying when using git.

**I would like if you could specify an array of hosts.** The first available host should be used.

e.g.:
```
{
  [...],
  "hosts": [
    { "host": "192.168.x.y", "port": 22 },
    { "host": "my.domain", "port": 22 }
  ]
}
```

**I would also need the possibility to use local directory specification** as I work on different computers on the same project.

e.g. something like
`
{
  "privatekey": "~/.ssh/mykey"
}
`
or
`
{
  "privatekey": "/home/$USER/.ssh/mykey"
}
`
or
`
{
  "privatekey": "$HOME/.ssh/mykey"
}
`
or an option?
This would not be necessary if this package would use the "~/.ssh/config" file.

What is your opinion about this?

**Comment by icetee** [comment]
I think you should set it up on the router to get a fixed (local) IP address for your device. Simply assign MAC address to IP. I write [mini script](https://gist.github.com/icetee/85739d374380d15ebfec271f41e8bfbe), this script check IP address, if change then modify subdomain data. But there are plenty of (free) solutions.

The package supported ssh-config! Check #834 PR.
I know it is not documented.
