### ISSUE TITLE
Download FIle problem

### ISSUE THREAD

**Issue by salarmzn** [icetee/remote-ftp#927]
In new Version , when I download a .php file from host , remore ftp create a folder instead .php file

**Comment by zavod008** [comment]
+1

**Comment by limesPL** [comment]
+1

**Comment by ejtrsolo** [comment]
I have the same problem. Please anybody helpme.

**Comment by wielski** [comment]
Same problem.

**Comment by gmargetic** [comment]
Same here.

**Comment by hifzi** [comment]
+1

**Comment by mortche** [comment]
+1

**Comment by icetee** [comment]
I unpublished 1.1.4 version, try re-install.

**Comment by icetee** [comment]
Replated #925
