### ISSUE TITLE
Everything on server is a folder

### ISSUE THREAD

**Issue by Devin-Neal** [icetee/remote-ftp#928]
Everything on my server is being downloaded as a folder.

Even a simple .css or .js file will be downloaded to the project folder as a folder with the name of the file itself.

i.e public_html -> css -> browse.css (where browse is a .css file on the server, but being downloaded as a folder).

This happens when actually attempting to download the file, or when just attempting to open the file by double-clicking.

**Comment by GameMoon** [comment]
I have the same issue. The txt and other files without extensions will be folder after download from the root directory.

**Comment by Devin-Neal** [comment]
I will note that this was working just fine yesterday with no changes to the server or my system.

I have also noticed that image files such as .png and .jpg don't actually download. They will simply display a completely blank image in Atom.

(This is for both Remote-FTP version 1.1.4 and 1.1.3 on Arch Linux)

**Comment by charlieagrinsoni** [comment]
I am having the same issue.

**Comment by wbsnippets** [comment]
Same issue.

**Comment by mostafamemariani** [comment]
same issue!!!!

**Comment by Devin-Neal** [comment]
This actually corrected itself for me. Just uninstall and reinstall. Should be version 1.1.3 now, and I haven't had any issues since earlier this morning.

**Comment by BytersNL** [comment]
Uninstall version 1.1.4, restart and re-install worked for me like @Devin-Neal suggested!

**Comment by mostafamemariani** [comment]
re-install worked for me too

**Comment by Ahmedyosry** [comment]
Reinstall and back to 1.1.3 worked for me

**Comment by ghost** [comment]
Reinstall saved me.
Maybe need to close issue?)
