### ISSUE TITLE
Is there a way to hide the password in the .ftpconfig file? 

### ISSUE THREAD

**Issue by etiennedupuis** [icetee/remote-ftp#935]
The whole website is beeing uploaded including the .ftpconfig file with my username and password so others can see. Is there a way to encrypt the password or store the .ftpconfig file elsewhere on my machine?

**Comment by ghost** [comment]
Try to add .ftpconfig to .ftpignore?

**Comment by ghost** [comment]
You can hide file from web, but leave it on server

- If you are using Apache (via .htaccess):
```apache
<FilesMatch "\.(ftpconfig)$">
   Order Allow,Deny
   Deny from all
</FilesMatch>
```
- If you are using nginx:
```nginx
location ~ /.ftpconfig { 
   deny all;
}
```

**Comment by icetee** [comment]
Hi @etiennedupuis,

No centralized password storage. I'm planning to introduce https://github.com/atom/node-keytar, so far, there is no way to do this.

**Solution 1**
FTP funds is not very safe... use SFTP and rsa_id with passphrase or use VPN. So if you have a password, it's useless FTP.

**Solution 2**
You should place the content inside a html folder.
```
/var/www/example.com/html/*
/var/www/example.com/.ftpconfig
```

**Comment by etiennedupuis** [comment]
Hi @icetee,

Having an option to prevent the .ftpconfig file to be uploaded/sync would save a lot of problems. I think this would be easier to implement.

**Comment by icetee** [comment]
Create and add .ftpignore file to project. https://github.com/icetee/remote-ftp/issues/935#issuecomment-321178006

Currently file upload method in Tree view ignoring her .ftpconfig, but simply `ctrl / cmd + s` upload take into consideration the rules.

**Comment by etiennedupuis** [comment]
Perfect! This should be documented. 

Thank you !
