### ISSUE TITLE
Opening a file as a folder

### ISSUE THREAD

**Issue by Juanses** [icetee/remote-ftp#936]
I use remote-ftp with a ftp-server on Ubuntu

When I double click on a remote file, remote-ftp creates a folder on my project tree and, of course, doesn't open the file.

How can I solve this ?

**Comment by mushegov** [comment]
Same problem

**Comment by icetee** [comment]
Please no use 1.1.4 version, this is pre-release. Try re-install (1.1.3).

**Comment by icetee** [comment]
Duplicate of  #925
