### ISSUE TITLE
FTP started auto upload old files

### ISSUE THREAD

**Issue by Kordonme** [icetee/remote-ftp#938]
We just had an incident, that caused the FTP to reupload old files. We are talking +50 folders with files, that have been overwritten with files up to a few month old. 

I'm not really sure if it's related to #887. The developer was running 1.1.3 that he updated just this morning. 

They were two people connected to the FTP. That's why I suspect it's related to #887.

**Comment by icetee** [comment]
Local files are old, probably synchronized.

**Tip 1:** You should delete the files before using it.
**Tip 2:** Use only Remote-FTP tree and hide local tree (or no use). So always the latest one will be used.

Unfortunately, many developers have to pay attention to this.

Is there a backup? Your other developer is probably more recent.

**Comment by UVLabs** [comment]
@icetee could you please check this out? https://github.com/icetee/remote-ftp/issues/923

**Comment by Kordonme** [comment]
@icetee We do have backup, not an issue. My fault, only one developer connected to ftp.
