### ISSUE TITLE
Shows as installed in my package search

### ISSUE THREAD

**Issue by spaced-out-factory** [icetee/remote-ftp#94]
When I search ftp this package shows up with the enable button after I deleted the folder because it wouldn't let me uninstall it.

![image](https://cloud.githubusercontent.com/assets/3946318/7636763/dea17b04-fa2e-11e4-811d-9583564e1c47.png)

**Comment by grenierdev** [comment]
I dont know what to say, no packages have done this to me. Maybe reinstall atom?

**Comment by jpxd** [comment]
Closing this since this is not a problem Remote-FTP is responsible for
