### ISSUE TITLE
mac sierra, toggle does not display connect/config option panel

### ISSUE THREAD

**Issue by sjeff83** [icetee/remote-ftp#941]
I'm using mac sierra,

toggle does not display the connect/edit configuration option panel.

basically step 2 of the getting started doesn't work..
"Open remote-ftp sidebar (Packages -> Remote-FTP -> Toggle)"

**Comment by aalireza439** [comment]
same here mac Sierra.
since this morning (couple hours ago in my timezone) toggle doesn't show and I can't connect to the server.

**Comment by JerryWang761208** [comment]
you can see a red bug on the bottom-right of your atom editor.

click the bug and click rebuild then it works.
