### ISSUE TITLE
Incompatible with Atom 1.19.0

### ISSUE THREAD

**Issue by wmelton** [icetee/remote-ftp#943]
Latest update of Atom 1.19.0 breaks the latest version of Remote-FTP on Mac OSX.  Toggle is broken and connections can't be made.

Errors reported: 

```binding@unknown – Cannot find module '/Users/user/.atom/packages/Remote-FTP/node_modules/fsevents/lib/binding'```

**Comment by wmelton** [comment]
Update: 

If you run `command+shift+p` and search 'Incompatible Packages: View' you see the errors reported above but are also given the option to 'rebuild packages'. If you rebuild, remote-ftp starts working again. 

Not a package developer, but I remember running in to this a few releases ago. Wondering if there's an update mechanism to force a total rebuild on update? Think it would remedy this issue.

**Comment by icetee** [comment]
Yep, this is a macOS build issue. https://github.com/icetee/remote-ftp/issues/839#issuecomment-313811278
