### ISSUE TITLE
i have remote ftp problem

### ISSUE THREAD

**Issue by sametsirinel** [icetee/remote-ftp#944]
Firstly I am working with a framework in php. I am working with some framework files in a way known as blade. For example, when I try to access a file named 'home.wizard.php', it recognizes this file as a folder and prevents me from opening the file with ftp. When I look at the local files, I see a folder called 'home.wizard.php'. Could you fix this problem

**Comment by icetee** [comment]
Go back to the previous version.
```
apm uninstall remote-ftp
apm install remote-ftp
```
