### ISSUE TITLE
Error: Handshake failed: no matching key exchange algorithm

### ISSUE THREAD

**Issue by lioutikov** [icetee/remote-ftp#952]
Hi,

I really like the package and it has been very useful in the past.
I haven't used the remote-ftp package in a while, so i am not sure which update "broke" it for me.
However, every time I try to connect now (via SFTP) I get an error message regarding key exchange algorithm.
The host apparently only accepts
'diffie-hellman-group-exchange-sha1' and 'diffie-hellman-group1-sha1'

I am using
ubuntu 16.04
atom 1.19.3
remote-ftp 1.1.3

I was able to fix the problem by changing the hash key in lib/client.js line 431 from "key" to "kex"

cheers,
Rudolf

**Comment by icetee** [comment]
Hi,

Thanks for report issue and solved.
Do you want to do a Pull Request? I know that's a little change, but you're a contributor.
(If it doesn't matter to you, I'll write it myself.)

I think it is incorrect since https://github.com/icetee/remote-ftp/commit/cb123c56a3067d8ef1f4961bc89f22509d5d6b25 commit.

I found these with this command `ssh -Q`.

key:
```
ssh-ed25519
ssh-ed25519-cert-v01@openssh.com
ssh-rsa
ssh-dss
ecdsa-sha2-nistp256
ecdsa-sha2-nistp384
ecdsa-sha2-nistp521
ssh-rsa-cert-v01@openssh.com
ssh-dss-cert-v01@openssh.com
ecdsa-sha2-nistp256-cert-v01@openssh.com
ecdsa-sha2-nistp384-cert-v01@openssh.com
ecdsa-sha2-nistp521-cert-v01@openssh.com
```

kex:
```
diffie-hellman-group1-sha1
diffie-hellman-group14-sha1
diffie-hellman-group-exchange-sha1
diffie-hellman-group-exchange-sha256
ecdh-sha2-nistp256
ecdh-sha2-nistp384
ecdh-sha2-nistp521
curve25519-sha256@libssh.org
```

cipher:
```
3des-cbc
blowfish-cbc
cast128-cbc
arcfour
arcfour128
arcfour256
aes128-cbc
aes192-cbc
aes256-cbc
rijndael-cbc@lysator.liu.se
aes128-ctr
aes192-ctr
aes256-ctr
aes128-gcm@openssh.com
aes256-gcm@openssh.com
chacha20-poly1305@openssh.com
```

**Comment by lioutikov** [comment]
Hi,

if I clone the current master branch I get an "Cannot find module 'fs-plus'" error. Not sure if you want to merge "my fix" into that version.
Anyhow just sent you a Pull Request.

Regarding the Handshake issue, instead of hard coding the algorithm lists in the client, I would suggest to use the constants defined in ssh2-streams.constants.ALGORITHMS.

**Comment by icetee** [comment]
Go to the remote-ftp folder and install node-modules `npm install` or `apm install`.

**Comment by lioutikov** [comment]
That makes sense of course...
Everything works fine now. 

cheers,
Rudolf

**Comment by icetee** [comment]
I merged https://github.com/icetee/remote-ftp/pull/953 thanks!

**Comment by lioutikov** [comment]
Great!
And keep up the good work!
