### ISSUE TITLE
Remote FTP didn't start

### ISSUE THREAD

**Issue by ghost** [icetee/remote-ftp#957]
Hi,

Since 3 days ago, .ftpconfig config cannot but runned ! Even with a new install

MacOS : 10.12.3
Atom : 1.19.5

Thanks

**Comment by icetee** [comment]
Check this https://github.com/icetee/remote-ftp/issues/839#issuecomment-313811278

**Comment by ghost** [comment]
Still not working.

[None of your packages contain incompatible native modules.]

And the package has been installed 3 times.

**Comment by ghost** [comment]
The issue has been solved...

the file .ftpconfig has been remove from .atom. Then I created a new file where I put the ftp configuration option.
