### ISSUE TITLE
atom 1.19.7 on mac cant get this to work at all?

### ISSUE THREAD

**Issue by jimspooner** [icetee/remote-ftp#960]
have had clean install of atom on mac 1.19.7, installed remote ftp on its own but does not work, even to create a config file, it gives no reports or errors?? cant toggle, cant navigate to its like the menu just doesn't work at all even with the shortcuts

**Comment by icetee** [comment]
Hi, check this https://github.com/icetee/remote-ftp/issues/839#issuecomment-313857979

**Comment by jimspooner** [comment]
many thanks, rebuild did the trick
