### ISSUE TITLE
Move Files

### ISSUE THREAD

**Issue by bay-lylekarstensen** [icetee/remote-ftp#967]
It would be great if you could add moving of files or at least copy and paste between folders.

**Comment by icetee** [comment]
I'am already work on it. :)
https://github.com/icetee/remote-ftp/tree/feature/drag_and_drop

**Comment by bay-lylekarstensen** [comment]
That is AWESOME.. Love the plugin!

**Comment by samuelesantoni** [comment]
Oh wow! Love this feature! Drag and drop for move and upload file would be fantastic!

**Comment by icetee** [comment]
Implemented. But for now, only files can be moved. Soon release!

**Comment by samuelesantoni** [comment]
Good. But how can i do for upload files?

**Comment by icetee** [comment]
All save the file (default global option) or project tree view and in context menu. It does not work between TreeViews. Related of #25
