### ISSUE TITLE
Allow base64 password

### ISSUE THREAD

**Issue by ignacionelson** [icetee/remote-ftp#968]
Small request for an awesome plugin!
Would make it easier to transition from Filezilla.
Maybe with a new parameter? 

"passdecode": "base64",

Thanks!

**Comment by icetee** [comment]
I can not see its meaning, it can be decoded in minutes :/
[https://www.base64decode.org](https://www.base64decode.org)

FileZilla I think is plain text, but only show hash. This is not working here.

I want this: https://github.com/atom/node-keytar

**Comment by ignacionelson** [comment]
Yes, it's not a security feature. Just to skip that decoding step (I'm moving 100+ sites from filezilla to remote ftp). 5 seconds * 100 sites :P

**Comment by icetee** [comment]
uhhf :)
