### ISSUE TITLE
i can't find configuration file

### ISSUE THREAD

**Issue by nickeypark** [icetee/remote-ftp#971]
Please help me about configuration file.
Thank you.

**Comment by icetee** [comment]
You must create a configuration file for each project. This is name .ftpconfig.

Currently only one project supported at the same time.

Read the [wiki](https://github.com/icetee/remote-ftp/wiki).

If you use macOS check this [issue](https://github.com/icetee/remote-ftp/issues/839#issuecomment-313811278).

**Comment by nickeypark** [comment]
Thank you for help~
