### ISSUE TITLE
failed to load FTP

### ISSUE THREAD

**Issue by psantang** [icetee/remote-ftp#974]
![screen shot 2017-09-21 at 6 28 45 am](https://user-images.githubusercontent.com/12601430/30691576-2d484d92-9e96-11e7-8401-b93b6616763c.png)

Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.

Mac OSX with Atom 1.20.1 X64

Hope this helps.  Let me know if you need more information.
Paul Santangelo

**Comment by icetee** [comment]
Known issue. https://github.com/icetee/remote-ftp/issues/839#issuecomment-313811278

An Atom version 1.21 comes out of native watch API and solves the problem.

**Comment by psantang** [comment]
Thank you very much.

I wasn't able to download 1.21 yet, but did run the sudo command as indicated in the warning message and after a app restart it is working correctly...just never had to do that before so was unfamiliar.  I assume the issue was due to xCode update which was done on my local last night.

Thanks again for developing a great ftp package.
Paul
