### ISSUE TITLE
[Feature needed] SSH forward via Gateway server

### ISSUE THREAD

**Issue by bearpaw** [icetee/remote-ftp#976]
Is it possible to connect a server via a gateway server like Mobaxterm? Thank you very much!

**Comment by icetee** [comment]
I can not really imagine why they should link the two. This package use [SSH2](https://www.npmjs.com/package/ssh2), no need "real" ssh client, it is base on Node.js.

Supported ssh config file! Check this https://github.com/icetee/remote-ftp/pull/834.

**Comment by bearpaw** [comment]
Thanks! I will have a try
