### ISSUE TITLE
Use new Filesystem Watcher API

### ISSUE THREAD

**Issue by icetee** [icetee/remote-ftp#980]
The Atom 1.21 supported [Filesystem Watcher API](http://blog.atom.io/2017/09/12/atom-1-20.html). Currently, the **chokidar** package is in use, it needs to be replaced to Atom Watcher API solution.

This will be the second major version, dropping old version support. (>=1.21)

It's a major issue #839

**Comment by putterson** [comment]
I'd be interested in picking this up for hacktoberfest

**Comment by icetee** [comment]
The [API docs](https://atom.io/docs/api/v1.21.0/PathWatcher).

**Comment by putterson** [comment]
I'm not sure my pr should be merged until https://github.com/atom/atom/issues/15642 has been resolved. I ran into this issue during development and had to develop on 1.22 beta. Merging before then would break the file watching functionality for users on linux.

**Comment by icetee** [comment]
I close the issue, pull request soon.
