### ISSUE TITLE
🚀 [1.2.0] Release 🚀 

### ISSUE THREAD

**Issue by icetee** [icetee/remote-ftp#989]
Bugs for the new version should be reported here. Use the [issue page](https://github.com/icetee/remote-ftp/issues) for everything else. The new version has changed a lot.

Known error under macOS #839! The fast answer:
> `Shift-Command-P`, `Incompatible Packages`, and `Rebuild Packages` worked.

# CHANGELOG

## Fixed
+ Fix .ftpconfig ENOENT issue
+ Add usable notifications [#896](https://github.com/icetee/remote-ftp/issues/896) [#112](https://github.com/icetee/remote-ftp/issues/112) [#373](https://github.com/icetee/remote-ftp/issues/873) [#434](https://github.com/icetee/remote-ftp/issues/434)
+ Add `ssh-agent` documentation [#849](https://github.com/icetee/remote-ftp/issues/849) (Thanks [@zlibra](https://github.com/zlibra), [@BenKennish](https://github.com/BenKennish))
+ Bad substr logic and set recursive download for 'Local < Remote' command [#918](https://github.com/icetee/remote-ftp/issues/918)
+ Add multiproject detail [#920](https://github.com/icetee/remote-ftp/issues/920)
+ Fix correct download list [#923](https://github.com/icetee/remote-ftp/issues/923)
+ Fix double click file download [#925](https://github.com/icetee/remote-ftp/issues/925)
+ Fix [#952](https://github.com/icetee/remote-ftp/issues/952) (Thanks [@lioutikov](https://github.com/lioutikov))
+ Fix keyboardInteractive dialog for Google Authenticator [#962](https://github.com/icetee/remote-ftp/issues/962) (Thanks [@maxswjeon](https://github.com/maxswjeon))
+ Fix memory leaks on save [#908](https://github.com/icetee/remote-ftp/issues/908)
+ Add (old school) method for check file type (if no available MLSD example IIS) [19e1738](https://github.com/icetee/remote-ftp/commit/19e17383d20a0079ec50ad67d35fd8a55b79c62a)
+ Fix duplication connect (when reconnected)
+ 🎨 Fix root icon position

## Featured
+ Supported UTF-8 filename in File-tree [#919](https://github.com/icetee/remote-ftp/issues/919)
+ Supported unix path style for privatekey [#216](https://github.com/icetee/remote-ftp/issues/216)
+ Supported IPv6 [#949](https://github.com/icetee/remote-ftp/issues/949)
+ Supported changes to permission and owner [#685](https://github.com/icetee/remote-ftp/issues/685)
+ Supported Drag & Drop (only move on a server) [BETA]

## Changed
+ Add `.ftpignore` documentation
+ Update deprecated packages
+ Tree view, File view, Directory view, file.js, directory.js changed to ES6
+ Extended `.eslintrc`
+ Remove `theorist` dependency (no maintained)
+ `Theorist` changed to `event-kit`
+ Begin notifications collect to notifications.js
+ Implemented `mlsd`
+ Add more helpers
+ Change double `cwd` to `mlsd` method
+ Centralized `isConnected` method in ftp.js
+ Change `self` to `this` several places
+ Optimized codes
+ 🎨 Change code styles
+ Add picto to offline view
+ Configurable server label [#848](https://github.com/icetee/remote-ftp/issues/848)
+ Add Permission Denied notification
+ 🎨 There are many code beauties 🎨
+ Add `remote-ftp:download-active` command (BETA)
+ Remove log when readconfig (spamming console)
+ Remove isAlreadyExits notification [a8019ff](https://github.com/icetee/remote-ftp/commit/a8019ff6449835383739851736d0f453c0fd8f78)
+ Implemented `SITE` method
+ Modify context-menu sequence [c68464b](https://github.com/icetee/remote-ftp/commit/c68464b2d9eb08aaf50e99065cea0e9b7b81a99e)
+ 🎨 Design if no use dock integration

### Editable permissions
![permissions](https://user-images.githubusercontent.com/1855340/31040792-14700150-a58c-11e7-95c5-f51336d4dbbe.gif)

### Adjustable server name
![server_name](https://user-images.githubusercontent.com/1855340/31040826-63dc0dec-a58c-11e7-9002-6deac0e06247.gif)

### Supported Two-Factor Authentication
![ssh_config_plus_google_auth](https://user-images.githubusercontent.com/1855340/31040831-6b86a3c2-a58c-11e7-814a-f6b0b344a821.gif)

### Drag and drop [BETA]
![drag_and_drop](https://user-images.githubusercontent.com/1855340/31040883-e5930854-a58c-11e7-8cc2-bd8e2691647f.gif)

**Comment by benjamenjohnsondev** [comment]
@icetee greate job on 1.2!
But! The latest releases are broken, there's something wrong with the version no.:
[v.1.2.2](https://github.com/icetee/remote-ftp/commit/ba240af80024f5c340cc21ab7d561e620085a13b
)
[v1.2.3](https://github.com/icetee/remote-ftp/commit/4b341ffb1f77da77056829f5eac2a35b53d85615)

anyone caught out by this can use: 
`$ apm install remote-ftp@1.2.1`

**EDIT**
In fact, are you pushing commits to the wrong branch?

**Comment by icetee** [comment]
@benjamenhogben Can you help what you experience? Does the v1.2.4 version help?

**Comment by benjamenjohnsondev** [comment]
The update failed, so apm rebuild but plugin wasn't recognised by atom as the metadata was blank and plugin didn't initialise

1.2.4 works fine, thanks!
