### ISSUE TITLE
SSH Agent on Mac

### ISSUE THREAD

**Issue by plttn** [icetee/remote-ftp#99]
What agent setting do we use to use the default ssh-agent on Yosemite?

**Comment by grenierdev** [comment]
I dont use SSH that much and use Win8.1. This package use [ssh2](https://github.com/mscdex/ssh2) library. Maybe you will get the information you want through their doc.

**Comment by plttn** [comment]
Digging through your code led me to find the correct answer.

'env' will use the AUTH_SOCK environment variable, giving me the authentication i want.

**Comment by grenierdev** [comment]
Great !
