### ISSUE TITLE
Unknown command 500

### ISSUE THREAD

**Issue by querysol** [icetee/remote-ftp#992]
After plugin update to version 1.2.1 I have this issue:
"Unknown command 500"
Windows 10 x64

Console log:
"<embedded>:118139 IntersectionObserver.observe(target): target element is not a descendant of root.
TreeView @ <embedded>:118139
C:\Users\qs\.atom\packages\emmet\lib\emmet.coffee:139 Loading Emmet extensions from ~/emmet
C:\Users\qs\.atom\packages\emmet\lib\emmet.coffee:156 Emmet: no such extension folder: C:\Users\qs/emmet
loadExtensions @ C:\Users\qs\.atom\packages\emmet\lib\emmet.coffee:156
"

Built-in Atom Packages
├── atom-dark-syntax@0
├── atom-dark-ui@0.53.
├── atom-light-syntax@
├── atom-light-ui@0.46
├── base16-tomorrow-da
├── base16-tomorrow-li
├── one-dark-ui@1.10.8
├── one-light-ui@1.10.
├── one-dark-syntax@1.
├── one-light-syntax@1
├── solarized-dark-syn
├── solarized-light-sy
├── about@1.7.8
├── archive-view@0.63.
├── autocomplete-atom-
├── autocomplete-css@0
├── autocomplete-html@
├── autocomplete-plus@
├── autocomplete-snipp
├── autoflow@0.29.0
├── autosave@0.24.3
├── background-tips@0.
├── bookmarks@0.44.4
├── bracket-matcher@0.
├── command-palette@0.
├── dalek@0.2.1
├── deprecation-cop@0.
├── dev-live-reload@0.
├── encoding-selector@
├── exception-reportin
├── find-and-replace@0
├── fuzzy-finder@1.5.8
├── github@0.6.2
├── git-diff@1.3.6
├── go-to-line@0.32.1
├── grammar-selector@0
├── image-view@0.62.3
├── incompatible-packa
├── keybinding-resolve
├── line-ending-select
├── link@0.31.3
├── markdown-preview@0
├── metrics@1.2.6
├── notifications@0.69
├── open-on-github@1.2
├── package-generator@
├── settings-view@0.25
├── snippets@1.1.4
├── spell-check@0.72.2
├── status-bar@1.8.13
├── styleguide@0.49.7
├── symbols-view@0.118
├── tabs@0.107.2
├── timecop@0.36.0
├── tree-view@0.217.9
├── update-package-dep
├── welcome@0.36.5
├── whitespace@0.37.3
├── wrap-guide@0.40.2
├── language-c@0.58.1
├── language-clojure@0
├── language-coffee-sc
├── language-csharp@0.
├── language-css@0.42.
├── language-gfm@0.90.
├── language-git@0.19.
├── language-go@0.44.2
├── language-html@0.47
├── language-hyperlink
├── language-java@0.27
├── language-javascrip
├── language-json@0.19
├── language-less@0.33
├── language-make@0.22
├── language-mustache@
├── language-objective
├── language-perl@0.37
├── language-php@0.42.
├── language-property-
├── language-python@0.
├── language-ruby@0.71
├── language-ruby-on-r
├── language-sass@0.61
├── language-shellscri
├── language-source@0.
├── language-sql@0.25.
├── language-text@0.7.
├── language-todo@0.29
├── language-toml@0.18
├── language-typescrip
├── language-xml@0.35.
└── language-yaml@0.30

Community Packages (24
├── atom-alignment@0.1
├── atom-material-synt
├── atom-material-ui@2
├── atom-monokai@0.10.
├── atom-zurb-foundati
├── busy-signal@1.4.3
├── emmet@2.4.3
├── emmet-snippets-com
├── file-icons@2.1.12
├── highlight-selected
├── intentions@1.1.5
├── jshint@1.8.6 (disa
├── language-vue@0.23.
├── linter@2.2.0
├── linter-jshint@3.1.
├── linter-php@1.5.1
├── linter-ui-default@
├── minimap@4.29.7
├── monokai@0.24.0
├── pigments@0.40.2
├── project-manager@3.
├── Remote-FTP@1.2.1
├── sass-autocompile@0
└── termination@0.6.1

**Comment by telmo-antunes** [comment]
Damn dude I just started a regular work day, saw that there was an update for atom and decided to proceed with it. Now I'm going to lose a shit ton of time because of this smh...

**Comment by icetee** [comment]
@telmo-antunes This is an open source project, it is impossible to test all server environments alone. Switch to the previous version. Two commands are not too complicated to issue.

```
apm remove remote-ftp  
apm install remote-ftp@1.1.3
```

**Comment by tamsrud** [comment]
I experience same problem, as mentioned in [Issue#991](https://github.com/icetee/remote-ftp/issues/991).
In my case it is the EPSV command that gets the "500 Unknown command" response.
I'm using simple FTP (no SFTP).

If you set Debug response in Remote-FTP settings view, the console will show what command that gives the response.

**Comment by telmo-antunes** [comment]
@icetee OMG thank you very much for the feedback!!

**Comment by eleumas** [comment]
Hi, i have a Mac with 10.13 and Atom 1.2. I have the same issue of @tamsrud . I wait a fix soon!

**Comment by icetee** [comment]
Fixed the [v.1.2.2](https://github.com/icetee/remote-ftp/releases/tag/v1.2.2)?

**Comment by tamsrud** [comment]
Same problem with v.1.2.3

The server should support EPSV. 
It might be a firewall problem on the server (quite strickt). I will check it out.

> < 220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------\r\n220-You are user number 1 of 50 allowed.\r\n220-Local time is now 08:02. Server port: 21.\r\n220-This is a private system - No anonymous login\r\n220-IPv6 connections are also welcome on this server.\r\n220 You will be disconnected after 15 minutes of inactivity.
> USER username
> < 331 User username OK. Password required
> PASS ******
> < 230 OK. Current restricted directory is /
> FEAT
> < 211-Extensions supported:\r\n EPRT\r\n IDLE\r\n MDTM\r\n SIZE\r\n MFMT\r\n REST STREAM\r\n MLST type*;size*;sizd*;modify*;UNIX.mode*;UNIX.uid*;UNIX.gid*;unique*;\r\n MLSD\r\n AUTH TLS\r\n PBSZ\r\n PROT\r\n UTF8\r\n ESTA\r\n PASV\r\n EPSV\r\n SPSV\r\n ESTP\r\n211 End.
> OPTS UTF8 ON
> < 200 OK, UTF-8 enabled
> TYPE I
> < 200 TYPE is now 8-bit binary
> EPSV
> < 500 Unknown command

**Comment by tamsrud** [comment]
If changing from 501 to 500 in line 103 it works for me.

`if (errEPSV.code === 501 || /Operation not permitted/.test(errEPSV.message)) {`

**Comment by tamsrud** [comment]
v.1.2.4 work like a charm.
Thanks @icetee
