### ISSUE TITLE
OOPS: vsf_sysutil_bind - error with last update

### ISSUE THREAD

**Issue by RalleSaid** [icetee/remote-ftp#994]
Hi, i'm getting this error when connect to ftp, or when i try open remote file.

![screenshot_2](https://user-images.githubusercontent.com/24841707/31184934-1cd02898-a901-11e7-8da5-22c7b66e6a3e.png)

This problem started today, after upgrading, had been working without problem for months.

.ftpconfig
```
{
    "protocol": "ftp",
    "host": "zzz.xxx.cc",
    "port": 21,
    "user": "user",
    "pass": "*****",
    "promptForPass": false,
    "remote": "/home/user/app",
    "local": "",
    "secure": false,
    "secureOptions": null,
    "connTimeout": 10000,
    "pasvTimeout": 10000,
    "keepalive": 10000,
    "watch": [],
    "watchTimeout": 500
}
```

Any idea?

ftp server:  CentOS Linux release 7.3.1611 (Core)
localhost: Windows 10 V 1703
atom: 1.21.0
remote-ftp: 1.2.1

**Comment by icetee** [comment]
Resolve the v1.2.4? Developer tools what do you write?

Try set `seccomp_sandbox=NO` in `/etc/vsftpd.conf` file on the server.

**Comment by RalleSaid** [comment]
yes, the problem has been solved with the last version, I do not know why it happened, but it did not happen anymore.
Thanks. 👍
