### ISSUE TITLE
Cannot access remote files

### ISSUE THREAD

**Issue by bcurtin144** [icetee/remote-ftp#996]
I'm running into an issue trying to open files from the Remote-FTP pane in the latest version. I'm running Atom 1.21.0 x64 on Windows 10. I'm connecting to FileZilla Server 0.9.60. This was not a problem in v1.1.3, so I've reverted.

Working in the Remote-FTP pane, I can expand folders just fine. Here are the server logs after browsing to /wwwroot:
> EPSV
> 229 Entering Extended Passive Mode (|||50048|)
> LIST -al /wwwroot
> 150 Opening data channel for directory listing of "/wwwroot"
> TLS connection for data connection established
> 226 Successfully transferred "/wwwroot"

The problem starts when I double-click a file to open it. Here's double-clicking index.cfm:
> EPSV
> 229 Entering Extended Passive Mode (|||50126|)
> MLSD /wwwroot/index.cfm
> 150 Opening data channel for directory listing of "/wwwroot/index.cfm"
> TLS connection for data connection established
> 226 Successfully transferred "/wwwroot/index.cfm"
> EPSV
> 229 Entering Extended Passive Mode (|||50046|)
> LIST -al /wwwroot/index.cfm
> 150 Opening data channel for directory listing of "/wwwroot/index.cfm"
> TLS connection for data connection established
> 226 Successfully transferred "/wwwroot/index.cfm"
> EPSV
> 229 Entering Extended Passive Mode (|||50391|)
> RETR index.cfm
> 550 File not found

This also creates an index.cfm *folder* in the Project folder on my hard drive if index.cfm isn't there. If a dummy file is there, Atom shows an error that the file already exists.

Back in v1.1.3, the commands worked. Browsing to /wwwroot is the same (except for PASV instead of EPSV, which doesn't seem to make a difference). But here are the logs for double-clicking index.cfm:
> PASV
> 227 Entering Passive Mode (34,232,101,253,195,163)
> LIST -al /wwwroot/index.cfm
> 150 Opening data channel for directory listing of "/wwwroot/index.cfm"
> TLS connection for data connection established
> 226 Successfully transferred "/wwwroot/index.cfm"
> CWD /wwwroot/index.cfm
> 550 CWD failed. "/wwwroot/index.cfm": directory not found.
> CWD /
> 250 CWD successful. "/" is current directory.
> PASV
> 227 Entering Passive Mode (34,232,101,253,195,206)
> RETR /wwwroot/index.cfm
> 150 Opening data channel for file download from server of "/wwwroot/index.cfm"
> TLS connection for data connection established
> 226 Successfully transferred "/wwwroot/index.cfm"
> MODE S
> 200 MODE set to S.

So the folder is being stripped from the RETR command. And I don't know what to say about the folder creation on the local side.

All this said, the package works if I start from the Project folder pane. Double-clicking local files opens them fine, and saving them automatically uploads a copy to the server.

Hope this information helps.

**Comment by bcurtin144** [comment]
I just realized that my .ftpconfig file has `"remote": "/wwwroot/"`
Don't know if that has an effect on the RETR command. Browsing to other folders in the Remote-FTP pane works fine, however.

**Comment by icetee** [comment]
The problem seems to me to be MLSD. The old way is a two CWD command (folder change). Unfortunately, only a folder change and a list of items can be found to be a folder or a file.

I examine. Thanks for the signal!

**Comment by icetee** [comment]
I remove MLSD method in v1.2.6, please try!

**Comment by bcurtin144** [comment]
So far, so good. Thanks very much for your work!
