### ISSUE TITLE
Download Remote -> Local not recursive

### ISSUE THREAD

**Issue by EvanHerman** [icetee/remote-ftp#997]
When you download a directory from a remote server only the top level files and directories are downloaded. Anything contained in child directories isn't downloaded.

To download those directories I have to go through and right click the directory and select download for each one.

**Expected:**
Downloading top level directories (Remote -> Local) should traverse recursively through the child directories and download those files and directories.

**Comment by AFullam** [comment]
I'm having this same problem. It seems that as well as downloading the top level directories it is also downloading child directories to top level too but without downloading the containing files.

**Comment by Victor-Villacis** [comment]
I'm having the same problem too, top level folders get downloaded only. Furthermore nested folders are getting put in the root directory.

**Comment by allygator** [comment]
Also having this issue.

**Comment by gvoronov** [comment]
Also having this issue, immediately after updating.

**Comment by AndreasBottcher** [comment]
@Victor-Villacis, same problem...
![atom_remote_ftp_error](https://user-images.githubusercontent.com/14309121/31318377-db9eb540-ac59-11e7-8f2f-3e051df2f88c.jpg)

**Comment by Victor-Villacis** [comment]
Does anyone know which version was the last to work?

**Comment by icetee** [comment]
Maybe 1.1.3  

```
apm uninstall remote-ftp
apm install remote-ftp@1.1.3
```

restart Atom.

Be 2017. október 12. -on 1:49:53, Victor Villacis (notifications@github.com(mailto:notifications@github.com)) írta:

**Comment by gvoronov** [comment]
1.1.3 Worked for me.

**Comment by ashishsajwan** [comment]
yes 1.1.3 is the life saver...

**Comment by kucits** [comment]
Downloaded files (such as PDFs) are created as a directory in the local repository instead of a file.

**Comment by icetee** [comment]
Try v1.2.6!
